from __future__ import annotations

from typing import Generic, Iterator, List, Optional, TypeVar, Union, overload

_T = TypeVar("_T")


class ScriptObjectCollection(Generic[_T]):
    """RayStation named collection: supports integer index, string name lookup, and iteration."""

    @overload
    def __getitem__(self, key: int) -> _T: ...
    @overload
    def __getitem__(self, key: str) -> _T: ...
    def __getitem__(self, key: Union[int, str]) -> _T: ...

    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: object) -> bool: ...

    def IndexOf(self, item: _T) -> int: ...
