from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.dose import DoseFallOffParameters, DoseVolumeParameters
    from raystation.v2025.optimization import OptimizationPhase
    from raystation.v2025.patient_db_types import DefaultNameToAlternativeNameMapping, EchoAlgorithmParameters, EudParameters, GuidedMimicAlgorithmParameters
    from raystation.v2025.plan import PlanningIntention



class AutoPlanningDefinition:
    @property
    def BodySite(self) -> str: ...
    @BodySite.setter
    def BodySite(self, value: str) -> None: ...
    @property
    def AutoPlanningStrategies(self) -> ScriptObjectCollection[AutoPlanningStrategy]: ...
    @AutoPlanningStrategies.setter
    def AutoPlanningStrategies(self, value: List[AutoPlanningStrategy]) -> None: ...
    @property
    def PlanningIntention(self) -> PlanningIntention: ...
    @PlanningIntention.setter
    def PlanningIntention(self, value: PlanningIntention) -> None: ...
    @property
    def RoiNameMapping(self) -> ScriptObjectCollection[DefaultNameToAlternativeNameMapping]: ...
    @RoiNameMapping.setter
    def RoiNameMapping(self, value: List[DefaultNameToAlternativeNameMapping]) -> None: ...
    def AddAlternativeNameToRoiNameMapping(self, DefaultName: str, AlternativeName: str) -> List[DefaultNameToAlternativeNameMapping]:
        """Adds an alternative name for a default name in the ROI name mapping of the AutoPlanningDefinition this action is used on."""
        ...
    def AddEchoAutoPlanningStrategy(self, Name: str) -> AutoPlanningStrategy:
        """Adds an ECHO auto-planning strategy to the auto-planning definition."""
        ...
    def AddGuidedMimicAutoPlanningStrategy(self, MachineLearningModelId: Optional[str] = ..., ReferenceDosePreprocessingSettings: str = ..., Phase1TargetBaseWeight: float = ..., Phase1OarBaseWeight: float = ..., Phase1ExternalMinusTargetWeight: float = ..., Phase2DvhMimicWeight: float = ..., Phase2SpatialMimicWeight: float = ..., Phase2InnerTargetDvhShift: float = ..., Phase2InnerTargetDvhTailShift: float = ..., Phase2OuterTargetDvhShift: float = ..., Phase2OuterTargetDvhTailShift: float = ..., Phase2OarDvhShift: float = ..., Name: str = ...) -> AutoPlanningStrategy:
        """Adds a guided mimic auto-planning strategy to the auto-planning definition."""
        ...
    def CopyAutoPlanningStrategy(self, AutoPlanningStrategy: AutoPlanningStrategy, Name: str) -> AutoPlanningStrategy:
        """Copies an auto-planning strategy and adds it to the auto-planning definition."""
        ...
    def DeleteAutoPlanningDefinition(self) -> None:
        """Deletes the auto-planning definition."""
        ...
    def RemoveAlternativeNameFromRoiNameMapping(self, DefaultName: str, AlternativeName: str) -> List[DefaultNameToAlternativeNameMapping]:
        """Removes an alternative name for a default name in the ROI name mapping of the AutoPlanningDefinition this action is used on."""
        ...

class AutoPlanningStrategy:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def AutoOptimizationAlgorithmParameters(self) -> Union[EchoAlgorithmParameters, GuidedMimicAlgorithmParameters]: ...
    @AutoOptimizationAlgorithmParameters.setter
    def AutoOptimizationAlgorithmParameters(self, value: Union[EchoAlgorithmParameters, GuidedMimicAlgorithmParameters]) -> None: ...
    @property
    def OptimizationPhases(self) -> ScriptObjectCollection[OptimizationPhase]: ...
    @OptimizationPhases.setter
    def OptimizationPhases(self, value: List[OptimizationPhase]) -> None: ...
    def DeleteAutoPlanningStrategy(self) -> None:
        """Deletes the auto-planning strategy."""
        ...

class AutoPlanningRoi:
    @property
    def IsRequired(self) -> bool: ...
    @IsRequired.setter
    def IsRequired(self, value: bool) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def RegionOfInterestType(self) -> Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar']: ...
    @RegionOfInterestType.setter
    def RegionOfInterestType(self, value: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar']) -> None: ...
    def DeleteAutoPlanningRoi(self) -> None:
        """Deletes the auto-planning ROI."""
        ...

class AutoPlanningFunctionDefinition:
    @property
    def IsConstraint(self) -> bool: ...
    @IsConstraint.setter
    def IsConstraint(self, value: bool) -> None: ...
    @property
    def IsRobust(self) -> bool: ...
    @IsRobust.setter
    def IsRobust(self, value: bool) -> None: ...
    @property
    def RestrictToAllBeamsIndividually(self) -> bool: ...
    @RestrictToAllBeamsIndividually.setter
    def RestrictToAllBeamsIndividually(self, value: bool) -> None: ...
    @property
    def RestrictToBeams(self) -> ScriptObjectCollection[str]: ...
    @RestrictToBeams.setter
    def RestrictToBeams(self, value: List[str]) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    @property
    def ForAutoPlanningRoi(self) -> AutoPlanningRoi: ...
    @ForAutoPlanningRoi.setter
    def ForAutoPlanningRoi(self, value: AutoPlanningRoi) -> None: ...
    @property
    def FunctionParameters(self) -> Union[DoseFallOffParameters, DoseVolumeParameters, EudParameters]: ...
    @FunctionParameters.setter
    def FunctionParameters(self, value: Union[DoseFallOffParameters, DoseVolumeParameters, EudParameters]) -> None: ...
    def DeleteAutoPlanningFunctionDefinition(self) -> None:
        """Deletes the auto-planning function definition."""
        ...
