from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ArcTrajectory, BeamCommissioningField, BeamImagerDrrSettings, ElectronBeam, PhotonBeam
    from raystation.v2025.brachy import BrachyTreatmentSetup
    from raystation.v2025.dose import DoseGrid, DoseSpecificationPoint
    from raystation.v2025.imaging import DrrImageGenerator, DrrSettings
    from raystation.v2025.ion import IonBeam
    from raystation.v2025.machine import MachineReference
    from raystation.v2025.machine_db_types import ModificationInfo
    from raystation.v2025.patient import PatientSetup
    from raystation.v2025.patient_db_types import BnctBeam, ChairSetup, DicomExportProperties, Examination, ExaminationStructureSet, FractionDose, FractionationPattern, IsocenterData, MotionSynchronizationTechniqueSettings, NominalContribution, Prescription, RadiationSetScenarioGroup, RayCareCustomLabels, RegionOfInterest, Review, SubStructureSet, TreatmentFraction
    from raystation.v2025.plan import TreatmentPlan
    from raystation.v2025.setup import SetupBeam, SetupBeamsSettings



class RadiationSet:
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def DeliveryTechnique(self) -> Optional[Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']]: ...
    @property
    def DicomPlanLabel(self) -> str: ...
    @DicomPlanLabel.setter
    def DicomPlanLabel(self, value: str) -> None: ...
    @property
    def EnableDynamicTracking(self) -> bool: ...
    @property
    def FrameOfReference(self) -> str: ...
    @property
    def IsRbeIncludedInIonTreatmentMachine(self) -> Optional[bool]: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def Number(self) -> int: ...
    @property
    def PatientPosition(self) -> Optional[Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']]: ...
    @property
    def PlanGenerationTechnique(self) -> Literal['Imrt', 'Conformal', 'Mixed']: ...
    @property
    def PlanIntent(self) -> Literal['Undefined', 'Research', 'Recalculation', 'Machine_QA']: ...
    @property
    def UncommissionedMachineVersion(self) -> Optional[str]: ...
    @property
    def BeamImagerDrrSettings(self) -> ScriptObjectCollection[BeamImagerDrrSettings]: ...
    @BeamImagerDrrSettings.setter
    def BeamImagerDrrSettings(self, value: List[BeamImagerDrrSettings]) -> None: ...
    @property
    def Beams(self) -> List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]: ...
    @Beams.setter
    def Beams(self, value: List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]) -> None: ...
    @property
    def BrachyTreatmentSetup(self) -> BrachyTreatmentSetup: ...
    @BrachyTreatmentSetup.setter
    def BrachyTreatmentSetup(self, value: BrachyTreatmentSetup) -> None: ...
    @property
    def ChairSetup(self) -> ChairSetup: ...
    @ChairSetup.setter
    def ChairSetup(self, value: ChairSetup) -> None: ...
    @property
    def DependentSubStructureSet(self) -> SubStructureSet: ...
    @DependentSubStructureSet.setter
    def DependentSubStructureSet(self, value: SubStructureSet) -> None: ...
    @property
    def DicomExportProperties(self) -> DicomExportProperties: ...
    @DicomExportProperties.setter
    def DicomExportProperties(self, value: DicomExportProperties) -> None: ...
    @property
    def DoseSpecificationPoints(self) -> ScriptObjectCollection[DoseSpecificationPoint]: ...
    @DoseSpecificationPoints.setter
    def DoseSpecificationPoints(self, value: List[DoseSpecificationPoint]) -> None: ...
    @property
    def DrrImageGenerators(self) -> ScriptObjectCollection[DrrImageGenerator]: ...
    @property
    def DrrSettings(self) -> ScriptObjectCollection[DrrSettings]: ...
    @DrrSettings.setter
    def DrrSettings(self, value: List[DrrSettings]) -> None: ...
    @property
    def FractionationPattern(self) -> FractionationPattern: ...
    @FractionationPattern.setter
    def FractionationPattern(self, value: FractionationPattern) -> None: ...
    @property
    def FractionDose(self) -> FractionDose: ...
    @FractionDose.setter
    def FractionDose(self, value: FractionDose) -> None: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @ModificationInfo.setter
    def ModificationInfo(self, value: ModificationInfo) -> None: ...
    @property
    def PatientSetup(self) -> PatientSetup: ...
    @PatientSetup.setter
    def PatientSetup(self, value: PatientSetup) -> None: ...
    @property
    def Prescription(self) -> Prescription: ...
    @Prescription.setter
    def Prescription(self, value: Prescription) -> None: ...
    @property
    def PrescriptionNominalContributions(self) -> ScriptObjectCollection[NominalContribution]: ...
    @PrescriptionNominalContributions.setter
    def PrescriptionNominalContributions(self, value: List[NominalContribution]) -> None: ...
    @property
    def RayCareCustomLabels(self) -> RayCareCustomLabels: ...
    @RayCareCustomLabels.setter
    def RayCareCustomLabels(self, value: RayCareCustomLabels) -> None: ...
    @property
    def Review(self) -> Review: ...
    @Review.setter
    def Review(self, value: Review) -> None: ...
    def AddBeamFromBeamCommissioningField(self, Field: BeamCommissioningField, BeamQualityId: str, SSD: Optional[float] = ...) -> PhotonBeam:
        """Create a beam by copying from a beam commissioning field."""
        ...
    def AddCyberKnifeSegment(self, RelativeWeight: float = ..., UpdateExistingRelativeWeights: bool = ..., PitchAngle: float = ..., RollAngle: float = ..., YawAngle: float = ..., LeafPositionsLeft: np.ndarray = ..., LeafPositionsRight: np.ndarray = ..., SourcePositionX: float = ..., SourcePositionY: float = ..., SourcePositionZ: float = ..., ConeName: str = ..., ConeDiameter: float = ..., NodeId: int = ...) -> None:
        """Adds a CyberKnife segment to a beam. Works on beam set level, due to CyberKnife"""
        ...
    def AddOpposedBeam(self, BeamName: str) -> None:
        """Action that creates an opposed beam from an already existing beam."""
        ...
    def AddPoiPrescriptionDoseReference(self, PoiName: str, Description: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddRoiPrescriptionDoseReference(self, RoiName: str, DoseVolume: float = ..., PrescriptionType: Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose'] = ..., Description: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddSitePrescriptionDoseReference(self, Description: str, NameOfDoseSpecificationPoint: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddVirtualBlock(self, Beam: str, Contour: List[Any] = ..., Type: Literal['Treat', 'Protect', 'Undefined'] = ...) -> RadiationSet:
        """Adds a virtual block to the domain state."""
        ...
    def ApplyNamingConvention(self, NamingStrategy: str = ...) -> None:
        """Rename Beam Set and related Treatment Beams."""
        ...
    def AutoBreastAddRoisAndBeams(self, BeamQualityId: str, BeamQualityIdHighNominalEnergy: str = ..., SUPName: str = ..., INFName: str = ..., MEDName: str = ..., LATName: str = ..., ANTName: str = ..., SeparationThreshold: float = ...) -> None:
        """For auto breast planning only."""
        ...
    def BeamSetIdentifier(self) -> str:
        """Returns a beam set identifier which can be used for DICOM export"""
        ...
    def CheckBeamEntry(self) -> str:
        """Runs a beam entry validation of the beam set."""
        ...
    def CheckCyberKnifeDeliverability(self) -> str:
        """Runs a deliverability check for CyberKnife beams."""
        ...
    def ClearBeams(self, RemoveBeams: bool = ..., ClearBeamModifiers: bool = ..., BeamNames: List[str] = ...) -> None:
        """Removes beams or clear the contents of beams of a beam set."""
        ...
    def ClearTreatOrProtectRoiAllBeams(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for all beams."""
        ...
    def ClearUnusedIsocenters(self) -> None:
        """Clears unused isocenters that are not referenced by any beams."""
        ...
    def ComputeDose(self, RunEntryValidation: bool = ...) -> None:
        """Computes dose values for the beam set according to the dose computation settings"""
        ...
    def ComputeDoseOnAdditionalSets(self, Examinations: List[Examination], Fractions: List[TreatmentFraction] = ..., StoreBeamDoseValues: bool = ..., ComputeDoseAveragedLet: bool = ..., AllowGridExpansion: bool = ...) -> List[FractionDose]:
        """Compute beam set dose on additional image sets."""
        ...
    def ComputePerturbedDose(self, DensityShift: float = ..., PatientShift: Any = ..., RotationPoint: Optional[Union[Point3[float], Point3Dict[float]]] = ..., YawDegrees: float = ..., PitchDegrees: float = ..., RollDegrees: float = ..., Examinations: List[Examination] = ..., Fractions: List[TreatmentFraction] = ..., StoreBeamDoseValues: bool = ..., ComputeDoseAveragedLet: bool = ..., AllowGridExpansion: bool = ...) -> List[FractionDose]:
        """Compute perturbed dose on a beam set."""
        ...
    def ConformAllIonApertures(self) -> None:
        """Conforms block and MLC apertures for all beams with a treat ROI defined (energy layers must exist for PBS/LS to conform MLC aperture)"""
        ...
    def ConvertPBSArcBeamSetIntoPBS(self) -> None:
        """Converts a PBS Arc beam set to PBS. The resulting beam set has a separate beam for each distinct gantry angle in the converted PBS Arc beams."""
        ...
    def CopyAndReverseBeam(self, BeamName: str) -> None:
        """Creates a copy of the beam for which the gantry rotates in the opposite direction."""
        ...
    def CopyBeam(self, BeamName: str) -> None:
        """Creates a copy of the specified beam and appends the copy to the beam list."""
        ...
    def CopyBeamFromBeamSet(self, BeamToCopy: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam], ResetBeamMu: bool = ...) -> None:
        """Copy beam from beam set."""
        ...
    def CopyBeamsFromBeamSet(self, BeamSetToCopyFrom: RadiationSet, BeamsToCopy: List[str] = ...) -> None:
        """Makes beam copies from selected beam set and attaches them to the context."""
        ...
    def CreateAdaptedBeamSet(self, AdaptedPlan: TreatmentPlan, Name: str, NumberOfFractions: int, RegistrationType: Literal['DeformableRegistration', 'FrameOfReferenceRegistration'] = ...) -> None:
        """Creates an adapted beam set from the base beam set and adds it to the specified adapted plan."""
        ...
    def CreateArcBeam(self, ArcStopGantryAngle: Optional[float] = ..., ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., BeamQualityId: str = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a beam of VMAT type."""
        ...
    def CreateBnctBeam(self, PlannedBloodBoronConcentration: Optional[float] = ..., CollimatorName: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> BnctBeam:
        """Creates and adds a BNCT beam."""
        ...
    def CreateBroadIonBeam(self, SnoutId: str, MinimumAirGap: Optional[float] = ..., PolarGazeAngle: float = ..., AzimuthalGazeAngle: float = ..., TwistAngle: float = ..., SkinPlanePosition: float = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of Single Scattering/Double Scattering/Uniform Scanning/Wobbling beam delivery type."""
        ...
    def CreateDefaultIsocenterData(self, Position: Any) -> Any:
        """Returns default IsocenterData for a position."""
        ...
    def CreateDoseSpecificationPoint(self, Name: str, Coordinates: Any = ..., VisualizationDiameter: float = ...) -> DoseSpecificationPoint:
        """Action that creates a dose specification point."""
        ...
    def CreateElectronBeam(self, ApplicatorName: str, BeamQualityId: str, InsertName: str = ..., IsAddCutoutChecked: bool = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> ElectronBeam:
        """Creates and adds a beam of electron type."""
        ...
    def CreateEPIDResponse(self, PhantomName: str, PhantomId: str, QAPlanName: str, IsoCenter: Any, DoseGrid: Any, GantryAngle: Optional[float] = ..., CollimatorAngle: Optional[float] = ..., CouchRotationAngle: Optional[float] = ..., ApplyFloodFieldCorrection: bool = ..., SingleFloodFieldBeamQualityId: str = ..., FloodFieldFactor: float = ...) -> None:
        """Creates an EPID QA plan and predicts response for the beams in a beam set."""
        ...
    def CreateEQD2Dose(self, Priorities: np.ndarray, AlphaBetas: np.ndarray, Rois: List[RegionOfInterest]) -> None:
        """Converts a fraction dose into an EQD2 dose and adds that dose to evaluation doses."""
        ...
    def CreatePBSIonBeam(self, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., ArcStopGantryAngle: Optional[float] = ..., SnoutId: str = ..., RangeShifter: str = ..., MinimumAirGap: Optional[float] = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of PBS (or Line scanning or PBS Arc) ion type."""
        ...
    def CreatePhotonBeam(self, BeamQualityId: str, CyberKnifeCollimationType: Literal['MLC', 'IrisCone', 'FixedCone', 'Undefined'] = ..., CyberKnifeNodeSetName: str = ..., CyberKnifeRampVersion: str = ..., CyberKnifeAllowIncreasedPitchCorrection: Optional[bool] = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a photon beam."""
        ...
    def CreateQAPlan(self, PhantomName: str, PhantomId: str, QAPlanName: str, IsoCenter: Any = ..., DoseGrid: Any = ..., GantryAngle: Optional[float] = ..., CollimatorAngle: Optional[float] = ..., CouchRotationAngle: Optional[float] = ..., ComputeDoseWhenPlanIsCreated: bool = ..., DesiredStatisticalUncertaintyForElectrons: Optional[float] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., RemoveCompensators: bool = ..., EnableDynamicTracking: bool = ..., SetupBeamsSettings: Union[SetupBeamsSettings, Any] = ...) -> None:
        """Creates a QA plan for a beam set."""
        ...
    def CreateRadiationSetScenarioGroup(self, Name: str, UseIsotropicPositionUncertainty: bool = ..., PositionUncertaintySuperior: float = ..., PositionUncertaintyInferior: float = ..., PositionUncertaintyPosterior: float = ..., PositionUncertaintyAnterior: float = ..., PositionUncertaintyLeft: float = ..., PositionUncertaintyRight: float = ..., PositionUncertaintyFormation: Literal['AxesEndPoints', 'DiagonalEndPoints', 'AxesAndDiagonalEndPoints', 'UserDefined', 'Automatic'] = ..., PositionUncertaintyList: List[Any] = ..., DensityUncertaintyPercent: float = ..., NumberOfDensityDiscretizationPoints: int = ..., ShallAddScenariosOnPlanningExamination: bool = ..., NamesOfNonPlanningExaminations: List[str] = ..., ComputeScenarioDosesAfterGroupCreation: bool = ..., IncludeZeroPositionUncertainty: bool = ...) -> RadiationSetScenarioGroup:
        """Create a RadiationSetScenarioGroup by specifying a name and one or more uncertainty types, such as patient position uncertainty shifts, and/or density uncertainty shifts."""
        ...
    def CreateReport(self, templateName: str, filename: str, ignoreWarnings: bool) -> str:
        """Create treatment plan report"""
        ...
    def CreateReportFromTemplateFile(self, templateFileName: str, filename: str, ignoreWarnings: bool) -> str:
        """Create treatment plan report from template file"""
        ...
    def DeleteBeam(self, BeamName: str) -> None:
        """Deletes a beam from the beam list."""
        ...
    def DeleteBeamSet(self) -> None:
        """Method for deleting a beam set."""
        ...
    def DeleteDoseSpecificationPoint(self, Name: str) -> None:
        """Action that deletes a dose specification point."""
        ...
    def DeletePrimaryPrescription(self) -> None:
        """Method for deleting the primary prescription."""
        ...
    def DeleteSetupBeam(self, BeamName: str) -> None:
        """Deletes a beam from the beam list."""
        ...
    def EditBrachyRadiationSet(self, SourceSerialNumber: str) -> None:
        """Edits a brachy radiation set."""
        ...
    def EditShowBeamVisualization(self, ShowBeams: bool, ShowContour: bool, ShowCenterLine: bool, ShowBeamsFromAllBeamSets: bool, ShowIsocenterNames: bool) -> None:
        """Setting beam related visualization settings."""
        ...
    def ExcludeRoiFromRadiationSet(self, RoiName: str) -> None:
        """Excludes ROI from list of ROIs that are specific to the beam set"""
        ...
    def GenerateConformalArcSegments(self, Beams: List[Any], IgnoreSmartAngles: bool = ...) -> None:
        """Creates segments for a Conformal Arc beam."""
        ...
    def GetArcTrajectory(self, BeamName: str) -> ArcTrajectory:
        """Returns the arc trajectory of the beam."""
        ...
    def GetDoseGrid(self) -> DoseGrid:
        """Gets the dose grid of the beam set."""
        ...
    def GetDoseImages(self, Orientations: List[str], Points: List[Any], FocusOnIsocenter: List[bool], ImageSize: Any, FocusOnRoi: str) -> List[str]:
        """Method for retrieving dose view images."""
        ...
    def GetIsocenterData(self, Name: str) -> Any:
        """Returns IsocenterData for an existing isocenter."""
        ...
    def GetIsoCenterDoseImages(self) -> List[str]:
        """Method for retrieving dose view images"""
        ...
    def GetOrderedIsocenters(self) -> List[Any]:
        """Gets a list of isocenter names ordered by beam number."""
        ...
    def GetPlanningExamination(self) -> Examination:
        """Gets the image set for which dose are calculated on during treatment planning."""
        ...
    def GetRadiationSetUuid(self) -> Optional[str]:
        """Gets the UUID from the RadiationSet"""
        ...
    def GetRoiNamePixelData(self) -> List[Any]:
        """Gets a 1D array the same size as the dose grid with ROI names for ROIs with material override in the corresponding dose grid voxel. The ROI name corresponds to the ROI which is covering"""
        ...
    def GetStructureSet(self) -> ExaminationStructureSet:
        """Gets the structure set for the planning image set of the beam set. It contains all structures defined on the image set."""
        ...
    def GetTreatmentTechniqueType(self) -> Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC']:
        """Returns the treatment technique type."""
        ...
    def HasImportedDose(self) -> bool:
        """Returns true if the dose has been imported, false otherwise."""
        ...
    def ImportClearanceMaps(self) -> None:
        """Imports clearance maps for all iso centers used in the beam set, computed using the specified margins"""
        ...
    def IncludeRoiInRadiationSet(self, RoiName: str) -> None:
        """Includes ROI in list of ROIs that are specific to the beam set"""
        ...
    def IsApprovedToUseAsBackgroundDose(self) -> bool:
        """Returns true if the dose has been approved to use as background dose (hence an imported dose which is being considered as clinical), false otherwise."""
        ...
    def MachineFeasibilityTest(self, TreatmentMachineName: str) -> str:
        """Returns string with information regarding if machine can be changed to 'TreatmentMachineName'. The string is empty if the change is feasible."""
        ...
    def MergeAutoBreastBeams(self) -> None:
        """Merge beams (A1 += A1_OPT, A2 += A2_OPT)."""
        ...
    def MergeBeamSegments(self, TargetBeamName: str, MergeBeamNames: List[str]) -> None:
        """Takes a target beam and a set of other beams and moves the segments from the other beams into the"""
        ...
    def MultiTargetBeamSetup(self, BeamNames: List[Any] = ..., MinNumberOfAdditionalBeams: np.ndarray = ..., MaxNumberOfAdditionalBeams: np.ndarray = ..., MinTotalNumberOfAdditionalBeams: int = ..., MaxTotalNumberOfAdditionalBeams: int = ..., MinDistanceBetweenTargetsTreatedTogether: float = ...) -> List[Any]:
        """This action modifies (i) the beam list, (ii) the treat ROIs selected per beam, and optionally (iii) the collimator angles, such that exposure between targets in the direction of MLC leaf motion is avoided as much as possible."""
        ...
    def PatientMarkingExport(self, OutputFormat: str, TargetDirectory: str, FileName: str) -> None:
        """Export patient marking"""
        ...
    def RegenerateDrrImageGenerators(self) -> None:
        """Regenerates DrrImageGenerator instances for a beam set. Can be used to correct an incorrect state for DRRs."""
        ...
    def RemoveSetupBeams(self) -> None:
        """Removes setup beams and turns off automatic setup beam creation."""
        ...
    def RemoveToleranceTable(self) -> None:
        """Remove tolerance table"""
        ...
    def ReverseBeam(self, BeamName: str) -> None:
        """Changes the beam so that the gantry rotates in the opposite direction."""
        ...
    def RunAutomaticFieldInFieldPlanning(self, NumberOfSubfieldsPerBeam: List[int] = ..., DoseTargetVolume: str = ..., TargetCoveragePushPercent: float = ..., DoseTargetConformMargin: float = ..., DoseTargetVolumeStrategy: Literal['Undefined', 'GenerateTargetROI', 'UseExistingROI'] = ..., ExposePrescriptionPoint: bool = ..., PrescriptionPointExposureMargin: float = ..., KeepAuxiliaryRois: bool = ...) -> None:
        """Automatically generate a field-in-field plan with uniform dose on a target volume."""
        ...
    def RunSmartAngles(self, BeamNames: List[Any] = ...) -> None:
        """Runs the Smart angles algorithm according to the beam angle initialization settings."""
        ...
    def ScaleToDoseGoal(self, DspName: str = ..., RoiNames: List[str] = ..., DoseValue: float = ..., DoseVolume: float = ..., PrescriptionType: Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose'] = ..., LockedBeamNames: List[str] = ..., EvaluateOptimizationFunctionsAfterScaling: bool = ..., IncludeBackgroundDose: bool = ...) -> None:
        """Scales the beam set dose and corresponding plan parameters to fulfill the specified dose goal."""
        ...
    def ScaleToPrimaryPrescriptionDoseReference(self, LockedBeamNames: List[str] = ..., EvaluateOptimizationFunctionsAfterScaling: bool = ...) -> None:
        """Scales the beam set dose and corresponding plan parameters to fulfill the primary prescription dose reference of the beam set."""
        ...
    def SendTransferredPlanToRayGateway(self, RayGatewayTitle: str, PreviousBeamSet: str = ..., OriginalBeamSet: str = ..., IgnorePreConditionWarnings: bool = ...) -> str:
        """Exports a transferred Tomo BeamSet to a specified RayGateway (and iDMS)."""
        ...
    def SetAllowIncreasedPitchCorrection(self, AllowIncreasedPitchCorrection: bool) -> RadiationSet:
        """Set if increased pitch correction should be used or not for a CyberKnife beam set."""
        ...
    def SetAutoScaleToPrimaryPrescription(self, AutoScale: bool = ...) -> None:
        """Activates or disables Auto scale to primary prescription for the beam set"""
        ...
    def SetBeamIsocenterColorVisualization(self) -> None:
        """Setting the beam color display type: isocenter."""
        ...
    def SetBeamIsVisible(self, BeamName: str, IsVisible: bool) -> None:
        """Setting if beam is visible or not."""
        ...
    def SetBeamSetBackrestPitchAngleFromImageSet(self) -> None:
        """Populates the backrest pitch angle of the beam set with the same value as the planning image set backrest pitch angle."""
        ...
    def SetCollimatorAngleInitializationSetting(self, Beam: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam], AngleSetting: Literal['PerBeam', 'PerControlPoint', 'None'] = ...) -> None:
        """Sets collimator angle initialization settings for a beam. Only supported for conformal arc beams."""
        ...
    def SetCollimatorAngleInitializationSettingForAllBeams(self, AngleSetting: Literal['PerBeam', 'PerControlPoint', 'None'] = ...) -> None:
        """Sets collimator angle initialization settings for all beams. Only supported for conformal arc beams."""
        ...
    def SetCurrent(self) -> None:
        """Sets the current Beam Set"""
        ...
    def SetDefaultDoseGrid(self, VoxelSize: Any = ...) -> RadiationSet:
        """Sets the dose grid of the beam set to cover the external ROI, the bolus, and support and fixation ROIs."""
        ...
    def SetDefaultFractionationPattern(self) -> None:
        """Sets/resets the fractionation pattern to default"""
        ...
    def SetDicomExportProperties(self, UseStereotacticApplicatorTypeForPhotonCones: Optional[bool] = ..., ExportedTreatmentMachineName: str = ...) -> None:
        """Sets DICOM export properties of a beam set."""
        ...
    def SetIndividualBeamColorVisualization(self) -> None:
        """Setting the beam color display type: individual."""
        ...
    def SetJawSetback(self, JawSetback: bool) -> None:
        """Setting jaw setback settings used to determine if jaws should be set back from the MLC by a margin during optimization or conforming."""
        ...
    def SetLeafPositioningThreshold(self, LeafPositioningThreshold: float = ...) -> None:
        """Setting leaf positioning threshold used around all treat areas when conforming the mlc."""
        ...
    def SetLineScanningDeliverableWeightsForAllBeams(self) -> None:
        """Rounds the line segment weights of all beams in the beamset to deliverable values"""
        ...
    def SetLineScanningHighestDeliverableDoseRates(self, DoseRateLimitMargin: float = ..., OnlyModifyNonDeliverableDoseRates: bool = ...) -> None:
        """Updates the segment dose rates of all beams in the beamset to deliverable values"""
        ...
    def SetMotionSynchronization(self, DisplayName: str = ..., MotionSynchronizationSettings: List[Any] = ..., RespiratoryIntervalTime: Optional[float] = ..., RespiratoryPhaseGatingDutyCycleTimePercentage: Optional[Union[Point2[float], Point2Dict[float]]] = ..., MotionSynchronizationTechniqueType: Literal['Undefined', 'Fiducial', 'FiducialWithRespiratory', 'FiducialWithInTempo', 'LungOneViewAWithRespiratory', 'LungOneViewBWithRespiratory', 'LungWithRespiratory', 'Skull', 'SkullWithInTempo', 'SpineSupine', 'SpineProneWithRespiratory', 'SpineSupineWithInTempo', 'Simulation', 'MedPhotonImaging'] = ...) -> None:
        """Sets motion synchronization parameters in a radiation set. Refer to the related beam model for valid compensation techniques and related settings."""
        ...
    def SetMUAndComputeDose(self) -> None:
        """Action that sets default MU on beams that has MU 0 and computes dose."""
        ...
    def SetPatientSetupTechnique(self, PatientSetupTechnique: str = ..., Comment: str = ...) -> None:
        """Setting PatientSetupTechnique of a BeamSet."""
        ...
    def SetPrescriptionDescription(self, Description: str = ...) -> None:
        """Sets or clears the description of a prescription."""
        ...
    def SetRayCareCustomLabels(self, PlanLabels: List[str] = ..., DoseLabels: List[str] = ..., DrrLabels: List[str] = ...) -> None:
        """Sets RayCare custom labels to be exported in DICOM objects related to a beam set."""
        ...
    def SetRbeModelReference(self, Name: str = ...) -> None:
        """Sets the RBE model reference property in current radiation set. A commissioned RBE model may be set according to its name."""
        ...
    def SetRestrictCollimatorAngleForSmartAngles(self, RestrictCollimatorAngleForSmartAngles: bool) -> None:
        """Setting restrict collimator angle for smart angles flag if the collimator angle from smart angles should be restricted based on the minimum collimator angle specified in RayPhysics"""
        ...
    def SetStandardBeamColorVisualization(self) -> None:
        """Setting the beam color display type: standard."""
        ...
    def SetToleranceTable(self, Label: str) -> None:
        """Sets a tolerance table for the selected beam set."""
        ...
    def SetTreatmentTechnique(self, Technique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ...) -> None:
        """Sets treatment technique for a beam set."""
        ...
    def SetTreatOrProtectRoiAllBeams(self, RoiName: str) -> None:
        """Select to use ROI as Treat or Protect for all beams, unless they already exist."""
        ...
    def SortSpots(self, MaximumStepLength: float = ..., UseFixedFirstSpot: bool = ..., PreferredDirection: Literal['NoPreference', 'X', 'Y'] = ..., OfflinePenaltyFactor: float = ...) -> None:
        """Adds a spot"""
        ...
    def SplitBeamSegmentsIntoBeams(self, BeamName: str) -> None:
        """Action that splits a beam containing multiple segments into several beams containing one segment each."""
        ...
    def TreatAndProtect(self, ShowProgress: bool = ...) -> RadiationSet:
        """Generate MLC or block aperture from treat and protect settings."""
        ...
    def UpdateDoseGrid(self, Corner: Any = ..., VoxelSize: Any = ..., NumberOfVoxels: Any = ...) -> RadiationSet:
        """Updates the dose grid of the beam set."""
        ...
    def UpdateSetupBeams(self, ResetSetupBeams: bool = ..., SetupBeamsGantryAngles: List[float] = ...) -> RadiationSet:
        """Updates setup beams"""
        ...

class TreatmentSetupIncludingRadiationSet:
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def DeliveryTechnique(self) -> Optional[Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']]: ...
    @property
    def DicomPlanLabel(self) -> str: ...
    @DicomPlanLabel.setter
    def DicomPlanLabel(self, value: str) -> None: ...
    @property
    def EnableDynamicTracking(self) -> bool: ...
    @property
    def FrameOfReference(self) -> str: ...
    @property
    def IsRbeIncludedInIonTreatmentMachine(self) -> Optional[bool]: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def Number(self) -> int: ...
    @property
    def PatientPosition(self) -> Optional[Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']]: ...
    @property
    def PlanGenerationTechnique(self) -> Literal['Imrt', 'Conformal', 'Mixed']: ...
    @property
    def PlanIntent(self) -> Literal['Undefined', 'Research', 'Recalculation', 'Machine_QA']: ...
    @property
    def UncommissionedMachineVersion(self) -> Optional[str]: ...
    @property
    def BeamImagerDrrSettings(self) -> ScriptObjectCollection[BeamImagerDrrSettings]: ...
    @BeamImagerDrrSettings.setter
    def BeamImagerDrrSettings(self, value: List[BeamImagerDrrSettings]) -> None: ...
    @property
    def Beams(self) -> List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]: ...
    @Beams.setter
    def Beams(self, value: List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]) -> None: ...
    @property
    def BrachyTreatmentSetup(self) -> BrachyTreatmentSetup: ...
    @BrachyTreatmentSetup.setter
    def BrachyTreatmentSetup(self, value: BrachyTreatmentSetup) -> None: ...
    @property
    def ChairSetup(self) -> ChairSetup: ...
    @ChairSetup.setter
    def ChairSetup(self, value: ChairSetup) -> None: ...
    @property
    def DependentSubStructureSet(self) -> SubStructureSet: ...
    @DependentSubStructureSet.setter
    def DependentSubStructureSet(self, value: SubStructureSet) -> None: ...
    @property
    def DicomExportProperties(self) -> DicomExportProperties: ...
    @DicomExportProperties.setter
    def DicomExportProperties(self, value: DicomExportProperties) -> None: ...
    @property
    def DoseSpecificationPoints(self) -> ScriptObjectCollection[DoseSpecificationPoint]: ...
    @DoseSpecificationPoints.setter
    def DoseSpecificationPoints(self, value: List[DoseSpecificationPoint]) -> None: ...
    @property
    def DrrImageGenerators(self) -> ScriptObjectCollection[DrrImageGenerator]: ...
    @property
    def DrrSettings(self) -> ScriptObjectCollection[DrrSettings]: ...
    @DrrSettings.setter
    def DrrSettings(self, value: List[DrrSettings]) -> None: ...
    @property
    def FractionationPattern(self) -> FractionationPattern: ...
    @FractionationPattern.setter
    def FractionationPattern(self, value: FractionationPattern) -> None: ...
    @property
    def FractionDose(self) -> FractionDose: ...
    @FractionDose.setter
    def FractionDose(self, value: FractionDose) -> None: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @ModificationInfo.setter
    def ModificationInfo(self, value: ModificationInfo) -> None: ...
    @property
    def PatientSetup(self) -> PatientSetup: ...
    @PatientSetup.setter
    def PatientSetup(self, value: PatientSetup) -> None: ...
    @property
    def Prescription(self) -> Prescription: ...
    @Prescription.setter
    def Prescription(self, value: Prescription) -> None: ...
    @property
    def PrescriptionNominalContributions(self) -> ScriptObjectCollection[NominalContribution]: ...
    @PrescriptionNominalContributions.setter
    def PrescriptionNominalContributions(self, value: List[NominalContribution]) -> None: ...
    @property
    def RayCareCustomLabels(self) -> RayCareCustomLabels: ...
    @RayCareCustomLabels.setter
    def RayCareCustomLabels(self, value: RayCareCustomLabels) -> None: ...
    @property
    def Review(self) -> Review: ...
    @Review.setter
    def Review(self, value: Review) -> None: ...
    def AddBeamFromBeamCommissioningField(self, Field: BeamCommissioningField, BeamQualityId: str, SSD: Optional[float] = ...) -> PhotonBeam:
        """Create a beam by copying from a beam commissioning field."""
        ...
    def AddCyberKnifeSegment(self, RelativeWeight: float = ..., UpdateExistingRelativeWeights: bool = ..., PitchAngle: float = ..., RollAngle: float = ..., YawAngle: float = ..., LeafPositionsLeft: np.ndarray = ..., LeafPositionsRight: np.ndarray = ..., SourcePositionX: float = ..., SourcePositionY: float = ..., SourcePositionZ: float = ..., ConeName: str = ..., ConeDiameter: float = ..., NodeId: int = ...) -> None:
        """Adds a CyberKnife segment to a beam. Works on beam set level, due to CyberKnife"""
        ...
    def AddOpposedBeam(self, BeamName: str) -> None:
        """Action that creates an opposed beam from an already existing beam."""
        ...
    def AddPoiPrescriptionDoseReference(self, PoiName: str, Description: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddRoiPrescriptionDoseReference(self, RoiName: str, DoseVolume: float = ..., PrescriptionType: Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose'] = ..., Description: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddSitePrescriptionDoseReference(self, Description: str, NameOfDoseSpecificationPoint: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Adds a prescription dose reference to the beam set prescription and sets it to primary if no primary prescription dose reference is defined."""
        ...
    def AddVirtualBlock(self, Beam: str, Contour: List[Any] = ..., Type: Literal['Treat', 'Protect', 'Undefined'] = ...) -> RadiationSet:
        """Adds a virtual block to the domain state."""
        ...
    def ApplyNamingConvention(self, NamingStrategy: str = ...) -> None:
        """Rename Beam Set and related Treatment Beams."""
        ...
    def AutoBreastAddRoisAndBeams(self, BeamQualityId: str, BeamQualityIdHighNominalEnergy: str = ..., SUPName: str = ..., INFName: str = ..., MEDName: str = ..., LATName: str = ..., ANTName: str = ..., SeparationThreshold: float = ...) -> None:
        """For auto breast planning only."""
        ...
    def BeamSetIdentifier(self) -> str:
        """Returns a beam set identifier which can be used for DICOM export"""
        ...
    def CheckBeamEntry(self) -> str:
        """Runs a beam entry validation of the beam set."""
        ...
    def CheckCyberKnifeDeliverability(self) -> str:
        """Runs a deliverability check for CyberKnife beams."""
        ...
    def ClearBeams(self, RemoveBeams: bool = ..., ClearBeamModifiers: bool = ..., BeamNames: List[str] = ...) -> None:
        """Removes beams or clear the contents of beams of a beam set."""
        ...
    def ClearTreatOrProtectRoiAllBeams(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for all beams."""
        ...
    def ClearUnusedIsocenters(self) -> None:
        """Clears unused isocenters that are not referenced by any beams."""
        ...
    def ComputeDose(self, RunEntryValidation: bool = ...) -> None:
        """Computes dose values for the beam set according to the dose computation settings"""
        ...
    def ComputeDoseOnAdditionalSets(self, Examinations: List[Examination], Fractions: List[TreatmentFraction] = ..., StoreBeamDoseValues: bool = ..., ComputeDoseAveragedLet: bool = ..., AllowGridExpansion: bool = ...) -> List[FractionDose]:
        """Compute beam set dose on additional image sets."""
        ...
    def ComputePerturbedDose(self, DensityShift: float = ..., PatientShift: Any = ..., RotationPoint: Optional[Union[Point3[float], Point3Dict[float]]] = ..., YawDegrees: float = ..., PitchDegrees: float = ..., RollDegrees: float = ..., Examinations: List[Examination] = ..., Fractions: List[TreatmentFraction] = ..., StoreBeamDoseValues: bool = ..., ComputeDoseAveragedLet: bool = ..., AllowGridExpansion: bool = ...) -> List[FractionDose]:
        """Compute perturbed dose on a beam set."""
        ...
    def ConformAllIonApertures(self) -> None:
        """Conforms block and MLC apertures for all beams with a treat ROI defined (energy layers must exist for PBS/LS to conform MLC aperture)"""
        ...
    def ConvertPBSArcBeamSetIntoPBS(self) -> None:
        """Converts a PBS Arc beam set to PBS. The resulting beam set has a separate beam for each distinct gantry angle in the converted PBS Arc beams."""
        ...
    def CopyAndReverseBeam(self, BeamName: str) -> None:
        """Creates a copy of the beam for which the gantry rotates in the opposite direction."""
        ...
    def CopyBeam(self, BeamName: str) -> None:
        """Creates a copy of the specified beam and appends the copy to the beam list."""
        ...
    def CopyBeamFromBeamSet(self, BeamToCopy: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam], ResetBeamMu: bool = ...) -> None:
        """Copy beam from beam set."""
        ...
    def CopyBeamsFromBeamSet(self, BeamSetToCopyFrom: RadiationSet, BeamsToCopy: List[str] = ...) -> None:
        """Makes beam copies from selected beam set and attaches them to the context."""
        ...
    def CreateAdaptedBeamSet(self, AdaptedPlan: TreatmentPlan, Name: str, NumberOfFractions: int, RegistrationType: Literal['DeformableRegistration', 'FrameOfReferenceRegistration'] = ...) -> None:
        """Creates an adapted beam set from the base beam set and adds it to the specified adapted plan."""
        ...
    def CreateArcBeam(self, ArcStopGantryAngle: Optional[float] = ..., ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., BeamQualityId: str = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a beam of VMAT type."""
        ...
    def CreateBnctBeam(self, PlannedBloodBoronConcentration: Optional[float] = ..., CollimatorName: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> BnctBeam:
        """Creates and adds a BNCT beam."""
        ...
    def CreateBroadIonBeam(self, SnoutId: str, MinimumAirGap: Optional[float] = ..., PolarGazeAngle: float = ..., AzimuthalGazeAngle: float = ..., TwistAngle: float = ..., SkinPlanePosition: float = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of Single Scattering/Double Scattering/Uniform Scanning/Wobbling beam delivery type."""
        ...
    def CreateDefaultIsocenterData(self, Position: Any) -> Any:
        """Returns default IsocenterData for a position."""
        ...
    def CreateDoseSpecificationPoint(self, Name: str, Coordinates: Any = ..., VisualizationDiameter: float = ...) -> DoseSpecificationPoint:
        """Action that creates a dose specification point."""
        ...
    def CreateElectronBeam(self, ApplicatorName: str, BeamQualityId: str, InsertName: str = ..., IsAddCutoutChecked: bool = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> ElectronBeam:
        """Creates and adds a beam of electron type."""
        ...
    def CreateEPIDResponse(self, PhantomName: str, PhantomId: str, QAPlanName: str, IsoCenter: Any, DoseGrid: Any, GantryAngle: Optional[float] = ..., CollimatorAngle: Optional[float] = ..., CouchRotationAngle: Optional[float] = ..., ApplyFloodFieldCorrection: bool = ..., SingleFloodFieldBeamQualityId: str = ..., FloodFieldFactor: float = ...) -> None:
        """Creates an EPID QA plan and predicts response for the beams in a beam set."""
        ...
    def CreateEQD2Dose(self, Priorities: np.ndarray, AlphaBetas: np.ndarray, Rois: List[RegionOfInterest]) -> None:
        """Converts a fraction dose into an EQD2 dose and adds that dose to evaluation doses."""
        ...
    def CreatePBSIonBeam(self, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., ArcStopGantryAngle: Optional[float] = ..., SnoutId: str = ..., RangeShifter: str = ..., MinimumAirGap: Optional[float] = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of PBS (or Line scanning or PBS Arc) ion type."""
        ...
    def CreatePhotonBeam(self, BeamQualityId: str, CyberKnifeCollimationType: Literal['MLC', 'IrisCone', 'FixedCone', 'Undefined'] = ..., CyberKnifeNodeSetName: str = ..., CyberKnifeRampVersion: str = ..., CyberKnifeAllowIncreasedPitchCorrection: Optional[bool] = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a photon beam."""
        ...
    def CreateQAPlan(self, PhantomName: str, PhantomId: str, QAPlanName: str, IsoCenter: Any = ..., DoseGrid: Any = ..., GantryAngle: Optional[float] = ..., CollimatorAngle: Optional[float] = ..., CouchRotationAngle: Optional[float] = ..., ComputeDoseWhenPlanIsCreated: bool = ..., DesiredStatisticalUncertaintyForElectrons: Optional[float] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., RemoveCompensators: bool = ..., EnableDynamicTracking: bool = ..., SetupBeamsSettings: Union[SetupBeamsSettings, Any] = ...) -> None:
        """Creates a QA plan for a beam set."""
        ...
    def CreateRadiationSetScenarioGroup(self, Name: str, UseIsotropicPositionUncertainty: bool = ..., PositionUncertaintySuperior: float = ..., PositionUncertaintyInferior: float = ..., PositionUncertaintyPosterior: float = ..., PositionUncertaintyAnterior: float = ..., PositionUncertaintyLeft: float = ..., PositionUncertaintyRight: float = ..., PositionUncertaintyFormation: Literal['AxesEndPoints', 'DiagonalEndPoints', 'AxesAndDiagonalEndPoints', 'UserDefined', 'Automatic'] = ..., PositionUncertaintyList: List[Any] = ..., DensityUncertaintyPercent: float = ..., NumberOfDensityDiscretizationPoints: int = ..., ShallAddScenariosOnPlanningExamination: bool = ..., NamesOfNonPlanningExaminations: List[str] = ..., ComputeScenarioDosesAfterGroupCreation: bool = ..., IncludeZeroPositionUncertainty: bool = ...) -> RadiationSetScenarioGroup:
        """Create a RadiationSetScenarioGroup by specifying a name and one or more uncertainty types, such as patient position uncertainty shifts, and/or density uncertainty shifts."""
        ...
    def CreateReport(self, templateName: str, filename: str, ignoreWarnings: bool) -> str:
        """Create treatment plan report"""
        ...
    def CreateReportFromTemplateFile(self, templateFileName: str, filename: str, ignoreWarnings: bool) -> str:
        """Create treatment plan report from template file"""
        ...
    def DeleteBeam(self, BeamName: str) -> None:
        """Deletes a beam from the beam list."""
        ...
    def DeleteBeamSet(self) -> None:
        """Method for deleting a beam set."""
        ...
    def DeleteDoseSpecificationPoint(self, Name: str) -> None:
        """Action that deletes a dose specification point."""
        ...
    def DeletePrimaryPrescription(self) -> None:
        """Method for deleting the primary prescription."""
        ...
    def DeleteSetupBeam(self, BeamName: str) -> None:
        """Deletes a beam from the beam list."""
        ...
    def EditBrachyRadiationSet(self, SourceSerialNumber: str) -> None:
        """Edits a brachy radiation set."""
        ...
    def EditShowBeamVisualization(self, ShowBeams: bool, ShowContour: bool, ShowCenterLine: bool, ShowBeamsFromAllBeamSets: bool, ShowIsocenterNames: bool) -> None:
        """Setting beam related visualization settings."""
        ...
    def ExcludeRoiFromRadiationSet(self, RoiName: str) -> None:
        """Excludes ROI from list of ROIs that are specific to the beam set"""
        ...
    def GenerateConformalArcSegments(self, Beams: List[Any], IgnoreSmartAngles: bool = ...) -> None:
        """Creates segments for a Conformal Arc beam."""
        ...
    def GetArcTrajectory(self, BeamName: str) -> ArcTrajectory:
        """Returns the arc trajectory of the beam."""
        ...
    def GetDoseGrid(self) -> DoseGrid:
        """Gets the dose grid of the beam set."""
        ...
    def GetDoseImages(self, Orientations: List[str], Points: List[Any], FocusOnIsocenter: List[bool], ImageSize: Any, FocusOnRoi: str) -> List[str]:
        """Method for retrieving dose view images."""
        ...
    def GetIsocenterData(self, Name: str) -> Any:
        """Returns IsocenterData for an existing isocenter."""
        ...
    def GetIsoCenterDoseImages(self) -> List[str]:
        """Method for retrieving dose view images"""
        ...
    def GetOrderedIsocenters(self) -> List[Any]:
        """Gets a list of isocenter names ordered by beam number."""
        ...
    def GetPlanningExamination(self) -> Examination:
        """Gets the image set for which dose are calculated on during treatment planning."""
        ...
    def GetRadiationSetUuid(self) -> Optional[str]:
        """Gets the UUID from the RadiationSet"""
        ...
    def GetRoiNamePixelData(self) -> List[Any]:
        """Gets a 1D array the same size as the dose grid with ROI names for ROIs with material override in the corresponding dose grid voxel. The ROI name corresponds to the ROI which is covering"""
        ...
    def GetStructureSet(self) -> ExaminationStructureSet:
        """Gets the structure set for the planning image set of the beam set. It contains all structures defined on the image set."""
        ...
    def GetTreatmentTechniqueType(self) -> Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC']:
        """Returns the treatment technique type."""
        ...
    def HasImportedDose(self) -> bool:
        """Returns true if the dose has been imported, false otherwise."""
        ...
    def ImportClearanceMaps(self) -> None:
        """Imports clearance maps for all iso centers used in the beam set, computed using the specified margins"""
        ...
    def IncludeRoiInRadiationSet(self, RoiName: str) -> None:
        """Includes ROI in list of ROIs that are specific to the beam set"""
        ...
    def IsApprovedToUseAsBackgroundDose(self) -> bool:
        """Returns true if the dose has been approved to use as background dose (hence an imported dose which is being considered as clinical), false otherwise."""
        ...
    def MachineFeasibilityTest(self, TreatmentMachineName: str) -> str:
        """Returns string with information regarding if machine can be changed to 'TreatmentMachineName'. The string is empty if the change is feasible."""
        ...
    def MergeAutoBreastBeams(self) -> None:
        """Merge beams (A1 += A1_OPT, A2 += A2_OPT)."""
        ...
    def MergeBeamSegments(self, TargetBeamName: str, MergeBeamNames: List[str]) -> None:
        """Takes a target beam and a set of other beams and moves the segments from the other beams into the"""
        ...
    def MultiTargetBeamSetup(self, BeamNames: List[Any] = ..., MinNumberOfAdditionalBeams: np.ndarray = ..., MaxNumberOfAdditionalBeams: np.ndarray = ..., MinTotalNumberOfAdditionalBeams: int = ..., MaxTotalNumberOfAdditionalBeams: int = ..., MinDistanceBetweenTargetsTreatedTogether: float = ...) -> List[Any]:
        """This action modifies (i) the beam list, (ii) the treat ROIs selected per beam, and optionally (iii) the collimator angles, such that exposure between targets in the direction of MLC leaf motion is avoided as much as possible."""
        ...
    def PatientMarkingExport(self, OutputFormat: str, TargetDirectory: str, FileName: str) -> None:
        """Export patient marking"""
        ...
    def RegenerateDrrImageGenerators(self) -> None:
        """Regenerates DrrImageGenerator instances for a beam set. Can be used to correct an incorrect state for DRRs."""
        ...
    def RemoveSetupBeams(self) -> None:
        """Removes setup beams and turns off automatic setup beam creation."""
        ...
    def RemoveToleranceTable(self) -> None:
        """Remove tolerance table"""
        ...
    def ReverseBeam(self, BeamName: str) -> None:
        """Changes the beam so that the gantry rotates in the opposite direction."""
        ...
    def RunAutomaticFieldInFieldPlanning(self, NumberOfSubfieldsPerBeam: List[int] = ..., DoseTargetVolume: str = ..., TargetCoveragePushPercent: float = ..., DoseTargetConformMargin: float = ..., DoseTargetVolumeStrategy: Literal['Undefined', 'GenerateTargetROI', 'UseExistingROI'] = ..., ExposePrescriptionPoint: bool = ..., PrescriptionPointExposureMargin: float = ..., KeepAuxiliaryRois: bool = ...) -> None:
        """Automatically generate a field-in-field plan with uniform dose on a target volume."""
        ...
    def RunSmartAngles(self, BeamNames: List[Any] = ...) -> None:
        """Runs the Smart angles algorithm according to the beam angle initialization settings."""
        ...
    def ScaleToDoseGoal(self, DspName: str = ..., RoiNames: List[str] = ..., DoseValue: float = ..., DoseVolume: float = ..., PrescriptionType: Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose'] = ..., LockedBeamNames: List[str] = ..., EvaluateOptimizationFunctionsAfterScaling: bool = ..., IncludeBackgroundDose: bool = ...) -> None:
        """Scales the beam set dose and corresponding plan parameters to fulfill the specified dose goal."""
        ...
    def ScaleToPrimaryPrescriptionDoseReference(self, LockedBeamNames: List[str] = ..., EvaluateOptimizationFunctionsAfterScaling: bool = ...) -> None:
        """Scales the beam set dose and corresponding plan parameters to fulfill the primary prescription dose reference of the beam set."""
        ...
    def SendTransferredPlanToRayGateway(self, RayGatewayTitle: str, PreviousBeamSet: str = ..., OriginalBeamSet: str = ..., IgnorePreConditionWarnings: bool = ...) -> str:
        """Exports a transferred Tomo BeamSet to a specified RayGateway (and iDMS)."""
        ...
    def SetAllowIncreasedPitchCorrection(self, AllowIncreasedPitchCorrection: bool) -> RadiationSet:
        """Set if increased pitch correction should be used or not for a CyberKnife beam set."""
        ...
    def SetAutoScaleToPrimaryPrescription(self, AutoScale: bool = ...) -> None:
        """Activates or disables Auto scale to primary prescription for the beam set"""
        ...
    def SetBeamIsocenterColorVisualization(self) -> None:
        """Setting the beam color display type: isocenter."""
        ...
    def SetBeamIsVisible(self, BeamName: str, IsVisible: bool) -> None:
        """Setting if beam is visible or not."""
        ...
    def SetBeamSetBackrestPitchAngleFromImageSet(self) -> None:
        """Populates the backrest pitch angle of the beam set with the same value as the planning image set backrest pitch angle."""
        ...
    def SetCollimatorAngleInitializationSetting(self, Beam: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam], AngleSetting: Literal['PerBeam', 'PerControlPoint', 'None'] = ...) -> None:
        """Sets collimator angle initialization settings for a beam. Only supported for conformal arc beams."""
        ...
    def SetCollimatorAngleInitializationSettingForAllBeams(self, AngleSetting: Literal['PerBeam', 'PerControlPoint', 'None'] = ...) -> None:
        """Sets collimator angle initialization settings for all beams. Only supported for conformal arc beams."""
        ...
    def SetCurrent(self) -> None:
        """Sets the current Beam Set"""
        ...
    def SetDefaultDoseGrid(self, VoxelSize: Any = ...) -> RadiationSet:
        """Sets the dose grid of the beam set to cover the external ROI, the bolus, and support and fixation ROIs."""
        ...
    def SetDefaultFractionationPattern(self) -> None:
        """Sets/resets the fractionation pattern to default"""
        ...
    def SetDicomExportProperties(self, UseStereotacticApplicatorTypeForPhotonCones: Optional[bool] = ..., ExportedTreatmentMachineName: str = ...) -> None:
        """Sets DICOM export properties of a beam set."""
        ...
    def SetIndividualBeamColorVisualization(self) -> None:
        """Setting the beam color display type: individual."""
        ...
    def SetJawSetback(self, JawSetback: bool) -> None:
        """Setting jaw setback settings used to determine if jaws should be set back from the MLC by a margin during optimization or conforming."""
        ...
    def SetLeafPositioningThreshold(self, LeafPositioningThreshold: float = ...) -> None:
        """Setting leaf positioning threshold used around all treat areas when conforming the mlc."""
        ...
    def SetLineScanningDeliverableWeightsForAllBeams(self) -> None:
        """Rounds the line segment weights of all beams in the beamset to deliverable values"""
        ...
    def SetLineScanningHighestDeliverableDoseRates(self, DoseRateLimitMargin: float = ..., OnlyModifyNonDeliverableDoseRates: bool = ...) -> None:
        """Updates the segment dose rates of all beams in the beamset to deliverable values"""
        ...
    def SetMotionSynchronization(self, DisplayName: str = ..., MotionSynchronizationSettings: List[Any] = ..., RespiratoryIntervalTime: Optional[float] = ..., RespiratoryPhaseGatingDutyCycleTimePercentage: Optional[Union[Point2[float], Point2Dict[float]]] = ..., MotionSynchronizationTechniqueType: Literal['Undefined', 'Fiducial', 'FiducialWithRespiratory', 'FiducialWithInTempo', 'LungOneViewAWithRespiratory', 'LungOneViewBWithRespiratory', 'LungWithRespiratory', 'Skull', 'SkullWithInTempo', 'SpineSupine', 'SpineProneWithRespiratory', 'SpineSupineWithInTempo', 'Simulation', 'MedPhotonImaging'] = ...) -> None:
        """Sets motion synchronization parameters in a radiation set. Refer to the related beam model for valid compensation techniques and related settings."""
        ...
    def SetMUAndComputeDose(self) -> None:
        """Action that sets default MU on beams that has MU 0 and computes dose."""
        ...
    def SetPatientSetupTechnique(self, PatientSetupTechnique: str = ..., Comment: str = ...) -> None:
        """Setting PatientSetupTechnique of a BeamSet."""
        ...
    def SetPrescriptionDescription(self, Description: str = ...) -> None:
        """Sets or clears the description of a prescription."""
        ...
    def SetRayCareCustomLabels(self, PlanLabels: List[str] = ..., DoseLabels: List[str] = ..., DrrLabels: List[str] = ...) -> None:
        """Sets RayCare custom labels to be exported in DICOM objects related to a beam set."""
        ...
    def SetRbeModelReference(self, Name: str = ...) -> None:
        """Sets the RBE model reference property in current radiation set. A commissioned RBE model may be set according to its name."""
        ...
    def SetRestrictCollimatorAngleForSmartAngles(self, RestrictCollimatorAngleForSmartAngles: bool) -> None:
        """Setting restrict collimator angle for smart angles flag if the collimator angle from smart angles should be restricted based on the minimum collimator angle specified in RayPhysics"""
        ...
    def SetStandardBeamColorVisualization(self) -> None:
        """Setting the beam color display type: standard."""
        ...
    def SetToleranceTable(self, Label: str) -> None:
        """Sets a tolerance table for the selected beam set."""
        ...
    def SetTreatmentTechnique(self, Technique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ...) -> None:
        """Sets treatment technique for a beam set."""
        ...
    def SetTreatOrProtectRoiAllBeams(self, RoiName: str) -> None:
        """Select to use ROI as Treat or Protect for all beams, unless they already exist."""
        ...
    def SortSpots(self, MaximumStepLength: float = ..., UseFixedFirstSpot: bool = ..., PreferredDirection: Literal['NoPreference', 'X', 'Y'] = ..., OfflinePenaltyFactor: float = ...) -> None:
        """Adds a spot"""
        ...
    def SplitBeamSegmentsIntoBeams(self, BeamName: str) -> None:
        """Action that splits a beam containing multiple segments into several beams containing one segment each."""
        ...
    def TreatAndProtect(self, ShowProgress: bool = ...) -> RadiationSet:
        """Generate MLC or block aperture from treat and protect settings."""
        ...
    def UpdateDoseGrid(self, Corner: Any = ..., VoxelSize: Any = ..., NumberOfVoxels: Any = ...) -> RadiationSet:
        """Updates the dose grid of the beam set."""
        ...
    def UpdateSetupBeams(self, ResetSetupBeams: bool = ..., SetupBeamsGantryAngles: List[float] = ...) -> RadiationSet:
        """Updates setup beams"""
        ...

class TreatmentSetup:
    @property
    def DeliveryTechnique(self) -> Optional[Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']]: ...
    @property
    def EnableDynamicTracking(self) -> bool: ...
    @property
    def IsRbeIncludedInIonTreatmentMachine(self) -> Optional[bool]: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def PatientPosition(self) -> Optional[Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']]: ...
    @property
    def UncommissionedMachineVersion(self) -> Optional[str]: ...
    @property
    def Beams(self) -> List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]: ...
    @Beams.setter
    def Beams(self, value: List[Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]]) -> None: ...
    @property
    def ChairSetup(self) -> ChairSetup: ...
    @ChairSetup.setter
    def ChairSetup(self, value: ChairSetup) -> None: ...
    def ClearUnusedIsocenters(self) -> None:
        """Clears unused isocenters that are not referenced by any beams."""
        ...
    def ConformAllIonApertures(self) -> None:
        """Conforms block and MLC apertures for all beams with a treat ROI defined (energy layers must exist for PBS/LS to conform MLC aperture)"""
        ...
    def CopyBeam(self, BeamName: str) -> None:
        """Creates a copy of the specified beam and appends the copy to the beam list."""
        ...
    def CreateArcBeam(self, ArcStopGantryAngle: Optional[float] = ..., ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., BeamQualityId: str = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a beam of VMAT type."""
        ...
    def CreateBnctBeam(self, PlannedBloodBoronConcentration: Optional[float] = ..., CollimatorName: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> BnctBeam:
        """Creates and adds a BNCT beam."""
        ...
    def CreateBroadIonBeam(self, SnoutId: str, MinimumAirGap: Optional[float] = ..., PolarGazeAngle: float = ..., AzimuthalGazeAngle: float = ..., TwistAngle: float = ..., SkinPlanePosition: float = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of Single Scattering/Double Scattering/Uniform Scanning/Wobbling beam delivery type."""
        ...
    def CreateElectronBeam(self, ApplicatorName: str, BeamQualityId: str, InsertName: str = ..., IsAddCutoutChecked: bool = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> ElectronBeam:
        """Creates and adds a beam of electron type."""
        ...
    def CreatePBSIonBeam(self, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ..., ArcStopGantryAngle: Optional[float] = ..., SnoutId: str = ..., RangeShifter: str = ..., MinimumAirGap: Optional[float] = ..., MetersetRateSetting: str = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> IonBeam:
        """Creates and adds a beam of PBS (or Line scanning or PBS Arc) ion type."""
        ...
    def CreatePhotonBeam(self, BeamQualityId: str, CyberKnifeCollimationType: Literal['MLC', 'IrisCone', 'FixedCone', 'Undefined'] = ..., CyberKnifeNodeSetName: str = ..., CyberKnifeRampVersion: str = ..., CyberKnifeAllowIncreasedPitchCorrection: Optional[bool] = ..., GimbalPanAngle: float = ..., GimbalTiltAngle: float = ..., XRayIrradiatorTubeCurrent: Optional[float] = ..., IsocenterData: Union[IsocenterData, Any] = ..., Name: str = ..., Description: str = ..., GantryAngle: float = ..., CouchRotationAngle: float = ..., CouchPitchAngle: float = ..., CouchRollAngle: float = ..., CollimatorAngle: float = ...) -> PhotonBeam:
        """Creates and adds a photon beam."""
        ...
    def DeleteBeam(self, BeamName: str) -> None:
        """Deletes a beam from the beam list."""
        ...
    def SetLineScanningDeliverableWeightsForAllBeams(self) -> None:
        """Rounds the line segment weights of all beams in the beamset to deliverable values"""
        ...
    def SetLineScanningHighestDeliverableDoseRates(self, DoseRateLimitMargin: float = ..., OnlyModifyNonDeliverableDoseRates: bool = ...) -> None:
        """Updates the segment dose rates of all beams in the beamset to deliverable values"""
        ...
