from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.clearance import CollisionCheckScenario
    from raystation.v2025.clinic_db import ConformalArcSettings, DmlcDefaultSettings, SmlcDefaultSettings, ThreeDCRTSettings, VmatDefaultSettings
    from raystation.v2025.dose import DoseAlgorithmVersion, DoseGrid, DoseGridRoi, DoseSpecificationPoint, DoseValues
    from raystation.v2025.imaging import DrrSettings
    from raystation.v2025.ion import IonBeam, IonDoseDeliveryCharacteristics
    from raystation.v2025.machine import CyberKnifeDefaultSettings, CyberKnifePropertiesPerBeam, Linac, MachineReference
    from raystation.v2025.machine_db_types import ApplicatorWithInsertSettings, BlockTrayTransmission, Calibration, CalibrationPoint, Collimator, ComputationSettings, ComputedDoseCurve, ComputedDoseCurvesGammaSettings, Cone, ConeCorrection, ConeFactor, CryostatTransmissionFactors, EnergySpectrumOptimization, LinacPhysics, Material, MeasuredDoseCurve, MillingTool, MlcLayer, ModelingStep, ModificationInfo, NormalizedDoseCurve, OutputFactor, OutputFactorCorrections, PrimarySource, RadialDistribution, SecondarySource, SiemensVirtualWedgeProperties, Wedge, WedgeFactor, WedgeFactorCorrections, WedgeParameters
    from raystation.v2025.patient import PatientToBeamMapping
    from raystation.v2025.patient_db_types import Block, BlockTray, BnctBeam, BraggPeakPositions, Compensator, DensityDistribution, EqdParameters, EqdRecoveryCorrectionParameters, FluenceMap, InterplayDoseProperties, MaterialOverride, MitsubishiReferenceValue, PerturbedDoseProperties, RegionOfInterest, Segment, SegmentBaseProperties, SitePrescriptionDoseReference, SpotsDelivery, VersioningStatus
    from raystation.v2025.roi import RoiGeometry, RoiPrescriptionDoseReference
    from raystation.v2025.setup import SetupBeam
    from raystation.v2025.tomo import TomoDirectDefaultSettings, TomoHelicalDefaultSettings, TomoPropertiesPerBeam



class BeamNominalContribution:
    @property
    def BeamContribution(self) -> float: ...
    @property
    def FromBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @property
    def ToPrescriptionDoseReference(self) -> Union[RoiPrescriptionDoseReference, SitePrescriptionDoseReference]: ...

class BeamImagerDrrSettings:
    @property
    def ForImager(self) -> str: ...
    @ForImager.setter
    def ForImager(self, value: str) -> None: ...
    @property
    def ForImagingSystem(self) -> str: ...
    @ForImagingSystem.setter
    def ForImagingSystem(self, value: str) -> None: ...
    @property
    def DrrSettings(self) -> DrrSettings: ...
    @DrrSettings.setter
    def DrrSettings(self, value: DrrSettings) -> None: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...

class BeamFractionDose:
    @property
    def Name(self) -> str: ...
    @property
    def BoliRoiGeometries(self) -> ScriptObjectCollection[RoiGeometry]: ...
    @property
    def BolusDensities(self) -> ScriptObjectCollection[MaterialOverride]: ...
    @property
    def BraggPeakPositions(self) -> ScriptObjectCollection[BraggPeakPositions]: ...
    @BraggPeakPositions.setter
    def BraggPeakPositions(self, value: List[BraggPeakPositions]) -> None: ...
    @property
    def DoseAtPoint(self) -> BeamDoseAtPoint: ...
    @DoseAtPoint.setter
    def DoseAtPoint(self, value: BeamDoseAtPoint) -> None: ...
    @property
    def DoseValues(self) -> DoseValues: ...
    @DoseValues.setter
    def DoseValues(self, value: DoseValues) -> None: ...
    @property
    def EqdParameters(self) -> EqdParameters: ...
    @EqdParameters.setter
    def EqdParameters(self, value: EqdParameters) -> None: ...
    @property
    def EqdRecoveryCorrectionParameters(self) -> EqdRecoveryCorrectionParameters: ...
    @EqdRecoveryCorrectionParameters.setter
    def EqdRecoveryCorrectionParameters(self, value: EqdRecoveryCorrectionParameters) -> None: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...
    @property
    def ImportedDoseAtPoint_ForDisplayUseOnly(self) -> BeamDoseAtPoint: ...
    @ImportedDoseAtPoint_ForDisplayUseOnly.setter
    def ImportedDoseAtPoint_ForDisplayUseOnly(self, value: BeamDoseAtPoint) -> None: ...
    @property
    def InDoseGrid(self) -> DoseGrid: ...
    @InDoseGrid.setter
    def InDoseGrid(self, value: DoseGrid) -> None: ...
    @property
    def InterplayDoseProperties(self) -> InterplayDoseProperties: ...
    @InterplayDoseProperties.setter
    def InterplayDoseProperties(self, value: InterplayDoseProperties) -> None: ...
    @property
    def IonDoseDeliveryCharacteristics(self) -> IonDoseDeliveryCharacteristics: ...
    @IonDoseDeliveryCharacteristics.setter
    def IonDoseDeliveryCharacteristics(self, value: IonDoseDeliveryCharacteristics) -> None: ...
    @property
    def MitsubishiReferenceValue(self) -> MitsubishiReferenceValue: ...
    @MitsubishiReferenceValue.setter
    def MitsubishiReferenceValue(self, value: MitsubishiReferenceValue) -> None: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @ModificationInfo.setter
    def ModificationInfo(self, value: ModificationInfo) -> None: ...
    @property
    def OnDensity(self) -> DensityDistribution: ...
    @OnDensity.setter
    def OnDensity(self, value: DensityDistribution) -> None: ...
    @property
    def PerturbedDoseProperties(self) -> PerturbedDoseProperties: ...
    @PerturbedDoseProperties.setter
    def PerturbedDoseProperties(self, value: PerturbedDoseProperties) -> None: ...
    @property
    def SpotsDeliverySettings(self) -> ScriptObjectCollection[SpotsDelivery]: ...
    @SpotsDeliverySettings.setter
    def SpotsDeliverySettings(self, value: List[SpotsDelivery]) -> None: ...
    @property
    def UserSetBeamDoseSpecificationPoint(self) -> DoseSpecificationPoint: ...
    @UserSetBeamDoseSpecificationPoint.setter
    def UserSetBeamDoseSpecificationPoint(self, value: DoseSpecificationPoint) -> None: ...
    @property
    def VersioningStatus(self) -> VersioningStatus: ...
    @VersioningStatus.setter
    def VersioningStatus(self, value: VersioningStatus) -> None: ...
    def DeleteEvaluationDose(self) -> None:
        """Deletes the dose distribution if it is an evaluation dose."""
        ...
    def GetCoordinateOfMaxDose(self) -> Tuple[float, ...]:
        """Get the coordinate corresponding to the max dose."""
        ...
    def GetDoseAtRelativeVolumes(self, RoiName: str, RelativeVolumes: List[float]) -> np.ndarray:
        """Method for retrieving DVH points."""
        ...
    def GetDoseGridRoi(self, RoiName: str) -> DoseGridRoi:
        """Gets the dose grid representation of a specific ROI for the dose grid of the dose distribution."""
        ...
    def GetDoseStatistic(self, RoiName: str, DoseType: str) -> float:
        """Method for retrieving dose statistics."""
        ...
    def GetRelativeVolumeAtDoseValues(self, RoiName: str, DoseValues: List[float]) -> np.ndarray:
        """Method for retrieving DVH points."""
        ...
    def GetTransformedAndResampledDoseValues(self, DoseGrid: DoseGrid) -> np.ndarray:
        """Resamples the dose distribution to the given dose grid."""
        ...
    def HasClinicalDose(self) -> bool:
        """Indicates if there is a dose that is considered clinically relevant for treatment."""
        ...
    def InterpolateDoseInPoint(self, Point: Any, PointFrameOfReference: str) -> float:
        """Returns interpolated dose value in point."""
        ...
    def InterpolateDoseInPoints(self, Points: List[Any], PointsFrameOfReference: str) -> np.ndarray:
        """Returns an array of interpolated dose values in the given array of points."""
        ...
    def SetDoseValues(self, Dose: np.ndarray, CalculationInfo: str = ..., DoseAlgorithm: str = ..., DoseUncertainties: np.ndarray = ..., ParticleEnergySpectraDose: np.ndarray = ..., DoseAveragedLet: np.ndarray = ..., DoseAveragedAlpha: np.ndarray = ..., DoseAveragedSqrtBeta: np.ndarray = ...) -> None:
        """Method for setting dose data in a dose distribution. Can also be used to set dose-averaged LET data in a corresponding distribution. The length of the provided arrays must match the number of voxels in the dose grid. The elements are iterated in X first, then Y and Z. If the dose distribution is a fraction dose from a BeamSet that belongs to a plan then the total dose of the plan is automatically updated. DoseAlgorithm will by default be set as 'Undefined'."""
        ...
    def SetWeightedDose(self, PlanNames: List[Any], Weights: np.ndarray) -> None:
        """Sets the dose to a weighted sum of the"""
        ...
    def UpdateDoseGridStructures(self) -> None:
        """Computes uncomputed RoiVolumeDistributions. If the current DoseGridStructures of the DoseDistribution contains DoseGridRois computed with an old algorithm version, the DoseGridStructures will be replaced with a new version."""
        ...

class BeamDoseAtPoint:
    @property
    def CompensatorPhysicalThickness(self) -> Optional[float]: ...
    @property
    def DoseValue(self) -> Optional[float]: ...
    @property
    def PhysicalDepth(self) -> Optional[float]: ...
    @property
    def RadiologicalDepth(self) -> Optional[float]: ...

class ArcSegment:
    @property
    def CollimatorAngle(self) -> float: ...
    @property
    def DeltaCouchAngle(self) -> float: ...
    @DeltaCouchAngle.setter
    def DeltaCouchAngle(self, value: float) -> None: ...
    @property
    def DeltaGantryAngle(self) -> float: ...
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def ImportedSourceToSurfaceDistance_ForDisplayUseOnly(self) -> Optional[float]: ...
    @property
    def IsVirtual(self) -> bool: ...
    @property
    def JawPositions(self) -> np.ndarray: ...
    @JawPositions.setter
    def JawPositions(self, value: np.ndarray) -> None: ...
    @property
    def LeafPositions(self) -> np.ndarray: ...
    @LeafPositions.setter
    def LeafPositions(self, value: np.ndarray) -> None: ...
    @property
    def RelativeWeight(self) -> float: ...
    @RelativeWeight.setter
    def RelativeWeight(self, value: float) -> None: ...
    @property
    def SegmentNumber(self) -> int: ...
    @property
    def Orm(self) -> FluenceMap: ...
    @Orm.setter
    def Orm(self, value: FluenceMap) -> None: ...
    def GetBEVImageOfSegment(self) -> str:
        """Method for retrieving BEV image for a segment."""
        ...

class ElectronSegment:
    @property
    def CollimatorAngle(self) -> float: ...
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def ImportedSourceToSurfaceDistance_ForDisplayUseOnly(self) -> Optional[float]: ...
    @property
    def JawPositions(self) -> np.ndarray: ...
    @JawPositions.setter
    def JawPositions(self, value: np.ndarray) -> None: ...
    @property
    def LeafPositions(self) -> np.ndarray: ...
    @LeafPositions.setter
    def LeafPositions(self, value: np.ndarray) -> None: ...
    @property
    def RelativeWeight(self) -> float: ...
    @RelativeWeight.setter
    def RelativeWeight(self, value: float) -> None: ...
    @property
    def SegmentNumber(self) -> int: ...
    @property
    def TrimmerPositions(self) -> np.ndarray: ...
    @TrimmerPositions.setter
    def TrimmerPositions(self, value: np.ndarray) -> None: ...
    def GetBEVImageOfSegment(self) -> str:
        """Method for retrieving BEV image for a segment."""
        ...

class ArcSegmentBaseProperties:
    @property
    def HasValidSegments(self) -> bool: ...
    @HasValidSegments.setter
    def HasValidSegments(self, value: bool) -> None: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...

class ElectronBeam:
    @property
    def ArcRotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...
    @property
    def ArcStopGantryAngle(self) -> Optional[float]: ...
    @property
    def BeamMU(self) -> float: ...
    @BeamMU.setter
    def BeamMU(self, value: float) -> None: ...
    @property
    def BeamQualityId(self) -> str: ...
    @BeamQualityId.setter
    def BeamQualityId(self, value: str) -> None: ...
    @property
    def CouchPitchAngle(self) -> float: ...
    @CouchPitchAngle.setter
    def CouchPitchAngle(self, value: float) -> None: ...
    @property
    def CouchRollAngle(self) -> float: ...
    @CouchRollAngle.setter
    def CouchRollAngle(self, value: float) -> None: ...
    @property
    def CouchRotationAngle(self) -> float: ...
    @CouchRotationAngle.setter
    def CouchRotationAngle(self, value: float) -> None: ...
    @property
    def CreatedDuringOptimization(self) -> bool: ...
    @property
    def DeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def GantryAngle(self) -> float: ...
    @GantryAngle.setter
    def GantryAngle(self, value: float) -> None: ...
    @property
    def InitialCollimatorAngle(self) -> float: ...
    @property
    def InitialJawPositions(self) -> np.ndarray: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def PatientPosition(self) -> Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']: ...
    @property
    def PlanGenerationTechnique(self) -> Optional[Literal['Imrt', 'Conformal', 'Mixed']]: ...
    @PlanGenerationTechnique.setter
    def PlanGenerationTechnique(self, value: Optional[Literal['Imrt', 'Conformal', 'Mixed']]) -> None: ...
    @property
    def Applicator(self) -> ElectronApplicatorReference: ...
    @Applicator.setter
    def Applicator(self, value: ElectronApplicatorReference) -> None: ...
    @property
    def Blocks(self) -> ScriptObjectCollection[Block]: ...
    @Blocks.setter
    def Blocks(self, value: List[Block]) -> None: ...
    @property
    def Boli(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @Boli.setter
    def Boli(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def Compensator(self) -> Compensator: ...
    @Compensator.setter
    def Compensator(self, value: Compensator) -> None: ...
    @property
    def Isocenter(self) -> PatientToBeamMapping: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def Segments(self) -> ScriptObjectCollection[Segment]: ...
    @Segments.setter
    def Segments(self, value: List[Segment]) -> None: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...
    def ClearTreatOrProtectRoi(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for the beam."""
        ...
    def ConformBlock(self) -> None:
        """Generates a block aperture according to the treat and protect settings."""
        ...
    def ConformMlc(self) -> None:
        """Generates a MLC aperture according to the treat and protect settings."""
        ...
    def CreateCircularValidationCutoutContour(self, Diameter: float = ...) -> None:
        """Creates a circular validation cutout contour for the beam."""
        ...
    def CreateRectangularField(self, Width: float = ..., Height: float = ..., CenterCoordinate: Any = ..., MoveMLC: bool = ..., MoveAllMLCLeaves: bool = ..., MoveJaw: bool = ..., JawMargins: Any = ..., DeleteWedge: bool = ..., PreventExtraLeafPairFromOpening: bool = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Creates rectangular field."""
        ...
    def CreateRectangularValidationCutoutContour(self, XPosition: float = ..., YPosition: float = ..., XSide: float = ..., YSide: float = ...) -> None:
        """Creates a rectangular validation cutout contour for the beam."""
        ...
    def CreateSquareValidationCutoutContour(self, Side: float = ...) -> None:
        """Creates a square validation cutout contour for the beam."""
        ...
    def DeleteArcTrajectory(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Deletes the arc trajectory on a beam."""
        ...
    def DeleteSegment(self, SegmentNumber: int = ...) -> None:
        """Deletes a segment."""
        ...
    def EditBeamLeafPositions(self, LeafPositions: np.ndarray) -> None:
        """Action for updating leaf positions for all segments of a beam"""
        ...
    def GetBEVImage(self, ShowFluence: bool) -> str:
        """Method for retrieving BEV image for a beam."""
        ...
    def GetDRRImage(self) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetDRRImageForSegment(self, SegmentIndex: int) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetSourceToSkinDistance(self) -> float:
        """Method for retrieving the source-to-skin distance for photon and electron beams."""
        ...
    def GetSourceToSurfaceDistance(self) -> float:
        """Method for retrieving the source-to-surface distance for photon and electron beams."""
        ...
    def SetArcTrajectory(self, GantryAngles: np.ndarray, CouchAngles: np.ndarray, CollimatorAngles: np.ndarray, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the arc trajectory on a beam."""
        ...
    def SetArcTrajectoryFromTemplate(self, NameOfTemplate: str) -> None:
        """Sets the arc trajectory on a beam from a template."""
        ...
    def SetBolus(self, BolusName: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the bolus with name BolusName on this photon beam. Returns the beam."""
        ...
    def SetDoseSpecificationPoint(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Select a dose specification point for this beam."""
        ...
    def SetInitialJawPositions(self, X1: float = ..., X2: float = ..., Y1: float = ..., Y2: float = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets initial jaw positions to the beam."""
        ...
    def SetIsocenter(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets an isocenter to a beam. If the name of the isocenter does not exist, a new isocenter will be created."""
        ...
    def SetIsocenterToMidpointInExternal(self) -> None:
        """Sets the isocenter for a beam to the midplane of the patient (external)."""
        ...
    def SetTreatOrProtectRoi(self, TopMargin: float = ..., BottomMargin: float = ..., LeftMargin: float = ..., RightMargin: float = ..., RoiName: str = ...) -> None:
        """Select to use ROI as Treat or Protect."""
        ...

class ElectronApplicatorReference:
    @property
    def DicomApplicatorId(self) -> str: ...
    @property
    def DicomType(self) -> Literal['Square', 'Rectangular', 'Circular', 'Short', 'Open']: ...
    @property
    def ElectronApplicatorName(self) -> str: ...

class PhotonBeam:
    @property
    def ArcRotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...
    @property
    def ArcStopGantryAngle(self) -> Optional[float]: ...
    @property
    def BeamMU(self) -> float: ...
    @BeamMU.setter
    def BeamMU(self, value: float) -> None: ...
    @property
    def BeamQualityId(self) -> str: ...
    @BeamQualityId.setter
    def BeamQualityId(self, value: str) -> None: ...
    @property
    def CouchPitchAngle(self) -> float: ...
    @CouchPitchAngle.setter
    def CouchPitchAngle(self, value: float) -> None: ...
    @property
    def CouchRollAngle(self) -> float: ...
    @CouchRollAngle.setter
    def CouchRollAngle(self, value: float) -> None: ...
    @property
    def CouchRotationAngle(self) -> float: ...
    @CouchRotationAngle.setter
    def CouchRotationAngle(self, value: float) -> None: ...
    @property
    def CreatedDuringOptimization(self) -> bool: ...
    @property
    def DeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def GantryAngle(self) -> float: ...
    @GantryAngle.setter
    def GantryAngle(self, value: float) -> None: ...
    @property
    def GimbalPanAngle(self) -> float: ...
    @property
    def GimbalTiltAngle(self) -> float: ...
    @property
    def InitialCollimatorAngle(self) -> float: ...
    @property
    def InitialJawPositions(self) -> np.ndarray: ...
    @property
    def IntendedJawPositionsForTomoBeam(self) -> Optional[Point2[float]]: ...
    @IntendedJawPositionsForTomoBeam.setter
    def IntendedJawPositionsForTomoBeam(self, value: Optional[Point2[float]]) -> None: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def PatientPosition(self) -> Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']: ...
    @property
    def PlanGenerationTechnique(self) -> Optional[Literal['Imrt', 'Conformal', 'Mixed']]: ...
    @PlanGenerationTechnique.setter
    def PlanGenerationTechnique(self, value: Optional[Literal['Imrt', 'Conformal', 'Mixed']]) -> None: ...
    @property
    def XRayIrradiatorTubeCurrent(self) -> Optional[float]: ...
    @XRayIrradiatorTubeCurrent.setter
    def XRayIrradiatorTubeCurrent(self, value: Optional[float]) -> None: ...
    @property
    def Blocks(self) -> ScriptObjectCollection[Block]: ...
    @Blocks.setter
    def Blocks(self, value: List[Block]) -> None: ...
    @property
    def BlockTray(self) -> BlockTray: ...
    @BlockTray.setter
    def BlockTray(self, value: BlockTray) -> None: ...
    @property
    def Boli(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @Boli.setter
    def Boli(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def Compensator(self) -> Compensator: ...
    @Compensator.setter
    def Compensator(self, value: Compensator) -> None: ...
    @property
    def Cone(self) -> Cone: ...
    @Cone.setter
    def Cone(self, value: Cone) -> None: ...
    @property
    def FilteredOrm(self) -> FluenceMap: ...
    @FilteredOrm.setter
    def FilteredOrm(self, value: FluenceMap) -> None: ...
    @property
    def Fluence(self) -> FluenceMap: ...
    @Fluence.setter
    def Fluence(self, value: FluenceMap) -> None: ...
    @property
    def Isocenter(self) -> PatientToBeamMapping: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def Orm(self) -> FluenceMap: ...
    @Orm.setter
    def Orm(self, value: FluenceMap) -> None: ...
    @property
    def Segments(self) -> ScriptObjectCollection[Segment]: ...
    @Segments.setter
    def Segments(self, value: List[Segment]) -> None: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...
    @property
    def Wedge(self) -> Wedge: ...
    @Wedge.setter
    def Wedge(self, value: Wedge) -> None: ...
    def CenterBeamInField(self) -> None:
        """Centers the photon beam (including jaws, MLC and block) around the isocenter."""
        ...
    def ClearTreatOrProtectRoi(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for the beam."""
        ...
    def ConformBlock(self) -> None:
        """Generates a block aperture according to the treat and protect settings."""
        ...
    def ConformMlc(self) -> None:
        """Generates a MLC aperture according to the treat and protect settings."""
        ...
    def CreateDotDecimalBlockContour(self, GridScale: float, HoleDiameterCm: float = ..., GridOffsetCm: Any = ...) -> None:
        """WARNING: This script method has only been validated for TrueBeam and Agility and is NOT intended for other machines."""
        ...
    def CreateRectangularField(self, Width: float = ..., Height: float = ..., CenterCoordinate: Any = ..., MoveMLC: bool = ..., MoveAllMLCLeaves: bool = ..., MoveJaw: bool = ..., JawMargins: Any = ..., DeleteWedge: bool = ..., PreventExtraLeafPairFromOpening: bool = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Creates rectangular field."""
        ...
    def DeleteArcTrajectory(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Deletes the arc trajectory on a beam."""
        ...
    def DeleteSegment(self, SegmentNumber: int = ...) -> None:
        """Deletes a segment."""
        ...
    def EditBeamLeafPositions(self, LeafPositions: np.ndarray) -> None:
        """Action for updating leaf positions for all segments of a beam"""
        ...
    def GetBeamApertureModulation(self, RoiNames: List[str]) -> float:
        """Computes the Beam Aperture Modulation (BAM) of the beam, with the union of specified ROIs used as target."""
        ...
    def GetBEVImage(self, ShowFluence: bool) -> str:
        """Method for retrieving BEV image for a beam."""
        ...
    def GetDRRImage(self) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetDRRImageForSegment(self, SegmentIndex: int) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetGimbalPanAngle(self) -> float:
        """Gets the gimbal pan angle for the photon beam."""
        ...
    def GetGimbalTiltAngle(self) -> float:
        """Gets the gimbal tilt angle for the photon beam."""
        ...
    def GetIrradiationTime(self) -> float:
        """Method to get the irradiation time for a small animal x-ray irradiator photon beam, in seconds."""
        ...
    def GetSourceToSkinDistance(self) -> float:
        """Method for retrieving the source-to-skin distance for photon and electron beams."""
        ...
    def GetSourceToSurfaceDistance(self) -> float:
        """Method for retrieving the source-to-surface distance for photon and electron beams."""
        ...
    def SetArcTrajectory(self, GantryAngles: np.ndarray, CouchAngles: np.ndarray, CollimatorAngles: np.ndarray, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the arc trajectory on a beam."""
        ...
    def SetArcTrajectoryFromTemplate(self, NameOfTemplate: str) -> None:
        """Sets the arc trajectory on a beam from a template."""
        ...
    def SetBlockTray(self, ID: str, Transmission: float = ...) -> PhotonBeam:
        """Sets a block tray on this photon beam. Returns the beam."""
        ...
    def SetBolus(self, BolusName: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the bolus with name BolusName on this photon beam. Returns the beam."""
        ...
    def SetDoseSpecificationPoint(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Select a dose specification point for this beam."""
        ...
    def SetFluenceProtectRoi(self, EntranceOnly: bool, RoiName: str) -> None:
        """Select to protect an ROI with Entrance or Entrance and exit (available for TomoHelical/TomoDirect/VMAT/CyberKnife)"""
        ...
    def SetGimbalAngles(self, GimbalPanAngle: Optional[float] = ..., GimbalTiltAngle: Optional[float] = ...) -> None:
        """Set gimbal pan angle and gimbal tilt angle"""
        ...
    def SetInitialJawPositions(self, X1: float = ..., X2: float = ..., Y1: float = ..., Y2: float = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets initial jaw positions to the beam."""
        ...
    def SetIrradiationTime(self, IrradiationTime: float) -> None:
        """Set irradiation time for an x-ray photon beam."""
        ...
    def SetIsocenter(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets an isocenter to a beam. If the name of the isocenter does not exist, a new isocenter will be created."""
        ...
    def SetIsocenterToMidpointInExternal(self) -> None:
        """Sets the isocenter for a beam to the midplane of the patient (external)."""
        ...
    def SetPhotonBlock(self, Name: str, Type: Literal['Shielding', 'Aperture', 'DynamicAperture'] = ..., Transmission: Optional[float] = ...) -> PhotonBeam:
        """Sets a block on this photon beam. Returns the beam."""
        ...
    def SetTreatOrProtectRoi(self, TopMargin: float = ..., BottomMargin: float = ..., LeftMargin: float = ..., RightMargin: float = ..., RoiName: str = ...) -> None:
        """Select to use ROI as Treat or Protect."""
        ...

class BeamCollisionStatus:
    @property
    def Nominal(self) -> Literal['Unknown', 'HasCollision', 'NoCollision']: ...
    @property
    def WithinSetupMargins(self) -> Literal['Unknown', 'HasCollision', 'NoCollision']: ...
    @property
    def FailedScenarios(self) -> ScriptObjectCollection[CollisionCheckScenario]: ...
    @FailedScenarios.setter
    def FailedScenarios(self, value: List[CollisionCheckScenario]) -> None: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...

class BeamClearanceStatus:
    @property
    def ClearanceStatus(self) -> Literal['Unknown', 'HasCollision', 'NoCollision']: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...

class BeamOptimizationSettings:
    @property
    def AllowBeamSplit(self) -> bool: ...
    @AllowBeamSplit.setter
    def AllowBeamSplit(self, value: bool) -> None: ...
    @property
    def BeamApertureLimit(self) -> Literal['NoLimit', 'MaxLimit', 'AtLimit']: ...
    @BeamApertureLimit.setter
    def BeamApertureLimit(self, value: Literal['NoLimit', 'MaxLimit', 'AtLimit']) -> None: ...
    @property
    def OptimizationTypes(self) -> ScriptObjectCollection[Any]: ...
    @OptimizationTypes.setter
    def OptimizationTypes(self, value: List[Any]) -> None: ...
    @property
    def SelectCollimatorAngle(self) -> bool: ...
    @SelectCollimatorAngle.setter
    def SelectCollimatorAngle(self, value: bool) -> None: ...
    @property
    def ArcConversionPropertiesPerBeam(self) -> ArcConversionPropertiesPerBeam: ...
    @ArcConversionPropertiesPerBeam.setter
    def ArcConversionPropertiesPerBeam(self, value: ArcConversionPropertiesPerBeam) -> None: ...
    @property
    def AvoidanceRois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @AvoidanceRois.setter
    def AvoidanceRois(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def CyberKnifePropertiesPerBeam(self) -> CyberKnifePropertiesPerBeam: ...
    @CyberKnifePropertiesPerBeam.setter
    def CyberKnifePropertiesPerBeam(self, value: CyberKnifePropertiesPerBeam) -> None: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...
    @property
    def TomoPropertiesPerBeam(self) -> TomoPropertiesPerBeam: ...
    @TomoPropertiesPerBeam.setter
    def TomoPropertiesPerBeam(self, value: TomoPropertiesPerBeam) -> None: ...
    def EditBeamOptimizationSettings(self, OptimizationTypes: List[Any] = ..., SelectCollimatorAngle: bool = ..., AllowBeamSplit: bool = ..., JawMotion: Literal['Undefined', 'Fixed', 'LockToLimits', 'UseLimitsAsMax', 'Automatic'] = ..., LeftJaw: Optional[float] = ..., RightJaw: Optional[float] = ..., TopJaw: Optional[float] = ..., BottomJaw: Optional[float] = ...) -> None:
        """Edits the beam optimization settings for selected beam"""
        ...

class ArcConversionPropertiesPerBeam:
    @property
    def BurstGantrySpacing(self) -> Optional[float]: ...
    @BurstGantrySpacing.setter
    def BurstGantrySpacing(self, value: Optional[float]) -> None: ...
    @property
    def FinalArcGantrySpacing(self) -> float: ...
    @FinalArcGantrySpacing.setter
    def FinalArcGantrySpacing(self, value: float) -> None: ...
    @property
    def MaxArcDeliveryTime(self) -> float: ...
    @MaxArcDeliveryTime.setter
    def MaxArcDeliveryTime(self, value: float) -> None: ...
    @property
    def MaxArcMU(self) -> Optional[float]: ...
    @MaxArcMU.setter
    def MaxArcMU(self, value: Optional[float]) -> None: ...
    @property
    def NumberOfArcs(self) -> int: ...
    @NumberOfArcs.setter
    def NumberOfArcs(self, value: int) -> None: ...
    def EditArcBasedBeamOptimizationSettings(self, CreateDualArcs: bool = ..., FinalGantrySpacing: float = ..., MaxArcDeliveryTime: float = ..., BurstGantrySpacing: Optional[float] = ..., MaxArcMU: Optional[float] = ...) -> None:
        """Edit the arc based beam optimization settings for selected beam"""
        ...

class ArcConversionProperties:
    @property
    def MaxLeafTravelDistancePerDegree(self) -> float: ...
    @MaxLeafTravelDistancePerDegree.setter
    def MaxLeafTravelDistancePerDegree(self, value: float) -> None: ...
    @property
    def UseMaxLeafTravelDistancePerDegree(self) -> bool: ...
    @UseMaxLeafTravelDistancePerDegree.setter
    def UseMaxLeafTravelDistancePerDegree(self, value: bool) -> None: ...
    @property
    def UseSlidingWindowSequencing(self) -> bool: ...
    @UseSlidingWindowSequencing.setter
    def UseSlidingWindowSequencing(self, value: bool) -> None: ...

class BeamCommissioningField:
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def FieldDeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @FieldDeliveryTechnique.setter
    def FieldDeliveryTechnique(self, value: Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']) -> None: ...
    @property
    def FieldId(self) -> str: ...
    @FieldId.setter
    def FieldId(self, value: str) -> None: ...
    @property
    def FieldMU(self) -> float: ...
    @FieldMU.setter
    def FieldMU(self, value: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def SegmentBaseProperties(self) -> SegmentBaseProperties: ...
    @SegmentBaseProperties.setter
    def SegmentBaseProperties(self, value: SegmentBaseProperties) -> None: ...
    @property
    def Segments(self) -> ScriptObjectCollection[Segment]: ...
    @Segments.setter
    def Segments(self, value: List[Segment]) -> None: ...
    def DowngradeWriteLockToReadLock(self) -> None:
        """Downgrades write lock to read lock, so that the field can be used from other actions."""
        ...

class ArcTrajectory:
    @property
    def ArcRotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...
    @ArcRotationDirection.setter
    def ArcRotationDirection(self, value: Literal['None', 'Clockwise', 'CounterClockwise']) -> None: ...
    @property
    def CollimatorAngles(self) -> np.ndarray: ...
    @CollimatorAngles.setter
    def CollimatorAngles(self, value: np.ndarray) -> None: ...
    @property
    def CouchAngles(self) -> np.ndarray: ...
    @CouchAngles.setter
    def CouchAngles(self, value: np.ndarray) -> None: ...
    @property
    def GantryAngles(self) -> np.ndarray: ...
    @GantryAngles.setter
    def GantryAngles(self, value: np.ndarray) -> None: ...

class PhotonBeamQuality:
    @property
    def DosimetricEnergy(self) -> float: ...
    @property
    def FluenceMode(self) -> Optional[Literal['FFF', 'SRS']]: ...
    @property
    def Label(self) -> str: ...
    @property
    def MaxDmlcDoseRate(self) -> Optional[float]: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def StaticPlanDoseRate(self) -> Optional[float]: ...
    @property
    def UseKernelsForMachineType(self) -> Optional[Literal['Clinac2100', 'ElektaBM', 'ElektaSynergy', 'SiemensArtiste']]: ...
    @property
    def AllowedWedges(self) -> ScriptObjectCollection[Wedge]: ...
    @property
    def BeamModels(self) -> ScriptObjectCollection[PhotonBeamModelProperties]: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def PhotonDosimetryData(self) -> PhotonDosimetryData: ...
    @property
    def SupportedCones(self) -> ScriptObjectCollection[Cone]: ...
    def GetPhotonBeamQualityId(self) -> str:
        """Returns the ID (e.g., "6 FFF") of the photon beam quality."""
        ...

class PhotonBeamModelProperties:
    @property
    def BeamModel(self) -> PhotonBeamModel: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def ModelingSteps(self) -> ScriptObjectCollection[ModelingStep]: ...
    @property
    def PhotonBeamQuality(self) -> PhotonBeamQuality: ...

class PhotonBeamModel:
    @property
    def ForDoseAlgorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @property
    def BeamProfile(self) -> RadialDistribution: ...
    @property
    def BeamQuality(self) -> PhotonBeamQuality: ...
    @property
    def Calibration(self) -> Calibration: ...
    @property
    def ConeCorrections(self) -> ScriptObjectCollection[ConeCorrection]: ...
    @property
    def ElectronEnergySpectrum(self) -> ElectronContaminationEnergySpectrum: ...
    @property
    def ElectronSource(self) -> SecondarySource: ...
    @property
    def EnergySpectrum(self) -> PhotonEnergySpectrum: ...
    @property
    def FlatteningFilter(self) -> RadialDistribution: ...
    @property
    def FlatteningFilterSource(self) -> SecondarySource: ...
    @property
    def LowerMlcLayer(self) -> Collimator: ...
    @property
    def MotorizedWedgeParameters(self) -> WedgeParameters: ...
    @property
    def OutputFactorCorrections(self) -> OutputFactorCorrections: ...
    @property
    def PhysicalWedgeParameters(self) -> ScriptObjectCollection[WedgeParameters]: ...
    @property
    def PrimarySource(self) -> PrimarySource: ...
    @property
    def SiemensVirtualWedgeProperties(self) -> SiemensVirtualWedgeProperties: ...
    @property
    def UpperMlcLayer(self) -> Collimator: ...
    @property
    def WedgeFactorCorrections(self) -> ScriptObjectCollection[WedgeFactorCorrections]: ...
    @property
    def XJaws(self) -> Collimator: ...
    @property
    def YJaws(self) -> Collimator: ...

class PhotonEnergySpectrum:
    @property
    def Energies(self) -> np.ndarray: ...
    @property
    def Intensities(self) -> np.ndarray: ...

class ElectronContaminationEnergySpectrum:
    @property
    def ParameterC(self) -> float: ...
    @property
    def ParameterE0(self) -> float: ...
    @property
    def ParameterFF(self) -> float: ...

class PhotonDosimetryData:
    @property
    def OutputFactorDepth(self) -> Optional[float]: ...
    @property
    def BlockTrayTransmissions(self) -> ScriptObjectCollection[BlockTrayTransmission]: ...
    @property
    def CalibrationPoint(self) -> CalibrationPoint: ...
    @property
    def ConeFactors(self) -> ScriptObjectCollection[ConeFactor]: ...
    @property
    def CryostatTransmissionFactors(self) -> CryostatTransmissionFactors: ...
    @property
    def LinacPhysics(self) -> LinacPhysics: ...
    @property
    def MeasuredCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def MissingOutputFactorFields(self) -> ScriptObjectCollection[OutputFactor]: ...
    @property
    def NormalizedCurves(self) -> ScriptObjectCollection[NormalizedDoseCurve]: ...
    @property
    def OutputFactors(self) -> ScriptObjectCollection[OutputFactor]: ...
    @property
    def WedgeFactors(self) -> ScriptObjectCollection[WedgeFactor]: ...

class BeamLineObject:
    @property
    def BottomZPosition(self) -> float: ...

class BeamLinePrimaryCollimator:
    @property
    def BottomZPosition(self) -> float: ...
    @property
    def FocalPoint(self) -> float: ...
    @property
    def InnerOpeningRadius(self) -> float: ...
    @property
    def Thickness(self) -> float: ...

class BeamLinePrimaryScatteringFoil:
    @property
    def BottomZPosition(self) -> float: ...

class BeamLineRectangularHoleSlab:
    @property
    def BottomZPosition(self) -> float: ...
    @property
    def FocalPoint(self) -> Optional[float]: ...
    @property
    def InnerOpeningX(self) -> float: ...
    @property
    def InnerOpeningY(self) -> float: ...
    @property
    def Thickness(self) -> float: ...

class BeamLineScraperLayer:
    @property
    def BottomZPosition(self) -> float: ...
    @property
    def FrontFaceAngleX(self) -> float: ...
    @property
    def FrontFaceAngleY(self) -> float: ...
    @property
    def InnerOpeningX(self) -> float: ...
    @property
    def InnerOpeningY(self) -> float: ...
    @property
    def MaterialName(self) -> str: ...
    @property
    def RimWidthX(self) -> float: ...
    @property
    def RimWidthY(self) -> float: ...
    @property
    def Shape(self) -> Literal['Cylindrical', 'Rectangular']: ...
    @property
    def Thickness(self) -> float: ...

class BeamLineSecondaryScatteringFoil:
    @property
    def BottomZPosition(self) -> float: ...

class BeamCurrentModulationCurve:
    @property
    def Angle(self) -> np.ndarray: ...
    @property
    def BeamCurrent(self) -> np.ndarray: ...
    @property
    def CurveId(self) -> str: ...
    @property
    def Name(self) -> str: ...

class PhotonBlockConstraints:
    @property
    def MaxApertureRadius(self) -> float: ...
    @property
    def OuterDimension(self) -> Optional[Point2[float]]: ...
    @property
    def Shape(self) -> Literal['Cylindrical', 'Rectangular']: ...
    @property
    def SourceToBlockTrayDistance(self) -> float: ...
    @property
    def SupportedBlockTypes(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedDivergences(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedMillingToolDiameters(self) -> np.ndarray: ...
    @property
    def SupportedThicknesses(self) -> np.ndarray: ...
    @property
    def SupportedMaterials(self) -> ScriptObjectCollection[Material]: ...
    @property
    def SupportedMillingTools(self) -> ScriptObjectCollection[MillingTool]: ...

class ElectronBeamQuality:
    @property
    def Label(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def BeamModel(self) -> ElectronBeamModel: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def ElectronDosimetryData(self) -> ElectronDosimetryData: ...
    @property
    def FieldShapingQualities(self) -> ScriptObjectCollection[ElectronFieldShapingQuality]: ...
    @property
    def Linac(self) -> Linac: ...
    @property
    def ModelingSteps(self) -> ScriptObjectCollection[ModelingStep]: ...

class ElectronFieldShapingQuality:
    @property
    def Label(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def BeamModel(self) -> ElectronFieldShapingModel: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def ElectronFieldShapingDosimetryData(self) -> ElectronFieldShapingDosimetryData: ...
    @property
    def FieldShapingSettings(self) -> ApplicatorWithInsertSettings: ...
    @property
    def ForElectronApplicator(self) -> ElectronApplicator: ...
    @property
    def Linac(self) -> Linac: ...
    @property
    def ParentBeamModelSource(self) -> ElectronBeamQuality: ...

class ElectronFieldShapingModel:
    @property
    def FluencePerMuCalibration(self) -> float: ...
    @property
    def IndirectElectronWeightTune(self) -> float: ...

class ElectronFieldShapingDosimetryData:
    @property
    def BlockDimensions(self) -> Optional[Point2[float]]: ...
    @property
    def OutputFactorDepth(self) -> Optional[float]: ...
    @property
    def BlockTrayTransmissions(self) -> ScriptObjectCollection[BlockTrayTransmission]: ...
    @property
    def CalibrationPoint(self) -> CalibrationPoint: ...
    @property
    def LinacPhysics(self) -> LinacPhysics: ...
    @property
    def MeasuredCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def NormalizedCurves(self) -> ScriptObjectCollection[NormalizedDoseCurve]: ...

class ElectronBeamModel:
    @property
    def ElectronEnergySpectrum(self) -> ElectronEnergySpectrum: ...
    @property
    def ElectronSourcePhaseSpace(self) -> ElectronSourcePhaseSpace: ...
    @property
    def PhotonContaminationParameters(self) -> PhotonContaminationParameters: ...

class ElectronEnergySpectrum:
    @property
    def B(self) -> float: ...
    @property
    def DeltaE(self) -> float: ...
    @property
    def E0(self) -> float: ...
    @property
    def Ecut(self) -> float: ...
    @property
    def K(self) -> float: ...
    @property
    def SlopeHigh(self) -> float: ...
    @property
    def SlopeLow(self) -> float: ...

class ElectronSourcePhaseSpace:
    @property
    def Rcut(self) -> float: ...
    @property
    def SigmaR(self) -> float: ...
    @property
    def SigmaThAtEdge(self) -> float: ...
    @property
    def SigmaThCurvature(self) -> float: ...
    @property
    def SigmaThOnAxis(self) -> float: ...
    @property
    def Zeff(self) -> float: ...

class PhotonContaminationParameters:
    @property
    def ApplicatorTransmission(self) -> float: ...
    @property
    def CutoutTransmission(self) -> float: ...
    @property
    def FluencePerMuCalibration(self) -> float: ...
    @property
    def Width(self) -> float: ...
    @property
    def EnergySpectrum(self) -> PhotonContaminationEnergySpectrum: ...
    @property
    def EnergySpectrumOptimization(self) -> EnergySpectrumOptimization: ...

class PhotonContaminationEnergySpectrum:
    ...

class ElectronDosimetryData:
    @property
    def OutputFactorDepth(self) -> Optional[float]: ...
    @property
    def SsdWaterMeasurement(self) -> float: ...
    @property
    def BlockTrayTransmissions(self) -> ScriptObjectCollection[BlockTrayTransmission]: ...
    @property
    def CalibrationPoint(self) -> CalibrationPoint: ...
    @property
    def LinacPhysics(self) -> LinacPhysics: ...
    @property
    def MeasuredCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def MeasuredWaterDepthCurve(self) -> MeasuredDoseCurve: ...
    @property
    def NormalizedCurves(self) -> ScriptObjectCollection[NormalizedDoseCurve]: ...

class ElectronApplicator:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def ApertureDeviceZOffset(self) -> float: ...
    @property
    def DicomApplicatorId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def NominalFieldSize(self) -> Tuple[float, ...]: ...
    @property
    def NominalFieldSsd(self) -> float: ...
    @property
    def TrayId(self) -> str: ...
    @property
    def ScraperLayers(self) -> ScriptObjectCollection[BeamLineScraperLayer]: ...

class ArcProperties:
    @property
    def AllowedFinalArcGantrySpacing(self) -> np.ndarray: ...
    @property
    def BurstOverheadDeliveryTimePerCP(self) -> float: ...
    @property
    def ConstantControlPointSpacing(self) -> bool: ...
    @property
    def IsDoseRateConstant(self) -> bool: ...
    @property
    def IsDoseRateDiscrete(self) -> bool: ...
    @property
    def IsSlidingWindowArcCapable(self) -> bool: ...
    @property
    def LimitLeafMotionPerGantryDegreeOnMachine(self) -> bool: ...
    @property
    def LimitMUPerGantryDegree(self) -> bool: ...
    @property
    def MaxBurstGantrySpacing(self) -> float: ...
    @property
    def MaxCollimatorAngleSpeed(self) -> float: ...
    @property
    def MaxCouchAngleSpeed(self) -> float: ...
    @property
    def MaxGantryAngleSpeed(self) -> float: ...
    @property
    def MaxGantrySpeedVariation(self) -> float: ...
    @property
    def MaxLeafMotionPerGantryDegree(self) -> Optional[float]: ...
    @property
    def MaxTrajectorySlope(self) -> float: ...
    @property
    def MinCollimatorAngleForSmartAngles(self) -> Optional[float]: ...
    @property
    def MinCollimatorAngleSpeed(self) -> float: ...
    @property
    def MinCouchAngleSpeed(self) -> float: ...
    @property
    def MinGantryAngleSpeed(self) -> float: ...
    @property
    def MinGantryDistanceBetweenDoseRateChanges(self) -> Optional[float]: ...
    @property
    def MinMUPerCollimatorDegree(self) -> float: ...
    @property
    def SameDominantAngleForEntireArc(self) -> bool: ...
    @property
    def SupportedWaveArcCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportsVariableCollimatorAngle(self) -> bool: ...
    @property
    def SupportsVariableCouchAngle(self) -> bool: ...
    @property
    def SupportsVariableGantrySpeed(self) -> bool: ...
    @property
    def UseArcBurstMode(self) -> bool: ...
    @property
    def ArcPropertiesPerEnergy(self) -> ScriptObjectCollection[ArcPropertiesPerEnergy]: ...
    @property
    def BeamQualitiesSource(self) -> Linac: ...

class ArcPropertiesPerEnergy:
    @property
    def DiscreteDoseRateLevels(self) -> np.ndarray: ...
    @property
    def MaxDynamicArcDoseRate(self) -> float: ...
    @property
    def MaxMUPerGantryDegree(self) -> float: ...
    @property
    def MaxStaticArcDoseRate(self) -> Optional[float]: ...
    @property
    def MinArcMUPerControlPoint(self) -> float: ...
    @property
    def MinDynamicArcDoseRate(self) -> float: ...
    @property
    def MinMUPerGantryDegree(self) -> float: ...
    @property
    def MinMUPerLeafTravelDistance(self) -> float: ...
    @property
    def MinStaticArcDoseRate(self) -> Optional[float]: ...
    @property
    def ForBeamQuality(self) -> PhotonBeamQuality: ...

class ElectronDoseDefaultSettings:
    @property
    def ElectronMCHistoriesPerSquareCentimeter(self) -> int: ...
    @property
    def MaxStatisticalUncertaintyForClinicalElectronDose(self) -> float: ...

class PhotonDoseDefaultSettings:
    @property
    def MaxStatisticalUncertaintyForClinicalPhotonDose(self) -> Optional[float]: ...
    @property
    def PhotonDoseAlgorithm(self) -> Literal['CCDose', 'PhotonMonteCarlo']: ...
    @property
    def PhotonMCStatisticalUncertaintyPerBeamForOptimization(self) -> float: ...

class PhotonOptimizationAndSegmentationDefaultSettings:
    @property
    def ConformalArcSettings(self) -> ConformalArcSettings: ...
    @property
    def CyberKnifeDefaultSettings(self) -> CyberKnifeDefaultSettings: ...
    @property
    def DmlcDefaultSettings(self) -> DmlcDefaultSettings: ...
    @property
    def SmlcDefaultSettings(self) -> SmlcDefaultSettings: ...
    @property
    def ThreeDCRTSettings(self) -> ThreeDCRTSettings: ...
    @property
    def TomoDirectDefaultSettings(self) -> TomoDirectDefaultSettings: ...
    @property
    def TomoHelicalDefaultSettings(self) -> TomoHelicalDefaultSettings: ...
    @property
    def VmatDefaultSettings(self) -> VmatDefaultSettings: ...
