from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.dose import DoseAlgorithmVersion
    from raystation.v2025.machine_db_types import CommissioningInfo
    from raystation.v2025.patient_db_types import AfterloaderReference, RegionOfInterest, SourceReference, TriangleMesh



class BrachyTreatmentSetup:
    @property
    def TreatmentType(self) -> Literal['HDR']: ...
    @property
    def AfterloaderReference(self) -> AfterloaderReference: ...
    @property
    def ApplicationSetups(self) -> ScriptObjectCollection[BrachyApplicationSetup]: ...
    @ApplicationSetups.setter
    def ApplicationSetups(self, value: List[BrachyApplicationSetup]) -> None: ...
    @property
    def SourceReference(self) -> SourceReference: ...
    def SaveTemplateDwellTimeDistribution(self, TemplateName: str) -> None:
        """Action for saving a template dwell time distribution."""
        ...

class BrachyApplicationSetup:
    @property
    def Comment(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def TransferTubeLength(self) -> Optional[float]: ...
    @property
    def TreatmentTechnique(self) -> Literal['Intralumenary', 'Intracavitary', 'Interstitial', 'Contact', 'Intravascular', 'Permanent']: ...
    @property
    def BrachyChannels(self) -> ScriptObjectCollection[BrachyChannel]: ...
    @property
    def CommissioningInfo(self) -> CommissioningInfo: ...
    def Unload(self) -> None:
        """Unloads the application setup and releases locks."""
        ...

class BrachyChannel:
    @property
    def ApplicatorID(self) -> str: ...
    @property
    def EffectiveLength(self) -> Optional[float]: ...
    @property
    def InnerLength(self) -> Optional[float]: ...
    @property
    def IsMandatory(self) -> bool: ...
    @property
    def MaxIrradiationLength(self) -> Optional[float]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> int: ...
    @property
    def OuterDiameter(self) -> Optional[float]: ...
    @property
    def PredefinedPathPoints(self) -> ScriptObjectCollection[Any]: ...
    @property
    def ReconstructionStartingPoint(self) -> Literal['Unspecified', 'ApplicatorLumenEnd', 'ApplicatorTip', 'CenterOfDistalMostSource']: ...
    @property
    def SourceApplicatorTipLength(self) -> Optional[float]: ...

class BrachyDwellPoint:
    @property
    def DwellTime(self) -> float: ...
    @property
    def IsLocked(self) -> bool: ...
    @IsLocked.setter
    def IsLocked(self, value: bool) -> None: ...
    @property
    def RelativePosition(self) -> float: ...

class BrachyTreatmentSetupOptimizationSettings:
    @property
    def ApplicationSetupSettings(self) -> ScriptObjectCollection[BrachyApplicationSetupOptimizationSettings]: ...
    @ApplicationSetupSettings.setter
    def ApplicationSetupSettings(self, value: List[BrachyApplicationSetupOptimizationSettings]) -> None: ...
    @property
    def ForBrachyTreatmentSetup(self) -> BrachyTreatmentSetup: ...
    @ForBrachyTreatmentSetup.setter
    def ForBrachyTreatmentSetup(self, value: BrachyTreatmentSetup) -> None: ...

class BrachyApplicationSetupOptimizationSettings:
    @property
    def DwellTimeLimits(self) -> Tuple[float, ...]: ...
    @DwellTimeLimits.setter
    def DwellTimeLimits(self, value: Tuple[float, ...]) -> None: ...
    @property
    def OptimizationTypes(self) -> ScriptObjectCollection[Any]: ...
    @OptimizationTypes.setter
    def OptimizationTypes(self, value: List[Any]) -> None: ...
    @property
    def ForBrachyApplicationSetup(self) -> BrachyApplicationSetup: ...
    @ForBrachyApplicationSetup.setter
    def ForBrachyApplicationSetup(self, value: BrachyApplicationSetup) -> None: ...

class BrachyApplicatorModel:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ApplicatorParts(self) -> ScriptObjectCollection[BrachyApplicatorPart]: ...
    @ApplicatorParts.setter
    def ApplicatorParts(self, value: List[BrachyApplicatorPart]) -> None: ...
    @property
    def Points(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @Points.setter
    def Points(self, value: List[RegionOfInterest]) -> None: ...

class BrachyApplicatorPart:
    @property
    def HasMeasuredSourcePath(self) -> bool: ...
    @property
    def IsFlexible(self) -> bool: ...
    @property
    def SourcePath(self) -> ScriptObjectCollection[Any]: ...
    @property
    def Surface(self) -> TriangleMesh: ...

class BrachyAfterloader:
    @property
    def Comment(self) -> str: ...
    @property
    def DeviceSerialNumber(self) -> str: ...
    @property
    def DwellPointStepSize(self) -> Optional[float]: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturersModelName(self) -> str: ...
    @property
    def MaxActiveDwellPointsPerChannel(self) -> Optional[int]: ...
    @property
    def MaxChannelDwellTime(self) -> Optional[float]: ...
    @property
    def MaxDwellPointTime(self) -> Optional[float]: ...
    @property
    def MaxInnerChannelLength(self) -> Optional[float]: ...
    @property
    def MinDwellPointTime(self) -> Optional[float]: ...
    @property
    def Name(self) -> str: ...
    @property
    def NumberOfChannels(self) -> Optional[int]: ...
    @property
    def CommissioningInfo(self) -> CommissioningInfo: ...
    @property
    def DicomSettings(self) -> BrachyDicomSettings: ...
    @property
    def SourceQuality(self) -> BrachySourceQuality: ...
    def Unload(self) -> None:
        """Unloads the afterloader and releases locks."""
        ...

class BrachySourceQuality:
    @property
    def MonteCarloSourceModel(self) -> Literal['None', 'BEBIG_Ir2_A85_2', 'BEBIG_Co0_A86']: ...
    @property
    def SourceModelID(self) -> str: ...
    @property
    def CommissionedForMonteCarloDoseAlgorithm(self) -> DoseAlgorithmVersion: ...
    @property
    def CommissionedForTG43DoseAlgorithm(self) -> DoseAlgorithmVersion: ...
    @property
    def Isotope(self) -> BrachyIsotope: ...
    @property
    def SourceModel(self) -> BrachySourceModel: ...

class BrachyIsotope:
    @property
    def HalfLife(self) -> Optional[float]: ...
    @property
    def Name(self) -> str: ...

class BrachySourceModel:
    @property
    def TG43ModelParameters(self) -> BrachyTG43ModelParameters: ...

class BrachyTG43ModelParameters:
    @property
    def ActiveLength(self) -> Optional[float]: ...
    @property
    def Description(self) -> str: ...
    @property
    def DoseRateConstant(self) -> Optional[float]: ...
    @property
    def AnisotropyFunction(self) -> BrachyAnisotropyFunction: ...
    @property
    def RadialDoseFunction(self) -> BrachyRadialDoseFunction: ...

class BrachyRadialDoseFunction:
    @property
    def Distances(self) -> np.ndarray: ...
    @property
    def RelativeRadialDoseRates(self) -> np.ndarray: ...

class BrachyAnisotropyFunction:
    @property
    def Distances(self) -> np.ndarray: ...
    @property
    def PolarAngles(self) -> np.ndarray: ...
    @property
    def RelativeDoseRates(self) -> np.ndarray: ...

class BrachyDicomSettings:
    @property
    def BrachyExportCompatibilityMode(self) -> Literal['SagiNova', 'Oncentra', 'Varian']: ...

class BrachySource:
    @property
    def AfterloaderReference(self) -> str: ...
    @property
    def Comment(self) -> str: ...
    @property
    def ReferenceAirKermaRate(self) -> Optional[float]: ...
    @property
    def ReferenceDateTimeUTC(self) -> Optional[str]: ...
    @property
    def SerialNumber(self) -> str: ...
    @property
    def CommissioningInfo(self) -> CommissioningInfo: ...
    def Unload(self) -> None:
        """Unloads the source and releases locks."""
        ...
