from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import BeamFractionDose
    from raystation.v2025.beam_set import RadiationSet
    from raystation.v2025.dose import DoseGrid
    from raystation.v2025.ml import MachineLearningDose
    from raystation.v2025.patient import PatientModel, PatientModelReference
    from raystation.v2025.patient_db_types import AutoBreastSettings, AuxiliaryDataInDoseGrid, ColorMap, CompositeDose, ConvertedExamination, DicomPersonName, EQD2Dose, EpisodeOfCare, Examination, ExaminationGroup, ExaminationStructureSet, FractionDose, FrameOfReferenceRegistration, MappedDose, Matrix4, MediaResource, OcularSetupRadiographPair, OrganUncertaintySettings, PredictedMachineLearningDose, RegionOfInterest, RigidRegistration, RigidTransformationData, Snapshot, Tag, TreatmentDelivery
    from raystation.v2025.plan import BackupPlanIncludingTreatmentPlanGroup, ExplorationPlan, PlanExploration, PlanGenerationProtocol, TreatmentPlan, TreatmentPlanIncludingTreatmentPlanGroup
    from raystation.v2025.roi import RoiOverlapMeasures, StructureRegistration
    from raystation.v2025.treatment_module import TreatmentModule_TreatmentCourse



class TreatmentCaseIncludingStudy:
    @property
    def BodySite(self) -> str: ...
    @BodySite.setter
    def BodySite(self, value: str) -> None: ...
    @property
    def CaseName(self) -> str: ...
    @CaseName.setter
    def CaseName(self, value: str) -> None: ...
    @property
    def Comments(self) -> str: ...
    @Comments.setter
    def Comments(self, value: str) -> None: ...
    @property
    def Diagnosis(self) -> str: ...
    @Diagnosis.setter
    def Diagnosis(self, value: str) -> None: ...
    @property
    def AutoBreastSettings(self) -> AutoBreastSettings: ...
    @AutoBreastSettings.setter
    def AutoBreastSettings(self, value: AutoBreastSettings) -> None: ...
    @property
    def BackupPlans(self) -> ScriptObjectCollection[BackupPlanIncludingTreatmentPlanGroup]: ...
    @BackupPlans.setter
    def BackupPlans(self, value: List[BackupPlanIncludingTreatmentPlanGroup]) -> None: ...
    @property
    def CaseSettings(self) -> CaseSettings: ...
    @CaseSettings.setter
    def CaseSettings(self, value: CaseSettings) -> None: ...
    @property
    def EpisodeOfCare(self) -> EpisodeOfCare: ...
    @EpisodeOfCare.setter
    def EpisodeOfCare(self, value: EpisodeOfCare) -> None: ...
    @property
    def ExaminationGroups(self) -> ScriptObjectCollection[ExaminationGroup]: ...
    @ExaminationGroups.setter
    def ExaminationGroups(self, value: List[ExaminationGroup]) -> None: ...
    @property
    def Examinations(self) -> ScriptObjectCollection[Examination]: ...
    @Examinations.setter
    def Examinations(self, value: List[Examination]) -> None: ...
    @property
    def FrameOfReferenceRegistrations(self) -> ScriptObjectCollection[FrameOfReferenceRegistration]: ...
    @FrameOfReferenceRegistrations.setter
    def FrameOfReferenceRegistrations(self, value: List[FrameOfReferenceRegistration]) -> None: ...
    @property
    def OcularSetupRadiographPairs(self) -> ScriptObjectCollection[OcularSetupRadiographPair]: ...
    @OcularSetupRadiographPairs.setter
    def OcularSetupRadiographPairs(self, value: List[OcularSetupRadiographPair]) -> None: ...
    @property
    def PatientModel(self) -> PatientModel: ...
    @PatientModel.setter
    def PatientModel(self, value: PatientModel) -> None: ...
    @property
    def PatientModelReferences(self) -> ScriptObjectCollection[PatientModelReference]: ...
    @PatientModelReferences.setter
    def PatientModelReferences(self, value: List[PatientModelReference]) -> None: ...
    @property
    def Photos(self) -> ScriptObjectCollection[MediaResource]: ...
    @Photos.setter
    def Photos(self, value: List[MediaResource]) -> None: ...
    @property
    def Physician(self) -> DicomPersonName: ...
    @Physician.setter
    def Physician(self, value: DicomPersonName) -> None: ...
    @property
    def PlanExplorations(self) -> ScriptObjectCollection[PlanExploration]: ...
    @PlanExplorations.setter
    def PlanExplorations(self, value: List[PlanExploration]) -> None: ...
    @property
    def ReferencedExaminationsInOtherStudies(self) -> ScriptObjectCollection[Examination]: ...
    @ReferencedExaminationsInOtherStudies.setter
    def ReferencedExaminationsInOtherStudies(self, value: List[Examination]) -> None: ...
    @property
    def RigidRegistrations(self) -> ScriptObjectCollection[RigidRegistration]: ...
    @RigidRegistrations.setter
    def RigidRegistrations(self, value: List[RigidRegistration]) -> None: ...
    @property
    def Snapshots(self) -> ScriptObjectCollection[Snapshot]: ...
    @property
    def StructureRegistrations(self) -> ScriptObjectCollection[StructureRegistration]: ...
    @StructureRegistrations.setter
    def StructureRegistrations(self, value: List[StructureRegistration]) -> None: ...
    @property
    def Tags(self) -> ScriptObjectCollection[Tag]: ...
    @property
    def TreatmentDelivery(self) -> TreatmentDelivery: ...
    @TreatmentDelivery.setter
    def TreatmentDelivery(self, value: TreatmentDelivery) -> None: ...
    @property
    def TreatmentPlans(self) -> ScriptObjectCollection[TreatmentPlanIncludingTreatmentPlanGroup]: ...
    @TreatmentPlans.setter
    def TreatmentPlans(self, value: List[TreatmentPlanIncludingTreatmentPlanGroup]) -> None: ...
    def AddAdaptedPlanAndBeamSets(self, BaseBeamSetNameToAdaptedBeamSetNumberOfFractions: Dict[str, Any] = ..., BaseBeamSetNameToAdaptedBeamSetName: Dict[str, Any] = ..., StartingAtFraction: int = ..., AdaptToPlanName: str = ..., BackgroundDoseSource: Literal['None', 'Planned', 'Delivered'] = ..., PlanName: str = ..., PlannedBy: str = ..., Comment: str = ..., ExaminationName: str = ..., IsMedicalOncologyPlan: bool = ..., AllowDuplicateNames: bool = ..., CreateEmptyTotalDoseGrid: Optional[bool] = ...) -> TreatmentPlan:
        """A base plan is used to create an adapted plan on a specified planning image set."""
        ...
    def AddBrachyTreatmentPlan(self, PlanName: str, PlannedBy: str = ..., Comment: str = ..., ExaminationName: str = ..., AfterloaderName: str = ..., ApplicationSetupName: str = ..., SourceSerialNumber: str = ..., BrachyTreatmentType: Literal['HDR'] = ..., NumberOfFractions: int = ...) -> TreatmentPlan:
        """Adds a new brachy treatment plan."""
        ...
    def AddCustomEvaluationDose(self, Name: str, ExaminationName: str, ReferencedBeamSet: RadiationSet, DoseGridNumberOfVoxels: Any, DoseGridVoxelSize: Any, DoseGridCorner: Any, FractionDoseValues: np.ndarray, IsRbeDose: bool = ...) -> None:
        """Adds a custom evaluation dose as a fraction dose in cGy."""
        ...
    def AddNewAdaptedPlan(self, StartingAtFraction: int, AdaptToPlanName: str, BackgroundDoseSource: Literal['None', 'Planned', 'Delivered'] = ..., PlanName: str = ..., PlannedBy: str = ..., Comment: str = ..., ExaminationName: str = ..., IsMedicalOncologyPlan: bool = ..., AllowDuplicateNames: bool = ..., CreateEmptyTotalDoseGrid: Optional[bool] = ...) -> TreatmentPlan:
        """Adds a new adapted plan without beamsets."""
        ...
    def AddNewPlan(self, PlanName: str, PlannedBy: str = ..., Comment: str = ..., ExaminationName: str = ..., IsMedicalOncologyPlan: bool = ..., AllowDuplicateNames: bool = ..., CreateEmptyTotalDoseGrid: Optional[bool] = ...) -> TreatmentPlan:
        """Adds a new treatment plan without beamsets."""
        ...
    def AddNewPlanFromBeamSets(self, PlanName: str, PlannedBy: str = ..., Comment: str = ..., ExaminationName: str = ..., RadiationSets: List[RadiationSet] = ...) -> TreatmentPlan:
        """Adds a new plan from existing beam sets"""
        ...
    def AddReferencesToExaminationsInOtherCases(self, Examinations: List[Examination]) -> None:
        """Adds references to examinations in other cases"""
        ...
    def AddSnapshot(self, ForPlan: TreatmentPlan, Title: str, ImageData: np.ndarray, Description: str = ..., ForBeamSet: RadiationSet = ..., ImageFormat: str = ..., CreationTime: str = ..., IncludedInReport: bool = ...) -> None:
        """Add a new snapshot to the treatment case. The snapshot must be associated with a plan in the treatment case."""
        ...
    def ComputeGrayLevelBasedImageRegistration(self, RegistrationName: str, UseOnlyTranslations: bool = ..., HighWeightOnBones: bool = ..., InitializeImages: bool = ..., FocusRoisNames: List[str] = ..., FocusVolumeOfInterest: List[Any] = ...) -> None:
        """Computes a rigid image registration based on graylevel information."""
        ...
    def ComputeGrayLevelBasedRigidRegistration(self, FloatingExamination: Examination, ReferenceExamination: Examination, RegistrationName: str = ..., UseOnlyTranslations: bool = ..., HighWeightOnBones: bool = ..., InitializeImages: bool = ..., FocusRoisNames: List[str] = ..., FocusVolumeOfInterest: List[Any] = ...) -> None:
        """Computes a rigid registration based on graylevel information. The result is stored either as"""
        ...
    def ComputeROIBasedFoRRegistration(self, FloatingExamination: Examination, ReferenceExamination: Examination, DiscardRotations: bool = ..., RoiNames: List[str] = ...) -> None:
        """Computes a rigid registration based on ROIs that have geometries in both floating and reference examination."""
        ...
    def CopyAndAdjustTomoPlanToNewMachine(self, PlanName: str, NewMachineName: str, OnlyCopyAndChangeMachine: bool = ...) -> None:
        """Copy a Tomo treatment plan to another Tomo machine and adjust the plan to compensate for the differences between the machines"""
        ...
    def CopyPlan(self, PlanName: str, NewPlanName: str, KeepBeamSetNames: bool = ...) -> None:
        """Copies a treatment plan."""
        ...
    def CopyPlanExploration(self, PlanExploration: PlanExploration, NewPlanExplorationName: str) -> PlanExploration:
        """Copies a plan exploration and all its data."""
        ...
    def Create4DCTProjection(self, ExaminationName: str, ExaminationGroupName: str, ProjectionMethod: Literal['MaximumIntensity', 'MinimumIntensity', 'AverageIntensity'] = ...) -> None:
        """Creates a projection of a 4DCT using minimum-, maximum- or average intensity projection."""
        ...
    def CreateBreastPlan(self, PlanName: str, Examination: str, PlannedBy: str = ..., DoseGridResolution: float = ..., NumberOfFractions: int = ..., TreatmentMachine: str = ..., FluenceMode: Optional[Literal['FFF', 'SRS']] = ..., DoseAlgorithm: Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls'] = ..., StatisticalUncertainty: Optional[float] = ..., CreateSetupBeams: bool = ..., UniformDoseToTarget: float = ..., TargetColor: str = ...) -> TreatmentPlan:
        """For auto breast planning only."""
        ...
    def CreateDefaultVSimPlan(self, Isocenter: Any, ExaminationName: str) -> str:
        """Adds a new treatment plan using the default machine specified in ClinicDB. If the machine"""
        ...
    def CreateExaminationGroup(self, ExaminationGroupName: str, ExaminationGroupType: Literal['Collection4dct', 'PetCT', 'CollectionMrProtocol', 'Collection4dMr', 'CollectionOrganMotion'] = ..., ExaminationNames: List[str] = ...) -> None:
        """Creates a group of examinations (4DCT, PETCT, MR protocol, 4DMR)."""
        ...
    def CreateExplorationPlanFromProtocol(self, PlanExploration: PlanExploration, Protocol: PlanGenerationProtocol, Examination: Examination) -> ExplorationPlan:
        """Creates an exploration plan using a protocol."""
        ...
    def CreateNamedFrameOfReferenceRegistration(self, FromExamination: Examination, ToExamination: Examination, RegistrationName: str = ..., Description: str = ..., RegistrationMatrix: Union[Matrix4, Any] = ...) -> None:
        """Creates a frame-of-reference registration with the suggested name and matrix."""
        ...
    def CreateNamedImageRegistration(self, FromExamination: Examination, ToExamination: Examination, RegistrationName: str, Description: str, RegistrationMatrix: Union[Matrix4, Any]) -> None:
        """Creates an image registration between two examinations with the suggested name and matrix."""
        ...
    def CreateNewCorrectedCbct(self, CorrectedCbctName: str, ReferenceExaminationName: str, TargetExaminationName: str, FovRoiName: str = ..., DeformableRegistrationName: str = ..., CreateNewDeformableRegistration: bool = ..., CreateNewFieldOfView: bool = ...) -> ConvertedExamination:
        """Method that converts a CBCT image to a CT-like image using the Corrected CBCT algorithm."""
        ...
    def CreateNewVirtualCt(self, VirtualCtName: str, ReferenceExaminationName: str, TargetExaminationName: str, FovRoiName: str = ..., DeformableRegistrationName: str = ..., CreateNewDeformableRegistration: bool = ..., CreateNewFieldOfView: bool = ...) -> ConvertedExamination:
        """Method that converts a CBCT image to a CT-like image using the Virtual CT algorithm."""
        ...
    def CreateOrUpdateSettings(self, SettingsData: AutoBreastSettings = ...) -> None:
        """Creates (if it does not exist) or updates (if it exists) AutoBreastSettings on specified TreatmentCase."""
        ...
    def CreatePlanExploration(self, Name: str, Description: str = ..., PlannedBy: str = ...) -> PlanExploration:
        """Creates a new plan exploration."""
        ...
    def CreateSummedDose(self, DoseName: str, FractionNumber: int = ..., DoseDistributions: List[Any] = ..., Weights: List[float] = ...) -> CompositeDose:
        """Creates a summed dosedistribution from the specified doses and adds the new dose to the specified fraction evaluation."""
        ...
    def CreateTreatmentPlanFromValidationDataSet(self, ValidationDataSet: Dict[str, Any]) -> None:
        """Creates an electron or ion treatment plan from a data set."""
        ...
    def DeleteExamination(self, Examination: Examination) -> None:
        """Action for deleting an examination."""
        ...
    def DeleteExaminationGroup(self, ExaminationGroup: ExaminationGroup) -> None:
        """Deletes an examination group."""
        ...
    def DeleteOcularSetupRadiographPair(self, RadiographPair: OcularSetupRadiographPair) -> None:
        """Deletes an OcularSetupRadiographPair."""
        ...
    def DeletePhoto(self, Photo: MediaResource) -> None:
        """Deletes a photo."""
        ...
    def DeleteStructureRegistrations(self, StructureRegistrations: List[StructureRegistration]) -> None:
        """Removes structure registrations (deformable registrations or structure registration used to store added rigid transform)."""
        ...
    def EditCaseInformation(self, CaseName: str, BodySite: str = ..., Comments: str = ..., EpisodeOfCareName: str = ..., PhysicianName: str = ...) -> None:
        """Updating the case information."""
        ...
    def EditPatientTags(self, StructureSetsAndAddedTags: Dict[str, Any], StructureSetsAndRemovedTags: Dict[str, Any], TreatmentPlansAndAddedTags: Dict[str, Any], TreatmentPlansAndRemovedTags: Dict[str, Any]) -> None:
        """Edits patient tags."""
        ...
    def GenerateOrganMotionExaminationGroup(self, OrganUncertaintySettings: Union[OrganUncertaintySettings, Any], OnlySimulateMaxOrganMotion: bool = ..., SourceExamination: Examination = ..., ExaminationGroupName: str = ..., MotionRoiName: str = ..., FixedRoiNames: List[Any] = ...) -> Dict[str, Any]:
        """Generate a group of deformed examinations to simulate the motion of organs."""
        ...
    def GenerateOrganMotionExaminationGroupForTranslationList(self, OrganTranslations: List[Any], SourceExamination: Examination, ExaminationGroupName: str, MotionRoiName: str, FixedRoiNames: List[Any]) -> Dict[str, Any]:
        """Generate a group of deformed examinations to simulate the motion of organs."""
        ...
    def GetCaseUuid(self) -> Optional[str]:
        """Gets the UUID from the TreatmentCase"""
        ...
    def GetTotalTransformForExaminations(self, FromExamination: str, ToExamination: str) -> np.ndarray:
        """Gets the rigid transform between two examinations based on their frame-of-reference registration (typically created by treatment position alignment) and additional rigid transform."""
        ...
    def GetTransform(self, FromFrameOfReference: str, ToFrameOfReference: str) -> np.ndarray:
        """Gets the rigid transform between two frame-of-references."""
        ...
    def GetTransformForExaminations(self, FromExamination: str, ToExamination: str) -> np.ndarray:
        """Gets the rigid transform between two examinations based on their frame-of-reference registration."""
        ...
    def ImageSimilarityForRigidRegistration(self, ReferenceImageName: str, TargetImageName: str, RigidTransformation: np.ndarray, RoiNames: List[str]) -> Dict[str, Any]:
        """Compute image similarity between two images (reference and target). A rigid transformation is applied to the reference image."""
        ...
    def ImportPhoto(self, FileName: str) -> None:
        """Imports a photo to the current case."""
        ...
    def LoadExamination(self, ExaminationInfo: Dict[str, Any]) -> Examination:
        """Sets the active/current examination. Returns a handle to the examination."""
        ...
    def LoadPlan(self, PlanInfo: Dict[str, Any]) -> TreatmentPlan:
        """Loads a plan from a case. Returns a handle to the plan."""
        ...
    def LoadTreatmentCourse(self) -> TreatmentModule_TreatmentCourse:
        """Loads the treatment course aggregate which is linked to the given patient id and case name."""
        ...
    def MapDose(self, FractionEvaluationIndex: int = ..., DoseDistribution: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose] = ..., StructureRegistration: StructureRegistration = ..., ReferenceDoseGrid: DoseGrid = ...) -> None:
        """Action for mapping dose from the target examination of the registration to the reference examination of the registration."""
        ...
    def OutlineMbsMesh(self, ExternalMbsRoiName: str = ..., ExternalMbsRoiColor: str = ..., ModelExaminationName: str = ..., TargetExaminationNames: List[str] = ..., SuperiorInferiorRange: np.ndarray = ..., UseExistingExternalMbsModel: bool = ...) -> None:
        """Creates an external MBS model based on the external geometry on the "model examination" and stores it in the data base (for future use)."""
        ...
    def QueryPlanInfo(self, Filter: Dict[str, Any]) -> List[Any]:
        """Returns info on plans in a case."""
        ...
    def RecomputeOrganMotionExaminations(self, ExaminationNames: List[str]) -> None:
        """Recompute organ motion examinations and related deformable registrations."""
        ...
    def RemoveFrameOfReferenceRegistration(self, FloatingFrameOfReference: str, ReferenceFrameOfReference: str) -> None:
        """Removes a registration between two frame-of-references."""
        ...
    def RemoveImageRegistration(self, ImageRegistrationName: str) -> None:
        """Removes an image registration"""
        ...
    def RemoveReferencesToExaminationsInOtherCases(self, Examinations: List[Examination]) -> None:
        """Removes references to examinations in other cases"""
        ...
    def RunAutomatedReplanning(self, TargetFraction: int, BaseBeamSet: RadiationSet, FractionImageSet: Examination, ReplanningProtocol: PlanGenerationProtocol) -> TreatmentPlan:
        """Runs automated replanning and returns the created adapted plan."""
        ...
    def SavePrimaryExamination(self, PrimaryExamination: Examination) -> None:
        """Storing the selected Primary image set in the case(study)."""
        ...
    def SaveSecondaryExamination(self, SecondaryExamination: Examination) -> None:
        """Storing the selected Secondary image set in the case(study)."""
        ...
    def ScriptableDicomExport(self, AnonymizationSettings: Dict[str, Any] = ..., Connection: Dict[str, Any] = ..., ExportFolderPath: str = ..., Examinations: List[str] = ..., RtStructureSetsForExaminations: List[str] = ..., RtStructureSetsReferencedFromBeamSets: List[str] = ..., RtStructureSetsWithDicomUIDs: List[str] = ..., BeamSets: List[str] = ..., RtRadiationSetForBeamSets: List[str] = ..., RtRadiationsForBeamSets: List[str] = ..., PhysicalBeamSetDoseForBeamSets: List[str] = ..., EffectiveBeamSetDoseForBeamSets: List[str] = ..., PhysicalBeamDosesForBeamSets: List[str] = ..., EffectiveBeamDosesForBeamSets: List[str] = ..., SpatialRegistrationForExaminations: List[str] = ..., DeformableSpatialRegistrationsForExaminations: List[str] = ..., TreatmentBeamDrrImages: List[str] = ..., SetupBeamDrrImages: List[str] = ..., DicomFilter: str = ..., IgnorePreConditionWarnings: bool = ..., RayGatewayTitle: str = ..., TransferSyntaxOverride: str = ..., ExportAsBdspDose: bool = ...) -> str:
        """Exports specified DICOM datasets to either disk or SCP."""
        ...
    def ScriptableDicomVsimExport(self, AnonymizationSettings: Dict[str, Any] = ..., Connection: Dict[str, Any] = ..., ExportFolderPath: str = ..., BeamSet: str = ..., DicomFilter: str = ..., IgnorePreConditionWarnings: bool = ..., TransferSyntaxOverride: str = ...) -> str:
        """Exports specified DICOM datasets to either disk or SCP."""
        ...
    def ScriptableDicomVSimImport(self, Connection: Dict[str, Any] = ..., ImportFolderPath: str = ..., SeriesOrInstances: List[Any] = ..., AllowMismatchingPatientID: bool = ..., DicomFilter: str = ...) -> str:
        """Imports a DICOM RT Plans as a VSIM plan."""
        ...
    def SetCurrent(self) -> None:
        """Sets the current Case for a loaded patient"""
        ...
    def SetFoRRegistrationMatrix(self, FromExamination: Examination, ToExamination: Examination, TransformationMatrix: Union[Matrix4, Any] = ...) -> None:
        """Sets the frame of reference registration matrix between two frame of references."""
        ...
    def SetFoRRegistrationRigidTransformation(self, FromExamination: Examination, ToExamination: Examination, RigidTransformation: Union[RigidTransformationData, Any]) -> None:
        """Sets the rigid transformation between two examinations."""
        ...
    def SetProtocolsForAutomatedReplanning(self, BeamSets: List[RadiationSet], ProtocolNames: List[str]) -> None:
        """Sets intended replanning protocol for beam set when used as base beam set in automated replanning."""
        ...
    def SetRegistrationAsTreatmentPositionAlignment(self, FractionExamination: Examination, PlanningExamination: Examination) -> None:
        """Sets a frame-of reference registration as treatment position alignment."""
        ...
    def SimilarityForRigidlyMappedRoiGeometry(self, FromImageName: str, ToImageName: str, RoiGeometryName: str, RigidTransformation: np.ndarray) -> RoiOverlapMeasures:
        """Maps an RoiGeometry (RG) in the "from" image to the "to" image using a rigid transform, resulting in RG_map,"""
        ...
    def TagPlan(self, IdentifierName: str, Plan: TreatmentPlan) -> None:
        """Action that adds a tag with identifier name for a plan."""
        ...
    def TagStructureSet(self, IdentifierName: str, StructureSet: ExaminationStructureSet) -> None:
        """Action that adds a tag with identifier name for a structure set."""
        ...
    def TransformPointFromExaminationToExamination(self, FromExamination: str, ToExamination: str, Point: Any = ...) -> Optional[Point3[float]]:
        """Transforms a point (in DICOM patient coordinate system) from FromExamination to ToExamination."""
        ...
    def TransformPointFromExaminationToExaminationUsingTotalTransform(self, FromExamination: str, ToExamination: str, Point: Any = ...) -> Optional[Point3[float]]:
        """Transforms a point (in DICOM patient coordinate system) from FromExamination to ToExamination using the total transform (combining frame-of-reference registration with additional rigid transform if such exists)."""
        ...
    def TransformPointFromFoRToFoR(self, FromFrameOfReference: str, ToFrameOfReference: str, Point: Any = ...) -> Optional[Point3[float]]:
        """Transforms a point (in DICOM patient coordinate system) from FromFrameOfReference to ToFrameOfReference."""
        ...
    def UntagPlan(self, IdentifierName: str, Plan: TreatmentPlan) -> None:
        """Action that removes a tag with identifier name from a plan."""
        ...
    def UntagStructureSet(self, IdentifierName: str, StructureSet: ExaminationStructureSet) -> None:
        """Action that removes a tag with identifier name from a structure set."""
        ...

class CaseSettings:
    @property
    def CompensatorColorMap(self) -> ColorMap: ...
    @CompensatorColorMap.setter
    def CompensatorColorMap(self, value: ColorMap) -> None: ...
    @property
    def DisplacementFieldColorMap(self) -> ColorMap: ...
    @DisplacementFieldColorMap.setter
    def DisplacementFieldColorMap(self, value: ColorMap) -> None: ...
    @property
    def DoseColorMap(self) -> ColorMap: ...
    @DoseColorMap.setter
    def DoseColorMap(self, value: ColorMap) -> None: ...
    @property
    def DoseDiffColorMap(self) -> ColorMap: ...
    @DoseDiffColorMap.setter
    def DoseDiffColorMap(self, value: ColorMap) -> None: ...
    @property
    def FluenceColorMap(self) -> ColorMap: ...
    @FluenceColorMap.setter
    def FluenceColorMap(self, value: ColorMap) -> None: ...
    @property
    def FluenceDiffColorMap(self) -> ColorMap: ...
    @FluenceDiffColorMap.setter
    def FluenceDiffColorMap(self, value: ColorMap) -> None: ...
    @property
    def GammaColorMap(self) -> ColorMap: ...
    @GammaColorMap.setter
    def GammaColorMap(self, value: ColorMap) -> None: ...
    @property
    def HiddenRegionsOfInterest(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @HiddenRegionsOfInterest.setter
    def HiddenRegionsOfInterest(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def LetColorMap(self) -> ColorMap: ...
    @LetColorMap.setter
    def LetColorMap(self, value: ColorMap) -> None: ...
    @property
    def LetDiffColorMap(self) -> ColorMap: ...
    @LetDiffColorMap.setter
    def LetDiffColorMap(self, value: ColorMap) -> None: ...
    @property
    def PetImageColorMap(self) -> ColorMap: ...
    @PetImageColorMap.setter
    def PetImageColorMap(self, value: ColorMap) -> None: ...
    @property
    def RbeColorMap(self) -> ColorMap: ...
    @RbeColorMap.setter
    def RbeColorMap(self, value: ColorMap) -> None: ...
    @property
    def ResponseColorMap(self) -> ColorMap: ...
    @ResponseColorMap.setter
    def ResponseColorMap(self, value: ColorMap) -> None: ...
    @property
    def ResponseDiffColorMap(self) -> ColorMap: ...
    @ResponseDiffColorMap.setter
    def ResponseDiffColorMap(self, value: ColorMap) -> None: ...
