from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import BeamClearanceStatus, BeamCollisionStatus
    from raystation.v2025.beam_set import RadiationSet, TreatmentSetupIncludingRadiationSet
    from raystation.v2025.clinic_db import MapRtConnectionSettings
    from raystation.v2025.patient import PatientToBeamMapping
    from raystation.v2025.patient_db_types import Prescription, SubStructureSet
    from raystation.v2025.roi import RoiGeometry
    from raystation.v2025.setup import SetupMargins



class CollisionProperties:
    @property
    def BeamCollisionStatus(self) -> ScriptObjectCollection[BeamCollisionStatus]: ...
    @BeamCollisionStatus.setter
    def BeamCollisionStatus(self, value: List[BeamCollisionStatus]) -> None: ...
    @property
    def ForPrescription(self) -> Prescription: ...
    @ForPrescription.setter
    def ForPrescription(self, value: Prescription) -> None: ...
    @property
    def ForRadiationSet(self) -> RadiationSet: ...
    @ForRadiationSet.setter
    def ForRadiationSet(self, value: RadiationSet) -> None: ...
    @property
    def ForSubStructureSet(self) -> SubStructureSet: ...
    @ForSubStructureSet.setter
    def ForSubStructureSet(self, value: SubStructureSet) -> None: ...
    @property
    def ForTreatmentSetup(self) -> TreatmentSetupIncludingRadiationSet: ...
    @ForTreatmentSetup.setter
    def ForTreatmentSetup(self, value: TreatmentSetupIncludingRadiationSet) -> None: ...
    @property
    def SetupMargins(self) -> SetupMargins: ...
    @SetupMargins.setter
    def SetupMargins(self, value: SetupMargins) -> None: ...
    def NominalCollisionCheck(self) -> None:
        """Perform a collision check for all beams of the current beam set with the patient at nominal position for all treatment rooms supported by the beam model."""
        ...
    def ReadOnlyNominalCollisionCheckForBeam(self, BeamName: str) -> Literal['Unknown', 'HasCollision', 'NoCollision']:
        """Perform a read-only collision check for one beam of the current beam set with the patient at nominal position for all treatment rooms supported by the beam model."""
        ...
    def ReadOnlyWithinMarginsCollisionCheckForBeam(self, BeamName: str) -> Literal['Unknown', 'HasCollision', 'NoCollision']:
        """Perform a collision check for one beam of the current beam set including scenarios of table top motion based on patient displacements within the setup margins for all treatment rooms supported by the beam model."""
        ...
    def WithinMarginsCollisionCheck(self) -> None:
        """Perform a collision check for all beams of the current beam set including scenarios of table top motion based on patient displacements within the setup margins for all treatment rooms supported by the beam model."""
        ...

class CollisionCheckScenario:
    @property
    def LateralShift(self) -> float: ...
    @property
    def LongitudinalShift(self) -> float: ...
    @property
    def PitchShift(self) -> float: ...
    @property
    def RollShift(self) -> float: ...
    @property
    def RoomName(self) -> str: ...
    @property
    def VerticalShift(self) -> float: ...
    @property
    def YawShift(self) -> float: ...

class ClearanceCheck:
    @property
    def CouchMargin(self) -> float: ...
    @CouchMargin.setter
    def CouchMargin(self, value: float) -> None: ...
    @property
    def PatientMargin(self) -> float: ...
    @PatientMargin.setter
    def PatientMargin(self, value: float) -> None: ...
    @property
    def BeamClearanceStatuses(self) -> ScriptObjectCollection[BeamClearanceStatus]: ...
    @BeamClearanceStatuses.setter
    def BeamClearanceStatuses(self, value: List[BeamClearanceStatus]) -> None: ...
    @property
    def ClearanceMaps(self) -> ScriptObjectCollection[ClearanceMap]: ...
    @ClearanceMaps.setter
    def ClearanceMaps(self, value: List[ClearanceMap]) -> None: ...
    @property
    def ForTreatmentSetup(self) -> TreatmentSetupIncludingRadiationSet: ...
    @ForTreatmentSetup.setter
    def ForTreatmentSetup(self, value: TreatmentSetupIncludingRadiationSet) -> None: ...

class ClearanceMap:
    @property
    def CollisionStatus(self) -> ScriptObjectCollection[Any]: ...
    @property
    def CouchRotationAngles(self) -> np.ndarray: ...
    @property
    def GantryAngles(self) -> np.ndarray: ...
    @property
    def ForPatientToBeamMapping(self) -> PatientToBeamMapping: ...
    @ForPatientToBeamMapping.setter
    def ForPatientToBeamMapping(self, value: PatientToBeamMapping) -> None: ...
    @property
    def ForRoiGeometries(self) -> ScriptObjectCollection[RoiGeometry]: ...
    @ForRoiGeometries.setter
    def ForRoiGeometries(self, value: List[RoiGeometry]) -> None: ...

class ClearanceCheckSettings:
    @property
    def DefaultCouchMargin(self) -> float: ...
    @property
    def DefaultPatientMargin(self) -> float: ...
    @property
    def MapRtConnectionSettings(self) -> MapRtConnectionSettings: ...
