from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ElectronDoseDefaultSettings, PhotonDoseDefaultSettings, PhotonOptimizationAndSegmentationDefaultSettings
    from raystation.v2025.clearance import ClearanceCheckSettings
    from raystation.v2025.dose import DoseDefaultSettings
    from raystation.v2025.ion import IonDefaultSettings
    from raystation.v2025.machine import MachineSignature



class ClinicSpecificFragmentSpectra:
    @property
    def Comment(self) -> str: ...
    @property
    def Depths(self) -> np.ndarray: ...
    @property
    def FragmentCharges(self) -> np.ndarray: ...
    @property
    def FragmentEnergyBinEdges(self) -> np.ndarray: ...
    @property
    def FragmentSpectra(self) -> np.ndarray: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def Name(self) -> str: ...
    @property
    def NominalEnergies(self) -> np.ndarray: ...
    @property
    def NrOfDepthsPerNominalEnergy(self) -> np.ndarray: ...
    @property
    def NrOfFragmentEnergyBinsPerNominalEnergy(self) -> np.ndarray: ...
    @property
    def NrOfPrimaryEnergyBinsPerNominalEnergy(self) -> np.ndarray: ...
    @property
    def PrimaryCharge(self) -> int: ...
    @property
    def PrimaryEnergyBinEdges(self) -> np.ndarray: ...
    @property
    def PrimarySpectra(self) -> np.ndarray: ...

class ClinicDB:
    def CreateNewTag(self, DisplayName: str) -> None:
        """Action for creating a new tag"""
        ...
    def DeleteTag(self, IdentifierName: str) -> None:
        """Action that deletes the tag with IdentifierName."""
        ...
    def EditTagName(self, NewDisplayName: str, IdentifierName: str) -> None:
        """Action that modifies the tag's display name."""
        ...
    def GetSiteSettings(self) -> SiteSettings:
        """Load Site Settings"""
        ...
    def ImportVolumeRenderingTemplate(self, FileName: str) -> None:
        """Imports a VolumeRenderingFilter template from an backup (.rsbak) file."""
        ...
    def QueryScriptingEnvironmentInfo(self) -> List[Any]:
        """Returns info on all scripting environments in the clinic database."""
        ...

class SiteSettings:
    @property
    def AutoRecoverySettings(self) -> AutoRecoverySettings: ...
    @property
    def ClearanceCheckSettings(self) -> ClearanceCheckSettings: ...
    @property
    def DefaultQAPlanReportTemplate(self) -> ReportTemplate: ...
    @property
    def DefaultSettings(self) -> DefaultSettings: ...
    @property
    def DefaultTreatmentPlanReportTemplate(self) -> ReportTemplate: ...
    @property
    def DicomSettings(self) -> DicomSettings: ...
    @property
    def DoseDefaultSettings(self) -> DoseDefaultSettings: ...
    @property
    def ElectronDoseDefaultSettings(self) -> ElectronDoseDefaultSettings: ...
    @property
    def IonDefaultSettings(self) -> IonDefaultSettings: ...
    @property
    def LicenseSettings(self) -> LicenseSettings: ...
    @property
    def MachineSignatures(self) -> ScriptObjectCollection[MachineSignature]: ...
    @property
    def PhotonDoseDefaultSettings(self) -> PhotonDoseDefaultSettings: ...
    @property
    def PhotonOptimizationAndSegmentationDefaultSettings(self) -> PhotonOptimizationAndSegmentationDefaultSettings: ...
    @property
    def RayCareEnvironmentSettings(self) -> RayCareEnvironment: ...
    @property
    def ReportSettings(self) -> ReportSettings: ...
    @property
    def ReportTemplates(self) -> ScriptObjectCollection[ReportTemplate]: ...
    @property
    def ScriptSettings(self) -> ScriptSettings: ...
    @property
    def TagSettings(self) -> TagSettings: ...
    @property
    def TreatmentSettings(self) -> TreatmentSettings: ...
    @property
    def VirtualSimulationSettings(self) -> VirtualSimulationSettings: ...
    def CreateTreatmentSettings(self, PacsEndpoint: str = ..., SignOffRequiresUserAuthentication: bool = ...) -> TreatmentSettings:
        """Initializes the treatment setting to store data related to how RayTreat connect to RayCare and its drivers."""
        ...

class ReportTemplate:
    @property
    def ApprovalTime(self) -> str: ...
    @property
    def ApprovedBy(self) -> str: ...
    @property
    def FileNameFormatString(self) -> str: ...
    @property
    def IsApproved(self) -> bool: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def ReportContent(self) -> np.ndarray: ...
    @property
    def Type(self) -> Literal['TreatmentPlanReport', 'QAPlanReport']: ...

class DefaultSettings:
    @property
    def CouchShiftCoordinateType(self) -> Literal['Patient', 'Couch']: ...
    @property
    def EnableAutomaticCopyAlphabeticToIdeographicPatientName(self) -> bool: ...
    @property
    def EnableIdeographicPatientName(self) -> bool: ...
    @property
    def EnablePhoneticPatientName(self) -> bool: ...
    @property
    def ExportServiceTempFileLocation(self) -> Literal['LocalAppData', 'TargetFolder']: ...
    @property
    def HelpPath(self) -> str: ...
    @property
    def ImagingSystemMismatchGuardOption(self) -> Literal['Accept', 'Info', 'Warning', 'Reject']: ...
    @property
    def InstitutionName(self) -> str: ...
    @property
    def KnowledgeBaseUrl(self) -> str: ...
    @property
    def LeafPositioningPolicy(self) -> float: ...
    @property
    def OnlineHelpUrl(self) -> str: ...
    @property
    def ReportPaperSize(self) -> Literal['A4', 'Letter']: ...
    @property
    def SafetyContact(self) -> str: ...
    @property
    def ShowAcquiredImagesInTreatmentCourseList(self) -> bool: ...
    @property
    def ShowMcoModulePerDefault(self) -> bool: ...
    @property
    def ShowOrientationLettersInPatientImageViews(self) -> bool: ...
    @property
    def ShowPlanningImageInTreatmentCourseList(self) -> bool: ...
    @property
    def UseClassicScriptEditor(self) -> bool: ...
    @property
    def UseDefinedTreatmentSites(self) -> bool: ...
    @property
    def UseLocalActiveDirectoryGroups(self) -> bool: ...
    @property
    def UsePatientTreatmentPositionSameAsImagingPatientPosition(self) -> bool: ...
    @property
    def WarnIfApplyingUnapprovedTemplate(self) -> bool: ...
    @property
    def BodySiteDefinitions(self) -> ScriptObjectCollection[BodySiteDefinition]: ...
    @property
    def SecuritySettings(self) -> ScriptObjectCollection[SecuritySetting]: ...
    @property
    def UserGroupMappings(self) -> ScriptObjectCollection[UserGroupMapping]: ...

class UserGroupMapping:
    @property
    def DefaultGroupName(self) -> str: ...
    @property
    def MappedName(self) -> str: ...

class BodySiteDefinition:
    @property
    def ImageKey(self) -> str: ...
    @property
    def Name(self) -> str: ...

class SecuritySetting:
    @property
    def Level(self) -> Literal['Password', 'SingleSignOnOrPassword']: ...
    @property
    def Operation(self) -> Literal['ApprovePlan', 'ApproveConvertedExamination', 'ApproveProtocol', 'DeleteCommissionedMachine', 'CommissionMachine', 'Administration', 'AdministrationRayCommand', 'DeletePatient', 'ApproveToleranceTable', 'DeleteToleranceTable', 'SetQAStatusOnTreatmentPlan', 'SignTreatmentSession', 'ManageMachineLearningModels', 'TemplateMaterials', 'ApproveMedicalOncologyCycle', 'CommissionMedicalOncologyRegimenTemplate', 'CommissionMedicalOncologyActiveSubstance', 'CommissionBrachyUnit', 'ManageCyberKnifeMachineParameters', 'ConfirmBeam', 'StartSessionWithoutPassedRequiredQa', 'StartSessionWithRejectedOfflineReviewResults', 'ExecuteMovementWithoutCollisionCheck', 'DisableBeam', 'CommissionAblationApplicator', 'DevelopScript', 'ApproveScript', 'CreateScriptEnvironment', 'SelectBeamSetForSession']: ...
    @property
    def RequiredGroup(self) -> UserGroupMapping: ...

class ScriptSettings:
    @property
    def AdditionalSearchPath(self) -> str: ...

class LicenseSettings:
    @property
    def LicenseServerMachineName(self) -> str: ...
    @property
    def LicenseServerPort(self) -> int: ...
    @property
    def Type(self) -> Optional[Literal['Clinical', 'Evaluation', 'Research', 'Educational', 'Development', 'ResearchCollaboration', 'UserSiteValidation', 'Training', 'ProductionVerificationTest', 'Factory']]: ...
    @property
    def UseLicenseServer(self) -> bool: ...

class DicomSettings:
    @property
    def AutoExportDefaultSetupDRR(self) -> bool: ...
    @property
    def AutoExportDefaultTreatmentDRR(self) -> bool: ...
    @property
    def CloseExportDialogAfterExport(self) -> bool: ...
    @property
    def DefaultCharacterSet(self) -> Literal['ISO_IR_100', 'ISO_IR_192']: ...
    @property
    def DefaultExportPath(self) -> str: ...
    @property
    def DefaultImportPath(self) -> str: ...
    @property
    def DefaultSSCPDeleteAfterSuccessfulImportSetting(self) -> bool: ...
    @property
    def DrrRtImageLabelAndNameMode(self) -> Literal['BeamNumber', 'BeamName']: ...
    @property
    def EnableChecksums(self) -> bool: ...
    @property
    def HideRoisInExportedDrr(self) -> bool: ...
    @property
    def OverrideOriginalTransferSyntax(self) -> bool: ...
    @property
    def QAPatientNameSuffix(self) -> str: ...
    @property
    def QAPlanPatientIdentity(self) -> Literal['Patient', 'Phantom']: ...
    @property
    def QueryRetrievePort(self) -> int: ...
    @property
    def ShowCrosshairInDrr(self) -> bool: ...
    @property
    def ShowTextAnnotationsInExportedDrr(self) -> bool: ...
    @property
    def TransferSyntaxMode(self) -> Literal['Implicit', 'Explicit']: ...
    @property
    def DefaultAnonymizationOptions(self) -> DefaultAnonymizationOptions: ...
    @property
    def DefaultExportSelection(self) -> DefaultExportSelection: ...
    @property
    def DefaultExportTarget(self) -> DicomCommunicatorInfo: ...
    @property
    def DefaultImportSelection(self) -> DefaultImportSelection: ...
    @property
    def DefaultImportSource(self) -> DicomCommunicatorInfo: ...
    @property
    def DicomApplicationEntities(self) -> ScriptObjectCollection[DicomApplicationEntity]: ...
    @property
    def DicomFilters(self) -> ScriptObjectCollection[DicomFilter]: ...
    @property
    def DicomStorage(self) -> DicomStorage: ...
    @property
    def ImportModifiers(self) -> ImportModifiers: ...
    @property
    def RayCareCustomLabels(self) -> ScriptObjectCollection[CustomLabel]: ...
    @property
    def RayGatewayConnectionInfos(self) -> ScriptObjectCollection[RayGatewayConnectionInfo]: ...

class DicomApplicationEntity:
    @property
    def CalledApplicationEntityTitle(self) -> str: ...
    @property
    def CallingApplicationEntityTitle(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Hostname(self) -> str: ...
    @property
    def IsAutoExportEnabled(self) -> bool: ...
    @property
    def IsExacTracSystem(self) -> bool: ...
    @property
    def IsRayCarePacs(self) -> bool: ...
    @property
    def Port(self) -> int: ...
    @property
    def RemoteCallingApplicationEntityTitle(self) -> str: ...
    @property
    def SupportQRRO(self) -> bool: ...
    @property
    def SupportsQueryRetrieve(self) -> bool: ...
    @property
    def SupportsStorage(self) -> bool: ...
    @property
    def Title(self) -> str: ...
    @property
    def UseBundle(self) -> bool: ...

class DicomFilter:
    @property
    def AlwaysRun(self) -> bool: ...
    @property
    def Code(self) -> np.ndarray: ...
    @property
    def Configuration(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Expires(self) -> Optional[str]: ...
    @property
    def ImplementationType(self) -> Literal['LegacyXmlPython', 'DotNetAssembly', 'PreinstalledLegacyPython']: ...
    @property
    def IsConfigurationRequired(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def SignedApplicationVersions(self) -> ScriptObjectCollection[str]: ...
    @property
    def Type(self) -> Literal['Import', 'Export']: ...
    @property
    def Version(self) -> str: ...

class RayGatewayConnectionInfo:
    @property
    def Hostname(self) -> str: ...
    @property
    def Port(self) -> int: ...
    @property
    def Target(self) -> Literal['IDMS']: ...
    @property
    def Title(self) -> str: ...

class CustomLabel:
    @property
    def Name(self) -> str: ...
    @property
    def UseByDefaultForRtDose(self) -> Optional[bool]: ...
    @property
    def UseByDefaultForRtImage(self) -> Optional[bool]: ...
    @property
    def UseByDefaultForRtPlan(self) -> Optional[bool]: ...

class DicomStorage:
    @property
    def ScpLocation(self) -> str: ...

class DefaultAnonymizationOptions:
    @property
    def CleanDescriptorsOption(self) -> bool: ...
    @property
    def CleanPixelDataOption(self) -> bool: ...
    @property
    def RetainDeviceIdentityOption(self) -> bool: ...
    @property
    def RetainInstitutionIdentityOption(self) -> bool: ...
    @property
    def RetainLongitudinalTemporalInformationFullDatesOption(self) -> bool: ...
    @property
    def RetainLongitudinalTemporalInformationModifiedDatesOption(self) -> bool: ...
    @property
    def RetainPatientCharacteristicsOption(self) -> bool: ...
    @property
    def RetainSafePrivateOption(self) -> bool: ...
    @property
    def RetainUIDs(self) -> bool: ...

class DefaultExportSelection:
    @property
    def DoseTypeSelection(self) -> Literal['All', 'Physical', 'Effective']: ...
    @property
    def SelectAllBeamSets(self) -> bool: ...
    @property
    def SelectAllBeamSetsBeamDoses(self) -> bool: ...
    @property
    def SelectAllBeamSetsPlanDoses(self) -> bool: ...
    @property
    def SelectAllExaminations(self) -> bool: ...
    @property
    def SelectAllExaminationStructureSets(self) -> bool: ...
    @property
    def SelectAllSetupDRR(self) -> bool: ...
    @property
    def SelectAllTreatmentDRR(self) -> bool: ...
    @property
    def SelectCurrentBeamSet(self) -> bool: ...
    @property
    def SelectCurrentBeamSetBeamDose(self) -> bool: ...
    @property
    def SelectCurrentBeamSetPlanDose(self) -> bool: ...
    @property
    def SelectDefaultSetupDRR(self) -> bool: ...
    @property
    def SelectDefaultTreatmentDRR(self) -> bool: ...
    @property
    def SelectPlanningExamination(self) -> bool: ...
    @property
    def SelectPlanningExaminationStructureSet(self) -> bool: ...

class DefaultImportSelection:
    @property
    def ImageSeriesSortOrder(self) -> Literal['Ascending', 'Descending']: ...
    @property
    def SelectBeamDoses(self) -> bool: ...
    @property
    def SelectImageModalities(self) -> bool: ...
    @property
    def SelectPlanDoses(self) -> bool: ...
    @property
    def SelectPlans(self) -> bool: ...
    @property
    def SelectSpatialRegistrations(self) -> bool: ...
    @property
    def SelectStructureSets(self) -> bool: ...
    @property
    def ShowStudyLevel(self) -> bool: ...

class ImportModifiers:
    @property
    def EnableAlignImageOrientationMR(self) -> bool: ...
    @property
    def EnableConvertUnsignedToSignedMR(self) -> bool: ...
    @property
    def EnableRemoveArtifactsFromCT(self) -> bool: ...
    @property
    def EnableRescalePET(self) -> bool: ...

class DicomCommunicatorInfo:
    @property
    def CommunicationMode(self) -> Literal['File', 'DicomApplicationEntity', 'RayGateway', 'StorageScp', 'None']: ...
    @property
    def Title(self) -> str: ...

class VirtualSimulationSettings:
    @property
    def AssignDefaultDoseGrid(self) -> bool: ...
    @property
    def CreateExternal(self) -> bool: ...
    @property
    def DefaultEnergy(self) -> int: ...
    @property
    def DefaultMachineName(self) -> str: ...

class AutoRecoverySettings:
    @property
    def CustomPath(self) -> str: ...
    @property
    def Mode(self) -> Literal['Off', 'Database', 'FileSystem']: ...

class TreatmentSettings:
    @property
    def HostNameToRoomNameMapping(self) -> Dict[str, Any]: ...
    @property
    def PacsEndpoint(self) -> str: ...
    @property
    def PacsRequiresAuthentication(self) -> bool: ...
    @property
    def SignOffRequiresUserAuthentication(self) -> bool: ...
    @property
    def RoomSettings(self) -> ScriptObjectCollection[TreatmentRoomSettings]: ...
    def AddTreatmentRoomSettings(self, RoomName: str, DriverId: str = ..., DriverVersion: str = ..., DriverRemoteEndpoint: str = ..., DriverLocalPort: int = ..., MachineModels: List[Any] = ..., IsCollisionCheckRequired: bool = ...) -> TreatmentRoomSettings:
        """Creates a new treatment room settings to connect to a new treament driver."""
        ...
    def EditTreatmentSettings(self, PacsEndpoint: str = ..., PacsRequiresAuthentication: bool = ..., SignOffRequiresUserAuthentication: bool = ...) -> None:
        """Edits the treatment setting which stores the data related to how RayTreat connect to RayCare and its drivers."""
        ...

class TreatmentRoomSettings:
    @property
    def ImagingDeviceTransformation(self) -> Optional[Point3[float]]: ...
    @property
    def InternalFeatures(self) -> Dict[str, Any]: ...
    @property
    def IsCollisionCheckRequired(self) -> bool: ...
    @property
    def MachineModels(self) -> ScriptObjectCollection[str]: ...
    @property
    def RoomName(self) -> str: ...
    @property
    def SupportedImagingProtocols(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedOnlineStrategies(self) -> ScriptObjectCollection[Any]: ...
    @property
    def DriverSettings(self) -> TreatmentDriverSettings: ...
    @property
    def UserCredentials(self) -> OAuthUserCredentials: ...
    def EditTreatmentRoomSettings(self, RoomName: str, DriverId: str = ..., DriverVersion: str = ..., DriverRemoteEndpoint: str = ..., DriverLocalPort: int = ..., DefaultComputerName: str = ..., ImagingProtocols: List[Any] = ..., OnlineStrategies: List[Any] = ..., InternalFeatures: Dict[str, Any] = ..., MachineModels: List[Any] = ..., ImagingDeviceTransformation: Optional[Union[Point3[float], Point3Dict[float]]] = ..., IsCollisionCheckRequired: bool = ...) -> None:
        """Edits an existing treatment room settings for an existing treatment driver."""
        ...
    def SetUserCredentials(self, Username: str, Password: str) -> None:
        """Sets the username and password used to connect to RayCare for the given driver."""
        ...

class OAuthUserCredentials:
    @property
    def EncryptedPassword(self) -> str: ...
    @property
    def Salt(self) -> np.ndarray: ...
    @property
    def Username(self) -> str: ...

class TreatmentDriverSettings:
    @property
    def DriverId(self) -> str: ...
    @property
    def LocalEndpointPort(self) -> int: ...
    @property
    def RemoteEndpoint(self) -> str: ...
    @property
    def Version(self) -> str: ...

class ThreeDCRTSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MinSegmentMuPerFraction(self) -> float: ...
    @property
    def OptimizationTolerance(self) -> float: ...

class VmatDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @property
    def IterationsBeforeConversion(self) -> int: ...
    @property
    def MaxLeafTravelDistancePerDegree(self) -> float: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MinSegmentArea(self) -> float: ...
    @property
    def OptimizationTolerance(self) -> float: ...
    @property
    def UseMaxLeafTravelDistancePerDegree(self) -> bool: ...
    @property
    def UseSlidingWindowSequencing(self) -> bool: ...

class SmlcDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @property
    def IterationsBeforeConversion(self) -> int: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MaxNumberOfSegments(self) -> int: ...
    @property
    def MinLeafEndSeparation(self) -> float: ...
    @property
    def MinNumberOfOpenLeafPairs(self) -> int: ...
    @property
    def MinSegmentArea(self) -> float: ...
    @property
    def MinSegmentMuPerFraction(self) -> float: ...
    @property
    def OptimizationTolerance(self) -> float: ...

class DmlcDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @property
    def IterationsBeforeConversion(self) -> int: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MaxNumberOfSegments(self) -> int: ...
    @property
    def OptimizationTolerance(self) -> float: ...

class ConformalArcSettings:
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def OptimizationTolerance(self) -> float: ...

class RayCareEnvironment:
    @property
    def CommercialVersion(self) -> str: ...
    @property
    def ConfigurationEndPoint(self) -> str: ...
    @property
    def Descriptor(self) -> str: ...
    @property
    def ClientCredentials(self) -> OAuthClientCredentials: ...

class OAuthClientCredentials:
    @property
    def ClientId(self) -> str: ...
    @property
    def EncryptedClientSecret(self) -> str: ...
    @property
    def Endpoint(self) -> str: ...
    @property
    def Salt(self) -> np.ndarray: ...

class TagSettings:
    @property
    def UseTags(self) -> bool: ...

class ReportSettings:
    @property
    def DefaultReportCreationPath(self) -> str: ...

class MapRtConnectionSettings:
    @property
    def HostName(self) -> str: ...
    @property
    def Port(self) -> int: ...
    @property
    def Timeout(self) -> int: ...

class VolumeRenderFilter:
    @property
    def CropToExternal(self) -> bool: ...
    @property
    def HistogramPan(self) -> Tuple[float, ...]: ...
    @property
    def HistogramScale(self) -> Tuple[float, ...]: ...
    @property
    def Modality(self) -> Literal['CT', 'MR', 'Cbct', 'Pet']: ...
    @property
    def Name(self) -> str: ...
    @property
    def TransferFunctions(self) -> ScriptObjectCollection[VolumeRenderTransferFunction]: ...
    def ExportVolumeRenderingFilterTemplate(self, FileName: str) -> None:
        """Exports a VolumeRenderFilter template to a backup (.rsbak) file."""
        ...

class VolumeRenderTransferFunction:
    @property
    def Color(self) -> str: ...
    @property
    def GradientWidth(self) -> float: ...
    @property
    def Is1D(self) -> bool: ...
    @property
    def Points(self) -> ScriptObjectCollection[Any]: ...
    @property
    def Visible(self) -> bool: ...
