from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.auto_planning import AutoPlanningRoi
    from raystation.v2025.beam import BeamFractionDose
    from raystation.v2025.beam_set import RadiationSet
    from raystation.v2025.ml import MachineLearningDose
    from raystation.v2025.patient_db_types import AlgorithmVersion, AuxiliaryDataInDoseGrid, CellTypeAndMaterialSpecificRbeDose, ComparativeEvaluation, CompositeDose, Constraint, DensityDistribution, EQD2Dose, EqdDistributions, EudFunction, Examination, ExaminationStructureSet, ExternalLibraryProperties, FractionDose, FractionationPattern, FrameOfReferenceRegistration, FunctionValues, LetVolumeFunction, LqModelParameters, MappedDose, OnesidedUniformReferenceDoseFunction, PhysicalData, PoiGeometry, PredictedMachineLearningDose, PrescribedDoseLevel, RbeModelData, ReferenceDoseFallOffFunction, ReferenceDoseFunction, ReferenceDvhFunction, ReferenceIsoDoseVolumeFunction, RegionOfInterest, ResponseFunctionParameters, SpatialDosePriorFunction, TotalCrossEntropyFunction, UniformityConstraint, VersioningStatus, VolumeLevel
    from raystation.v2025.plan import PlanningGoal, PlanningGoalFunction
    from raystation.v2025.roi import RoiGeometry, RoiVolumeDistribution



class DoseFallOffParameters:
    @property
    def AdaptToTargetDoseLevels(self) -> bool: ...
    @AdaptToTargetDoseLevels.setter
    def AdaptToTargetDoseLevels(self, value: bool) -> None: ...
    @property
    def FunctionType(self) -> Literal['MinDose', 'MaxDose', 'UniformDose', 'MinDoseAtVolume', 'MaxDoseAtVolume', 'MinEud', 'MaxEud', 'DoseFallOff']: ...
    @FunctionType.setter
    def FunctionType(self, value: Literal['MinDose', 'MaxDose', 'UniformDose', 'MinDoseAtVolume', 'MaxDoseAtVolume', 'MinEud', 'MaxEud', 'DoseFallOff']) -> None: ...
    @property
    def LowDoseDistance(self) -> float: ...
    @LowDoseDistance.setter
    def LowDoseDistance(self, value: float) -> None: ...
    @property
    def RelativeLowDoseWeight(self) -> float: ...
    @RelativeLowDoseWeight.setter
    def RelativeLowDoseWeight(self, value: float) -> None: ...
    @property
    def HighDoseLevel(self) -> DoseLevel: ...
    @HighDoseLevel.setter
    def HighDoseLevel(self, value: DoseLevel) -> None: ...
    @property
    def LowDoseLevel(self) -> DoseLevel: ...
    @LowDoseLevel.setter
    def LowDoseLevel(self, value: DoseLevel) -> None: ...

class DoseLevel:
    @property
    def AbsoluteValue(self) -> Optional[float]: ...
    @property
    def PercentValue(self) -> Optional[float]: ...
    @property
    def RelativeToDoseLevel(self) -> PrescribedDoseLevel: ...
    @RelativeToDoseLevel.setter
    def RelativeToDoseLevel(self, value: PrescribedDoseLevel) -> None: ...
    def EditDoseLevel(self, AbsoluteDoseLevel: Optional[float] = ..., PercentDoseLevel: Optional[float] = ..., RelativeToDoseLevel: PrescribedDoseLevel = ...) -> None:
        """Edits the dose level."""
        ...

class DoseVolumeParameters:
    @property
    def FunctionType(self) -> Literal['MinDose', 'MaxDose', 'UniformDose', 'MinDoseAtVolume', 'MaxDoseAtVolume', 'MinEud', 'MaxEud', 'DoseFallOff']: ...
    @FunctionType.setter
    def FunctionType(self, value: Literal['MinDose', 'MaxDose', 'UniformDose', 'MinDoseAtVolume', 'MaxDoseAtVolume', 'MinEud', 'MaxEud', 'DoseFallOff']) -> None: ...
    @property
    def DoseLevel(self) -> DoseLevel: ...
    @DoseLevel.setter
    def DoseLevel(self, value: DoseLevel) -> None: ...
    @property
    def VolumeLevel(self) -> VolumeLevel: ...
    @VolumeLevel.setter
    def VolumeLevel(self, value: VolumeLevel) -> None: ...

class DoseAtVolumeGoal:
    @property
    def GoalCriteria(self) -> Literal['AtLeast', 'AtMost']: ...
    @GoalCriteria.setter
    def GoalCriteria(self, value: Literal['AtLeast', 'AtMost']) -> None: ...
    @property
    def ForAutoPlanningRoi(self) -> AutoPlanningRoi: ...
    @ForAutoPlanningRoi.setter
    def ForAutoPlanningRoi(self, value: AutoPlanningRoi) -> None: ...
    @property
    def PrimaryDoseLevel(self) -> DoseLevel: ...
    @PrimaryDoseLevel.setter
    def PrimaryDoseLevel(self, value: DoseLevel) -> None: ...
    @property
    def SecondaryDoseLevel(self) -> DoseLevel: ...
    @SecondaryDoseLevel.setter
    def SecondaryDoseLevel(self, value: DoseLevel) -> None: ...
    @property
    def VolumeLevel(self) -> VolumeLevel: ...
    @VolumeLevel.setter
    def VolumeLevel(self, value: VolumeLevel) -> None: ...
    def DeleteAutoPlanningDoseGoal(self) -> None:
        """Deletes the auto-planning dose goal."""
        ...

class DoseSpecificationPoint:
    @property
    def Coordinates(self) -> Tuple[float, ...]: ...
    @Coordinates.setter
    def Coordinates(self, value: Tuple[float, ...]) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def VisualizationDiameter(self) -> float: ...
    @VisualizationDiameter.setter
    def VisualizationDiameter(self, value: float) -> None: ...

class DoseValues:
    @property
    def CalculationInfo(self) -> str: ...
    @property
    def DoseData(self) -> np.ndarray: ...
    @property
    def DoseUncertainty(self) -> np.ndarray: ...
    @property
    def IsAccurate(self) -> bool: ...
    @property
    def IsFromUncommissionedMachine(self) -> Optional[bool]: ...
    @property
    def MCTotalNumberOfHistories(self) -> Optional[int]: ...
    @property
    def RelativeStatisticalUncertainty(self) -> Optional[float]: ...
    @property
    def AlgorithmProperties(self) -> DoseAlgorithmProperties: ...
    @property
    def EqdDistributions(self) -> EqdDistributions: ...
    @EqdDistributions.setter
    def EqdDistributions(self, value: EqdDistributions) -> None: ...
    @property
    def PhysicalData(self) -> PhysicalData: ...
    @PhysicalData.setter
    def PhysicalData(self, value: PhysicalData) -> None: ...
    @property
    def RbeDosePerCellTypeAndMaterial(self) -> ScriptObjectCollection[CellTypeAndMaterialSpecificRbeDose]: ...
    @property
    def RbeModelData(self) -> RbeModelData: ...
    @RbeModelData.setter
    def RbeModelData(self, value: RbeModelData) -> None: ...

class DoseAlgorithmProperties:
    @property
    def DoseAlgorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @property
    def LemClassicNumberOfRepetitions(self) -> Optional[int]: ...
    @property
    def TissueHeterogeneityCorrections(self) -> ScriptObjectCollection[Any]: ...
    @property
    def AlgorithmVersion(self) -> AlgorithmVersion: ...
    @property
    def ExternalLibraryProperties(self) -> ExternalLibraryProperties: ...

class DoseComputationSettings:
    @property
    def BrachyMCHistories(self) -> Optional[int]: ...
    @BrachyMCHistories.setter
    def BrachyMCHistories(self, value: Optional[int]) -> None: ...
    @property
    def ComputeDoseAveragedLet(self) -> bool: ...
    @ComputeDoseAveragedLet.setter
    def ComputeDoseAveragedLet(self, value: bool) -> None: ...
    @property
    def DoseAlgorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @DoseAlgorithm.setter
    def DoseAlgorithm(self, value: Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']) -> None: ...
    @property
    def IonMCHistoriesPerSpotForOptimization(self) -> Optional[int]: ...
    @IonMCHistoriesPerSpotForOptimization.setter
    def IonMCHistoriesPerSpotForOptimization(self, value: Optional[int]) -> None: ...
    @property
    def IonMCMeanHistoriesPerSpotForFinalDose(self) -> Optional[int]: ...
    @IonMCMeanHistoriesPerSpotForFinalDose.setter
    def IonMCMeanHistoriesPerSpotForFinalDose(self, value: Optional[int]) -> None: ...
    @property
    def IonMCUseStatisticalUncertaintyInsteadOfHistoriesForFinalDose(self) -> bool: ...
    @IonMCUseStatisticalUncertaintyInsteadOfHistoriesForFinalDose.setter
    def IonMCUseStatisticalUncertaintyInsteadOfHistoriesForFinalDose(self, value: bool) -> None: ...
    @property
    def LemClassicNumberOfRepetitions(self) -> Optional[int]: ...
    @LemClassicNumberOfRepetitions.setter
    def LemClassicNumberOfRepetitions(self, value: Optional[int]) -> None: ...
    @property
    def MCStatisticalUncertaintyForFinalDose(self) -> Optional[float]: ...
    @MCStatisticalUncertaintyForFinalDose.setter
    def MCStatisticalUncertaintyForFinalDose(self, value: Optional[float]) -> None: ...
    @property
    def StoreBeamDoseValues(self) -> bool: ...
    @StoreBeamDoseValues.setter
    def StoreBeamDoseValues(self, value: bool) -> None: ...

class DoseReferenceIdentifier:
    @property
    def UID(self) -> str: ...
    @UID.setter
    def UID(self, value: str) -> None: ...

class DoseResponse:
    @property
    def ResponsePlotXAxis(self) -> np.ndarray: ...
    @ResponsePlotXAxis.setter
    def ResponsePlotXAxis(self, value: np.ndarray) -> None: ...
    @property
    def ResponsePlotYAxis(self) -> np.ndarray: ...
    @ResponsePlotYAxis.setter
    def ResponsePlotYAxis(self, value: np.ndarray) -> None: ...

class DoseBasedRoiFunction:
    @property
    def Tag(self) -> str: ...
    @Tag.setter
    def Tag(self, value: str) -> None: ...
    @property
    def UseBeamSpecificForAllBeams(self) -> bool: ...
    @UseBeamSpecificForAllBeams.setter
    def UseBeamSpecificForAllBeams(self, value: bool) -> None: ...
    @property
    def UseRobustness(self) -> bool: ...
    @UseRobustness.setter
    def UseRobustness(self, value: bool) -> None: ...
    @property
    def ComparativeEvaluations(self) -> ScriptObjectCollection[ComparativeEvaluation]: ...
    @ComparativeEvaluations.setter
    def ComparativeEvaluations(self, value: List[ComparativeEvaluation]) -> None: ...
    @property
    def Constraint(self) -> Constraint: ...
    @Constraint.setter
    def Constraint(self, value: Constraint) -> None: ...
    @property
    def DoseFunctionParameters(self) -> Union[DoseFallOffFunction, DoseVolumeFunction, EudFunction, LetVolumeFunction, OnesidedUniformReferenceDoseFunction, PlanningGoalFunction, ReferenceDoseFallOffFunction, ReferenceDoseFunction, ReferenceDvhFunction, ReferenceIsoDoseVolumeFunction, SpatialDosePriorFunction, TotalCrossEntropyFunction, UniformityConstraint]: ...
    @DoseFunctionParameters.setter
    def DoseFunctionParameters(self, value: Union[DoseFallOffFunction, DoseVolumeFunction, EudFunction, LetVolumeFunction, OnesidedUniformReferenceDoseFunction, PlanningGoalFunction, ReferenceDoseFallOffFunction, ReferenceDoseFunction, ReferenceDvhFunction, ReferenceIsoDoseVolumeFunction, SpatialDosePriorFunction, TotalCrossEntropyFunction, UniformityConstraint]) -> None: ...
    @property
    def ForDoseGridStructures(self) -> DoseGridStructures: ...
    @ForDoseGridStructures.setter
    def ForDoseGridStructures(self, value: DoseGridStructures) -> None: ...
    @property
    def ForRegionOfInterest(self) -> RegionOfInterest: ...
    @ForRegionOfInterest.setter
    def ForRegionOfInterest(self, value: RegionOfInterest) -> None: ...
    @property
    def FunctionValue(self) -> FunctionValues: ...
    @FunctionValue.setter
    def FunctionValue(self, value: FunctionValues) -> None: ...
    @property
    def OfDoseDistributions(self) -> List[Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]]: ...
    @OfDoseDistributions.setter
    def OfDoseDistributions(self, value: List[Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]]) -> None: ...
    @property
    def OfDoseGridRoi(self) -> DoseGridRoi: ...
    @OfDoseGridRoi.setter
    def OfDoseGridRoi(self, value: DoseGridRoi) -> None: ...
    @property
    def OfPoiGeometry(self) -> PoiGeometry: ...
    @OfPoiGeometry.setter
    def OfPoiGeometry(self, value: PoiGeometry) -> None: ...
    @property
    def PlanningGoal(self) -> PlanningGoal: ...
    @PlanningGoal.setter
    def PlanningGoal(self, value: PlanningGoal) -> None: ...
    @property
    def ResponseFunctionParameters(self) -> ResponseFunctionParameters: ...
    @ResponseFunctionParameters.setter
    def ResponseFunctionParameters(self, value: ResponseFunctionParameters) -> None: ...
    def DeleteFunction(self) -> None:
        """Deletes an optimization function."""
        ...
    def EvaluateClinicalGoal(self, EvaluateUsingSecondaryAcceptanceLevelIfExists: Optional[bool] = ...) -> bool:
        """Method for evaluation of a physical clinical goal function."""
        ...
    def EvaluateClinicalGoalForAccumulatedDose(self, EvaluateUsingSecondaryAcceptanceLevelIfExists: Optional[bool] = ..., FromFractionNumber: int = ..., ToFractionNumber: int = ..., DoseScaling: str = ..., IsDeliveredDose: bool = ...) -> bool:
        """Method for evaluation of a physical clinical goal function with respect to accumulated dose (planned or delivered)."""
        ...
    def EvaluateClinicalGoalForEvaluationDose(self, EvaluateUsingSecondaryAcceptanceLevelIfExists: Optional[bool] = ..., DoseDistribution: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose] = ..., ScaleFractionDoseToBeamSet: bool = ...) -> bool:
        """Method for evaluation of a physical clinical goal function with respect to the dose 'DoseDistribution' (inparameter)."""
        ...
    def GetClinicalGoalValue(self) -> float:
        """Method for evaluation of a physical clinical goal function."""
        ...
    def GetClinicalGoalValueForAccumulatedDose(self, FromFractionNumber: int = ..., ToFractionNumber: int = ..., DoseScaling: str = ..., IsDeliveredDose: bool = ...) -> float:
        """Method for evaluation of a physical clinical goal function with respect to accumulated dose (planned or delivered)."""
        ...
    def GetClinicalGoalValueForEvaluationDose(self, DoseDistribution: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose], ScaleFractionDoseToBeamSet: bool) -> float:
        """Method for evaluation of a physical clinical goal function with respect to the dose 'DoseDistribution' (inparameter)."""
        ...

class DoseFallOffFunction:
    @property
    def AdaptToTargetDoseLevels(self) -> bool: ...
    @AdaptToTargetDoseLevels.setter
    def AdaptToTargetDoseLevels(self, value: bool) -> None: ...
    @property
    def HighDoseLevel(self) -> float: ...
    @HighDoseLevel.setter
    def HighDoseLevel(self, value: float) -> None: ...
    @property
    def LowDoseDistance(self) -> float: ...
    @LowDoseDistance.setter
    def LowDoseDistance(self, value: float) -> None: ...
    @property
    def LowDoseLevel(self) -> float: ...
    @LowDoseLevel.setter
    def LowDoseLevel(self, value: float) -> None: ...
    @property
    def PenaltyType(self) -> Literal['Dose', 'Volume']: ...
    @PenaltyType.setter
    def PenaltyType(self, value: Literal['Dose', 'Volume']) -> None: ...
    @property
    def RelativeLowDoseWeight(self) -> float: ...
    @RelativeLowDoseWeight.setter
    def RelativeLowDoseWeight(self, value: float) -> None: ...
    @property
    def Smoothness(self) -> float: ...
    @Smoothness.setter
    def Smoothness(self, value: float) -> None: ...
    @property
    def VicinityExponent(self) -> float: ...
    @VicinityExponent.setter
    def VicinityExponent(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    @property
    def DoseGridStructuresSource(self) -> DoseBasedRoiFunction: ...
    @DoseGridStructuresSource.setter
    def DoseGridStructuresSource(self, value: DoseBasedRoiFunction) -> None: ...
    @property
    def ForTargetRoi(self) -> RegionOfInterest: ...
    @ForTargetRoi.setter
    def ForTargetRoi(self, value: RegionOfInterest) -> None: ...
    @property
    def LqModelParameters(self) -> LqModelParameters: ...
    @LqModelParameters.setter
    def LqModelParameters(self, value: LqModelParameters) -> None: ...
    @property
    def OfTargetDoseGridRoi(self) -> DoseGridRoi: ...
    @OfTargetDoseGridRoi.setter
    def OfTargetDoseGridRoi(self, value: DoseGridRoi) -> None: ...

class DoseVolumeFunction:
    @property
    def AbsoluteVolume(self) -> float: ...
    @AbsoluteVolume.setter
    def AbsoluteVolume(self, value: float) -> None: ...
    @property
    def DoseLevel(self) -> float: ...
    @DoseLevel.setter
    def DoseLevel(self, value: float) -> None: ...
    @property
    def FunctionType(self) -> Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'SmoothMinDVH', 'SmoothMaxDVH']: ...
    @FunctionType.setter
    def FunctionType(self, value: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'SmoothMinDVH', 'SmoothMaxDVH']) -> None: ...
    @property
    def IsAbsoluteVolume(self) -> bool: ...
    @IsAbsoluteVolume.setter
    def IsAbsoluteVolume(self, value: bool) -> None: ...
    @property
    def PercentVolume(self) -> float: ...
    @PercentVolume.setter
    def PercentVolume(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    @property
    def LqModelParameters(self) -> LqModelParameters: ...
    @LqModelParameters.setter
    def LqModelParameters(self, value: LqModelParameters) -> None: ...

class DoseCalculationProperties:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @ComputeFinalDose.setter
    def ComputeFinalDose(self, value: bool) -> None: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @ComputeIntermediateDose.setter
    def ComputeIntermediateDose(self, value: bool) -> None: ...
    @property
    def IterationsInPreparationsPhase(self) -> int: ...
    @IterationsInPreparationsPhase.setter
    def IterationsInPreparationsPhase(self, value: int) -> None: ...
    @property
    def MCStatisticalUncertaintyPerBeamForIntermediateDose(self) -> Optional[float]: ...
    @MCStatisticalUncertaintyPerBeamForIntermediateDose.setter
    def MCStatisticalUncertaintyPerBeamForIntermediateDose(self, value: Optional[float]) -> None: ...
    @property
    def OptimizationDoseAlgorithm(self) -> DoseComputationSettings: ...
    @OptimizationDoseAlgorithm.setter
    def OptimizationDoseAlgorithm(self, value: DoseComputationSettings) -> None: ...

class DoseMimicParameters:
    @property
    def TargetPriority(self) -> float: ...
    @TargetPriority.setter
    def TargetPriority(self, value: float) -> None: ...
    @property
    def VoxelDosePriority(self) -> float: ...
    @VoxelDosePriority.setter
    def VoxelDosePriority(self, value: float) -> None: ...

class DoseForAlternativePattern:
    @property
    def DoseScaleFactor(self) -> float: ...
    @DoseScaleFactor.setter
    def DoseScaleFactor(self, value: float) -> None: ...
    @property
    def AlternativePattern(self) -> FractionationPattern: ...
    @AlternativePattern.setter
    def AlternativePattern(self, value: FractionationPattern) -> None: ...
    @property
    def ForBeamSet(self) -> RadiationSet: ...
    @ForBeamSet.setter
    def ForBeamSet(self, value: RadiationSet) -> None: ...

class DoseGrid:
    @property
    def Corner(self) -> Tuple[float, ...]: ...
    @property
    def FrameOfReference(self) -> str: ...
    @property
    def NrVoxels(self) -> Tuple[float, ...]: ...
    @property
    def VoxelSize(self) -> Tuple[float, ...]: ...

class DoseGridStructures:
    @property
    def DensityDistribution(self) -> DensityDistribution: ...
    @DensityDistribution.setter
    def DensityDistribution(self, value: DensityDistribution) -> None: ...
    @property
    def DoseGridRois(self) -> ScriptObjectCollection[DoseGridRoi]: ...
    @DoseGridRois.setter
    def DoseGridRois(self, value: List[DoseGridRoi]) -> None: ...
    @property
    def ForExaminationStructureSet(self) -> ExaminationStructureSet: ...
    @ForExaminationStructureSet.setter
    def ForExaminationStructureSet(self, value: ExaminationStructureSet) -> None: ...
    @property
    def InDoseGrid(self) -> DoseGrid: ...
    @InDoseGrid.setter
    def InDoseGrid(self, value: DoseGrid) -> None: ...
    @property
    def RegistrationBetweenSourceAndDoseGrid(self) -> FrameOfReferenceRegistration: ...
    @RegistrationBetweenSourceAndDoseGrid.setter
    def RegistrationBetweenSourceAndDoseGrid(self, value: FrameOfReferenceRegistration) -> None: ...

class DoseGridRoi:
    @property
    def InDoseGrid(self) -> DoseGrid: ...
    @InDoseGrid.setter
    def InDoseGrid(self, value: DoseGrid) -> None: ...
    @property
    def OfRoiGeometry(self) -> RoiGeometry: ...
    @OfRoiGeometry.setter
    def OfRoiGeometry(self, value: RoiGeometry) -> None: ...
    @property
    def RoiVolumeDistribution(self) -> RoiVolumeDistribution: ...
    @RoiVolumeDistribution.setter
    def RoiVolumeDistribution(self, value: RoiVolumeDistribution) -> None: ...
    @property
    def VersioningStatus(self) -> VersioningStatus: ...
    @VersioningStatus.setter
    def VersioningStatus(self, value: VersioningStatus) -> None: ...

class DoseOnExamination:
    @property
    def DoseEvaluations(self) -> List[Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]]: ...
    @DoseEvaluations.setter
    def DoseEvaluations(self, value: List[Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]]) -> None: ...
    @property
    def OnExamination(self) -> Examination: ...
    @OnExamination.setter
    def OnExamination(self, value: Examination) -> None: ...

class DoseDependencyStringArgs:
    @property
    def BeamSetName(self) -> str: ...
    @property
    def DoseDependentType(self) -> Literal['Beam', 'BeamSet', 'Total']: ...
    @property
    def DoseType(self) -> Literal['Unknown', 'PhotonEquivalent', 'Physical', 'ScalabeRbe', 'NonScalableRbe', 'UnknownRbe', 'Gamma', 'Let', 'RepairIndependentEQD2']: ...
    @property
    def RestrictToBeams(self) -> ScriptObjectCollection[str]: ...
    @property
    def ForFunction(self) -> DoseBasedRoiFunction: ...
    @ForFunction.setter
    def ForFunction(self, value: DoseBasedRoiFunction) -> None: ...

class DoseAlgorithmVersion:
    @property
    def Algorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @property
    def Date(self) -> str: ...
    @property
    def MajorVersion(self) -> int: ...
    @property
    def MinorVersion(self) -> int: ...

class DoseDetector:
    @property
    def DetectorHeight(self) -> float: ...
    @property
    def DetectorLateralShape(self) -> Literal['Quadratic', 'Circular']: ...
    @property
    def DetectorWidth(self) -> float: ...

class DoseDefaultSettings:
    @property
    def AdditionalDoseDecimals(self) -> int: ...
    @property
    def DoseGridVoxelSizeX(self) -> float: ...
    @property
    def DoseGridVoxelSizeY(self) -> float: ...
    @property
    def DoseGridVoxelSizeZ(self) -> float: ...
    @property
    def DoseUnit(self) -> Literal['cGy', 'Gy']: ...
    @property
    def UseNormalizedDosePrescriptionForColortable(self) -> bool: ...
