from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ElectronBeam, PhotonBeam
    from raystation.v2025.beam_set import RadiationSet, TreatmentSetupIncludingRadiationSet
    from raystation.v2025.dose import DoseGrid
    from raystation.v2025.ion import IonBeam
    from raystation.v2025.machine_db_types import ModificationInfo
    from raystation.v2025.patient import PatientSetup
    from raystation.v2025.patient_db_types import BnctBeam, PetConversionParameters, PixelDataConversionParameters
    from raystation.v2025.setup import SetupBeam



class ImageStack:
    @property
    def ColumnDirection(self) -> Tuple[float, ...]: ...
    @property
    def Corner(self) -> Tuple[float, ...]: ...
    @property
    def DataTypeOfStoredValues(self) -> Literal['Short', 'Double']: ...
    @property
    def DicomDataSet(self) -> np.ndarray: ...
    @property
    def ImageType(self) -> str: ...
    @property
    def ImportedDicomSliceUIDs(self) -> ScriptObjectCollection[Any]: ...
    @property
    def MaxStoredValue(self) -> float: ...
    @property
    def MinStoredValue(self) -> float: ...
    @property
    def NrPixels(self) -> Tuple[float, ...]: ...
    @property
    def OriginalTransferSyntax(self) -> str: ...
    @property
    def PixelData(self) -> np.ndarray: ...
    @property
    def PixelSize(self) -> Tuple[float, ...]: ...
    @property
    def RowDirection(self) -> Tuple[float, ...]: ...
    @property
    def SliceDirection(self) -> Tuple[float, ...]: ...
    @property
    def SlicePositions(self) -> np.ndarray: ...
    @property
    def TableTopPitchAngle(self) -> Optional[float]: ...
    @property
    def TableTopRollAngle(self) -> Optional[float]: ...
    @property
    def ConversionParameters(self) -> PixelDataConversionParameters: ...
    @ConversionParameters.setter
    def ConversionParameters(self, value: PixelDataConversionParameters) -> None: ...
    @property
    def PetConversionParameters(self) -> PetConversionParameters: ...
    @PetConversionParameters.setter
    def PetConversionParameters(self, value: PetConversionParameters) -> None: ...
    @property
    def Thumbnail(self) -> ImageStackThumbnail: ...
    @Thumbnail.setter
    def Thumbnail(self, value: ImageStackThumbnail) -> None: ...
    def GetBoundingBox(self) -> List[Any]:
        """Gets the bounding box of the image stack."""
        ...
    def GetImageStackHistogram(self, BinSize: int = ..., ExcludePixelPadding: bool = ..., RoiName: str = ..., ConvertCbctValueToHu: bool = ...) -> List[Any]:
        """Computes an histogram over image intensities, either over the whole image or inside an ROI."""
        ...
    def GetIntensityStatistics(self, RoiName: str = ...) -> Dict[str, Any]:
        """Computes statistics for the intensities inside an ROI. The result is returned as a dictionary with statistics type ("Average", "Min", "Max") value and unit."""
        ...
    def GetResampledPixelData(self, DoseGrid: DoseGrid) -> np.ndarray:
        """Gets the pixel data of the image stack resampled on a dose grid."""
        ...
    def ResampleImageDataOnGrids(self, NrVoxelsVec: List[Any], VoxelSizesVec: List[Any], CornerVec: List[Any]) -> np.ndarray:
        """Resamples the image volume of ImageStack using a given list of coordinates and voxel sizes that defines one or multiple image regions."""
        ...
    def ResampleImageDataViaRegistrationOnGrids(self, NrVoxelsVec: List[Any], VoxelSizesVec: List[Any], CornerVec: List[Any], TargetExaminationName: str, RegistrationId: str = ...) -> np.ndarray:
        """Given a set of grid representing coordinates in the current image stack, resamples"""
        ...

class ImageStackThumbnail:
    @property
    def PixelData(self) -> np.ndarray: ...
    @PixelData.setter
    def PixelData(self, value: np.ndarray) -> None: ...
    @property
    def PixelSize(self) -> Tuple[float, ...]: ...
    @PixelSize.setter
    def PixelSize(self, value: Tuple[float, ...]) -> None: ...
    @property
    def Size(self) -> Tuple[float, ...]: ...
    @Size.setter
    def Size(self, value: Tuple[float, ...]) -> None: ...

class CbctSettings:
    @property
    def IntrinsicIsocenter(self) -> Tuple[float, ...]: ...
    @IntrinsicIsocenter.setter
    def IntrinsicIsocenter(self, value: Tuple[float, ...]) -> None: ...
    @property
    def IsocenterReference(self) -> Literal['Intrinsic', 'RtPlan']: ...
    @IsocenterReference.setter
    def IsocenterReference(self, value: Literal['Intrinsic', 'RtPlan']) -> None: ...

class ImageViewTransformation:
    @property
    def Pitch(self) -> float: ...
    @Pitch.setter
    def Pitch(self, value: float) -> None: ...
    @property
    def Roll(self) -> float: ...
    @Roll.setter
    def Roll(self, value: float) -> None: ...
    @property
    def Yaw(self) -> float: ...
    @Yaw.setter
    def Yaw(self, value: float) -> None: ...

class DrrSettings:
    @property
    def BoneEnhancementFactor(self) -> float: ...
    @BoneEnhancementFactor.setter
    def BoneEnhancementFactor(self, value: float) -> None: ...
    @property
    def BoneThreshold(self) -> int: ...
    @BoneThreshold.setter
    def BoneThreshold(self, value: int) -> None: ...
    @property
    def CropToExternal(self) -> bool: ...
    @CropToExternal.setter
    def CropToExternal(self, value: bool) -> None: ...
    @property
    def CtThresholdHigh(self) -> int: ...
    @CtThresholdHigh.setter
    def CtThresholdHigh(self, value: int) -> None: ...
    @property
    def CtThresholdLow(self) -> int: ...
    @CtThresholdLow.setter
    def CtThresholdLow(self, value: int) -> None: ...
    @property
    def CutPlane1(self) -> float: ...
    @CutPlane1.setter
    def CutPlane1(self, value: float) -> None: ...
    @property
    def CutPlane2(self) -> float: ...
    @CutPlane2.setter
    def CutPlane2(self, value: float) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def DrrCtFilterName(self) -> str: ...
    @DrrCtFilterName.setter
    def DrrCtFilterName(self, value: str) -> None: ...
    @property
    def DrrEngineVersion(self) -> int: ...
    @DrrEngineVersion.setter
    def DrrEngineVersion(self, value: int) -> None: ...
    @property
    def HighlightMarkers(self) -> bool: ...
    @HighlightMarkers.setter
    def HighlightMarkers(self, value: bool) -> None: ...
    @property
    def InvertDrr(self) -> bool: ...
    @InvertDrr.setter
    def InvertDrr(self, value: bool) -> None: ...
    @property
    def Level(self) -> float: ...
    @Level.setter
    def Level(self, value: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ShowTextInExportedDrr(self) -> bool: ...
    @ShowTextInExportedDrr.setter
    def ShowTextInExportedDrr(self, value: bool) -> None: ...
    @property
    def UseBoneEnhancementFactor(self) -> bool: ...
    @UseBoneEnhancementFactor.setter
    def UseBoneEnhancementFactor(self, value: bool) -> None: ...
    @property
    def UseCtThreshold(self) -> bool: ...
    @UseCtThreshold.setter
    def UseCtThreshold(self, value: bool) -> None: ...
    @property
    def UseCutPlanes(self) -> bool: ...
    @UseCutPlanes.setter
    def UseCutPlanes(self, value: bool) -> None: ...
    @property
    def UseMipAsDrr(self) -> bool: ...
    @UseMipAsDrr.setter
    def UseMipAsDrr(self, value: bool) -> None: ...
    @property
    def Window(self) -> float: ...
    @Window.setter
    def Window(self, value: float) -> None: ...
    @property
    def BeamListSource(self) -> TreatmentSetupIncludingRadiationSet: ...
    @BeamListSource.setter
    def BeamListSource(self, value: TreatmentSetupIncludingRadiationSet) -> None: ...
    @property
    def SetupBeamListSource(self) -> PatientSetup: ...
    @SetupBeamListSource.setter
    def SetupBeamListSource(self, value: PatientSetup) -> None: ...

class DrrImageGenerator:
    @property
    def SetupImagerName(self) -> str: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @property
    def ForBeamSet(self) -> RadiationSet: ...
    @property
    def ForDrrSettings(self) -> DrrSettings: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...

class CbctDensityThresholdsData:
    @property
    def AirLung(self) -> int: ...
    @property
    def LungAdipose(self) -> int: ...
    @property
    def AdiposeTissue(self) -> int: ...
    @property
    def TissueCartilageBone(self) -> int: ...
    @property
    def CartilageBoneOther(self) -> int: ...

class ImageRegionStatistics:
    @property
    def ImageModality(self) -> Literal['CT', 'MR', 'Cbct', 'Pet', 'Undefined']: ...
    @property
    def MaxEdgeMagnitude(self) -> float: ...
    @property
    def MeanIntensity(self) -> float: ...
    @property
    def MeanInnerIntensity(self) -> float: ...
    @property
    def MeanOuterIntensity(self) -> float: ...
    @property
    def MinIntensity(self) -> float: ...
    @property
    def MinInnerIntensity(self) -> float: ...
    @property
    def MinOuterIntensity(self) -> float: ...
    @property
    def MaxIntensity(self) -> float: ...
    @property
    def MaxInnerIntensity(self) -> float: ...
    @property
    def MaxOuterIntensity(self) -> float: ...
    @property
    def StdDev(self) -> float: ...
    @property
    def StdDevInner(self) -> float: ...
    @property
    def StdDevOuter(self) -> float: ...
    @property
    def BrightObject(self) -> bool: ...
    @property
    def AllowModifications(self) -> bool: ...

class ImagingSystemReference:
    @property
    def ImagingSystemName(self) -> str: ...
    @property
    def CommissioningTime(self) -> Optional[str]: ...
    @property
    def CommissioningTimeUtc(self) -> Optional[str]: ...

class ImagerReceptor:
    @property
    def IsocenterToReceptorPlaneDistance(self) -> float: ...
    @property
    def ReceptorSize(self) -> Tuple[float, ...]: ...

class ImageExportData:
    @property
    def FitImageToReceptorSize(self) -> bool: ...
    @property
    def PixelCount(self) -> Tuple[float, ...]: ...
    @property
    def PixelSpacing(self) -> Tuple[float, ...]: ...

class DrrSettingsTemplate:
    @property
    def BoneEnhancementFactor(self) -> float: ...
    @property
    def BoneThreshold(self) -> int: ...
    @property
    def CropToExternal(self) -> bool: ...
    @property
    def CtThresholdHigh(self) -> int: ...
    @property
    def CtThresholdLow(self) -> int: ...
    @property
    def FilterName(self) -> str: ...
    @property
    def HighlightMarkers(self) -> bool: ...
    @property
    def InvertDrr(self) -> bool: ...
    @property
    def Level(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def ShowTextInExportedDrr(self) -> Optional[bool]: ...
    @property
    def UseBoneEnhancementFactor(self) -> bool: ...
    @property
    def UseCtThreshold(self) -> bool: ...
    @property
    def UseMipAsDrr(self) -> bool: ...
    @property
    def Window(self) -> float: ...
