from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ArcConversionPropertiesPerBeam, ElectronBeam, PhotonBeam
    from raystation.v2025.dose import DoseAlgorithmVersion, DoseDetector
    from raystation.v2025.machine import CyberKnifePropertiesPerBeam, MachineReference
    from raystation.v2025.machine_db_types import ComputationSettings, ComputedDoseCurve, ComputedDoseCurvesGammaSettings, ComputedIonCalibrationPoint, HyperscanEnergySelectorSettings, Material, MeasuredDoseCurve, MetersetRateSetting, MlcLayer, NominalSpotSize, RangeModulatorModel, RangeOption, ScanningBeamSetup, ScanningProperties, Snout, SpotShapeParameters
    from raystation.v2025.patient import PatientToBeamMapping
    from raystation.v2025.patient_db_types import Block, BnctBeam, Compensator, CompensatorProperties, GazeAngles, InterplaySpotScalingPerExamination, RegionOfInterest, ScannedBeamProperties, Segment, Spots
    from raystation.v2025.setup import SetupBeam
    from raystation.v2025.tomo import TomoPropertiesPerBeam



class IonSprProperties:
    @property
    def SprEnergy(self) -> float: ...
    @property
    def SprIonType(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...

class IonDoseDeliveryCharacteristics:
    @property
    def DeliveryTimeModel(self) -> IonScanningDeliveryTimeModel: ...
    @DeliveryTimeModel.setter
    def DeliveryTimeModel(self, value: IonScanningDeliveryTimeModel) -> None: ...
    @property
    def SpotScalingPerExaminations(self) -> ScriptObjectCollection[InterplaySpotScalingPerExamination]: ...
    @SpotScalingPerExaminations.setter
    def SpotScalingPerExaminations(self, value: List[InterplaySpotScalingPerExamination]) -> None: ...

class IonScanningDeliveryTimeModel:
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def EnergySwitchingTime(self) -> float: ...
    @EnergySwitchingTime.setter
    def EnergySwitchingTime(self, value: float) -> None: ...
    @property
    def ScanningSpeedX(self) -> float: ...
    @ScanningSpeedX.setter
    def ScanningSpeedX(self, value: float) -> None: ...
    @property
    def ScanningSpeedY(self) -> float: ...
    @ScanningSpeedY.setter
    def ScanningSpeedY(self, value: float) -> None: ...

class IonSegment:
    @property
    def ApertureContour(self) -> ScriptObjectCollection[Any]: ...
    @ApertureContour.setter
    def ApertureContour(self, value: List[Any]) -> None: ...
    @property
    def BeamCurrentModulationId(self) -> str: ...
    @property
    def CollimatorAngle(self) -> float: ...
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def FirstScattererUsedLollipops(self) -> ScriptObjectCollection[str]: ...
    @property
    def ImportedSourceToSurfaceDistance_ForDisplayUseOnly(self) -> Optional[float]: ...
    @property
    def JawPositions(self) -> np.ndarray: ...
    @JawPositions.setter
    def JawPositions(self, value: np.ndarray) -> None: ...
    @property
    def LeafPositions(self) -> np.ndarray: ...
    @LeafPositions.setter
    def LeafPositions(self, value: np.ndarray) -> None: ...
    @property
    def MaximumNozzleEquivalentThickness(self) -> Optional[float]: ...
    @property
    def MaximumRange(self) -> Optional[float]: ...
    @property
    def MinimumNozzleEquivalentThickness(self) -> Optional[float]: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def RangeModulationGatingStartValue(self) -> Optional[float]: ...
    @property
    def RangeModulationGatingStopValue(self) -> Optional[float]: ...
    @property
    def RangeOptionId(self) -> Optional[str]: ...
    @property
    def RangeShifterSetting(self) -> Optional[int]: ...
    @property
    def RelativeWeight(self) -> float: ...
    @RelativeWeight.setter
    def RelativeWeight(self, value: float) -> None: ...
    @property
    def ScannedFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def SegmentNumber(self) -> int: ...
    @property
    def SobpWidth(self) -> Optional[float]: ...
    @property
    def ToshibaIntensity(self) -> Optional[float]: ...
    @property
    def IonArcSegmentProperties(self) -> IonArcSegmentProperties: ...
    @property
    def Spots(self) -> Spots: ...
    @Spots.setter
    def Spots(self, value: Spots) -> None: ...
    def EditNominalEnergy(self, NominalEnergy: float = ...) -> None:
        """Sets the nominal energy for the energy layer and then sorts all energy layers of the beam"""
        ...
    def EditSegmentIntensity(self, SegmentIntensity: Optional[float] = ...) -> None:
        """Sets the Toshiba intensity for the energy layer in MU/s."""
        ...
    def GetBEVImageOfSegment(self) -> str:
        """Method for retrieving BEV image for a segment."""
        ...
    def RemoveEnergyLayer(self) -> None:
        """Removes the energy layer and re-normalizes spot weights for all energy layers in the beam"""
        ...
    def SetLineScanningDeliverableWeights(self) -> None:
        """Rounds the line segment weights of the segment to deliverable values"""
        ...
    def SetLineScanningHighestDeliverableDoseRate(self, DoseRateLimitMargin: float = ...) -> None:
        """Sets a deliverable dose rate for a LineScanning energy layer"""
        ...

class IonArcSegmentProperties:
    @property
    def DeltaCouchAngle(self) -> float: ...
    @property
    def DeltaGantryAngle(self) -> float: ...
    @property
    def GantryAngleWindow(self) -> float: ...
    @property
    def RotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...

class IonSegmentBaseProperties:
    @property
    def MaximumRange(self) -> Optional[float]: ...
    @property
    def SnoutPosition(self) -> Optional[float]: ...
    @property
    def SobpWidth(self) -> Optional[float]: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...

class IonBeam:
    @property
    def ArcRotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...
    @property
    def ArcStopGantryAngle(self) -> Optional[float]: ...
    @property
    def BeamMU(self) -> float: ...
    @BeamMU.setter
    def BeamMU(self, value: float) -> None: ...
    @property
    def BeamQualityId(self) -> str: ...
    @BeamQualityId.setter
    def BeamQualityId(self, value: str) -> None: ...
    @property
    def CouchPitchAngle(self) -> float: ...
    @CouchPitchAngle.setter
    def CouchPitchAngle(self, value: float) -> None: ...
    @property
    def CouchRollAngle(self) -> float: ...
    @CouchRollAngle.setter
    def CouchRollAngle(self, value: float) -> None: ...
    @property
    def CouchRotationAngle(self) -> float: ...
    @CouchRotationAngle.setter
    def CouchRotationAngle(self, value: float) -> None: ...
    @property
    def CreatedDuringOptimization(self) -> bool: ...
    @property
    def DeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def FilterTargetType(self) -> Literal['DistalEdgeTumor', 'FrontEdgeRoi', 'PatchToBeam']: ...
    @property
    def FirstScattererId(self) -> Optional[str]: ...
    @property
    def GantryAngle(self) -> float: ...
    @GantryAngle.setter
    def GantryAngle(self, value: float) -> None: ...
    @property
    def InitialCollimatorAngle(self) -> float: ...
    @property
    def InitialJawPositions(self) -> np.ndarray: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def MetersetRateSettingId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def PatientPosition(self) -> Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']: ...
    @property
    def PlanGenerationTechnique(self) -> Optional[Literal['Imrt', 'Conformal', 'Mixed']]: ...
    @PlanGenerationTechnique.setter
    def PlanGenerationTechnique(self, value: Optional[Literal['Imrt', 'Conformal', 'Mixed']]) -> None: ...
    @property
    def PrimaryDosimeterUnit(self) -> Literal['MonitorUnit', 'NumberOfParticles']: ...
    @property
    def RadiationAtomicNumber(self) -> float: ...
    @property
    def RadiationMassNumber(self) -> float: ...
    @property
    def RangeModulatorId(self) -> str: ...
    @property
    def RangeOptionName(self) -> str: ...
    @property
    def RangeShifterId(self) -> Optional[str]: ...
    @property
    def RepaintingOrder(self) -> Literal['Layer', 'Volumetric']: ...
    @property
    def SecondScattererId(self) -> Optional[str]: ...
    @property
    def SnoutId(self) -> str: ...
    @property
    def SourceAxisDistanceForDeviceScaling(self) -> Optional[Point2[float]]: ...
    @property
    def TreatmentMachineNameAlias(self) -> str: ...
    @property
    def Blocks(self) -> ScriptObjectCollection[Block]: ...
    @Blocks.setter
    def Blocks(self, value: List[Block]) -> None: ...
    @property
    def Boli(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @Boli.setter
    def Boli(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def Compensator(self) -> Compensator: ...
    @Compensator.setter
    def Compensator(self, value: Compensator) -> None: ...
    @property
    def FilterTargetBeam(self) -> IonBeam: ...
    @FilterTargetBeam.setter
    def FilterTargetBeam(self, value: IonBeam) -> None: ...
    @property
    def FilterTargetRoi(self) -> RegionOfInterest: ...
    @FilterTargetRoi.setter
    def FilterTargetRoi(self, value: RegionOfInterest) -> None: ...
    @property
    def GazeAngles(self) -> GazeAngles: ...
    @GazeAngles.setter
    def GazeAngles(self, value: GazeAngles) -> None: ...
    @property
    def IonWedge(self) -> IonWedge: ...
    @IonWedge.setter
    def IonWedge(self, value: IonWedge) -> None: ...
    @property
    def Isocenter(self) -> PatientToBeamMapping: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def Segments(self) -> ScriptObjectCollection[Segment]: ...
    @Segments.setter
    def Segments(self, value: List[Segment]) -> None: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...
    def AddEnergyLayerWithSpots(self, Energy: float, SpotPositionsX: np.ndarray, SpotPositionsY: np.ndarray, SpotWeights: np.ndarray) -> None:
        """Method for adding an energy layer to the beam including spots with positions and weights."""
        ...
    def AddOrEditCompensator(self, Name: str, MaterialName: str, MillingToolDiameter: float, Resolution: Optional[float] = ..., MinimumThicknessLimit: float = ..., MaximumThicknessLimit: float = ...) -> None:
        """Adds a compensator if no compensator exits, edit it otherwise"""
        ...
    def AddOrEditIonBlock(self, BlockName: str, MaterialName: str, Thickness: float, MillingToolDiameter: float, Type: Literal['Shielding', 'Aperture', 'DynamicAperture'] = ...) -> Block:
        """Add or edit the block for an ion beam."""
        ...
    def ClearTreatOrProtectRoi(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for the beam."""
        ...
    def ComputeBeamSOBP(self) -> None:
        """Computes SOBP range and width and the corresponding nozzle settings according to the treat and protect settings. To run the action, the aperture contour and compensator (if defined on the beam) must first be computed. Treat and protect roi:s, margins, etc. are set in RayStation."""
        ...
    def ComputeCompensator(self, ComputeSOBP: bool = ...) -> None:
        """Generates a compensator geometry according to the treat and protect settings. The snout position is modified to maintain the expected air gap for the beam. Treat and protect roi:s, margins, etc. are set in RayStation."""
        ...
    def ComputeIonBeamParameters(self) -> IonBeam:
        """Computes aperture openings, compensator geometry, snout position, and SOBP range and width as well as the corresponding nozzle settings according to the treat and protect settings. The beam MU is set to 1. Treat and protect roi:s, margins, etc. are set in RayStation."""
        ...
    def ConformBlock(self) -> None:
        """Generates a block aperture according to the treat and protect settings."""
        ...
    def ConformMlc(self) -> None:
        """Generates a MLC aperture according to the treat and protect settings."""
        ...
    def ConvertSobpRangeAndWidthToNozzleSettings(self, Range: Optional[float] = ..., Width: Optional[float] = ...) -> None:
        """Action for setting range and modulation (and getting a RangeOption)"""
        ...
    def CreateCircularValidationBlockContour(self, Diameter: float = ..., SnoutPosition: float = ...) -> None:
        """Creates a circular validation block contour for the beam."""
        ...
    def CreateMlcPositionsFromPolygon(self, Points: List[Any]) -> None:
        """Creates an MLC contour based on the corner positions of a polygon"""
        ...
    def CreatePBSIonSegment(self, CenterCoordinate: Any = ..., ScannedFieldSize: Optional[Union[Point2[float], Point2Dict[float]]] = ..., SpotSpacing: Optional[float] = ..., NominalEnergy: float = ..., SpotPositions: List[Any] = ..., SpotWeights: List[float] = ..., UseHexagonalPattern: bool = ...) -> IonSegment:
        """Creates a PBS ion field, either rectangular or single spot"""
        ...
    def CreateRectangularField(self, Width: float = ..., Height: float = ..., CenterCoordinate: Any = ..., MoveMLC: bool = ..., MoveAllMLCLeaves: bool = ..., MoveJaw: bool = ..., JawMargins: Any = ..., DeleteWedge: bool = ..., PreventExtraLeafPairFromOpening: bool = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Creates rectangular field."""
        ...
    def CreateRectangularValidationBlockContour(self, XPosition: float = ..., YPosition: float = ..., XSide: float = ..., YSide: float = ..., SnoutPosition: float = ...) -> None:
        """Creates a rectangular validation block contour for the beam."""
        ...
    def CreateSquareValidationBlockContour(self, Side: float = ..., SnoutPosition: float = ...) -> None:
        """Creates a square validation block contour for the beam."""
        ...
    def DeleteArcTrajectory(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Deletes the arc trajectory on a beam."""
        ...
    def DeleteSegment(self, SegmentNumber: int = ...) -> None:
        """Deletes a segment."""
        ...
    def EditBeamLeafPositions(self, LeafPositions: np.ndarray) -> None:
        """Action for updating leaf positions for all segments of a beam"""
        ...
    def EditGap(self, GapDelta: Optional[float] = ...) -> None:
        """Increases or decreases the gap."""
        ...
    def EditSnoutPosition(self, SnoutPosition: Optional[float] = ...) -> None:
        """Sets the snout position for an ionbeam and checks that the new snout position is allowed."""
        ...
    def GetAirGap(self) -> Dict[str, Any]:
        """Gets the central axis air gap and minimum air gap."""
        ...
    def GetBeamNP(self) -> float:
        """Method for retrieving the ion beam meterset in units of Number of Particles"""
        ...
    def GetBEVImage(self, ShowFluence: bool) -> str:
        """Method for retrieving BEV image for a beam."""
        ...
    def GetCentralAxisAirGap(self) -> float:
        """Gets the air gap along the central axis."""
        ...
    def GetCompensatorProtectMargin(self) -> Optional[float]:
        """Gets the protect margin when using 'Protect with Compensator' in the Treat and Protect settings (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)."""
        ...
    def GetDistalTreatMargin(self) -> Optional[float]:
        """Gets the distal treat margin (cm) for 'Treat and Protect' (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)"""
        ...
    def GetDRRImage(self) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetDRRImageForSegment(self, SegmentIndex: int) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetFirstScattererParameters(self) -> Dict[str, Any]:
        """Gets the the first scatterer parameters."""
        ...
    def GetIsocenterToBlockTrayDistance(self) -> float:
        """Method for computing the isocenter to block tray distance (cm)."""
        ...
    def GetIsocenterToCompensatorTrayDistance(self) -> float:
        """Method for computing the isocenter to compensator tray distance (cm) for current range compensator."""
        ...
    def GetMaximumRangeForMitsubishiAndSumitomoBeam(self) -> float:
        """Gets the maximum range for a beam."""
        ...
    def GetMinAirGap(self) -> float:
        """Gets the minimum air gap."""
        ...
    def GetNominalEnergy(self) -> float:
        """Gets the nominal energy."""
        ...
    def GetProximalTreatMargin(self) -> Optional[float]:
        """Gets the proximal treat margin for 'Treat and Protect' (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)"""
        ...
    def GetSecondScattererParameters(self) -> Dict[str, Any]:
        """Gets the the second scatterer parameters."""
        ...
    def GetSourceToSkinDistance(self) -> float:
        """Method for retrieving the source-to-skin distance for photon and electron beams."""
        ...
    def GetSourceToSurfaceDistance(self) -> float:
        """Method for retrieving the source-to-surface distance for photon and electron beams."""
        ...
    def MakeBlockMillable(self) -> None:
        """Makes the block on the ion beam millable, given a milling tool diameter."""
        ...
    def ResetMlcPositions(self) -> None:
        """Resets the position of the mlc leaves to the most retracted position."""
        ...
    def SetArcTrajectory(self, GantryAngles: np.ndarray, CouchAngles: np.ndarray, CollimatorAngles: np.ndarray, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the arc trajectory on a beam."""
        ...
    def SetArcTrajectoryFromTemplate(self, NameOfTemplate: str) -> None:
        """Sets the arc trajectory on a beam from a template."""
        ...
    def SetBeamNP(self, NumberOfParticles: float) -> None:
        """Method for setting the ion beam meterset in units of Number of Particles"""
        ...
    def SetBolus(self, BolusName: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the bolus with name BolusName on this photon beam. Returns the beam."""
        ...
    def SetCompensatorProtectMargin(self, Margin: float) -> None:
        """Sets the protect margin when using 'Protect with Compensator' in the Treat and Protect settings (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)"""
        ...
    def SetCompensatorProtectRoi(self, RoiName: str) -> None:
        """Select to protect an ROI with compensator"""
        ...
    def SetDefaultSynchrotronDeliverySettings(self) -> None:
        """Sets the synchrotron delivery settings for an ion beam to the default values as specified by the referenced ion treatment machine."""
        ...
    def SetDoseSpecificationPoint(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Select a dose specification point for this beam."""
        ...
    def SetGap(self, Gap: Optional[float] = ..., OnCentralAxis: bool = ...) -> None:
        """Sets the specified gap for the ion beam."""
        ...
    def SetInitialJawPositions(self, X1: float = ..., X2: float = ..., Y1: float = ..., Y2: float = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets initial jaw positions to the beam."""
        ...
    def SetIsocenter(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets an isocenter to a beam. If the name of the isocenter does not exist, a new isocenter will be created."""
        ...
    def SetIsocenterToMidpointInExternal(self) -> None:
        """Sets the isocenter for a beam to the midplane of the patient (external)."""
        ...
    def SetLayerRepainting(self, FixedNumberOfPaintings: int = ..., MaxMuPerRepaintedLayer: float = ..., MaxMuPerRepaintedSpot: float = ..., CreateDeliverySequence: bool = ...) -> None:
        """Set layer repainting for all energy layers for this scanned beam"""
        ...
    def SetSnout(self, SnoutId: str) -> None:
        """Sets snout of the beam."""
        ...
    def SetTreatDistalMargin(self, DistalMargin: float) -> None:
        """Set the treat distal margin for 'Treat and Protect' (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)"""
        ...
    def SetTreatOrProtectRoi(self, TopMargin: float = ..., BottomMargin: float = ..., LeftMargin: float = ..., RightMargin: float = ..., RoiName: str = ...) -> None:
        """Select to use ROI as Treat or Protect."""
        ...
    def SetTreatProximalMargin(self, ProximalMargin: float) -> None:
        """Set the treat proximal margin for 'Treat and Protect' (only used for UniformScanning/DoubleScattering/SingleScattering/Wobbling)"""
        ...

class IonWedge:
    @property
    def ID(self) -> str: ...
    @property
    def OpeningAngle(self) -> float: ...
    @property
    def Material(self) -> Material: ...

class IonBeamOptimizationSettings:
    @property
    def AllowBeamSplit(self) -> bool: ...
    @AllowBeamSplit.setter
    def AllowBeamSplit(self, value: bool) -> None: ...
    @property
    def AutoSelectRangeShifter(self) -> bool: ...
    @AutoSelectRangeShifter.setter
    def AutoSelectRangeShifter(self, value: bool) -> None: ...
    @property
    def BeamApertureLimit(self) -> Literal['NoLimit', 'MaxLimit', 'AtLimit']: ...
    @BeamApertureLimit.setter
    def BeamApertureLimit(self, value: Literal['NoLimit', 'MaxLimit', 'AtLimit']) -> None: ...
    @property
    def DensityUncertainty(self) -> float: ...
    @DensityUncertainty.setter
    def DensityUncertainty(self, value: float) -> None: ...
    @property
    def MaximumRadiologicalDepth(self) -> Optional[float]: ...
    @MaximumRadiologicalDepth.setter
    def MaximumRadiologicalDepth(self, value: Optional[float]) -> None: ...
    @property
    def MinimumAirGap(self) -> Optional[float]: ...
    @MinimumAirGap.setter
    def MinimumAirGap(self, value: Optional[float]) -> None: ...
    @property
    def MinimumRadiologicDepthMargin(self) -> float: ...
    @MinimumRadiologicDepthMargin.setter
    def MinimumRadiologicDepthMargin(self, value: float) -> None: ...
    @property
    def OptimizationTypes(self) -> ScriptObjectCollection[Any]: ...
    @OptimizationTypes.setter
    def OptimizationTypes(self, value: List[Any]) -> None: ...
    @property
    def OrganAtRiskRangeMargin(self) -> float: ...
    @OrganAtRiskRangeMargin.setter
    def OrganAtRiskRangeMargin(self, value: float) -> None: ...
    @property
    def SelectCollimatorAngle(self) -> bool: ...
    @SelectCollimatorAngle.setter
    def SelectCollimatorAngle(self, value: bool) -> None: ...
    @property
    def ArcConversionPropertiesPerBeam(self) -> ArcConversionPropertiesPerBeam: ...
    @ArcConversionPropertiesPerBeam.setter
    def ArcConversionPropertiesPerBeam(self, value: ArcConversionPropertiesPerBeam) -> None: ...
    @property
    def AvoidanceRois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @AvoidanceRois.setter
    def AvoidanceRois(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def CompensatorProperties(self) -> CompensatorProperties: ...
    @CompensatorProperties.setter
    def CompensatorProperties(self, value: CompensatorProperties) -> None: ...
    @property
    def CyberKnifePropertiesPerBeam(self) -> CyberKnifePropertiesPerBeam: ...
    @CyberKnifePropertiesPerBeam.setter
    def CyberKnifePropertiesPerBeam(self, value: CyberKnifePropertiesPerBeam) -> None: ...
    @property
    def ForBeam(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]: ...
    @ForBeam.setter
    def ForBeam(self, value: Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]) -> None: ...
    @property
    def ScannedBeamProperties(self) -> ScannedBeamProperties: ...
    @ScannedBeamProperties.setter
    def ScannedBeamProperties(self, value: ScannedBeamProperties) -> None: ...
    @property
    def TomoPropertiesPerBeam(self) -> TomoPropertiesPerBeam: ...
    @TomoPropertiesPerBeam.setter
    def TomoPropertiesPerBeam(self, value: TomoPropertiesPerBeam) -> None: ...
    def EditBeamOptimizationSettings(self, OptimizationTypes: List[Any] = ..., SelectCollimatorAngle: bool = ..., AllowBeamSplit: bool = ..., JawMotion: Literal['Undefined', 'Fixed', 'LockToLimits', 'UseLimitsAsMax', 'Automatic'] = ..., LeftJaw: Optional[float] = ..., RightJaw: Optional[float] = ..., TopJaw: Optional[float] = ..., BottomJaw: Optional[float] = ...) -> None:
        """Edits the beam optimization settings for selected beam"""
        ...
    def SetAvoidanceStructures(self, RoiNames: List[str]) -> IonBeamOptimizationSettings:
        """Sets ROIs to be be protected. Bragg peaks are not positioned within or distal to the selected ROIs including the set proximal margin (OrganAtRiskRangeMargin)."""
        ...

class IonArcProperties:
    @property
    def DynamicProperties(self) -> IonArcDynamicProperties: ...
    @property
    def StaticProperties(self) -> IonArcStaticProperties: ...

class IonArcStaticProperties:
    @property
    def DefaultNumberOfDirections(self) -> int: ...

class IonArcDynamicProperties:
    @property
    def DefaultGantryAngleSpacing(self) -> float: ...
    @property
    def DefaultGantryAngleWindow(self) -> float: ...
    @property
    def MaximumGantryAngleWindowForClinicalDose(self) -> Optional[float]: ...
    @property
    def MinimumGantryAngleWindow(self) -> Optional[float]: ...

class IonBeamSetup:
    @property
    def IsocenterToSurfaceDistance(self) -> Optional[float]: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def PhantomMaterial(self) -> Optional[Literal['Water', 'RW3', 'PMMA']]: ...
    @property
    def SnoutPosition(self) -> float: ...
    @property
    def ForSnout(self) -> Snout: ...
    @property
    def ScanningBeamSetup(self) -> ScanningBeamSetup: ...

class IonCalibrationPoint:
    @property
    def Depth(self) -> float: ...
    @property
    def DosePerMeterset(self) -> float: ...
    @property
    def Ssd(self) -> float: ...
    @property
    def DoseDetector(self) -> DoseDetector: ...
    @property
    def IonCalibrationPointSetup(self) -> IonBeamSetup: ...

class IonBeamQuality:
    @property
    def ForDeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def ForDiscreteGantryAngle(self) -> Optional[float]: ...
    @property
    def Label(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def NominalEnergyLimits(self) -> Optional[Point2[float]]: ...
    @property
    def SupportedDiscreteNominalEnergies(self) -> np.ndarray: ...
    @property
    def TreatmentMachineNameAlias(self) -> str: ...
    @property
    def VariableEnergyMode(self) -> Literal['Discrete', 'Continuous']: ...
    @property
    def AllowedSnouts(self) -> ScriptObjectCollection[Snout]: ...
    @property
    def BeamModel(self) -> IonBeamModel: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputationSettingsForAbsoluteDosimetry(self) -> ComputationSettings: ...
    @property
    def ComputationSettingsForSpotProfiles(self) -> ComputationSettings: ...
    @property
    def ComputedCalibrationPoints(self) -> ScriptObjectCollection[ComputedIonCalibrationPoint]: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def HyperscanEnergySelectorSettings(self) -> HyperscanEnergySelectorSettings: ...
    @property
    def IonDosimetryData(self) -> IonDosimetryData: ...
    @property
    def IonProperties(self) -> IonProperties: ...
    @property
    def MetersetRateSettings(self) -> ScriptObjectCollection[MetersetRateSetting]: ...
    @property
    def ScanningProperties(self) -> ScanningProperties: ...

class IonProperties:
    @property
    def AtomicMass(self) -> float: ...
    @property
    def AtomicNumber(self) -> float: ...
    @property
    def ChargeState(self) -> float: ...

class IonBeamModel:
    @property
    def ClinicSpecificFragmentSpectraId(self) -> Optional[str]: ...
    @property
    def ExcludeNuclearScattering(self) -> bool: ...
    @property
    def FocalLengthsXY(self) -> Tuple[float, ...]: ...
    @property
    def RangeModulatorModelType(self) -> Literal['IndividualSteps', 'AllStepsCombined']: ...
    @property
    def SpotTuneId(self) -> str: ...
    @property
    def RangeModulatorModels(self) -> ScriptObjectCollection[RangeModulatorModel]: ...
    @property
    def RangeOptions(self) -> ScriptObjectCollection[RangeOption]: ...
    @property
    def SpotShapeParameters(self) -> SpotShapeParameters: ...

class IonDosimetryData:
    @property
    def IonCalibrationPoints(self) -> ScriptObjectCollection[IonCalibrationPoint]: ...
    @property
    def MeasuredCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...

class IonTreatmentMachineDicomSettings:
    @property
    def AlternativeTreatmentMachineNames(self) -> ScriptObjectCollection[str]: ...
    @property
    def ConfigurationBaselineNumber(self) -> str: ...
    @property
    def EnableSiemensIontrisExport(self) -> bool: ...
    @property
    def ExportSetupBeams(self) -> bool: ...
    @property
    def ExportSpotIslandsAsSeparateControlPoints(self) -> bool: ...
    @property
    def ExportTreatmentBeamDrrReferenceForPatientSetup(self) -> bool: ...
    @property
    def MergeEnergyLayersOnExport(self) -> bool: ...
    @property
    def PatientSupportId(self) -> str: ...
    @property
    def NominalSpotSizes(self) -> ScriptObjectCollection[NominalSpotSize]: ...

class IonDefaultSettings:
    @property
    def AutomaticRangeShifterSelection(self) -> bool: ...
    @property
    def ComputeDoseAveragedLet(self) -> bool: ...
    @property
    def EnergyLayerSeparationFactor(self) -> float: ...
    @property
    def HidePhysicalDoseForScalableRBE(self) -> bool: ...
    @property
    def IonMCHistoriesPerSpotForOptimization(self) -> int: ...
    @property
    def IonMCMeanHistoriesPerSpotForFinalDose(self) -> int: ...
    @property
    def IterationsBeforeSpotFiltering(self) -> int: ...
    @property
    def MaxNumberOfEnergyLayers(self) -> Optional[int]: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MaxStatisticalUncertaintyForClinicalIonDose(self) -> Optional[float]: ...
    @property
    def OptimizationTolerance(self) -> float: ...
    @property
    def ProtonPbsFinalDoseAlgorithm(self) -> Literal['SpotWeightPencilBeam', 'SpotWeightMonteCarlo']: ...
    @property
    def ProtonPbsOptimizationDoseAlgorithm(self) -> Literal['SpotWeightPencilBeamFast', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo']: ...
    @property
    def ReferenceIntensity(self) -> Optional[float]: ...
    @property
    def ReferenceIntensityMode(self) -> Literal['Automatic', 'Manual']: ...
    @property
    def SpotPattern(self) -> Literal['Hexagonal', 'Square']: ...
    @property
    def SpotSelectionDistalTargetLayerMargin(self) -> int: ...
    @property
    def SpotSelectionLateralMarginScaleFactor(self) -> float: ...
    @property
    def SpotSelectionProximalTargetLayerMargin(self) -> int: ...
    @property
    def SpotSpacingSeparationFactor(self) -> float: ...
