from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ArcProperties, ElectronApplicator, ElectronBeamQuality, PhotonBeamQuality, PhotonBlockConstraints
    from raystation.v2025.dose import DoseAlgorithmVersion
    from raystation.v2025.ion import IonBeamQuality, IonTreatmentMachineDicomSettings, IonWedge
    from raystation.v2025.machine_db_types import BlockConstraints, BlockTrayDevice, CompensatorConstraints, Cone, FirstScatterer, FixationLight, GeneralDicomSettings, GimbalProperties, HyperscanEnergySelector, JawRoundingSettings, Jaws, LateralSpreadingDevice, LinacDicomSettings, LinacPhysics, Mlc, ModificationInfo, MotionSynchronizationMode, NctCollimator, NozzleExitWindow, RangeModulator, RangeShifter, ReferenceFieldSetup, ScanPatternConstraints, SecondScatterer, Snout, SynchrotronDeliveryParameters, XRayIrradiatorBeamQuality, XRayIrradiatorFixedCone
    from raystation.v2025.ml import FileImportLog
    from raystation.v2025.plan import PlanExploration
    from raystation.v2025.setup import SetupImagingSystem
    from raystation.v2025.tomo import TomoBeamQuality, TomoJaw, TomoMlc, TomoProperties



class CyberKnifeLibraryProperties:
    @property
    def RailVersion(self) -> str: ...
    @RailVersion.setter
    def RailVersion(self, value: str) -> None: ...

class CyberKnifeSegment:
    @property
    def CollimatorAngle(self) -> float: ...
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def ImagingBlocked(self) -> bool: ...
    @ImagingBlocked.setter
    def ImagingBlocked(self, value: bool) -> None: ...
    @property
    def ImportedSourceToSurfaceDistance_ForDisplayUseOnly(self) -> Optional[float]: ...
    @property
    def JawPositions(self) -> np.ndarray: ...
    @JawPositions.setter
    def JawPositions(self, value: np.ndarray) -> None: ...
    @property
    def LeafPositions(self) -> np.ndarray: ...
    @LeafPositions.setter
    def LeafPositions(self, value: np.ndarray) -> None: ...
    @property
    def NodeId(self) -> int: ...
    @NodeId.setter
    def NodeId(self, value: int) -> None: ...
    @property
    def PitchAngle(self) -> float: ...
    @PitchAngle.setter
    def PitchAngle(self, value: float) -> None: ...
    @property
    def RelativeWeight(self) -> float: ...
    @RelativeWeight.setter
    def RelativeWeight(self, value: float) -> None: ...
    @property
    def RollAngle(self) -> float: ...
    @RollAngle.setter
    def RollAngle(self, value: float) -> None: ...
    @property
    def SegmentNumber(self) -> int: ...
    @property
    def SourcePosition(self) -> Tuple[float, ...]: ...
    @SourcePosition.setter
    def SourcePosition(self, value: Tuple[float, ...]) -> None: ...
    @property
    def YawAngle(self) -> float: ...
    @YawAngle.setter
    def YawAngle(self, value: float) -> None: ...
    @property
    def Cone(self) -> Cone: ...
    @Cone.setter
    def Cone(self, value: Cone) -> None: ...
    def GetBEVImageOfSegment(self) -> str:
        """Method for retrieving BEV image for a segment."""
        ...

class CyberKnifePropertiesPerBeam:
    @property
    def MaxNumberOfBeamDirections(self) -> Optional[int]: ...
    @property
    def MaxNumberOfNodes(self) -> Optional[int]: ...
    @property
    def MaxNumberOfSegments(self) -> Optional[int]: ...
    @property
    def MaxSegmentMu(self) -> Optional[float]: ...
    @property
    def MaxTotalMu(self) -> Optional[float]: ...
    @property
    def MuReductionWeight(self) -> float: ...
    @property
    def NumberOfCandidateBeamDirections(self) -> int: ...
    def EditCyberKnifeBeamOptimizationSettings(self, MaxNumberOfNodes: Optional[int] = ..., MaxNumberOfSegments: Optional[int] = ..., MaxNumberOfBeamDirections: Optional[int] = ..., NumberOfCandidateBeamDirections: int = ..., MuReductionWeight: float = ..., MaxTotalMu: Optional[float] = ..., MaxSegmentMu: Optional[float] = ...) -> None:
        """Edit the CyberKnife beam optimization settings"""
        ...

class MachineReferenceFilter:
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...
    @property
    def InPlanExploration(self) -> PlanExploration: ...
    @InPlanExploration.setter
    def InPlanExploration(self, value: PlanExploration) -> None: ...
    @property
    def MachineReferenceFilterSettings(self) -> ScriptObjectCollection[MachineReferenceFilterSettings]: ...
    @MachineReferenceFilterSettings.setter
    def MachineReferenceFilterSettings(self, value: List[MachineReferenceFilterSettings]) -> None: ...

class MachineReferenceFilterSettings:
    @property
    def Include(self) -> bool: ...
    @Include.setter
    def Include(self, value: bool) -> None: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @MachineReference.setter
    def MachineReference(self, value: MachineReference) -> None: ...
    @property
    def InPlanExploration(self) -> PlanExploration: ...
    @InPlanExploration.setter
    def InPlanExploration(self, value: PlanExploration) -> None: ...

class MachineReference:
    @property
    def MachineName(self) -> str: ...
    @property
    def CommissioningTime(self) -> Optional[str]: ...
    @property
    def CommissioningTimeUtc(self) -> Optional[str]: ...
    @property
    def Energy(self) -> Optional[float]: ...

class CyberKnifeLinac:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def DoseRate(self) -> float: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def PhotonBeamQualities(self) -> ScriptObjectCollection[PhotonBeamQuality]: ...
    @property
    def Physics(self) -> LinacPhysics: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class CyberKnifeFixedCone:
    @property
    def BottomPosition(self) -> float: ...
    @property
    def Diameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def TopPosition(self) -> float: ...

class CyberKnifeIrisCone:
    @property
    def ApprovedForClinicalCollapsedConeDose(self) -> bool: ...
    @property
    def BottomPosition(self) -> float: ...
    @property
    def Diameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def TopPosition(self) -> float: ...

class MachineParameterComputationStep:
    @property
    def NumberOfHistoriesPerAreaFluence(self) -> Optional[int]: ...
    @property
    def SortOrder(self) -> int: ...
    @property
    def StatisticalUncertainty(self) -> Optional[float]: ...
    @property
    def Type(self) -> Literal['None', 'ElectronContamination', 'EnergySpectrumAndOutputCorrections', 'BeamProfileCorrections', 'OffAxisSoftening', 'OutputCorrections', 'PrimarySource', 'CollimatorTransmission', 'TurnOffElectronContamination', 'OffAxisSofteningAnalytical', 'FlatteningFilter', 'CollimatorParametersAnalytical', 'BeamProfileCorrectionsAnalytical', 'LeafTipWidth', 'MotorizedWedgeModulation', 'MotorizedWedgeSource', 'WedgeSourceAndModulation', 'SiemensVirtualWedgeParameters', 'VarianEnhancedDynamicParameters', 'UpdateOFCFieldSizes', 'OverallNormalization', 'WedgeHardeningFactor', 'WedgeOutputFactorCorrections', 'EnergySpectrumAnalytical', 'UpdateWedgeOFCFieldSizes', 'ElectronEnergySpectrum', 'ElectronSourcePhaseSpace', 'DoseContributionWeighting', 'ConeFactorCorrections', 'EntireBeamModel', 'ElectronDoseNormalization', 'ElectronEnergySpectrumFromApplicatorCurves', 'ElectronEnergySpectrumAndSourcePhaseSpace', 'ComputeDoseContributions', 'UpdateWeightsFromOldVersion']: ...
    @property
    def VoxelSize(self) -> Tuple[float, ...]: ...

class MachineParameterModificationStep:
    @property
    def SortOrder(self) -> int: ...
    @property
    def Type(self) -> Literal['None', 'ElectronContamination', 'EnergySpectrumAndOutputCorrections', 'BeamProfileCorrections', 'OffAxisSoftening', 'OutputCorrections', 'PrimarySource', 'CollimatorTransmission', 'TurnOffElectronContamination', 'OffAxisSofteningAnalytical', 'FlatteningFilter', 'CollimatorParametersAnalytical', 'BeamProfileCorrectionsAnalytical', 'LeafTipWidth', 'MotorizedWedgeModulation', 'MotorizedWedgeSource', 'WedgeSourceAndModulation', 'SiemensVirtualWedgeParameters', 'VarianEnhancedDynamicParameters', 'UpdateOFCFieldSizes', 'OverallNormalization', 'WedgeHardeningFactor', 'WedgeOutputFactorCorrections', 'EnergySpectrumAnalytical', 'UpdateWedgeOFCFieldSizes', 'ElectronEnergySpectrum', 'ElectronSourcePhaseSpace', 'DoseContributionWeighting', 'ConeFactorCorrections', 'EntireBeamModel', 'ElectronDoseNormalization', 'ElectronEnergySpectrumFromApplicatorCurves', 'ElectronEnergySpectrumAndSourcePhaseSpace', 'ComputeDoseContributions', 'UpdateWeightsFromOldVersion']: ...

class MachineParameterOptimizationStep:
    @property
    def MaxIterations(self) -> int: ...
    @property
    def NumberOfHistoriesPerAreaFluence(self) -> Optional[int]: ...
    @property
    def SortOrder(self) -> int: ...
    @property
    def StatisticalUncertainty(self) -> Optional[float]: ...
    @property
    def Tolerance(self) -> float: ...
    @property
    def Type(self) -> Literal['None', 'ElectronContamination', 'EnergySpectrumAndOutputCorrections', 'BeamProfileCorrections', 'OffAxisSoftening', 'OutputCorrections', 'PrimarySource', 'CollimatorTransmission', 'TurnOffElectronContamination', 'OffAxisSofteningAnalytical', 'FlatteningFilter', 'CollimatorParametersAnalytical', 'BeamProfileCorrectionsAnalytical', 'LeafTipWidth', 'MotorizedWedgeModulation', 'MotorizedWedgeSource', 'WedgeSourceAndModulation', 'SiemensVirtualWedgeParameters', 'VarianEnhancedDynamicParameters', 'UpdateOFCFieldSizes', 'OverallNormalization', 'WedgeHardeningFactor', 'WedgeOutputFactorCorrections', 'EnergySpectrumAnalytical', 'UpdateWedgeOFCFieldSizes', 'ElectronEnergySpectrum', 'ElectronSourcePhaseSpace', 'DoseContributionWeighting', 'ConeFactorCorrections', 'EntireBeamModel', 'ElectronDoseNormalization', 'ElectronEnergySpectrumFromApplicatorCurves', 'ElectronEnergySpectrumAndSourcePhaseSpace', 'ComputeDoseContributions', 'UpdateWeightsFromOldVersion']: ...
    @property
    def VoxelSize(self) -> Tuple[float, ...]: ...

class CyberKnifeMachineParameters:
    @property
    def CyberKnifeLinacAggregateId(self) -> Optional[str]: ...
    @property
    def ImportedBy(self) -> str: ...
    @property
    def ImportTime(self) -> Optional[str]: ...
    @property
    def RampFileContent(self) -> np.ndarray: ...
    @property
    def RampVersion(self) -> str: ...
    @property
    def SerialID(self) -> str: ...
    @property
    def SystemCalibrationValidForRampVersions(self) -> ScriptObjectCollection[str]: ...
    @property
    def NodeSets(self) -> ScriptObjectCollection[CyberKnifeNodeSet]: ...

class CyberKnifeNodeSet:
    @property
    def Anatomy(self) -> Literal['Head', 'Body', 'Undefined', 'AQA90deg', 'SingleBeam']: ...
    @property
    def CollimationType(self) -> Literal['MLC', 'Cone', 'Undefined']: ...
    @property
    def Name(self) -> str: ...
    @property
    def NodeList(self) -> ScriptObjectCollection[CyberKnifeNode]: ...

class CyberKnifeNode:
    @property
    def ImagingBlocked(self) -> bool: ...
    @property
    def NodeId(self) -> int: ...
    @property
    def PitchAngle(self) -> float: ...
    @property
    def RollAngle(self) -> float: ...
    @property
    def SourcePosition(self) -> Tuple[float, ...]: ...
    @property
    def SupportsIncreasedCorrection(self) -> bool: ...
    @property
    def SupportsSynchrony(self) -> bool: ...
    @property
    def YawAngle(self) -> float: ...

class IonTreatmentMachine:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Design(self) -> Literal['Generic', 'IbaUniversalNozzle', 'IbaDedicatedNozzle', 'TslPassive', 'MevionS250', 'Sumitomo', 'Cnao', 'Mitsubishi', 'Optivus']: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def IsRbeIncluded(self) -> Optional[bool]: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def PrimaryDosimeterUnit(self) -> Literal['MonitorUnit', 'NumberOfParticles']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def BeamQualities(self) -> ScriptObjectCollection[IonBeamQuality]: ...
    @property
    def BlockConstraints(self) -> BlockConstraints: ...
    @property
    def CompensatorConstraints(self) -> CompensatorConstraints: ...
    @property
    def DicomSettings(self) -> IonTreatmentMachineDicomSettings: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def FirstScatterers(self) -> ScriptObjectCollection[FirstScatterer]: ...
    @property
    def FixationLight(self) -> FixationLight: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def HyperscanEnergySelector(self) -> HyperscanEnergySelector: ...
    @property
    def IonWedges(self) -> ScriptObjectCollection[IonWedge]: ...
    @property
    def JawPhysics(self) -> Jaws: ...
    @property
    def MagnetX(self) -> LateralSpreadingDevice: ...
    @property
    def MagnetY(self) -> LateralSpreadingDevice: ...
    @property
    def MlcPhysics(self) -> Mlc: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def NozzleExitWindow(self) -> NozzleExitWindow: ...
    @property
    def RangeModulators(self) -> ScriptObjectCollection[RangeModulator]: ...
    @property
    def RangeShifters(self) -> ScriptObjectCollection[RangeShifter]: ...
    @property
    def ScanPatternConstraints(self) -> ScanPatternConstraints: ...
    @property
    def Scatterer(self) -> LateralSpreadingDevice: ...
    @property
    def SecondScatterers(self) -> ScriptObjectCollection[SecondScatterer]: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    @property
    def Snouts(self) -> ScriptObjectCollection[Snout]: ...
    @property
    def SynchrotronDeliveryParameters(self) -> SynchrotronDeliveryParameters: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class Linac:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def ElectronBeamDoseRate(self) -> Optional[float]: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def JawPresentationLabeling(self) -> Literal['Iec61217', 'Iec601']: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def NumberOfLeafPositionDecimals(self) -> Optional[int]: ...
    @property
    def NumberOfMuDecimals(self) -> Optional[int]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReferenceFieldSize(self) -> Tuple[float, ...]: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SetupBeamDoseRate(self) -> Optional[float]: ...
    @property
    def SourceToWedgeTrayDistanceForStandardWedges(self) -> Optional[float]: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryRotationDirection(self) -> Literal['Clockwise', 'CounterClockwise', 'ClockwiseAndCounterClockwise']: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def WedgeTypes(self) -> ScriptObjectCollection[Any]: ...
    @property
    def ArcProperties(self) -> ArcProperties: ...
    @property
    def BlockConstraints(self) -> PhotonBlockConstraints: ...
    @property
    def BlockTrayDevices(self) -> ScriptObjectCollection[BlockTrayDevice]: ...
    @property
    def DicomSettings(self) -> LinacDicomSettings: ...
    @property
    def ElectronApplicators(self) -> ScriptObjectCollection[ElectronApplicator]: ...
    @property
    def ElectronBeamQualities(self) -> ScriptObjectCollection[ElectronBeamQuality]: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def GimbalProperties(self) -> GimbalProperties: ...
    @property
    def JawRoundingSettings(self) -> JawRoundingSettings: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def PhotonBeamQualities(self) -> ScriptObjectCollection[PhotonBeamQuality]: ...
    @property
    def Physics(self) -> LinacPhysics: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class NctTreatmentMachine:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SourceAxisDistance(self) -> float: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    @property
    def SupportedCollimators(self) -> ScriptObjectCollection[NctCollimator]: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class TomoLinac:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def Jaw(self) -> TomoJaw: ...
    @property
    def Mlc(self) -> TomoMlc: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    @property
    def TomoBeamQualities(self) -> ScriptObjectCollection[TomoBeamQuality]: ...
    @property
    def TomoProperties(self) -> TomoProperties: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class TreatmentMachine:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class SmallAnimalXRayIrradiator:
    @property
    def CollimatorScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def Comment(self) -> str: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def CouchScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def GantryScale(self) -> Literal['Iec61217', 'VarianIec', 'VarianStandard']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Manufacturer(self) -> str: ...
    @property
    def ManufacturerModelName(self) -> str: ...
    @property
    def MaxDoseRate(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameAliases(self) -> ScriptObjectCollection[str]: ...
    @property
    def PatientSupportType(self) -> Literal['Table', 'Chair']: ...
    @property
    def PresentationFieldCoordinateSystem(self) -> Literal['Iec', 'PositiveFieldPositions']: ...
    @property
    def ReplaceCouchRotationByRingRotation(self) -> bool: ...
    @property
    def RoomViewModel(self) -> Literal['SchematicLinac', 'RingGantry', 'OnlyCouch', 'CyberKnife', 'TomoTherapy', 'UCTLinac', 'RingGantryVero', 'RingGantryOxray', 'ProtonTherapy', 'SeatedTreatment', 'LCC_Chair']: ...
    @property
    def SourceAxisDistance(self) -> float: ...
    @property
    def SupportedCollimatorAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedCouchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGantryRotationDirection(self) -> Literal['Clockwise', 'CounterClockwise', 'ClockwiseAndCounterClockwise']: ...
    @property
    def SupportedPitchAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedRollAngles(self) -> Tuple[float, ...]: ...
    @property
    def UncommissionedFolder(self) -> str: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def GeneralDicomSettings(self) -> GeneralDicomSettings: ...
    @property
    def Jaws(self) -> Jaws: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @property
    def MotionSynchronizationModes(self) -> ScriptObjectCollection[MotionSynchronizationMode]: ...
    @property
    def ReferenceFieldSetup(self) -> ReferenceFieldSetup: ...
    @property
    def SetupImagingSystems(self) -> ScriptObjectCollection[SetupImagingSystem]: ...
    @property
    def SupportedCones(self) -> ScriptObjectCollection[XRayIrradiatorFixedCone]: ...
    @property
    def XRayIrradiatorBeamQualities(self) -> ScriptObjectCollection[XRayIrradiatorBeamQuality]: ...
    def MachineBackup(self, FileName: str) -> None:
        """Make a file backup of the treatment machine"""
        ...

class MachineSignature:
    @property
    def CommissioningTime(self) -> str: ...
    @property
    def MachineName(self) -> str: ...
    @property
    def Signature(self) -> str: ...

class CyberKnifeDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @property
    def IterationsBeforeConversion(self) -> int: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def MinLeafEndSeparation(self) -> float: ...
    @property
    def MinNumberOfOpenLeafPairs(self) -> int: ...
    @property
    def MinSegmentArea(self) -> float: ...
    @property
    def MinSegmentMuPerFraction(self) -> float: ...
    @property
    def OptimizationTolerance(self) -> float: ...
