from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import BeamCurrentModulationCurve, BeamLineObject, PhotonEnergySpectrum
    from raystation.v2025.dose import DoseAlgorithmVersion, DoseDetector
    from raystation.v2025.ion import IonArcProperties, IonBeamSetup, IonCalibrationPoint
    from raystation.v2025.machine import MachineParameterComputationStep, MachineParameterModificationStep, MachineParameterOptimizationStep, SmallAnimalXRayIrradiator



class ModificationInfo:
    @property
    def ModificationTime(self) -> str: ...
    @property
    def SoftwareVersion(self) -> str: ...
    @property
    def UserName(self) -> str: ...

class Material:
    @property
    def ElementalAtomicNumbers(self) -> np.ndarray: ...
    @property
    def ElementalMasses(self) -> np.ndarray: ...
    @property
    def ElementalWeights(self) -> np.ndarray: ...
    @property
    def MassDensity(self) -> float: ...
    @property
    def MaterialId(self) -> str: ...
    @property
    def MeanExcitationEnergy(self) -> float: ...
    @property
    def Name(self) -> str: ...

class MlcLayer:
    @property
    def LeafCenterPositions(self) -> np.ndarray: ...
    @property
    def LeafWidths(self) -> np.ndarray: ...
    @property
    def MaxTipPositions(self) -> np.ndarray: ...
    @property
    def MinTipPositions(self) -> np.ndarray: ...
    @property
    def NumOfLeafPairs(self) -> int: ...
    @property
    def PhysicalBottomZPosition(self) -> float: ...

class NctCollimator:
    @property
    def InnerDiameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def PatientSideOuterDiameter(self) -> float: ...
    @property
    def SourceSideOuterDiameter(self) -> float: ...
    @property
    def Thickness(self) -> float: ...

class Wedge:
    @property
    def Angle(self) -> float: ...
    @property
    def MaxEdgePosition(self) -> Tuple[float, ...]: ...
    @property
    def MaxMU(self) -> Optional[float]: ...
    @property
    def MinEdgePosition(self) -> Tuple[float, ...]: ...
    @property
    def MinMU(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def Type(self) -> Literal['None', 'VarianEnhancedDynamic', 'SiemensVirtual', 'ElektaMotorized', 'Standard']: ...
    @property
    def Orientations(self) -> ScriptObjectCollection[OrientationProperties]: ...

class Cone:
    @property
    def BottomPosition(self) -> float: ...
    @property
    def Diameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def TopPosition(self) -> float: ...

class MotionSynchronizationMode:
    @property
    def DisplayName(self) -> str: ...
    @property
    def MotionSynchronizationTechnique(self) -> Literal['Undefined', 'Fiducial', 'FiducialWithRespiratory', 'FiducialWithInTempo', 'LungOneViewAWithRespiratory', 'LungOneViewBWithRespiratory', 'LungWithRespiratory', 'Skull', 'SkullWithInTempo', 'SpineSupine', 'SpineProneWithRespiratory', 'SpineSupineWithInTempo', 'Simulation', 'MedPhotonImaging']: ...
    @property
    def RequireRespiratoryIntervalTime(self) -> bool: ...
    @property
    def RequireRespiratoryPhaseGatingDutyCycleTimePercentage(self) -> bool: ...
    @property
    def UseMotionSynchronizationInTreatmentPlanAsDefaultForQAPlans(self) -> bool: ...
    @property
    def MotionSynchronizationProperties(self) -> ScriptObjectCollection[MotionSynchronizationProperties]: ...

class MotionSynchronizationProperties:
    @property
    def RespiratoryMotionCompensationTechnique(self) -> Literal['Disabled', 'None', 'Gating', 'Tracking', 'Realtime', 'IntervalImaging']: ...
    @property
    def RespiratorySignalSource(self) -> Literal['Disabled', 'None', 'ExternalMarker', 'Spirometer', 'Belt', 'InternalMarker', 'Fiducials', 'TrackedRegionOfInterest', 'Image', 'PositiveImagerX', 'NegativeImagerX', 'DualImagers']: ...

class QuasiDiscreteProperties:
    @property
    def ComputeSpillDose(self) -> bool: ...
    @property
    def ControlTime(self) -> Optional[float]: ...
    @property
    def MaxSpotDistanceWithBeamOn(self) -> Optional[float]: ...
    @property
    def ResponseTime(self) -> Optional[float]: ...
    @property
    def SpotSpacingFactorWithBeamOn(self) -> Optional[float]: ...
    @property
    def UseNominalSpotSizesForSpacing(self) -> bool: ...
    @property
    def ScanSpeeds(self) -> ScriptObjectCollection[ScanSpeed]: ...

class FixationLight:
    @property
    def ArmMountingAngle(self) -> float: ...
    @property
    def IsocenterToArmDistance(self) -> float: ...
    @property
    def MaxPolarAngle(self) -> float: ...
    @property
    def MinPolarAngle(self) -> float: ...

class AlgorithmsCommissionedForImageConversion:
    @property
    def ImagingSystemAggregateId(self) -> str: ...
    @property
    def ConvertedExaminationAlgorithmVersions(self) -> ScriptObjectCollection[ConvertedExaminationAlgorithmVersion]: ...

class ConvertedExaminationAlgorithmVersion:
    @property
    def Algorithm(self) -> Literal['MachineLearningModel', 'CbctVirtual', 'CbctConverted']: ...
    @property
    def MajorVersion(self) -> int: ...
    @property
    def MinorVersion(self) -> int: ...
    @property
    def CommissioningInfo(self) -> CommissioningInfo: ...

class CommissioningInfo:
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def Status(self) -> Literal['Commissioned', 'Deprecated', 'Uncommissioned']: ...

class ActiveSubstance:
    @property
    def ActiveSubstanceType(self) -> Literal['AntiCancer', 'Support']: ...
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def DisplayColor(self) -> str: ...
    @property
    def DoseIncrement(self) -> Optional[float]: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def MaxDosePerAdministration(self) -> Optional[float]: ...
    @property
    def MaxDosePerLifetime(self) -> Optional[float]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Notes(self) -> str: ...

class AblationApplicator:
    @property
    def ApplicatorLength(self) -> float: ...
    @property
    def ApplicatorRadius(self) -> float: ...
    @property
    def Comment(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def AblationApplicatorSettings(self) -> ScriptObjectCollection[AblationApplicatorSettings]: ...
    @property
    def CommissioningInfo(self) -> CommissioningInfo: ...

class AblationApplicatorSettings:
    @property
    def AblationZoneDiameter(self) -> float: ...
    @property
    def AblationZoneLength(self) -> float: ...
    @property
    def DistancePastTip(self) -> float: ...
    @property
    def Duration(self) -> int: ...
    @property
    def Power(self) -> int: ...

class OrientationProperties:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def Orientation(self) -> Literal['In', 'Out', 'Left', 'Right']: ...
    @property
    def WedgeID(self) -> str: ...

class LinacCone:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def BottomPosition(self) -> float: ...
    @property
    def Diameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def TopPosition(self) -> float: ...
    @property
    def CollimatorPositions(self) -> FixedCollimatorPositionProperties: ...

class FixedCollimatorPositionProperties:
    @property
    def FixedMlcLeafPositions(self) -> Tuple[float, ...]: ...
    @property
    def FixedMlcYLimits(self) -> Tuple[float, ...]: ...
    @property
    def FixedXJawPositions(self) -> Tuple[float, ...]: ...
    @property
    def FixedYJawPositions(self) -> Tuple[float, ...]: ...
    @property
    def IsMlcRetracted(self) -> bool: ...

class XRayIrradiatorFixedCone:
    @property
    def BottomPosition(self) -> float: ...
    @property
    def Diameter(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def Shape(self) -> Literal['Circular', 'Square', 'Rectangular', 'Elliptical', 'Hexagonal', 'Dodecagonal']: ...
    @property
    def TopPosition(self) -> float: ...
    @property
    def XOffset(self) -> float: ...
    @property
    def YOffset(self) -> float: ...
    @property
    def YWidth(self) -> Optional[float]: ...
    @property
    def EntranceCone(self) -> EntranceCone: ...

class EntranceCone:
    @property
    def AngleOffset(self) -> float: ...
    @property
    def EffectivePosition(self) -> float: ...
    @property
    def Shape(self) -> Literal['Circular', 'Square', 'Rectangular', 'Elliptical', 'Hexagonal', 'Dodecagonal']: ...
    @property
    def XOffset(self) -> float: ...
    @property
    def XWidth(self) -> float: ...
    @property
    def YOffset(self) -> float: ...
    @property
    def YWidth(self) -> Optional[float]: ...

class ComputedDoseCurve:
    @property
    def DoseComponent(self) -> Literal['FullDoseCurve', 'PrimaryElectrons', 'ScatteredElectrons', 'PhotonContamination']: ...
    @property
    def DoseValues(self) -> np.ndarray: ...
    @property
    def NumberOfHistories(self) -> Optional[int]: ...
    @property
    def Positions(self) -> ScriptObjectCollection[Any]: ...
    @property
    def UncertaintyValues(self) -> np.ndarray: ...
    @property
    def ComputedDoseCurveStatistics(self) -> ComputedDoseCurveStatistics: ...
    @property
    def DoseAlgorithmVersion(self) -> DoseAlgorithmVersion: ...
    @property
    def ForComputationSettings(self) -> ComputationSettings: ...
    @property
    def ForMeasuredCurve(self) -> MeasuredDoseCurve: ...

class ComputedDoseCurveStatistics:
    @property
    def RelativeDoseDifference(self) -> np.ndarray: ...
    @property
    def ComputedDoseCurveGammaCurve(self) -> ComputedDoseCurveGammaCurve: ...

class ComputedDoseCurveGammaCurve:
    @property
    def GammaValues(self) -> np.ndarray: ...
    @property
    def ForGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...

class ModelingStep:
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> str: ...
    @property
    def FieldSizeMatchAfter(self) -> FieldSizeMatch: ...
    @property
    def FieldSizeMatchBefore(self) -> FieldSizeMatch: ...

class FieldSizeMatch:
    @property
    def Buildup(self) -> float: ...
    @property
    def Falloff(self) -> float: ...
    @property
    def FieldSize(self) -> Tuple[float, ...]: ...
    @property
    def InField(self) -> float: ...
    @property
    def OutOfField(self) -> float: ...
    @property
    def Penumbra(self) -> float: ...

class ParameterComputationStep:
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> str: ...
    @property
    def DoseCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def FieldSizeMatchAfter(self) -> FieldSizeMatch: ...
    @property
    def FieldSizeMatchBefore(self) -> FieldSizeMatch: ...
    @property
    def MachineParameterComputationStep(self) -> MachineParameterComputationStep: ...

class ParameterModificationStep:
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> str: ...
    @property
    def FieldSizeMatchAfter(self) -> FieldSizeMatch: ...
    @property
    def FieldSizeMatchBefore(self) -> FieldSizeMatch: ...
    @property
    def MachineParameterModificationStep(self) -> MachineParameterModificationStep: ...

class ParameterOptimizationStep:
    @property
    def CompletedIterations(self) -> int: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> str: ...
    @property
    def DoseCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def FieldSizeMatchAfter(self) -> FieldSizeMatch: ...
    @property
    def FieldSizeMatchBefore(self) -> FieldSizeMatch: ...
    @property
    def MachineParameterOptimizationStep(self) -> MachineParameterOptimizationStep: ...

class WedgeParameters:
    @property
    def MaterialFactor(self) -> float: ...
    @property
    def SourceToWedgeDistance(self) -> float: ...
    @property
    def WedgeModulation(self) -> np.ndarray: ...
    @property
    def WedgeModulationParametersX(self) -> np.ndarray: ...
    @property
    def WedgeModulationParametersY(self) -> np.ndarray: ...
    @property
    def ScatteringSource(self) -> SecondarySource: ...
    @property
    def Wedge(self) -> Wedge: ...

class SecondarySource:
    @property
    def Weight(self) -> float: ...
    @property
    def Width(self) -> float: ...
    @property
    def YWidthNonCircularSource(self) -> Optional[float]: ...
    @property
    def ZDistance(self) -> float: ...

class WedgeFactorCorrections:
    @property
    def Corrections(self) -> np.ndarray: ...
    @property
    def FieldMeasures(self) -> np.ndarray: ...
    @property
    def ForWedge(self) -> Wedge: ...

class ConeCorrection:
    @property
    def DiameterCorrectionFactor(self) -> float: ...
    @property
    def MaterialFactor(self) -> float: ...
    @property
    def OutputFactorCorrection(self) -> float: ...
    @property
    def ForCone(self) -> Cone: ...

class Calibration:
    @property
    def AbsoluteCalibration(self) -> float: ...

class PrimarySource:
    @property
    def XWidth(self) -> float: ...
    @property
    def YWidth(self) -> float: ...

class Collimator:
    @property
    def BottomZPosition(self) -> Optional[float]: ...
    @property
    def CornerTransmission(self) -> Optional[float]: ...
    @property
    def Curvature(self) -> float: ...
    @property
    def Gain(self) -> float: ...
    @property
    def LeafTipTransmission(self) -> Optional[float]: ...
    @property
    def LeafTipWidth(self) -> Optional[float]: ...
    @property
    def Offset(self) -> float: ...
    @property
    def OrthogonalGain(self) -> float: ...
    @property
    def Thickness(self) -> Optional[float]: ...
    @property
    def TongueAndGroove(self) -> Optional[float]: ...
    @property
    def Transmission(self) -> float: ...
    @property
    def ZDistance(self) -> float: ...

class RadialDistribution:
    @property
    def Radii(self) -> np.ndarray: ...
    @property
    def Values(self) -> np.ndarray: ...

class OutputFactorCorrections:
    @property
    def Corrections(self) -> np.ndarray: ...
    @property
    def FieldMeasures(self) -> np.ndarray: ...

class SiemensVirtualWedgeProperties:
    @property
    def CalibrationFactor(self) -> float: ...
    @property
    def MeanLinearAttenuationFactor(self) -> float: ...

class ComputationSettings:
    @property
    def DepthVoxelSize(self) -> float: ...
    @property
    def DoseEngine(self) -> str: ...
    @property
    def LateralVoxelSize(self) -> float: ...
    @property
    def NumberOfHistories(self) -> Optional[int]: ...
    @property
    def PhantomSize(self) -> Tuple[float, ...]: ...
    @property
    def PostProcess(self) -> bool: ...
    @property
    def StatisticalUncertainty(self) -> Optional[float]: ...
    @property
    def UseStatisticalUncertaintyInsteadOfHistoriesForDoseComputation(self) -> bool: ...

class ComputedDoseCurvesGammaSettings:
    @property
    def DistanceToAgreement(self) -> float: ...
    @property
    def RelativeDoseDifference(self) -> float: ...

class BlockTrayTransmission:
    @property
    def Transmission(self) -> float: ...
    @property
    def ForBlockTrayDevice(self) -> BlockTrayDevice: ...

class MeasuredDoseCurve:
    @property
    def DepthOffset(self) -> float: ...
    @property
    def DoseValues(self) -> np.ndarray: ...
    @property
    def FieldCollimation(self) -> Literal['JawsOnlyCollimated', 'MlcOnlyCollimated', 'JawsAndMlcCollimated', 'MixedCollimated']: ...
    @property
    def FieldCorner(self) -> Tuple[float, ...]: ...
    @property
    def FieldSize(self) -> Tuple[float, ...]: ...
    @property
    def ImportFilePath(self) -> str: ...
    @property
    def IsAirMeasurement(self) -> bool: ...
    @property
    def JawFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def MlcFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def MlcLeafTipOffset(self) -> float: ...
    @property
    def Positions(self) -> ScriptObjectCollection[Any]: ...
    @property
    def Type(self) -> Literal['Depth', 'X', 'Y', 'Diagonal']: ...
    @property
    def DoseDetector(self) -> DoseDetector: ...
    @property
    def ForCone(self) -> Cone: ...
    @property
    def IonBeamSetup(self) -> IonBeamSetup: ...
    @property
    def LinacFieldSetup(self) -> LinacFieldSetup: ...
    @property
    def WedgeOrientation(self) -> OrientationProperties: ...

class ScanningBeamSetup:
    @property
    def HasNozzleExitWindow(self) -> Optional[bool]: ...
    @property
    def IsSingleSpot(self) -> bool: ...
    @property
    def RangeModulatorName(self) -> str: ...
    @property
    def ScannedFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def SpotSpacing(self) -> Optional[float]: ...
    @property
    def SpotTuneId(self) -> str: ...

class LinacFieldSetup:
    ...

class ArbitraryLinacFieldSetup:
    @property
    def AbsoluteDoseScaleFactor(self) -> float: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def FieldId(self) -> str: ...
    @property
    def Ssd(self) -> float: ...

class NormalizedDoseCurve:
    @property
    def DoseValues(self) -> np.ndarray: ...
    @property
    def Positions(self) -> ScriptObjectCollection[Any]: ...
    @property
    def ForMeasuredCurve(self) -> MeasuredDoseCurve: ...

class WedgeFactor:
    @property
    def Factor(self) -> float: ...
    @property
    def FieldSize(self) -> Tuple[float, ...]: ...
    @property
    def ForWedge(self) -> Wedge: ...

class OutputFactor:
    @property
    def Factor(self) -> float: ...
    @property
    def FieldSize(self) -> Tuple[float, ...]: ...

class ConeFactor:
    @property
    def Factor(self) -> float: ...
    @property
    def ForCone(self) -> Cone: ...

class CalibrationPoint:
    @property
    def Depth(self) -> float: ...
    @property
    def DosePerMeterset(self) -> float: ...
    @property
    def Ssd(self) -> float: ...

class ComputedIonCalibrationPoint:
    @property
    def Depth(self) -> float: ...
    @property
    def DosePerMeterset(self) -> float: ...
    @property
    def NumberOfHistories(self) -> Optional[int]: ...
    @property
    def Ssd(self) -> float: ...
    @property
    def Uncertainty(self) -> Optional[float]: ...
    @property
    def DoseAlgorithmVersion(self) -> DoseAlgorithmVersion: ...
    @property
    def ForIonCalibrationPoint(self) -> IonCalibrationPoint: ...

class CryostatTransmissionFactors:
    @property
    def Factors(self) -> np.ndarray: ...
    @property
    def GantryAngles(self) -> np.ndarray: ...

class GeneralDicomSettings:
    @property
    def DefaultDoseReferenceDescription(self) -> Literal['BeamSetNameCombinedWithPrescriptionInfo', 'BeamSetNameMinusCaseIdCombinedWithPrescriptionInfo', 'ShortPrescriptionInfo', 'LongPrescriptionInfo']: ...
    @property
    def DefaultPatientSetupTechnique(self) -> Literal['None', 'Isocentric', 'FixedSSD']: ...
    @property
    def ExportBdspDoseAsFractionOfPrescriptionDose(self) -> bool: ...
    @property
    def ExportedBeamOrderMode(self) -> Literal['TreatmentBeamsFirst', 'SetupBeamsFirst', 'OrderByBeamNumber']: ...
    @property
    def RtImageDicomSettings(self) -> RtImageDicomSettings: ...

class RtImageDicomSettings:
    @property
    def ExportRadiationMachineNameAsTreatmentMachineName(self) -> bool: ...
    @property
    def ExportRtImageNameAsSetupImagerName(self) -> bool: ...
    @property
    def SkipExportOfPixelIntensityRelationshipAttributesIfOther(self) -> bool: ...

class LinacPhysics:
    @property
    def MagneticField(self) -> Optional[Point3[float]]: ...
    @property
    def SourceAxisDistance(self) -> float: ...
    @property
    def BeamLineObjects(self) -> ScriptObjectCollection[BeamLineObject]: ...
    @property
    def JawPhysics(self) -> Jaws: ...
    @property
    def MlcPhysics(self) -> Mlc: ...

class Jaws:
    @property
    def JawPositioning(self) -> Literal['Fixed', 'PerSegment', 'PerBeam']: ...
    @property
    def LeftRightJawTipRadius(self) -> Optional[float]: ...
    @property
    def LeftRightJawType(self) -> Literal['AsymmetricX', 'AsymmetricY', 'X', 'Y']: ...
    @property
    def LeftRightPhysicalBottomZPosition(self) -> float: ...
    @property
    def LeftRightPhysicalThickness(self) -> float: ...
    @property
    def LeftRightTipShape(self) -> Literal['Rounded', 'Orthogonal', 'Focused']: ...
    @property
    def MaxBottomJawPos(self) -> float: ...
    @property
    def MaxJawSpeed(self) -> float: ...
    @property
    def MaxRightJawPos(self) -> float: ...
    @property
    def MinBottomJawPos(self) -> float: ...
    @property
    def MinFieldSizeX(self) -> float: ...
    @property
    def MinFieldSizeY(self) -> float: ...
    @property
    def MinRightJawPos(self) -> float: ...
    @property
    def MlcReplacesJaw(self) -> bool: ...
    @property
    def TopBottomJawTipRadius(self) -> Optional[float]: ...
    @property
    def TopBottomJawType(self) -> Literal['AsymmetricX', 'AsymmetricY', 'X', 'Y']: ...
    @property
    def TopBottomPhysicalBottomZPosition(self) -> float: ...
    @property
    def TopBottomPhysicalThickness(self) -> float: ...
    @property
    def TopBottomTipShape(self) -> Literal['Rounded', 'Orthogonal', 'Focused']: ...
    @property
    def UseMultipleCarriageGroupsForSplitBeams(self) -> bool: ...

class Mlc:
    @property
    def ApertureBoundingBoxToMlcMargin(self) -> float: ...
    @property
    def ApertureToMlcMargin(self) -> float: ...
    @property
    def AutoConformLeavesToBlock(self) -> bool: ...
    @property
    def ClosedLeavesPosition(self) -> Optional[float]: ...
    @property
    def Interdigitation(self) -> bool: ...
    @property
    def IsApexAddOnMlc(self) -> bool: ...
    @property
    def LeafJawOverlap(self) -> float: ...
    @property
    def LeafProjectionPlane(self) -> Literal['Isocenter', 'MlcVirtualTray']: ...
    @property
    def LeafSideGeometry(self) -> Literal['Focused', 'Orthogonal']: ...
    @property
    def LeafTipCenterOffset(self) -> float: ...
    @property
    def LeafTipGeometry(self) -> Literal['Rounded', 'Orthogonal', 'Focused']: ...
    @property
    def LeafTipRadius(self) -> float: ...
    @property
    def MaxLeafSpeed(self) -> float: ...
    @property
    def MaxTipDifference(self) -> float: ...
    @property
    def MinGap(self) -> float: ...
    @property
    def MinGapMoving(self) -> float: ...
    @property
    def MovementDirection(self) -> Literal['X', 'Y']: ...
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def UseDynamicLeafTipGapForStaticFields(self) -> bool: ...
    @property
    def Carriage(self) -> Carriage: ...
    @property
    def GuardLeavesSettings(self) -> GuardLeavesSettings: ...
    @property
    def JawRetractSettings(self) -> JawRetractSettings: ...
    @property
    def LeafMaterial(self) -> Material: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...
    @property
    def VariableMinGapSettings(self) -> VariableMinGapSettings: ...

class Carriage:
    @property
    def CarriageType(self) -> Literal['DynamicCarriage', 'StaticCarriage']: ...
    @property
    def MaxCarriagePosition(self) -> float: ...
    @property
    def MaxCarriageSpeed(self) -> float: ...
    @property
    def MaxLeafOutOfCarriageDistance(self) -> float: ...
    @property
    def MinCarriagePosition(self) -> float: ...

class GuardLeavesSettings:
    @property
    def MinimumDistance(self) -> float: ...

class JawRetractSettings:
    @property
    def ParallelDistance(self) -> float: ...
    @property
    def PerpendicularDistance(self) -> float: ...

class VariableMinGapSettings:
    @property
    def VariableMinGapOffset(self) -> float: ...

class RangeModulator:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def IsocenterToTrayDistance(self) -> float: ...
    @property
    def LayerMaterialNames(self) -> ScriptObjectCollection[Any]: ...
    @property
    def ModulationsPerRotation(self) -> int: ...
    @property
    def MountingPosition(self) -> Literal['PatientSide', 'SourceSide', 'DoubleSided', 'Undefined']: ...
    @property
    def Name(self) -> str: ...
    @property
    def RangeModulatorId(self) -> str: ...
    @property
    def RangeModulatorSequenceNameAlias(self) -> ScriptObjectCollection[Any]: ...
    @property
    def StepEdgeAngles(self) -> np.ndarray: ...
    @property
    def StepPhysicalThickness(self) -> np.ndarray: ...
    @property
    def StepUpstreamFaceToTrayDistance(self) -> np.ndarray: ...
    @property
    def StepWaterEquivalentThickness(self) -> np.ndarray: ...
    @property
    def StopDigitToAngleTable(self) -> np.ndarray: ...
    @property
    def Type(self) -> Literal['Fixed', 'WheelFixedWeights', 'WheelModulatedWeights']: ...
    @property
    def BeamCurrentModulationCurves(self) -> ScriptObjectCollection[BeamCurrentModulationCurve]: ...
    @property
    def LayerMaterials(self) -> ScriptObjectCollection[Material]: ...

class MetersetRateSetting:
    @property
    def MetersetRateSettingId(self) -> str: ...
    @property
    def MinimumPrescriptionDose(self) -> Optional[float]: ...
    @property
    def MetersetRates(self) -> ScriptObjectCollection[MetersetRate]: ...

class MetersetRate:
    @property
    def Intensity(self) -> float: ...
    @property
    def NominalEnergy(self) -> float: ...

class RangeModulatorModel:
    @property
    def MaximumRange(self) -> float: ...
    @property
    def SobpWidth(self) -> float: ...
    @property
    def StepEffectiveWeights(self) -> np.ndarray: ...
    @property
    def TreatmentEnergies(self) -> np.ndarray: ...
    @property
    def TreatmentEnergyFractions(self) -> np.ndarray: ...
    @property
    def ForRangeModulator(self) -> RangeModulator: ...
    @property
    def NominalDiscreteEnergies(self) -> ScriptObjectCollection[DiscreteEnergy]: ...
    @property
    def OutputFactorCorrections(self) -> OutputFactorCorrections: ...

class DiscreteEnergy:
    @property
    def IonsPerBeamMeterset(self) -> float: ...
    @property
    def MeanEnergy(self) -> float: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def NominalRange(self) -> Optional[float]: ...
    @property
    def NozzleEquivalentThickness(self) -> float: ...
    @property
    def RangeShifterWaterEquivalentThickness(self) -> Optional[float]: ...
    @property
    def VirtualSourceAxisDistance(self) -> Tuple[float, ...]: ...
    @property
    def EnergyHistogram(self) -> EnergyHistogram: ...
    @property
    def IddProfile(self) -> IddProfile: ...
    @property
    def OutputFactorCorrections(self) -> OutputFactorCorrections: ...
    @property
    def PrimaryGaussianParameters(self) -> ScriptObjectCollection[PrimaryGaussianParameters]: ...
    @property
    def SecondaryGaussianParameters(self) -> ScriptObjectCollection[SecondaryGaussianParameters]: ...

class PrimaryGaussianParameters:
    @property
    def FEParametersX(self) -> Tuple[float, ...]: ...
    @property
    def FEParametersY(self) -> Tuple[float, ...]: ...
    @property
    def ScatteringPowerInAir(self) -> float: ...
    @property
    def SnoutPosition(self) -> float: ...

class SecondaryGaussianParameters:
    @property
    def FEParametersX(self) -> Tuple[float, ...]: ...
    @property
    def FEParametersY(self) -> Tuple[float, ...]: ...
    @property
    def ScatteringPowerInAir(self) -> float: ...
    @property
    def SnoutPosition(self) -> float: ...
    @property
    def Weight(self) -> float: ...

class IddProfile:
    @property
    def Depth(self) -> np.ndarray: ...
    @property
    def IDose(self) -> np.ndarray: ...
    @property
    def Parameters(self) -> np.ndarray: ...
    @property
    def Type(self) -> Literal['DoseCurve', 'RslParametric']: ...

class EnergyHistogram:
    @property
    def BinEdges(self) -> np.ndarray: ...
    @property
    def Intensities(self) -> np.ndarray: ...

class RangeOption:
    @property
    def MaximumFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def MaximumSobpWidth(self) -> float: ...
    @property
    def MetersetRate(self) -> Optional[float]: ...
    @property
    def MinimumFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def Name(self) -> str: ...
    @property
    def NominalBeamEnergyLimits(self) -> Tuple[float, ...]: ...
    @property
    def NozzleWaterEquivalentThicknessCorrection(self) -> float: ...
    @property
    def RangeLimits(self) -> Tuple[float, ...]: ...
    @property
    def RangeOptionId(self) -> str: ...
    @property
    def RangeShifterWaterEquivalentThicknessLimits(self) -> Optional[Point2[float]]: ...
    @property
    def ConversionAlgorithm(self) -> Union[Convalgo, DiscreteSobpConversionAlgorithm, GenericConversionAlgorithm, SumitomoNozzleSettings, Wobalgo]: ...
    @property
    def NominalDiscreteEnergies(self) -> ScriptObjectCollection[DiscreteEnergy]: ...
    @property
    def RadialFluenceCorrection(self) -> RadialScalingDistribution: ...
    @property
    def RangeModulatorModels(self) -> ScriptObjectCollection[RangeModulatorModel]: ...
    @property
    def ScanPatternSetup(self) -> ScanPatternSetup: ...
    @property
    def TreatmentDiscreteEnergies(self) -> ScriptObjectCollection[DiscreteEnergy]: ...
    @property
    def UsingFirstScatterer(self) -> FirstScatterer: ...
    @property
    def UsingRangeModulator(self) -> RangeModulator: ...
    @property
    def UsingSecondScatterer(self) -> SecondScatterer: ...

class Convalgo:
    @property
    def BeamCurrentModulationRangeEdges(self) -> np.ndarray: ...
    @property
    def FirstScattererWeTPolynome(self) -> np.ndarray: ...
    @property
    def Name(self) -> str: ...
    @property
    def RangeModulatorStopDigitPolynome(self) -> np.ndarray: ...
    @property
    def RangeModulatorStopDigitTable(self) -> np.ndarray: ...
    @property
    def RangeToEnergyConversionParameters(self) -> np.ndarray: ...
    @property
    def RangeToEnergyTable(self) -> np.ndarray: ...
    @property
    def SobpRangeDefinition(self) -> Literal['Sobp', 'PristineMaxBraggPeak']: ...
    @property
    def SobpRangeLevel(self) -> float: ...
    @property
    def SobpWidthLevels(self) -> Tuple[float, ...]: ...
    @property
    def BeamCurrentModulationCurves(self) -> ScriptObjectCollection[BeamCurrentModulationCurve]: ...

class DiscreteSobpConversionAlgorithm:
    @property
    def Name(self) -> str: ...
    @property
    def RangeShifterMinimumStep(self) -> Optional[float]: ...
    @property
    def SobpRangeDefinition(self) -> Literal['Sobp', 'PristineMaxBraggPeak']: ...
    @property
    def SobpRangeLevel(self) -> float: ...
    @property
    def SobpWidthLevels(self) -> Tuple[float, ...]: ...

class GenericConversionAlgorithm:
    @property
    def Name(self) -> str: ...
    @property
    def RangeToEnergyTable(self) -> np.ndarray: ...
    @property
    def SobpRangeDefinition(self) -> Literal['Sobp', 'PristineMaxBraggPeak']: ...
    @property
    def SobpRangeLevel(self) -> float: ...
    @property
    def SobpWidthLevels(self) -> Tuple[float, ...]: ...
    @property
    def SOBPWidthToStopWeightTable(self) -> np.ndarray: ...

class SumitomoNozzleSettings:
    @property
    def IntrinsicSpotSize(self) -> np.ndarray: ...
    @property
    def Name(self) -> str: ...
    @property
    def NominalEnergyToNominalRangeTable(self) -> np.ndarray: ...
    @property
    def NominalEnergyToScatterThicknessTable(self) -> np.ndarray: ...
    @property
    def RangeToEnergyConversionParameters(self) -> np.ndarray: ...
    @property
    def SobpRangeDefinition(self) -> Literal['Sobp', 'PristineMaxBraggPeak']: ...
    @property
    def SobpRangeLevel(self) -> float: ...
    @property
    def SobpWidthLevels(self) -> Tuple[float, ...]: ...
    @property
    def SpotSizeToScannedFlatFieldRadiusRatio(self) -> float: ...
    @property
    def WobblingRadiusToSpotSizeRatio(self) -> float: ...
    @property
    def FixedFieldSizes(self) -> ScriptObjectCollection[FixedFieldSizeParameters]: ...

class FixedFieldSizeParameters:
    @property
    def Name(self) -> str: ...
    @property
    def RadiusOfFlatRegion(self) -> float: ...
    @property
    def TreatmentEnergyToScattererThicknessConversionParameters(self) -> np.ndarray: ...

class Wobalgo:
    @property
    def EnergyLayerStopWeightTable(self) -> np.ndarray: ...
    @property
    def EnergyLayerWeightRangeEdges(self) -> np.ndarray: ...
    @property
    def EnergyLayerWeights(self) -> np.ndarray: ...
    @property
    def Name(self) -> str: ...
    @property
    def RangeToEnergyConversionParameters(self) -> np.ndarray: ...
    @property
    def RangeToEnergyTable(self) -> np.ndarray: ...
    @property
    def ScanningAmplitudeCoefficients(self) -> np.ndarray: ...
    @property
    def SobpRangeDefinition(self) -> Literal['Sobp', 'PristineMaxBraggPeak']: ...
    @property
    def SobpRangeLevel(self) -> float: ...
    @property
    def SobpWidth(self) -> np.ndarray: ...
    @property
    def SobpWidthLevels(self) -> Tuple[float, ...]: ...
    @property
    def SpotToFieldSizeRatio(self) -> float: ...
    @property
    def EnergyLayers(self) -> ScriptObjectCollection[UniformScanningEnergyLayer]: ...

class UniformScanningEnergyLayer:
    @property
    def RangeShifterSetting(self) -> Optional[int]: ...
    @property
    def FirstScattererLollipops(self) -> ScriptObjectCollection[Lollipop]: ...

class ScanPatternSetup:
    @property
    def ScannedFieldSize(self) -> Tuple[float, ...]: ...
    @property
    def SpotSpacing(self) -> float: ...
    @property
    def SpotWeightEdgeFactor(self) -> float: ...

class RadialScalingDistribution:
    @property
    def RadialScalingValues(self) -> ScriptObjectCollection[RadialScalingValue]: ...

class RadialScalingValue:
    @property
    def Radius(self) -> float: ...
    @property
    def Value(self) -> float: ...

class SpotShapeParameters:
    @property
    def Parameters(self) -> np.ndarray: ...
    @property
    def Type(self) -> Literal['SingleGaussian']: ...

class ScanningProperties:
    @property
    def BeamCurrentLimits(self) -> Tuple[float, ...]: ...
    @property
    def DefaultDynamicRangeForLineScanning(self) -> Optional[float]: ...
    @property
    def DoseRateLimitNominalEnergies(self) -> np.ndarray: ...
    @property
    def DoseRateMaximumLimit(self) -> np.ndarray: ...
    @property
    def DoseRateMinimumLimit(self) -> np.ndarray: ...
    @property
    def GenerateDeliverySequence(self) -> bool: ...
    @property
    def MinMetersetPerEnergyLayer(self) -> float: ...
    @property
    def ModulatedScanModeType(self) -> Optional[Literal['Stationary', 'Leaping', 'Linear', 'Mixed']]: ...
    @property
    def OfflinePenalty(self) -> float: ...
    @property
    def PreferredScanDirection(self) -> Literal['X', 'Y']: ...
    @property
    def ScanMode(self) -> Literal['Modulated', 'ModulatedSpec']: ...
    @property
    def SortEnergyLayersAscending(self) -> bool: ...
    @property
    def SpotDeliveryTimeResolution(self) -> Optional[float]: ...
    @property
    def SpotMetersetLimits(self) -> Tuple[float, ...]: ...
    @property
    def AnisotropicScanSpeedLimits(self) -> ScriptObjectCollection[AnisotropicScanSpeedLimits]: ...
    @property
    def IonArcProperties(self) -> IonArcProperties: ...
    @property
    def IsotropicScanSpeedLimits(self) -> ScriptObjectCollection[IsotropicScanSpeedLimits]: ...
    @property
    def QuasiDiscreteProperties(self) -> QuasiDiscreteProperties: ...
    @property
    def ToshibaIntensityProperties(self) -> ToshibaIntensityProperties: ...

class IsotropicScanSpeedLimits:
    @property
    def Maximum(self) -> float: ...
    @property
    def Minimum(self) -> float: ...
    @property
    def NominalEnergy(self) -> float: ...

class AnisotropicScanSpeedLimits:
    @property
    def MaximumX(self) -> float: ...
    @property
    def MaximumY(self) -> float: ...
    @property
    def NominalEnergy(self) -> float: ...

class ScanSpeed:
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def X(self) -> float: ...
    @property
    def Y(self) -> float: ...

class ToshibaIntensityProperties:
    @property
    def LowerLimitIntensity(self) -> float: ...
    @property
    def UpperLimitIntensity(self) -> float: ...
    @property
    def MaxIntensityComputationParameters(self) -> MaxIntensityComputationParameters: ...

class MaxIntensityComputationParameters:
    @property
    def A1(self) -> float: ...
    @property
    def A2(self) -> float: ...
    @property
    def A3(self) -> float: ...
    @property
    def B1(self) -> float: ...
    @property
    def B2(self) -> float: ...
    @property
    def B3(self) -> float: ...
    @property
    def C1(self) -> float: ...
    @property
    def C2(self) -> float: ...
    @property
    def C3(self) -> float: ...
    @property
    def D1(self) -> float: ...
    @property
    def D2(self) -> float: ...
    @property
    def D3(self) -> float: ...
    @property
    def IrradiationTimeCorrectionFactor(self) -> float: ...
    @property
    def IrradiationTimePerEnergy(self) -> float: ...
    @property
    def SafetyFactor(self) -> float: ...

class HyperscanEnergySelectorSettings:
    @property
    def UnshiftedNominalEnergy(self) -> float: ...
    @property
    def DiscreteEnergiesSource(self) -> ScriptObjectCollection[RangeOption]: ...
    @property
    def ForEnergySelector(self) -> HyperscanEnergySelector: ...
    @property
    def NominalEnergyToPlateConfigurations(self) -> ScriptObjectCollection[HyperscanEnergyToPlateConfiguration]: ...

class HyperscanEnergyToPlateConfiguration:
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def PlateConfiguration(self) -> np.ndarray: ...

class RangeShifter:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def IsocenterToVirtualTrayDistance(self) -> Optional[float]: ...
    @property
    def LateralDimensions(self) -> Optional[Point2[float]]: ...
    @property
    def MountingPosition(self) -> Literal['PatientSide', 'SourceSide', 'DoubleSided', 'Undefined']: ...
    @property
    def Name(self) -> str: ...
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def RangeShifterId(self) -> str: ...
    @property
    def Shape(self) -> Optional[Literal['Cylindrical', 'Rectangular']]: ...
    @property
    def Type(self) -> Literal['Analog', 'Binary', 'Static']: ...
    @property
    def WaterEquivalentThickness(self) -> Optional[float]: ...
    @property
    def Material(self) -> Material: ...

class FirstScatterer:
    @property
    def Description(self) -> str: ...
    @property
    def FirstScattererId(self) -> str: ...
    @property
    def IsocenterToTrayDistance(self) -> float: ...
    @property
    def LateralSpreadingDeviceSetting(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def Type(self) -> Literal['Fixed', 'Lollipops']: ...
    @property
    def Lollipops(self) -> ScriptObjectCollection[Lollipop]: ...
    @property
    def Material(self) -> Material: ...

class Lollipop:
    @property
    def LollipopId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def UpstreamFaceToTrayDistance(self) -> float: ...
    @property
    def UsedForRangeShifting(self) -> bool: ...
    @property
    def WaterEquivalentThickness(self) -> float: ...
    @property
    def Material(self) -> Material: ...

class SecondScatterer:
    @property
    def Description(self) -> str: ...
    @property
    def IsocenterToTrayDistance(self) -> float: ...
    @property
    def LateralSpreadingDeviceSetting(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def SecondScattererId(self) -> str: ...
    @property
    def WaterEquivalentThickness(self) -> float: ...

class Snout:
    @property
    def BlockAndCompensatorTrayPositionMounting(self) -> Literal['AllFixed', 'BlockFixedAndCompensatorDownstream', 'BlockUpstreamAndCompensatorFixed']: ...
    @property
    def BlockCompensatorGap(self) -> Optional[float]: ...
    @property
    def BlockMountingPosition(self) -> Literal['PatientSide', 'SourceSide', 'DoubleSided', 'Undefined']: ...
    @property
    def BlockSupport(self) -> Literal['Optional', 'Required', 'None']: ...
    @property
    def BlockTrayId(self) -> str: ...
    @property
    def CenterPointOfOuterDimension(self) -> Tuple[float, ...]: ...
    @property
    def CompensatorMountingPosition(self) -> Literal['PatientSide', 'SourceSide', 'DoubleSided', 'Undefined']: ...
    @property
    def CompensatorSupport(self) -> Literal['Optional', 'Required', 'None']: ...
    @property
    def DiscretePositions(self) -> np.ndarray: ...
    @property
    def ExportSnoutAsApplicator(self) -> bool: ...
    @property
    def FieldLimitLowerLeft(self) -> Tuple[float, ...]: ...
    @property
    def FieldLimitUpperRight(self) -> Tuple[float, ...]: ...
    @property
    def InnerDimension(self) -> Optional[Point2[float]]: ...
    @property
    def IsIonWedgeSupported(self) -> bool: ...
    @property
    def MlcOpening(self) -> Optional[Point2[float]]: ...
    @property
    def MlcTrayToSnoutDistance(self) -> float: ...
    @property
    def OuterDimension(self) -> Optional[Point2[float]]: ...
    @property
    def PositionEndPoints(self) -> Optional[Point2[float]]: ...
    @property
    def RangeShifterSupported(self) -> bool: ...
    @property
    def Shape(self) -> Literal['Cylindrical', 'Rectangular']: ...
    @property
    def SnoutId(self) -> str: ...
    @property
    def SnoutLabel(self) -> str: ...
    @property
    def SnoutPositionToHyperscanEnergySelectorVirtualTrayDistance(self) -> Optional[float]: ...
    @property
    def SnoutPositionToNozzleExitWindowVirtualTrayDistance(self) -> Optional[float]: ...
    @property
    def SnoutPositionToSnoutTipDistance(self) -> float: ...
    @property
    def SnoutToBlockTrayDistance(self) -> Optional[float]: ...
    @property
    def SnoutToCompensatorVirtualTraydistance(self) -> Optional[float]: ...
    @property
    def SnoutToIonWedgeVirtualTrayDistance(self) -> Optional[float]: ...
    @property
    def SnoutToRangeShifterVirtualTrayDistance(self) -> float: ...
    @property
    def SnoutType(self) -> Literal['Fixed', 'Discrete', 'Continuous']: ...

class BlockConstraints:
    @property
    def MaxApertureRadius(self) -> float: ...
    @property
    def OuterDimension(self) -> Optional[Point2[float]]: ...
    @property
    def Shape(self) -> Literal['Cylindrical', 'Rectangular']: ...
    @property
    def SupportedBlockTypes(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedDivergences(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedMillingToolDiameters(self) -> np.ndarray: ...
    @property
    def SupportedThicknesses(self) -> np.ndarray: ...
    @property
    def SupportedMaterials(self) -> ScriptObjectCollection[Material]: ...
    @property
    def SupportedMillingTools(self) -> ScriptObjectCollection[MillingTool]: ...

class MillingTool:
    @property
    def Diameter(self) -> float: ...
    @property
    def MaximumDrillDepth(self) -> float: ...
    @property
    def Name(self) -> str: ...

class CompensatorConstraints:
    @property
    def DefaultMaxCompensatorThickness(self) -> float: ...
    @property
    def ManufacturingMethod(self) -> Literal['DrillingRegularQuadratic', 'DrillingHexagonal']: ...
    @property
    def MaxCompensatorThickness(self) -> float: ...
    @property
    def MinCompensatorThickness(self) -> float: ...
    @property
    def OuterDimension(self) -> Optional[Point2[float]]: ...
    @property
    def Shape(self) -> Literal['Cylindrical', 'Rectangular']: ...
    @property
    def SupportedMillingToolDiameters(self) -> np.ndarray: ...
    @property
    def SupportedMaterials(self) -> ScriptObjectCollection[Material]: ...

class ScanPatternConstraints:
    @property
    def SupportedScanModulationTypes(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SupportedScanRasterPatterns(self) -> ScriptObjectCollection[Any]: ...

class SynchrotronDeliveryParameters:
    @property
    def MeasuredIntensityDegradation(self) -> np.ndarray: ...
    @property
    def ParticlesPerSpill(self) -> float: ...
    @property
    def SpillLength(self) -> float: ...
    @property
    def SynchrotronDegraderValue(self) -> np.ndarray: ...

class LateralSpreadingDevice:
    @property
    def IsocenterToLateralSpreadingDeviceDistance(self) -> float: ...
    @property
    def LateralSpreadingDeviceSetting(self) -> str: ...
    @property
    def LateralSpreadingDeviceWaterEquivalentThickness(self) -> float: ...
    @property
    def Name(self) -> str: ...

class NominalSpotSize:
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def SpotSize(self) -> float: ...

class HyperscanEnergySelector:
    @property
    def PlateSequence(self) -> ScriptObjectCollection[HyperscanEnergySelectorPlate]: ...

class HyperscanEnergySelectorPlate:
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def ReferencePositionToPlateTrayDistance(self) -> float: ...
    @property
    def Material(self) -> Material: ...

class NozzleExitWindow:
    @property
    def MountingPosition(self) -> Literal['PatientSide', 'SourceSide', 'DoubleSided', 'Undefined']: ...
    @property
    def PhysicalThickness(self) -> float: ...
    @property
    def Material(self) -> Material: ...

class ApplicatorWithInsertSettings:
    @property
    def CalibrationInsert(self) -> CalibrationInsert: ...
    @property
    def CollimatorPositions(self) -> FixedCollimatorPositionProperties: ...

class CalibrationInsert:
    @property
    def CalibrationInsertSizeX(self) -> float: ...
    @property
    def CalibrationInsertSizeY(self) -> float: ...
    @property
    def IsCalibrationInsertCircular(self) -> bool: ...
    @property
    def MaterialName(self) -> str: ...
    @property
    def Thickness(self) -> float: ...

class EnergySpectrumOptimization:
    @property
    def MeasurementDepth(self) -> float: ...
    @property
    def RelativePhotonWeight(self) -> float: ...

class BlockTrayDevice:
    @property
    def BlockTrayId(self) -> str: ...

class LinacDicomSettings:
    @property
    def DefaultExportApplicatorTypeIsStereotacticForPhotons(self) -> bool: ...
    @property
    def ElectronApplicatorsExportNameForApplicatorID(self) -> str: ...
    @property
    def ExportDoseRateForEachControlPointForVmatAndConformalArc(self) -> bool: ...
    @property
    def ExportGeneralAccessorySequenceForElectrons(self) -> bool: ...
    @property
    def ExportJawsAsNominalApplicatorSizeForElectrons(self) -> bool: ...
    @property
    def ExportReferencedReferenceImageSequenceForBeams(self) -> bool: ...
    @property
    def ExportSymmetricalJawPositionsAsXY(self) -> bool: ...
    @property
    def ExportTableTopDisplacement(self) -> bool: ...
    @property
    def ExportWithoutLeafPositionsForElectrons(self) -> bool: ...
    @property
    def OmitFullyRetractedMlcFromExportForCones(self) -> bool: ...
    @property
    def VirtualJawFixedPosition(self) -> float: ...
    @property
    def VirtualJawPositioning(self) -> Literal['None', 'PerSegment', 'PerBeam', 'Fixed']: ...
    @property
    def HighDoseTechniqueTypeSettings(self) -> HighDoseTechniqueTypeSettings: ...

class HighDoseTechniqueTypeSettings:
    @property
    def MaximumBeamMUForExport(self) -> Optional[int]: ...
    @property
    def SrsThresholdForDmlcBeam(self) -> Optional[int]: ...
    @property
    def SrsThresholdForDynamicArcBeamWithConstantSegmentWeights(self) -> Optional[int]: ...
    @property
    def SrsThresholdForDynamicArcBeamWithVariableSegmentWeights(self) -> Optional[int]: ...
    @property
    def SrsThresholdForStaticArcBeam(self) -> Optional[int]: ...
    @property
    def SrsThresholdForStaticBeamWithMultipleSegments(self) -> Optional[int]: ...
    @property
    def SrsThresholdForStaticBeamWithOneSegment(self) -> Optional[int]: ...

class JawRoundingSettings:
    @property
    def LeftRightJawRoundingStrategy(self) -> Literal['RoundToClosest', 'MoveOutOfField']: ...
    @property
    def NumberOfDecimals(self) -> int: ...
    @property
    def TopBottomJawRoundingStrategy(self) -> Literal['RoundToClosest', 'MoveOutOfField']: ...

class GimbalProperties:
    @property
    def SupportedGimbalPanAngles(self) -> Tuple[float, ...]: ...
    @property
    def SupportedGimbalTiltAngles(self) -> Tuple[float, ...]: ...

class JawPenumbraFilter:
    @property
    def JawPosition(self) -> float: ...
    @property
    def JawType(self) -> Literal['Front', 'Back']: ...
    @property
    def LongitudinalPositions(self) -> np.ndarray: ...
    @property
    def Penumbra(self) -> np.ndarray: ...

class MlcLeafFilters:
    @property
    def BothClosed(self) -> MlcFilter: ...
    @property
    def LeftClosed(self) -> MlcFilter: ...
    @property
    def RightClosed(self) -> MlcFilter: ...

class MlcFilter:
    @property
    def PenumbraValue(self) -> np.ndarray: ...
    @property
    def Position(self) -> np.ndarray: ...

class JawConversion:
    @property
    def BackFieldEdge(self) -> float: ...
    @property
    def BackPosition(self) -> float: ...
    @property
    def FrontFieldEdge(self) -> float: ...
    @property
    def FrontPosition(self) -> float: ...

class JawField:
    @property
    def JawFluenceOutputFactor(self) -> float: ...
    @property
    def Width(self) -> float: ...

class TransverseDistribution:
    @property
    def OffAxisPositions(self) -> np.ndarray: ...
    @property
    def Values(self) -> np.ndarray: ...

class LeafLatency:
    @property
    def Offset(self) -> float: ...
    @property
    def ProjectionTime(self) -> float: ...
    @property
    def Slope(self) -> float: ...

class XRayIrradiatorBeamQuality:
    @property
    def Label(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def XRayIrradiatorBeamModel(self) -> XRayIrradiatorBeamModel: ...
    @property
    def XRayIrradiatorDosimetryData(self) -> XRayIrradiatorDosimetryData: ...

class XRayIrradiatorDosimetryData:
    @property
    def OutputFactorDepth(self) -> float: ...
    @property
    def CalibrationPoint(self) -> CalibrationPoint: ...
    @property
    def ConeFactors(self) -> ScriptObjectCollection[ConeFactor]: ...
    @property
    def MeasuredDoseCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def MissingOutputFactorFields(self) -> ScriptObjectCollection[OutputFactor]: ...
    @property
    def NormalizedDoseCurves(self) -> ScriptObjectCollection[NormalizedDoseCurve]: ...
    @property
    def OutputFactors(self) -> ScriptObjectCollection[OutputFactor]: ...

class XRayIrradiatorBeamModel:
    @property
    def ForDoseAlgorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @property
    def Calibration(self) -> XRayTubeCalibration: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def ConeCorrections(self) -> ScriptObjectCollection[ConeCorrection]: ...
    @property
    def EnergySpectrum(self) -> PhotonEnergySpectrum: ...
    @property
    def OutputFactorCorrections(self) -> OutputFactorCorrections: ...
    @property
    def SmallAnimalXRayIrradiator(self) -> SmallAnimalXRayIrradiator: ...
    @property
    def Source(self) -> XRayIrradiatorSource: ...
    @property
    def XJaws(self) -> Collimator: ...
    @property
    def YJaws(self) -> Collimator: ...

class XRayTubeCalibration:
    @property
    def AbsoluteCalibration(self) -> float: ...
    @property
    def XRayTubeProperties(self) -> ScriptObjectCollection[XRayTubeProperties]: ...

class XRayTubeProperties:
    @property
    def HalfRiseTime(self) -> float: ...
    @property
    def SteadyDoseRate(self) -> float: ...
    @property
    def TubeCurrent(self) -> float: ...

class XRayIrradiatorSource:
    @property
    def Shape(self) -> Literal['Gaussian', 'Rectangular', 'Elliptical']: ...
    @property
    def XOffset(self) -> float: ...
    @property
    def XWidth(self) -> float: ...
    @property
    def YOffset(self) -> float: ...
    @property
    def YWidth(self) -> float: ...

class ReferenceFieldSetup:
    @property
    def JawFieldSize(self) -> Optional[Point2[float]]: ...
    @property
    def XRayIrradiatorFixedCone(self) -> XRayIrradiatorFixedCone: ...
