from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.dose import DoseGrid, DoseGridRoi, DoseValues
    from raystation.v2025.machine_db_types import ModificationInfo
    from raystation.v2025.patient_db_types import DensityDistribution, EqdParameters, EqdRecoveryCorrectionParameters, PerturbedDoseProperties, VersioningStatus



class MachineLearningDose:
    @property
    def ModelMetaData(self) -> str: ...
    @property
    def ModelSettings(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def TimeOfGeneration(self) -> str: ...
    @property
    def DoseValues(self) -> DoseValues: ...
    @DoseValues.setter
    def DoseValues(self, value: DoseValues) -> None: ...
    @property
    def EqdParameters(self) -> EqdParameters: ...
    @EqdParameters.setter
    def EqdParameters(self, value: EqdParameters) -> None: ...
    @property
    def EqdRecoveryCorrectionParameters(self) -> EqdRecoveryCorrectionParameters: ...
    @EqdRecoveryCorrectionParameters.setter
    def EqdRecoveryCorrectionParameters(self, value: EqdRecoveryCorrectionParameters) -> None: ...
    @property
    def InDoseGrid(self) -> DoseGrid: ...
    @InDoseGrid.setter
    def InDoseGrid(self, value: DoseGrid) -> None: ...
    @property
    def MachineLearningModelParameters(self) -> MachineLearningModelParameters: ...
    @MachineLearningModelParameters.setter
    def MachineLearningModelParameters(self, value: MachineLearningModelParameters) -> None: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    @ModificationInfo.setter
    def ModificationInfo(self, value: ModificationInfo) -> None: ...
    @property
    def OnDensity(self) -> DensityDistribution: ...
    @OnDensity.setter
    def OnDensity(self, value: DensityDistribution) -> None: ...
    @property
    def PerturbedDoseProperties(self) -> PerturbedDoseProperties: ...
    @PerturbedDoseProperties.setter
    def PerturbedDoseProperties(self, value: PerturbedDoseProperties) -> None: ...
    @property
    def VersioningStatus(self) -> VersioningStatus: ...
    @VersioningStatus.setter
    def VersioningStatus(self, value: VersioningStatus) -> None: ...
    def DeleteEvaluationDose(self) -> None:
        """Deletes the dose distribution if it is an evaluation dose."""
        ...
    def GetCoordinateOfMaxDose(self) -> Tuple[float, ...]:
        """Get the coordinate corresponding to the max dose."""
        ...
    def GetDoseAtRelativeVolumes(self, RoiName: str, RelativeVolumes: List[float]) -> np.ndarray:
        """Method for retrieving DVH points."""
        ...
    def GetDoseGridRoi(self, RoiName: str) -> DoseGridRoi:
        """Gets the dose grid representation of a specific ROI for the dose grid of the dose distribution."""
        ...
    def GetDoseStatistic(self, RoiName: str, DoseType: str) -> float:
        """Method for retrieving dose statistics."""
        ...
    def GetRelativeVolumeAtDoseValues(self, RoiName: str, DoseValues: List[float]) -> np.ndarray:
        """Method for retrieving DVH points."""
        ...
    def GetTransformedAndResampledDoseValues(self, DoseGrid: DoseGrid) -> np.ndarray:
        """Resamples the dose distribution to the given dose grid."""
        ...
    def HasClinicalDose(self) -> bool:
        """Indicates if there is a dose that is considered clinically relevant for treatment."""
        ...
    def InterpolateDoseInPoint(self, Point: Any, PointFrameOfReference: str) -> float:
        """Returns interpolated dose value in point."""
        ...
    def InterpolateDoseInPoints(self, Points: List[Any], PointsFrameOfReference: str) -> np.ndarray:
        """Returns an array of interpolated dose values in the given array of points."""
        ...
    def SetDoseValues(self, Dose: np.ndarray, CalculationInfo: str = ..., DoseAlgorithm: str = ..., DoseUncertainties: np.ndarray = ..., ParticleEnergySpectraDose: np.ndarray = ..., DoseAveragedLet: np.ndarray = ..., DoseAveragedAlpha: np.ndarray = ..., DoseAveragedSqrtBeta: np.ndarray = ...) -> None:
        """Method for setting dose data in a dose distribution. Can also be used to set dose-averaged LET data in a corresponding distribution. The length of the provided arrays must match the number of voxels in the dose grid. The elements are iterated in X first, then Y and Z. If the dose distribution is a fraction dose from a BeamSet that belongs to a plan then the total dose of the plan is automatically updated. DoseAlgorithm will by default be set as 'Undefined'."""
        ...
    def SetWeightedDose(self, PlanNames: List[Any], Weights: np.ndarray) -> None:
        """Sets the dose to a weighted sum of the"""
        ...
    def UpdateDoseGridStructures(self) -> None:
        """Computes uncomputed RoiVolumeDistributions. If the current DoseGridStructures of the DoseDistribution contains DoseGridRois computed with an old algorithm version, the DoseGridStructures will be replaced with a new version."""
        ...

class MachineLearningModelParameters:
    @property
    def ModelId(self) -> str: ...
    @property
    def ModelVersion(self) -> int: ...
    @property
    def Parameters(self) -> Dict[str, Any]: ...

class FileImportLog:
    @property
    def FileCheckSum(self) -> np.ndarray: ...
    @property
    def FileName(self) -> str: ...
    @property
    def Time(self) -> str: ...

class DeepLearningSegmentationModel:
    @property
    def ApprovalDate(self) -> Optional[str]: ...
    @property
    def Approved(self) -> bool: ...
    @property
    def ApprovedBy(self) -> str: ...
    @property
    def AvailableForUsage(self) -> bool: ...
    @property
    def Description(self) -> str: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def MetaData(self) -> np.ndarray: ...
    @property
    def ModelDataChecksum(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Origin(self) -> str: ...
    @property
    def RuntimeFramework(self) -> Literal['TensorRT', 'TensorFlow']: ...
    @property
    def ScriptingEnvironmentId(self) -> str: ...
    @property
    def Settings(self) -> np.ndarray: ...
    @property
    def TrainingOrigin(self) -> Literal['NotSpecified', 'RaySearch', 'MDACC', 'AblationMDACC']: ...
    @property
    def Type(self) -> Literal['AutomaticPlanning', 'OARSegmentation', 'Other']: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def InitializationData(self) -> InitializationData: ...
    @property
    def ModelFiles(self) -> ScriptObjectCollection[ModelFile]: ...
    @property
    def Scripts(self) -> ScriptObjectCollection[MachineLearningScript]: ...
    def MachineLearningModelBackup(self, FileName: str) -> None:
        """Make a backup of a machine learning model"""
        ...
    def Unload(self) -> None:
        """Unloads the machine learning model and releases locks."""
        ...

class ModelFile:
    @property
    def FileData(self) -> np.ndarray: ...
    @property
    def RelativePath(self) -> str: ...

class MachineLearningScript:
    @property
    def FileName(self) -> str: ...
    @property
    def Script(self) -> np.ndarray: ...

class InitializationData:
    @property
    def Description(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Images(self) -> ScriptObjectCollection[VoxelObject]: ...
    @property
    def VoxelStructureSets(self) -> ScriptObjectCollection[VoxelStructureSet]: ...

class VoxelObject:
    @property
    def Corner(self) -> Tuple[float, ...]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Size(self) -> Tuple[float, ...]: ...
    @property
    def VoxelData(self) -> np.ndarray: ...
    @property
    def VoxelDataType(self) -> Literal['Unknown', 'Int8', 'Uint8', 'Int16', 'Uint16', 'Float', 'Double']: ...
    @property
    def VoxelSize(self) -> Tuple[float, ...]: ...

class VoxelStructureSet:
    @property
    def Name(self) -> str: ...
    @property
    def PatientOutlineStructure(self) -> VoxelObject: ...
    @property
    def Structures(self) -> ScriptObjectCollection[VoxelObject]: ...

class MachineLearningDB:
    def GetRoisForSegmentation(self, ModelName: str) -> List[str]:
        """Lists the names of the ROIs for segmentation included in a machine learning model"""
        ...
    def LoadMachineLearningModel(self, modelName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> MachineLearningModel:
        """Loads a machine learning model from the database and locks it for reading or writing. When the model is not used anymore, the Unload method of the model can be called to release the lock and free memory."""
        ...
    def QueryMachineLearningModelInfo(self) -> List[Any]:
        """Returns info on all machine learning models in the machine learning database."""
        ...

class MachineLearningModel:
    @property
    def ApprovalDate(self) -> Optional[str]: ...
    @property
    def Approved(self) -> bool: ...
    @property
    def ApprovedBy(self) -> str: ...
    @property
    def AvailableForUsage(self) -> bool: ...
    @property
    def Description(self) -> str: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def MetaData(self) -> np.ndarray: ...
    @property
    def ModelDataChecksum(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Origin(self) -> str: ...
    @property
    def RuntimeFramework(self) -> Literal['TensorRT', 'TensorFlow']: ...
    @property
    def ScriptingEnvironmentId(self) -> str: ...
    @property
    def Settings(self) -> np.ndarray: ...
    @property
    def TrainingOrigin(self) -> Literal['NotSpecified', 'RaySearch', 'MDACC', 'AblationMDACC']: ...
    @property
    def Type(self) -> Literal['AutomaticPlanning', 'OARSegmentation', 'Other']: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @property
    def ModelFiles(self) -> ScriptObjectCollection[ModelFile]: ...
    @property
    def Scripts(self) -> ScriptObjectCollection[MachineLearningScript]: ...
    def MachineLearningModelBackup(self, FileName: str) -> None:
        """Make a backup of a machine learning model"""
        ...
    def Unload(self) -> None:
        """Unloads the machine learning model and releases locks."""
        ...
