from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import BeamFractionDose
    from raystation.v2025.beam_set import RadiationSet
    from raystation.v2025.brachy import BrachyTreatmentSetupOptimizationSettings
    from raystation.v2025.dose import DoseBasedRoiFunction, DoseCalculationProperties, DoseMimicParameters
    from raystation.v2025.ml import MachineLearningDose
    from raystation.v2025.patient_db_types import AutoOptimizationSettings, AuxiliaryDataInDoseGrid, CompositeDose, CompositeFunction, EQD2Dose, FineTuningOptimizationSettings, FluenceCalculationProperties, FractionDose, MappedDose, PencilBeamScanningProperties, PredictedMachineLearningDose, ProgressOfOptimization, RegionOfInterest, RobustnessParameters, TreatmentSetupOptimizationSettings
    from raystation.v2025.template import TemplateTreatmentOptimization



class OptimizationPhase:
    @property
    def OptimizationRuns(self) -> ScriptObjectCollection[OptimizationRunParameters]: ...
    @OptimizationRuns.setter
    def OptimizationRuns(self, value: List[OptimizationRunParameters]) -> None: ...
    def AddOptimizationRun(self, MaxNumberOfIterations: int = ..., OptimalityTolerance: float = ..., IterationsInPreparationsPhase: int = ..., ComputeFinalDose: bool = ..., ComputeIntermediateDose: bool = ..., NumberOfIterationsBeforeSpotWeightBounding: int = ...) -> OptimizationRunParameters:
        """Adds an optimization run to an optimization phase."""
        ...

class OptimizationRunParameters:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @ComputeFinalDose.setter
    def ComputeFinalDose(self, value: bool) -> None: ...
    @property
    def ComputeIntermediateDose(self) -> bool: ...
    @ComputeIntermediateDose.setter
    def ComputeIntermediateDose(self, value: bool) -> None: ...
    @property
    def IterationsInPreparationsPhase(self) -> int: ...
    @IterationsInPreparationsPhase.setter
    def IterationsInPreparationsPhase(self, value: int) -> None: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @MaxNumberOfIterations.setter
    def MaxNumberOfIterations(self, value: int) -> None: ...
    @property
    def NumberOfIterationsBeforeSpotWeightBounding(self) -> int: ...
    @NumberOfIterationsBeforeSpotWeightBounding.setter
    def NumberOfIterationsBeforeSpotWeightBounding(self, value: int) -> None: ...
    @property
    def OptimalityTolerance(self) -> float: ...
    @OptimalityTolerance.setter
    def OptimalityTolerance(self, value: float) -> None: ...
    def DeleteOptimizationRun(self) -> None:
        """Deletes the optimization run."""
        ...

class OptimizationParameters:
    @property
    def TumorOverlapFraction(self) -> float: ...
    @TumorOverlapFraction.setter
    def TumorOverlapFraction(self, value: float) -> None: ...
    @property
    def UseTumorOverlapFraction(self) -> bool: ...
    @UseTumorOverlapFraction.setter
    def UseTumorOverlapFraction(self, value: bool) -> None: ...
    @property
    def Algorithm(self) -> OptimizationAlgorithmProperties: ...
    @Algorithm.setter
    def Algorithm(self, value: OptimizationAlgorithmProperties) -> None: ...
    @property
    def BrachyTreatmentSetupSettings(self) -> ScriptObjectCollection[BrachyTreatmentSetupOptimizationSettings]: ...
    @BrachyTreatmentSetupSettings.setter
    def BrachyTreatmentSetupSettings(self, value: List[BrachyTreatmentSetupOptimizationSettings]) -> None: ...
    @property
    def DoseCalculation(self) -> DoseCalculationProperties: ...
    @DoseCalculation.setter
    def DoseCalculation(self, value: DoseCalculationProperties) -> None: ...
    @property
    def DoseMimicParameters(self) -> DoseMimicParameters: ...
    @DoseMimicParameters.setter
    def DoseMimicParameters(self, value: DoseMimicParameters) -> None: ...
    @property
    def FineTuningOptimizationSettings(self) -> FineTuningOptimizationSettings: ...
    @FineTuningOptimizationSettings.setter
    def FineTuningOptimizationSettings(self, value: FineTuningOptimizationSettings) -> None: ...
    @property
    def FluenceCalculation(self) -> FluenceCalculationProperties: ...
    @FluenceCalculation.setter
    def FluenceCalculation(self, value: FluenceCalculationProperties) -> None: ...
    @property
    def PencilBeamScanningProperties(self) -> PencilBeamScanningProperties: ...
    @PencilBeamScanningProperties.setter
    def PencilBeamScanningProperties(self, value: PencilBeamScanningProperties) -> None: ...
    @property
    def RobustnessParameters(self) -> RobustnessParameters: ...
    @RobustnessParameters.setter
    def RobustnessParameters(self, value: RobustnessParameters) -> None: ...
    @property
    def TreatmentSetupSettings(self) -> ScriptObjectCollection[TreatmentSetupOptimizationSettings]: ...
    @TreatmentSetupSettings.setter
    def TreatmentSetupSettings(self, value: List[TreatmentSetupOptimizationSettings]) -> None: ...
    def SaveRobustnessParameters(self, PositionUncertaintyAnterior: float = ..., PositionUncertaintyPosterior: float = ..., PositionUncertaintySuperior: float = ..., PositionUncertaintyInferior: float = ..., PositionUncertaintyLeft: float = ..., PositionUncertaintyRight: float = ..., DensityUncertainty: float = ..., UseReducedSetOfDensityShifts: bool = ..., PositionUncertaintySetting: Literal['Universal', 'IndependentBeams', 'IndependentIsocenters', 'None'] = ..., IndependentLeftRight: bool = ..., IndependentAnteriorPosterior: bool = ..., IndependentSuperiorInferior: bool = ..., ComputeExactScenarioDoses: bool = ..., NamesOfNonPlanningExaminations: List[str] = ..., PatientGeometryUncertaintyType: Literal['PerTreatmentCourse', 'PerFraction', 'WithinFraction'] = ..., PositionUncertaintyType: Literal['PerTreatmentCourse', 'PerFraction'] = ..., TreatmentCourseScenariosFactor: int = ..., PositionUncertaintyList: List[Any] = ..., PositionUncertaintyFormation: Literal['AxesEndPoints', 'DiagonalEndPoints', 'AxesAndDiagonalEndPoints', 'UserDefined', 'Automatic'] = ..., RobustMethodPerTreatmentCourse: Literal['WeightedPowerMean', 'VoxelwiseWorstCase'] = ...) -> None:
        """Save robustness parameters."""
        ...

class OptimizationAlgorithmProperties:
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @MaxNumberOfIterations.setter
    def MaxNumberOfIterations(self, value: int) -> None: ...
    @property
    def OptimalityTolerance(self) -> float: ...
    @OptimalityTolerance.setter
    def OptimalityTolerance(self, value: float) -> None: ...

class OptimizationProblem:
    @property
    def AutoOptimizationSettings(self) -> AutoOptimizationSettings: ...
    @AutoOptimizationSettings.setter
    def AutoOptimizationSettings(self, value: AutoOptimizationSettings) -> None: ...
    @property
    def Constraints(self) -> List[Union[CompositeFunction, DoseBasedRoiFunction]]: ...
    @Constraints.setter
    def Constraints(self, value: List[Union[CompositeFunction, DoseBasedRoiFunction]]) -> None: ...
    @property
    def Objective(self) -> Union[CompositeFunction, DoseBasedRoiFunction]: ...
    @Objective.setter
    def Objective(self, value: Union[CompositeFunction, DoseBasedRoiFunction]) -> None: ...
    @property
    def OptimizationParameters(self) -> OptimizationParameters: ...
    @OptimizationParameters.setter
    def OptimizationParameters(self, value: OptimizationParameters) -> None: ...
    @property
    def OptimizedBeamSets(self) -> ScriptObjectCollection[RadiationSet]: ...
    @property
    def ProgressOfOptimization(self) -> ProgressOfOptimization: ...
    @ProgressOfOptimization.setter
    def ProgressOfOptimization(self, value: ProgressOfOptimization) -> None: ...
    def AddBiologicalOptimizationFunction(self, RoiName: str, EndpointOrTumorStage: str, IsConstraint: bool = ..., Bound: Optional[float] = ..., ModelType: str = ..., ResponseFunctionType: Literal['Tcp', 'Ntcp'] = ..., UseRepair: bool = ..., UseRepopulation: bool = ...) -> DoseBasedRoiFunction:
        """Adds a biological optimization function."""
        ...
    def AddOnesidedUniformRefDoseFunction(self, RoiName: str, ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, WeightForMinDose: float, WeightForMaxDose: float, VolumeThreshold: float, IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add a onesided uniform reference dose optimization function to the OptimizationProblem."""
        ...
    def AddOptimizationFunction(self, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'] = ..., RoiName: str = ..., IsConstraint: bool = ..., RestrictAllBeamsIndividually: bool = ..., RestrictToBeams: List[str] = ..., IsRobust: bool = ..., RestrictToBeamSet: str = ..., UseRbeDose: bool = ..., UseEqd: bool = ...) -> DoseBasedRoiFunction:
        """Creates and adds an objective constituent or a constraint."""
        ...
    def AddReferenceIsoDoseVolumeFunction(self, RoiName: str, ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, Weight: float, IsoDoseVolumeWeights: List[float], ThresholdDoses: List[float], IsoDoseVolumeFunctions: List[str], VoxelWeights: List[float], IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add an onesided uniform reference DVH optimization function to the OptimizationProblem."""
        ...
    def AddReferenceOptimizationFunction(self, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'] = ..., ReferenceDoseDistribution: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose] = ..., RoiName: str = ..., IsConstraint: bool = ..., RestrictAllBeamsIndividually: bool = ..., RestrictToBeams: List[str] = ..., IsRobust: bool = ..., RestrictToBeamSet: str = ..., UseRbeDose: bool = ..., UseEqd: bool = ...) -> DoseBasedRoiFunction:
        """Creates and adds a reference optimization function"""
        ...
    def AddWeightedOptimizationFunction(self, RoiName: str, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'], ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, Weight: float, IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add a weighted optimization function to the OptimizationProblem."""
        ...
    def ApplyOptimizationTemplate(self, Template: TemplateTreatmentOptimization, AssociatedRoisAndPois: Dict[str, Any] = ..., ReplaceExistingOptimizationFunctions: bool = ...) -> None:
        """Copies optimization functions from a template."""
        ...
    def ClearConstituentFunctions(self) -> None:
        """Remove all constituent functions from the problem."""
        ...
    def EvaluateOptimizationFunctions(self) -> None:
        """Evaluates the optimization functions of this optimization problem"""
        ...
    def PersistFineTuningOptimizationSettings(self, ClinicalGoals: List[DoseBasedRoiFunction], RoiList: List[RegionOfInterest], OptimalityTolerance: float, MaxNumberOfIterations: int, ComputeIntermediateDose: bool, ComputeFinalDose: bool, ClinicalGoalRelativeImportance: float, SpatialConservationObjectiveWeight: float, ClinicalGoalShift: float) -> None:
        """Saves settings to the fine-tuning optimization problem."""
        ...
    def ResetOptimization(self) -> None:
        """Resets the optimization."""
        ...
    def RunFineTuningOptimization(self, ClinicalGoalsToExplore: List[DoseBasedRoiFunction] = ..., ConservationRois: List[RegionOfInterest] = ..., OptimizationSpecs: List[Any] = ...) -> None:
        """Action performing fine-tuning with respect to clinical goals."""
        ...
    def RunOptimization(self) -> None:
        """Runs an optimization."""
        ...
    def RunReduceOARDoseOptimization(self, UseVoxelBasedMimickingForTargets: bool = ..., UseVoxelBasedMimickingForOrgansAtRisk: bool = ..., OrgansAtRiskToImprove: List[Any] = ..., TargetsToMaintain: List[Any] = ..., OrgansAtRiskToMaintain: List[Any] = ...) -> None:
        """Runs a reduce organ-at-risk optimization."""
        ...
    def SetAutoOptimizationSettings(self, AutoPlanningStrategyName: str, PlanningIntentionName: str, RoiNameMatches: Dict[str, Any], MachineLearningModelId: Optional[str] = ..., AutoPlanningStrategyType: Literal['MachineLearningPlanning', 'ECHO'] = ...) -> None:
        """Sets auto-optimization settings for the optimization problem. Existing settings will be over-written, and all objectives and constraints will be cleared."""
        ...
    def SingleOptimization(self) -> None:
        """Do not use this action for new scripts. It may not be available in future versions."""
        ...
