from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam_set import TreatmentSetupIncludingRadiationSet
    from raystation.v2025.brachy import BrachyApplicationSetup, BrachyApplicatorModel, BrachyChannel
    from raystation.v2025.case import TreatmentCaseIncludingStudy
    from raystation.v2025.clearance import ClearanceCheck, CollisionProperties
    from raystation.v2025.machine_db_types import Material, ModificationInfo
    from raystation.v2025.patient_db_types import BaseToleranceTable, ContractInformation, DeformableStructureRegistration, Examination, ExaminationStructureSet, ExaminationStructureSetReference, HybridAlgorithmSettingsData, LogEntry, LoiGeometry, MotionSynchronization, PoiGeometry, RegionOfInterest, RegionOfInterestAssociationPair, SurfaceInfo, TpsDefinedFixationDevice, TreatmentSetupPosition
    from raystation.v2025.roi import RoiMaterial, RoiVisualizationSettings, StructureRegistrationGroup
    from raystation.v2025.setup import SetupBeam
    from raystation.v2025.template import TemplatePatientModel



class Patient:
    @property
    def Comments(self) -> str: ...
    @Comments.setter
    def Comments(self, value: str) -> None: ...
    @property
    def DateOfBirth(self) -> Optional[str]: ...
    @property
    def Gender(self) -> Literal['Female', 'Male', 'Other', 'Unknown']: ...
    @property
    def Name(self) -> str: ...
    @property
    def PatientID(self) -> str: ...
    @property
    def Cases(self) -> ScriptObjectCollection[TreatmentCaseIncludingStudy]: ...
    @Cases.setter
    def Cases(self, value: List[TreatmentCaseIncludingStudy]) -> None: ...
    @property
    def ContractInformation(self) -> ContractInformation: ...
    @property
    def ImportLogs(self) -> ScriptObjectCollection[LogEntry]: ...
    @ImportLogs.setter
    def ImportLogs(self, value: List[LogEntry]) -> None: ...
    @property
    def ModificationInfo(self) -> ModificationInfo: ...
    def CalculateGammaForFractionDose(self, EvaluationPlan: str, ReferencePlan: str, DistanceCriteria: float, DoseCriteria: float, SampleDistance: float, NumberOfRefineIterations: int, RefineLayers: int, Limit: float) -> np.ndarray:
        """Method to calculate gamma using global maximum dose. It can be used for cases when the dose grid of the evaluated plan is the same as for the reference plan. The method requires that for each plan there is only one study, one treatment case, one treatment plan group and one beam set. Gamma is calculated using the fraction dose."""
        ...
    def CalculateGammaForFractionDoseII(self, Case: str, EvaluationPlan: str, EvaluationBeamSet: str, ReferencePlan: str, ReferenceBeamSet: str, DistanceCriteria: float, DoseCriteria: float, SampleDistance: float, NumberOfRefineIterations: int, RefineLayers: int, Limit: float) -> np.ndarray:
        """Method to calculate gamma using global maximum dose. It can be used for cases when the dose grid of the evaluated plan is the same as for the reference plan. The method requires that for each case there is only one treatment plan group. Gamma is calculated using the fraction dose."""
        ...
    def EditRoiLineWidthVisualization(self, RoiLineWidth: float) -> None:
        """Specifies the ROI line width."""
        ...
    def EditShowDoseGridVisualization(self, ShowDoseGrid: bool) -> None:
        """Setting the visualization of the dose grid."""
        ...
    def EditShowDoseVisualization(self, ShowDose: bool, ShowInterpolated: bool, ShowIsolines: bool, ShowColorWash: bool, ColorWashTransparency: float) -> None:
        """Setting dose related visualization settings."""
        ...
    def GetAllSurfaceScanInfos(self) -> List[SurfaceInfo]:
        """Fetch info about the surface scans available for the patient."""
        ...
    def GetAlphabeticPatientName(self) -> Dict[str, Any]:
        """Gets the alphabetic representation of the patient's name."""
        ...
    def GetIdeographicPatientName(self) -> Dict[str, Any]:
        """Gets the ideographic representation of the patient's name."""
        ...
    def GetImagingSystemsNames(self) -> List[Any]:
        """Retrieves a list of imaging machines that may be assigned to an image set. Only CT imaging machines will be listed."""
        ...
    def GetPatientUuid(self) -> Optional[str]:
        """Gets the UUID from the Patient"""
        ...
    def GetPhoneticPatientName(self) -> Dict[str, Any]:
        """Gets the phonetic representation of the patient's name."""
        ...
    def GetPoiVisibility(self, PoiName: str) -> bool:
        """Setting if a POI is visible or not."""
        ...
    def GetRoiVisibility(self, RoiName: str) -> bool:
        """Get if an ROI is visible or not."""
        ...
    def ImportDataFromPath(self, Path: str, SeriesOrInstances: List[Any], CaseName: str = ..., ImportFilter: str = ..., AllowMismatchingPatientID: bool = ..., BrachyPlanImportOverrides: Dict[str, Any] = ...) -> str:
        """Imports DICOM data from a folder into this patient."""
        ...
    def ImportDataFromRepository(self, Connection: Dict[str, Any], SeriesOrInstances: List[Any], CaseName: str = ..., ImportFilter: str = ..., AllowMismatchingPatientID: bool = ..., BrachyPlanImportOverrides: Dict[str, Any] = ...) -> str:
        """Imports DICOM data from a repository into this patient."""
        ...
    def ImportDataFromRepositoryByAETitle(self, AETitle: str, SeriesOrInstances: List[Any], CaseName: str = ..., ImportFilter: str = ..., AllowMismatchingPatientID: bool = ...) -> str:
        """Imports DICOM data from a repository into this patient."""
        ...
    def Save(self) -> None:
        """Saves the patient state.."""
        ...
    def SetAlphabeticPatientName(self, Title: str = ..., FirstName: str = ..., MiddleName: str = ..., LastName: str = ..., Suffix: str = ...) -> None:
        """Set the alphabetic representation of the patient name."""
        ...
    def SetContractInformation(self, DateOfTagging: Optional[str] = ..., TaggingDescription: str = ..., AllowedUsagesOfData: List[str] = ..., DistributionType: List[str] = ..., TaggingToolSoftwareVersion: str = ..., DateOfDeletion: Optional[str] = ...) -> None:
        """Sets contract information on a patient."""
        ...
    def SetIdeographicPatientName(self, Title: str = ..., FirstName: str = ..., MiddleName: str = ..., LastName: str = ..., Suffix: str = ...) -> None:
        """Set the ideographic representation of the patient name."""
        ...
    def SetPatientInformation(self, Title: str = ..., FirstName: str = ..., MiddleName: str = ..., LastName: str = ..., Suffix: str = ..., Gender: Literal['Female', 'Male', 'Other', 'Unknown'] = ..., DateOfBirth: Optional[str] = ..., Comment: str = ...) -> None:
        """Sets new patient details including name, gender, date of birth and patient comment."""
        ...
    def SetPhoneticPatientName(self, Title: str = ..., FirstName: str = ..., MiddleName: str = ..., LastName: str = ..., Suffix: str = ...) -> None:
        """Sets the phonetic representation of the patient name."""
        ...
    def SetPoiVisibility(self, PoiName: str, IsVisible: bool) -> None:
        """Setting if a POI is visible or not."""
        ...
    def SetRoiVisibility(self, RoiName: str, IsVisible: bool) -> None:
        """Setting if an ROI is visible or not."""
        ...
    def SetShowDoseGridOutlineVisualization(self) -> None:
        """Setting the dose grid display type: outline."""
        ...
    def SetShowDoseGridVoxelsVisualization(self) -> None:
        """Setting the dose grid display type: voxel."""
        ...

class PatientSetup:
    @property
    def IsocenterType(self) -> Literal['TreatmentIsocenter', 'LocalizationPoint', 'CustomDefined']: ...
    @property
    def UseSetupBeams(self) -> bool: ...
    @UseSetupBeams.setter
    def UseSetupBeams(self, value: bool) -> None: ...
    @property
    def ClearanceCheck(self) -> ClearanceCheck: ...
    @ClearanceCheck.setter
    def ClearanceCheck(self, value: ClearanceCheck) -> None: ...
    @property
    def CollisionProperties(self) -> CollisionProperties: ...
    @CollisionProperties.setter
    def CollisionProperties(self, value: CollisionProperties) -> None: ...
    @property
    def CustomDefinedSetupIsocenters(self) -> ScriptObjectCollection[PatientToBeamMapping]: ...
    @property
    def MotionSynchronization(self) -> MotionSynchronization: ...
    @property
    def OfTreatmentSetup(self) -> TreatmentSetupIncludingRadiationSet: ...
    @OfTreatmentSetup.setter
    def OfTreatmentSetup(self, value: TreatmentSetupIncludingRadiationSet) -> None: ...
    @property
    def PatientSetupDevice(self) -> PatientSetupDevice: ...
    @PatientSetupDevice.setter
    def PatientSetupDevice(self, value: PatientSetupDevice) -> None: ...
    @property
    def PatientSetupTechnique(self) -> PatientSetupTechnique: ...
    @PatientSetupTechnique.setter
    def PatientSetupTechnique(self, value: PatientSetupTechnique) -> None: ...
    @property
    def PatientToBeamMappingFromLocalizationPoint(self) -> PatientToBeamMapping: ...
    @property
    def SetupBeams(self) -> ScriptObjectCollection[SetupBeam]: ...
    @SetupBeams.setter
    def SetupBeams(self, value: List[SetupBeam]) -> None: ...
    @property
    def ToleranceTable(self) -> BaseToleranceTable: ...
    @ToleranceTable.setter
    def ToleranceTable(self, value: BaseToleranceTable) -> None: ...
    @property
    def TpsDefinedFixationDevices(self) -> ScriptObjectCollection[TpsDefinedFixationDevice]: ...
    @TpsDefinedFixationDevices.setter
    def TpsDefinedFixationDevices(self, value: List[TpsDefinedFixationDevice]) -> None: ...
    @property
    def TreatmentSetupPositions(self) -> ScriptObjectCollection[TreatmentSetupPosition]: ...
    @TreatmentSetupPositions.setter
    def TreatmentSetupPositions(self, value: List[TreatmentSetupPosition]) -> None: ...
    def AddTpsDefinedFixationDevice(self, Type: str, Label: str = ..., AccessoryCode: str = ..., Description: str = ...) -> None:
        """Add a TPS defined fixation device to be exported in the"""
        ...

class PatientToBeamMapping:
    @property
    def Position(self) -> Tuple[float, ...]: ...
    @property
    def Annotation(self) -> PatientToBeamMappingAnnotation: ...
    @Annotation.setter
    def Annotation(self, value: PatientToBeamMappingAnnotation) -> None: ...
    def EditIsocenter(self, Name: str, Color: str = ..., Position: Any = ...) -> None:
        """Edits any or all of the following isocenter parameters for the beam."""
        ...

class PatientToBeamMappingAnnotation:
    @property
    def DisplayColor(self) -> str: ...
    @DisplayColor.setter
    def DisplayColor(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...

class PatientSetupDevice:
    @property
    def Type(self) -> Literal['LaserPoint']: ...
    @Type.setter
    def Type(self, value: Literal['LaserPoint']) -> None: ...
    @property
    def SetupReferencePoint(self) -> PoiGeometry: ...
    @SetupReferencePoint.setter
    def SetupReferencePoint(self, value: PoiGeometry) -> None: ...

class PatientSetupTechnique:
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def SetupTechnique(self) -> Literal['Isocentric', 'FixedSSD']: ...
    @SetupTechnique.setter
    def SetupTechnique(self, value: Literal['Isocentric', 'FixedSSD']) -> None: ...

class PatientGeometryUncertaintyParameters:
    @property
    def PatientGeometryUncertaintyType(self) -> Literal['PerTreatmentCourse', 'PerFraction', 'WithinFraction']: ...
    @PatientGeometryUncertaintyType.setter
    def PatientGeometryUncertaintyType(self, value: Literal['PerTreatmentCourse', 'PerFraction', 'WithinFraction']) -> None: ...
    @property
    def DeformableRegistrations(self) -> ScriptObjectCollection[DeformableStructureRegistration]: ...
    @DeformableRegistrations.setter
    def DeformableRegistrations(self, value: List[DeformableStructureRegistration]) -> None: ...
    @property
    def Examinations(self) -> ScriptObjectCollection[Examination]: ...
    @Examinations.setter
    def Examinations(self, value: List[Examination]) -> None: ...

class PatientModel:
    @property
    def BrachyApplicatorModels(self) -> ScriptObjectCollection[BrachyApplicatorModel]: ...
    @BrachyApplicatorModels.setter
    def BrachyApplicatorModels(self, value: List[BrachyApplicatorModel]) -> None: ...
    @property
    def LinesOfInterest(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @LinesOfInterest.setter
    def LinesOfInterest(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def Materials(self) -> ScriptObjectCollection[Material]: ...
    @Materials.setter
    def Materials(self, value: List[Material]) -> None: ...
    @property
    def PointsOfInterest(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @PointsOfInterest.setter
    def PointsOfInterest(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def RegionsOfInterest(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @RegionsOfInterest.setter
    def RegionsOfInterest(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def RoiVisualizationSettings(self) -> ScriptObjectCollection[RoiVisualizationSettings]: ...
    @RoiVisualizationSettings.setter
    def RoiVisualizationSettings(self, value: List[RoiVisualizationSettings]) -> None: ...
    @property
    def StructureRegistrationGroups(self) -> ScriptObjectCollection[StructureRegistrationGroup]: ...
    @StructureRegistrationGroups.setter
    def StructureRegistrationGroups(self, value: List[StructureRegistrationGroup]) -> None: ...
    @property
    def StructureSets(self) -> ScriptObjectCollection[ExaminationStructureSet]: ...
    @StructureSets.setter
    def StructureSets(self, value: List[ExaminationStructureSet]) -> None: ...
    def AdaptMbsMeshes(self, Examination: Examination, RoiNames: List[str], CustomStatistics: Dict[str, Any] = ..., CustomSettings: Dict[str, Any] = ...) -> None:
        """Adapts MBS meshes to the specified examination."""
        ...
    def ApplyAutoBreastAtlas(self, Examination: Examination, StructureTemplateName: str = ..., NumberOfFusionAtlases: int = ...) -> None:
        """Generates atlas based Lung and Heart ROIs."""
        ...
    def CopyGeometries(self, SourceExamination: Examination, TargetExamination: Examination, RoiNames: List[str], PoiNames: List[str], ImageRegistrationName: str, UseAddedRigidRegistrationIfOneExists: bool) -> None:
        """Copies geometries from a source structure set to a target structure set."""
        ...
    def CopyRoiGeometryToExistingRoi(self, ExaminationNames: List[str], SourceRoiName: str, TargetRoiName: str) -> None:
        """Copies a ROI geometry to an existing ROI on the same examination."""
        ...
    def CreateAndRegisterAvatar(self, ExaminationName: str, AvatarDictionary: Dict[str, Any], PatientPosition: str, Height: int, Weight: int, BodyType: str, BodyPosition: str, PatientRoi: str, DiscardRotations: bool, KeepOnlyThePartsOfAvatarOutsideImageStack: bool) -> None:
        """Creates an Avatar that is a set of ROIs containing a head, torso, right and left arm, leg and foot. The ROIs are registered to the chosen body ROI and rescales the Avatar according to the input height and weight."""
        ...
    def CreateBiomechanicalDeformableRegistrationGroup(self, RegistrationGroupName: str, ReferenceExamination: Examination, TargetExaminations: List[Examination], ControllingRois: List[Any], DeformationGridVoxelSize: Any = ..., ExternalRoiName: str = ...) -> None:
        """Creates a deformable registration group with biomechanical deformable registrations for the selected reference examination and target examinations."""
        ...
    def CreateBoundaryConditionsForMorfeus(self, RoiNames: List[str], ReferenceExaminationName: str, TargetExaminationNames: List[str], VoxelRepresentationVoxelSideLength: float, TriangulationEqualEdgeLength: int, TriangulationUseCurvatureAdaptation: bool, TriangulationSmoothingIterations: int, MaxNrOfSmoothingSteps: int) -> Dict[str, Any]:
        """Given ROI geometries with any representation (voxel, contour, triangle mesh) in two, or more, image sets,"""
        ...
    def CreateControllingRoiGeometries(self, ReferenceExaminationName: str, TargetExaminationNames: List[str], RoiGeometryNames: List[str], SmoothingRadius: float = ..., DesiredTriangleEdgeLength: float = ..., CreateNewRois: bool = ...) -> Dict[str, Any]:
        """Creates controlling ROI geometries for reference and target examinations."""
        ...
    def CreateCouchPoint(self, ExaminationName: str, ReferencePoiName: str, NewPoiName: str) -> None:
        """Detects couch's surface in the plane where the isocenter is marked and creates a POI at that point."""
        ...
    def CreateHybridDeformableRegistrationGroup(self, RegistrationGroupName: str, ReferenceExamination: Examination, TargetExaminations: List[Examination], ControllingRoiNames: List[str] = ..., ControllingPoiNames: List[str] = ..., FocusRoiNames: List[str] = ..., AlgorithmSettings: Union[HybridAlgorithmSettingsData, Any] = ...) -> Dict[str, Any]:
        """Creates a deformable registration group with hybrid deformable registrations for the selected reference examination and target examinations."""
        ...
    def CreateIsocentersFromMarkersInCtImages(self, ExaminationName: str) -> None:
        """Detects in-plane fiducial markers defining one or more isocenters for treatment of the patient."""
        ...
    def CreateLoi(self, Examination: Examination = ..., LinePoints: List[Any] = ..., Color: str = ..., Type: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ...) -> RegionOfInterest:
        """Create a new LOI."""
        ...
    def CreateMaterial(self, BaseOnMaterial: Material, Name: str, MassDensityOverride: float = ...) -> None:
        """Action for creating a new material based on another material. Elemental atomic numbers, elemental masses, elemental weights and mean excitation energy will be copied from the other material, only density can be set."""
        ...
    def CreatePoi(self, Examination: Examination = ..., Point: Any = ..., Name: str = ..., Color: str = ..., VisualizationDiameter: float = ..., Type: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ...) -> RegionOfInterest:
        """Create a new POI."""
        ...
    def CreatePoisFromChannel(self, Channel: BrachyChannel, Distance: float, Angle: int = ..., CreateForEveryActive: bool = ..., MinimumRelativePosition: float = ..., MaximumRelativePosition: float = ..., PoiSpacing: float = ..., BasePoiName: str = ..., PoiColor: str = ..., PoiType: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ..., PoiDiameter: float = ...) -> None:
        """Creates points at a given distance from the dwell points of a channel."""
        ...
    def CreatePredefinedBrachyChannel(self, Examination: Examination = ..., LinePoints: List[Any] = ..., Type: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ..., ChannelNumber: int = ..., ApplicationSetupPatientDB: BrachyApplicationSetup = ...) -> None:
        """Create a predefined brachy channel and the corresponding LOI geometry."""
        ...
    def CreateRoi(self, Name: str, Color: str = ..., Type: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ..., TissueName: str = ..., RbeCellTypeName: str = ..., RoiMaterial: RoiMaterial = ...) -> RegionOfInterest:
        """Create a new ROI."""
        ...
    def CreateRoiAndImportVisionRtSurfaceScanGeometry(self, Examination: Examination, RoiName: str, RoiColor: str, SurfaceScanId: str) -> None:
        """Creates a new ROI with the specified name and color, then imports a surface scan mesh, associated with the supplied scan meta data, and assigns it as the geometry for the ROI on the specified examination"""
        ...
    def CreateStructuresFromAtlas(self, SourceExaminationsNames: List[str], NrOfFusionAtlases: int = ..., AdaptMbsMeshes: bool = ..., SourceTemplate: TemplatePatientModel = ..., SourceRoiNames: List[str] = ..., SourcePoiNames: List[str] = ..., AssociateStructuresByName: bool = ..., TargetExamination: Examination = ..., UpdateDerivedRois: bool = ..., MappingExamination: Examination = ...) -> None:
        """Create structures from template using atlas-based initialization."""
        ...
    def CreateStructuresFromTemplate(self, SourceExaminationName: str, InitializationOption: Literal['None', 'EmptyGeometry', 'AlignImageCenters', 'RigidRegistration', 'DeformableRegistration', 'AtlasBased', 'DLS', 'MappedStructure', 'Derived', 'AutoGeneratedExternal', 'UserDefined'] = ..., SourceTemplate: TemplatePatientModel = ..., SourceRoiNames: List[str] = ..., SourcePoiNames: List[str] = ..., AssociateStructuresByName: bool = ..., TargetExamination: Examination = ..., UpdateDerivedRois: bool = ..., MappingExamination: Examination = ...) -> None:
        """Create structures from template."""
        ...
    def CreateTriangleMeshesForBiomechanicalDir(self, RoiMeshingDatas: List[Any], ReferenceExaminationName: str, TargetExaminationNames: List[str], MaxNumberOfSmoothingSteps: int, SeparationMarginInterval: Any, ExternalSupInfRange: Any = ...) -> Dict[str, Any]:
        """Given ROI geometries with any representation (voxel, contour, triangle mesh) in two, or more, image sets,"""
        ...
    def DeleteChannelCandidate(self, LoiGeometry: LoiGeometry) -> None:
        """Deletes a channel candidate. If the channel candidate is not part of an applicator model, the LOI is removed."""
        ...
    def DetectBreastMarkers(self, Examination: str, SUPName: str = ..., INFName: str = ..., MEDName: str = ..., LATName: str = ..., ANTName: str = ..., ExternalName: str = ...) -> None:
        """For auto breast planning only."""
        ...
    def DetectChannels(self, Examination: Examination, SmallestRadius: float = ..., LargestRadius: float = ...) -> None:
        """Given an examination, performs an automatic segmentation of brachy channels, creating line of interests."""
        ...
    def GetAlgorithmSettingsForHybridDIR(self, ReferenceExamination: Examination, TargetExamination: Examination, DeformationStrategy: str, FinalResolution: Any = ..., DiscardImageInformation: bool = ..., UsesControllingROIs: bool = ...) -> Any:
        """Gets the hybrid deformable registration algorithm settings used when running "Create hybrid deformable registrations" from UI."""
        ...
    def GetAlgorithmSettingsForHybridDIRWithMutualInformation(self, ReferenceExamination: Examination, TargetExamination: Examination, DeformationStrategy: str, FinalResolution: Any = ..., DiscardImageInformation: bool = ..., UsesControllingROIs: bool = ...) -> Any:
        """Gets the hybrid deformable registration algorithm settings suitable for using the Mutual Information similarity measure."""
        ...
    def GetConvexHullsAsRois(self, Examination: Examination, RoisList: List[RegionOfInterest]) -> None:
        """Calculates convex hulls of the provided ROIs and creates new ROIs for the hull geometries"""
        ...
    def GetRoiNameWithRespectToExistingRois(self, DesiredRoiName: str, ExaminationName: str) -> str:
        """Returns a unique roi name (by adding a number in parenthesis at the end of name) if there is already an roi"""
        ...
    def GetUniqueRoiName(self, DesiredName: str) -> str:
        """Returns a unique ROI name from desired name, by adding a number in paranthesis at the end of"""
        ...
    def ImportVisionRtSurfaceScanGeometry(self, Examination: Examination, RegionOfInterest: RegionOfInterest, SurfaceScanId: str) -> None:
        """Imports a surface scan mesh, associated with the supplied scan meta data, and assigns it as the geometry for the specified ROI on the specified examination"""
        ...
    def MapPoiGeometriesDeformably(self, PoiGeometryNames: List[str], CreateNewPois: bool = ..., StructureRegistrationGroupNames: List[str] = ..., ReferenceExaminations: List[Examination] = ..., TargetExaminations: List[Examination] = ..., ReverseMapping: bool = ..., AbortWhenBadDisplacementField: bool = ...) -> List[str]:
        """Map POI geometries according to selected deformable registration(s)."""
        ...
    def MapPoiGeometriesRigidly(self, PoiGeometryNames: List[str], CreateNewPois: bool = ..., ReferenceExamination: Examination = ..., TargetExaminations: List[Examination] = ..., Transformations: List[Any] = ...) -> None:
        """Map POI geometries according to selected transformation(s)."""
        ...
    def MapRoiGeometriesDeformably(self, RoiGeometryNames: List[str], CreateNewRois: bool = ..., StructureRegistrationGroupNames: List[str] = ..., ReferenceExaminations: List[Examination] = ..., TargetExaminations: List[Examination] = ..., ReverseMapping: bool = ..., AbortWhenBadDisplacementField: bool = ...) -> List[str]:
        """Map ROI geometries according to selected deformable registration(s)."""
        ...
    def MapRoiGeometriesRigidly(self, RoiGeometryNames: List[str], CreateNewRois: bool = ..., ReferenceExamination: Examination = ..., TargetExaminations: List[Examination] = ..., Transformations: List[Any] = ...) -> None:
        """Map ROI geometries according to selected transformation(s)."""
        ...
    def MBSAutoInitializer(self, MbsRois: List[Any], CreateNewRois: bool = ..., Examination: Examination = ..., UseAtlasBasedInitialization: bool = ...) -> None:
        """Initialize MBS meshes."""
        ...
    def MeshSeparationOfBoundaryConditionsForMorfeus(self, RoiNames: List[str], ExternalRoiName: str, ExaminationNames: List[str], SeparationMarginInterval: Any, CreateNewRois: bool) -> List[str]:
        """Mesh separation of boundary conditions for morfeus DIR."""
        ...
    def RegisterScannedAvatar(self, ExaminationName: str, AvatarRoi: str, PatientRoi: str, DiscardRotations: bool, InitializeAutomatically: bool, KeepOnlyThePartsOfAvatarOutsideImageStack: bool) -> None:
        """Registers a scanned avatar ROI to the chosen patient ROI."""
        ...
    def RemoveMaterial(self, Name: str) -> None:
        """Removes a non-template material from a patient."""
        ...
    def SetVoxelValuesForRois(self, Examination: Examination, VoxelCountForRoi: Dict[str, Any], CornerCenterForRoi: Dict[str, Any], VoxelSizeForRoi: Dict[str, Any], VoxelValuesForRoi: Dict[str, Any]) -> None:
        """Action used in deep learning segmentation to set voxel values for ROIs."""
        ...
    def ToggleExcludeFromExport(self, ExcludeFromExport: bool = ..., RegionOfInterests: List[str] = ..., PointsOfInterests: List[str] = ...) -> None:
        """Sets if the ROI/POI shall be exported or not."""
        ...
    def UpdateDerivedGeometries(self, RoiNames: List[str], Examination: Examination, Algorithm: Literal['Voxels', 'Contours', 'Auto', 'LineGrid'] = ..., AreEmptyDependenciesAllowed: bool = ...) -> None:
        """Updates the derived geometries for the specified examination."""
        ...

class PatientModelReference:
    @property
    def ExaminationStructureSetReferences(self) -> ScriptObjectCollection[ExaminationStructureSetReference]: ...
    @property
    def PoiAssociations(self) -> ScriptObjectCollection[RegionOfInterestAssociationPair]: ...
    @property
    def RoiAssociations(self) -> ScriptObjectCollection[RegionOfInterestAssociationPair]: ...
    def AddRoiAssociationPairs(self, RoiAssociationPairs: Dict[str, Any], PoiAssociationPairs: Dict[str, Any]) -> None:
        """Adds ROI association pairs to PatientModelReference"""
        ...
    def DeleteRoiAssociationPairs(self, AssociatedRois: List[RegionOfInterest], AssociatedPois: List[RegionOfInterest]) -> None:
        """Deletes ROI association pairs from PatientModelReference"""
        ...
