from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.auto_planning import AutoPlanningDefinition
    from raystation.v2025.beam import BeamCommissioningField, PhotonBeam
    from raystation.v2025.beam_set import RadiationSet
    from raystation.v2025.patient import Patient, PatientModel
    from raystation.v2025.patient_db_types import ConstantFactorModel, LocalEffectModel, MicrodosimetricKineticModel, RbeModelReference, RegionOfInterest, StandardBnctModel
    from raystation.v2025.plan import BackupPlanProtocol, PlanGenerationProtocol
    from raystation.v2025.template import TemplateArcTrajectory, TemplateBrachyDwellTimeDistribution, TemplateColorMap, TemplateMaterial, TemplateMbsModel, TemplatePatientModel, TemplatePlanExploration, TemplateResponseParameters, TemplateToleranceTable, TemplateTreatmentOptimization, TemplateTreatmentSetup
    from raystation.v2025.treatment_module import TreatmentModule_TreatmentCourse



class PatientDB:
    def AddAutoPlanningDefinition(self, BodySite: str, PlanningIntentionName: str) -> AutoPlanningDefinition:
        """Adds an auto-planning definition to the database and saves the patient state."""
        ...
    def BackupPatient(self, PatientInfo: Dict[str, Any], TargetPath: str, AnonymizationSettings: Dict[str, Any]) -> None:
        """Creates a backup of a patient."""
        ...
    def CopyAutoPlanningDefinition(self, AutoPlanningDefinition: AutoPlanningDefinition, PlanningIntentionName: str) -> AutoPlanningDefinition:
        """Copies an auto-planning definition and adds it to the database."""
        ...
    def CopyBeamToBeamCommissioningField(self, FieldName: str, BeamToCopy: PhotonBeam, Description: str = ...) -> BeamCommissioningField:
        """Create a beam commissioning field by copying from a beam."""
        ...
    def CopyPlanGenerationProtocolAndSave(self, Protocol: PlanGenerationProtocol, NewName: str) -> PlanGenerationProtocol:
        """Creates a copy of a plan generation protocol and saves the changes."""
        ...
    def CopyStructureTemplate(self, NameOfTemplateToCopy: str, NameOfNewTemplate: str = ..., TemplateDescription: str = ..., InitializationType: Optional[Literal['Undefined', 'GeometriesFromTemplate', 'EmptyGeometries', 'GeometriesFromTemplateAndUseRigidRegistration', 'GeometriesFromTemplateAndUseDeformableRegistration', 'AtlasBased']] = ...) -> None:
        """Creates a copy of an existing structure template. If a new name is supplied, the copy will get the desired template name if possible. If the name is not unique or too long, a suffix will be added or the name shortened."""
        ...
    def CreateExplorationTemplate(self, Name: str, ProtocolNames: List[str]) -> TemplatePlanExploration:
        """Creates a new plan exploration template."""
        ...
    def CreatePatient(self, LastName: str, FirstName: str = ..., PatientID: str = ..., BirthDate: Optional[str] = ..., Gender: str = ...) -> str:
        """Create a new patient in DB, without image sets."""
        ...
    def CreateRTIonToleranceTableTemplate(self, Label: str) -> TemplateToleranceTable:
        """Creates a new tolerance table template."""
        ...
    def CreateRTToleranceTableTemplate(self, Label: str) -> TemplateToleranceTable:
        """Creates a new tolerance table template."""
        ...
    def CreateStructureTemplate(self, Name: str, Description: str = ..., PatientModel: PatientModel = ..., ExaminationNames: List[str] = ..., RoiNames: List[str] = ..., PoiNames: List[str] = ..., RoiAndModelGeneratedRoiGeometryDictionary: Dict[str, Any] = ..., InitializationType: Literal['Undefined', 'GeometriesFromTemplate', 'EmptyGeometries', 'GeometriesFromTemplateAndUseRigidRegistration', 'GeometriesFromTemplateAndUseDeformableRegistration', 'AtlasBased'] = ...) -> None:
        """Create a structure template."""
        ...
    def CreateTemplateArcTrajectory(self, Name: str, GantryAngles: np.ndarray = ..., CouchAngles: np.ndarray = ..., CollimatorAngles: np.ndarray = ..., RotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ...) -> None:
        """Creates an Wave Arc template."""
        ...
    def DeleteTemplateArcTrajectory(self, Name: str) -> None:
        """Deletes a Wave Arc template."""
        ...
    def GetArcTrajectoryTemplateNames(self) -> List[str]:
        """Retrieves the names in a list of all existing arc trajectory templates"""
        ...
    def GetAutoPlanningDefinitionsInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing auto-planning definitions."""
        ...
    def GetBeamListTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing beam list templates"""
        ...
    def GetBrachyDwellTimeDistributionTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing brachy dwell time distribution templates"""
        ...
    def GetClinicalGoalTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing clinical goal templates"""
        ...
    def GetColorMapTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing color map templates"""
        ...
    def GetEndpointsForRoi(self, Roi: RegionOfInterest) -> List[str]:
        """Gets all endpoints defined for the ROI."""
        ...
    def GetMbsModelTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing MBS model templates"""
        ...
    def GetOptimizationFunctionTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing optimization function templates"""
        ...
    def GetPatientModelTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing patient model templates"""
        ...
    def GetPlanExplorationTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing plan exploration templates"""
        ...
    def GetPlanGenerationProtocolsInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing plan generation protocols."""
        ...
    def GetRayStationInfo(self) -> Dict[str, Any]:
        """Retrieves information regarding the current RayStation version."""
        ...
    def GetRbeModel(self, RbeModelReference: RbeModelReference) -> Union[ConstantFactorModel, LocalEffectModel, MicrodosimetricKineticModel, StandardBnctModel]:
        """Retruns the RBE model corresponding to the provided RBE model reference."""
        ...
    def GetResponseParametersTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing response parameter templates"""
        ...
    def GetSystemMemoryUsage(self) -> str:
        """Get an approximation of the number of bytes currently thought to be allocated in managed memory"""
        ...
    def GetTemplateMaterialNames(self) -> List[str]:
        """Retrieves a list of template material names (excluding patient specific materials)."""
        ...
    def GetTemplateMaterials(self) -> List[TemplateMaterial]:
        """Retrieves the material templates."""
        ...
    def GetToleranceTableTemplateInfo(self) -> List[Any]:
        """Retrieves a list of info objects of all existing tolerance table templates"""
        ...
    def GetTumorStagesForRoi(self, Roi: RegionOfInterest) -> List[str]:
        """Gets all tumor stages defined for the ROI."""
        ...
    def ImportPatientFromPath(self, Path: str, SeriesOrInstances: List[Any], ImportFilter: str = ..., BrachyPlanImportOverrides: Dict[str, Any] = ...) -> str:
        """Imports one new patient from path into the database.  Sets current patient to the imported patient and saves to database."""
        ...
    def ImportPatientFromRepository(self, Connection: Dict[str, Any], SeriesOrInstances: List[Any], ImportFilter: str = ..., BrachyPlanImportOverrides: Dict[str, Any] = ...) -> str:
        """Imports one new patient from repository into the database. Sets current patient to the imported patient and saves to database."""
        ...
    def ImportPatientFromRepositoryByAETitle(self, AETitle: str, SeriesOrInstances: List[Any], ImportFilter: str = ...) -> str:
        """Imports one new patient from repository into the database. Sets current patient to the imported patient and saves to database."""
        ...
    def ImportStructureTemplate(self, FileName: str) -> None:
        """Imports a structure template from a backup (.rsbak) file."""
        ...
    def ListAllBeamCommissioningFieldNames(self) -> List[str]:
        """Lists the name of all beam commissioning fields in the database"""
        ...
    def LoadAutoPlanningDefinition(self, Name: str, EnableEditing: bool) -> AutoPlanningDefinition:
        """Returns the loaded auto-planning definition."""
        ...
    def LoadBackupPlanProtocol(self, name: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']]) -> BackupPlanProtocol:
        """Gets the BackupPlanProtocol with the specified name. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadBeamCommissioningField(self, FieldName: str) -> BeamCommissioningField:
        """Returns the field if already loaded, otherwise loads the field in read only mode"""
        ...
    def LoadPatient(self, PatientInfo: Dict[str, Any], AllowPatientUpgrade: bool = ...) -> Patient:
        """Loads a patient from the database. Returns a handle to the loaded patient."""
        ...
    def LoadPlanGenerationProtocol(self, Name: str) -> PlanGenerationProtocol:
        """Returns the loaded plan generation protocol in read-only mode."""
        ...
    def LoadTemplateArcTrajectory(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateArcTrajectory:
        """Loads an arc trajectory template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateBeamList(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateTreatmentSetup:
        """Loads a beam list template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateBrachyDwellTimeDistribution(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateBrachyDwellTimeDistribution:
        """Loads a brachy dwell time distribution template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateClinicalGoals(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateTreatmentOptimization:
        """Loads a clinical goal list template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateColorMap(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateColorMap:
        """Loads a color map template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateMbsModel(self, templateName: str) -> TemplateMbsModel:
        """Loads a template MBS model from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateOptimizationFunctions(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateTreatmentOptimization:
        """Loads a optimization function template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplatePatientModel(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplatePatientModel:
        """Loads a template patient model from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplatePlanExploration(self, templateName: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplatePlanExploration:
        """Loads a plan exploration template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateResponseParameters(self, tissueName: str, endpointOrTumorStage: str) -> TemplateResponseParameters:
        """Loads a response parameter template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTemplateToleranceTable(self, templateLabel: str, lockMode: Optional[Literal['NoLock', 'Read', 'Write', 'Snapshot']] = ...) -> TemplateToleranceTable:
        """Loads a tolerance table template from the database. A template has to be loaded before actions reading data from the template can be run."""
        ...
    def LoadTreatmentCourse(self, PatientId: str, GivenName: str, FamilyName: str, EpisodeOfCareName: str) -> TreatmentModule_TreatmentCourse:
        """Loads the treatment course aggregate which are linked to the given patient id, patient name as well as episode of care."""
        ...
    def QueryCaseInfo(self, PatientInfo: Dict[str, Any], UseIndexService: bool = ...) -> List[Any]:
        """Returns info on all cases for a given patient."""
        ...
    def QueryExaminationInfo(self, PatientInfo: Dict[str, Any], Filter: Dict[str, Any], UseIndexService: bool = ...) -> List[Any]:
        """Returns info on all examinations for a given patient."""
        ...
    def QueryInstancesFromPath(self, Path: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all instances of a patient study's series matching search criterias from DICOM files in a path."""
        ...
    def QueryInstancesFromRepository(self, Connection: Dict[str, Any], SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all instances of a patient study's series matching search criterias from DICOM files from a repository."""
        ...
    def QueryInstancesFromRepositoryByAETitle(self, AETitle: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all instances of a patient study's series matching search criterias from DICOM files from a repository."""
        ...
    def QueryPatientInfo(self, Filter: Dict[str, Any], UseIndexService: bool = ...) -> List[Any]:
        """Returns info on all patients in the patient database."""
        ...
    def QueryPatientsFromPath(self, Path: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all patients matching search criterias from DICOM files in a path."""
        ...
    def QueryPatientsFromRepository(self, Connection: Dict[str, Any], SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all patients matching search criterias from DICOM files from a repository."""
        ...
    def QueryPatientsFromRepositoryByTitle(self, Title: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all patients matching search criterias from DICOM datasets from a repository."""
        ...
    def QueryPhantomInfo(self, Filter: Dict[str, Any], UseIndexService: bool = ...) -> List[Any]:
        """Returns info on all phantoms in the patient database."""
        ...
    def QueryPlanInfo(self, PatientInfo: Dict[str, Any], Filter: Dict[str, Any], UseIndexService: bool = ...) -> List[Any]:
        """Returns info on all plans for a given patient."""
        ...
    def QuerySeriesFromPath(self, Path: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all series of a patient's study matching search criterias from DICOM files in a path."""
        ...
    def QuerySeriesFromRepository(self, Connection: Dict[str, Any], SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all series matching search criterias from DICOM files from a repository."""
        ...
    def QuerySeriesFromRepositoryByAETitle(self, AETitle: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all series matching search criterias from DICOM files from a repository."""
        ...
    def QueryStudiesFromPath(self, Path: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all studies of a patient matching search criterias from DICOM files in a path."""
        ...
    def QueryStudiesFromRepository(self, Connection: Dict[str, Any], SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all studies of a patient matching search criterias from DICOM from a repository."""
        ...
    def QueryStudiesFromRepositoryByAETitle(self, AETitle: str, SearchCriterias: Dict[str, Any]) -> List[Any]:
        """Returns info on all studies of a patient matching search criterias from DICOM from a repository."""
        ...
    def RemoveBeamCommissioningField(self, FieldName: str) -> None:
        """Removes the beam commissioning field with the given name from the database"""
        ...
    def RenameTemplateArcTrajectory(self, Name: str, RenameTo: str) -> None:
        """Renames a Wave Arc template."""
        ...
    def RestoreTreatmentCourse(self, Patient: Patient, EpisodeOfCareName: str, BeamSet: RadiationSet = ...) -> None:
        """Unloads all treatment courses and restores the snapshot lock for the one of the current patient."""
        ...
    def RunMachineLearningModel(self, ModelName: str, ModelParams: Dict[str, Any] = ...) -> None:
        """Runs a Machine Learning model of type ModelType.Other on the current patient"""
        ...
    def Save(self) -> None:
        """Saves all unsaved objects that belong to the patient database."""
        ...
    def ScriptableBomb(self, ExceptionType: Literal['LogicalException', 'SanityCheckException', 'None'], TimerMs: int = ...) -> None:
        """Action that throws an exception from within a script and is called on an instance of PatientDB."""
        ...
    def UnloadBeamCommissioningField(self, FieldName: str) -> None:
        """Unloads the field with name FieldName. Changes to field must be saved before unloading."""
        ...
