from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.auto_planning import AutoPlanningRoi
    from raystation.v2025.beam import BeamFractionDose
    from raystation.v2025.beam_set import RadiationSet
    from raystation.v2025.clinical_goals import ClinicalGoal
    from raystation.v2025.dose import DoseAtVolumeGoal, DoseBasedRoiFunction, DoseGrid, DoseGridStructures
    from raystation.v2025.ml import MachineLearningDose
    from raystation.v2025.optimization import OptimizationParameters
    from raystation.v2025.patient_db_types import AblationTreatment, AutoOptimizationSettings, AutoScaleManager, AuxiliaryDataInDoseGrid, AverageDoseGoal, CompositeDose, CompositeFunction, EQD2Dose, EqdParameters, Examination, ExaminationStructureSet, ExplorationFilters, FractionDose, LqModelParameters, MappedDose, Mco, MedicationActivity, MotionSynchronizationTechniqueSettings, PhantomStudy, PredictedMachineLearningDose, PrescribedDoseLevel, ProgressOfOptimization, RegionOfInterest, Review, TradeOffEvaluation, TreatmentCourse, TreatmentDelivery, TreatmentPhase, VolumeAtDoseGoal, WeightedObjectiveFunction
    from raystation.v2025.regimen import Regimen, RegimenTemplateReference
    from raystation.v2025.template import TemplateTreatmentOptimization



class PlanningIntention:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def AutoPlanningDoseGoals(self) -> List[Union[AverageDoseGoal, DoseAtVolumeGoal, VolumeAtDoseGoal]]: ...
    @AutoPlanningDoseGoals.setter
    def AutoPlanningDoseGoals(self, value: List[Union[AverageDoseGoal, DoseAtVolumeGoal, VolumeAtDoseGoal]]) -> None: ...
    @property
    def AutoPlanningRois(self) -> ScriptObjectCollection[AutoPlanningRoi]: ...
    @AutoPlanningRois.setter
    def AutoPlanningRois(self, value: List[AutoPlanningRoi]) -> None: ...
    @property
    def PrescribedDoseLevels(self) -> ScriptObjectCollection[PrescribedDoseLevel]: ...
    @PrescribedDoseLevels.setter
    def PrescribedDoseLevels(self, value: List[PrescribedDoseLevel]) -> None: ...
    def AddAutoPlanningRoi(self, IsRequired: bool = ..., Name: str = ..., RegionOfInterestType: Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar'] = ...) -> AutoPlanningRoi:
        """Adds an auto-planning ROI to the planning intention."""
        ...
    def AddAverageDoseGoal(self, AbsolutePrimaryDoseLevel: Optional[float] = ..., PercentPrimaryDoseLevel: Optional[float] = ..., RelativeToPrimaryDoseLevel: PrescribedDoseLevel = ..., AbsoluteSecondaryDoseLevel: Optional[float] = ..., PercentSecondaryDoseLevel: Optional[float] = ..., RelativeToSecondaryDoseLevel: PrescribedDoseLevel = ..., GoalCriteria: Literal['AtLeast', 'AtMost'] = ..., ForAutoPlanningRoi: AutoPlanningRoi = ...) -> AverageDoseGoal:
        """Adds an average dose goal to the planning intention."""
        ...
    def AddDoseAtVolumeGoal(self, PercentVolumeLevel: Optional[float] = ..., AbsoluteVolumeLevel: Optional[float] = ..., AbsolutePrimaryDoseLevel: Optional[float] = ..., PercentPrimaryDoseLevel: Optional[float] = ..., RelativeToPrimaryDoseLevel: PrescribedDoseLevel = ..., AbsoluteSecondaryDoseLevel: Optional[float] = ..., PercentSecondaryDoseLevel: Optional[float] = ..., RelativeToSecondaryDoseLevel: PrescribedDoseLevel = ..., GoalCriteria: Literal['AtLeast', 'AtMost'] = ..., ForAutoPlanningRoi: AutoPlanningRoi = ...) -> DoseAtVolumeGoal:
        """Adds a dose-at-volume goal to the planning intention."""
        ...
    def AddPrescribedDoseLevel(self, DosePerFraction: float, NumberOfFractions: int, ForAutoPlanningRois: List[AutoPlanningRoi]) -> PrescribedDoseLevel:
        """Adds a prescribed dose level to the planning intention."""
        ...
    def AddVolumeAtDoseGoal(self, AbsolutePrimaryVolumeLevel: Optional[float] = ..., PercentPrimaryVolumeLevel: Optional[float] = ..., AbsoluteSecondaryVolumeLevel: Optional[float] = ..., PercentSecondaryVolumeLevel: Optional[float] = ..., AbsoluteDoseLevel: Optional[float] = ..., PercentDoseLevel: Optional[float] = ..., RelativeToDoseLevel: PrescribedDoseLevel = ..., GoalCriteria: Literal['AtLeast', 'AtMost'] = ..., ForAutoPlanningRoi: AutoPlanningRoi = ...) -> VolumeAtDoseGoal:
        """Adds a volume-at-dose goal to a planning intention."""
        ...
    def EditNumberOfFractionsForPrescribedDoseLevels(self, NumberOfFractions: int) -> None:
        """Edits the number of fractions for all prescribed dose levels of the planning intention."""
        ...

class TreatmentPlanIncludingTreatmentPlanGroup:
    @property
    def Comments(self) -> str: ...
    @Comments.setter
    def Comments(self, value: str) -> None: ...
    @property
    def FractionNumber(self) -> int: ...
    @FractionNumber.setter
    def FractionNumber(self, value: int) -> None: ...
    @property
    def IsBackupPlan(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlanGenerationProtocol(self) -> str: ...
    @property
    def PlannedBy(self) -> str: ...
    @PlannedBy.setter
    def PlannedBy(self, value: str) -> None: ...
    @property
    def AblationTreatment(self) -> AblationTreatment: ...
    @AblationTreatment.setter
    def AblationTreatment(self, value: AblationTreatment) -> None: ...
    @property
    def AdaptionTo(self) -> TreatmentPlan: ...
    @AdaptionTo.setter
    def AdaptionTo(self, value: TreatmentPlan) -> None: ...
    @property
    def AutomatedReplanningSettingsPerRadiationSet(self) -> ScriptObjectCollection[AutomatedReplanningRadiationSetSettings]: ...
    @AutomatedReplanningSettingsPerRadiationSet.setter
    def AutomatedReplanningSettingsPerRadiationSet(self, value: List[AutomatedReplanningRadiationSetSettings]) -> None: ...
    @property
    def BackupPlans(self) -> ScriptObjectCollection[BackupPlanIncludingTreatmentPlanGroup]: ...
    @BackupPlans.setter
    def BackupPlans(self, value: List[BackupPlanIncludingTreatmentPlanGroup]) -> None: ...
    @property
    def BeamSets(self) -> ScriptObjectCollection[RadiationSet]: ...
    @BeamSets.setter
    def BeamSets(self, value: List[RadiationSet]) -> None: ...
    @property
    def EqdParameters(self) -> EqdParameters: ...
    @EqdParameters.setter
    def EqdParameters(self, value: EqdParameters) -> None: ...
    @property
    def PlanOptimizations(self) -> ScriptObjectCollection[PlanningPhase]: ...
    @PlanOptimizations.setter
    def PlanOptimizations(self, value: List[PlanningPhase]) -> None: ...
    @property
    def Regimens(self) -> ScriptObjectCollection[Regimen]: ...
    @Regimens.setter
    def Regimens(self, value: List[Regimen]) -> None: ...
    @property
    def Review(self) -> Review: ...
    @Review.setter
    def Review(self, value: Review) -> None: ...
    @property
    def TreatmentCourse(self) -> TreatmentCourse: ...
    @TreatmentCourse.setter
    def TreatmentCourse(self, value: TreatmentCourse) -> None: ...
    @property
    def TreatmentPhases(self) -> ScriptObjectCollection[TreatmentPhase]: ...
    @TreatmentPhases.setter
    def TreatmentPhases(self, value: List[TreatmentPhase]) -> None: ...
    @property
    def VerificationPlans(self) -> ScriptObjectCollection[VerificationPlan]: ...
    @VerificationPlans.setter
    def VerificationPlans(self, value: List[VerificationPlan]) -> None: ...
    def AddNewAutomaticPlanningBeamSet(self, MachineLearningModelID: str, MachineLearningModelParameters: Dict[str, Any] = ..., AutoPlanningStrategyName: str = ..., PlanningIntentionName: str = ..., RoiNameMatches: Dict[str, Any] = ..., Name: str = ..., ExaminationName: str = ..., MachineName: str = ..., Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set for machine learning optimization."""
        ...
    def AddNewBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set."""
        ...
    def AddNewCyberKnifeMachineQaBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set for CyberKnife QA. Modality has to be Photons. Treatment technique has to be CyberKnife."""
        ...
    def AddNewResearchIntentBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set with Plan intent 'Research'. For a beam set with this plan intent,"""
        ...
    def AutomaticPlanningPreprocessing(self) -> None:
        """Prepare plan for running automatic planning algorithm. Only used for automatic planning machine learning models."""
        ...
    def CopyBeamSetAndOptimizationProblemToCurrentPlan(self, RadiationSets: List[RadiationSet], ExaminationName: str) -> None:
        """Copy beam sets and associated objectives/constraints to current plan."""
        ...
    def CreateAlternativePlan(self, PlanName: str, ExaminationName: str) -> None:
        """An alternative plan is created by copying a plan and its beam sets to a different examination."""
        ...
    def EditBrachyOptimizationSettings(self, MaximumNumberOfIterations: int, OptimizationTolerance: float, DwellTimeLimits: Any) -> None:
        """Edits optimization settings for a brachy plan."""
        ...
    def EditBrachyTreatmentPlan(self, PlanName: str, PlannedBy: str = ..., Comment: str = ..., NumberOfFractions: int = ...) -> None:
        """Edits a brachy treatment plan."""
        ...
    def GetPlanUuid(self) -> Optional[str]:
        """Gets the UUID from the TreatmentPlan"""
        ...
    def GetTotalDoseGrid(self) -> DoseGrid:
        """Gets the dose grid for the total dose of the treatment plan."""
        ...
    def GetTotalDoseStructureSet(self) -> ExaminationStructureSet:
        """Gets the structure set for the total dose of the treatment plan."""
        ...
    def GetTotalPlanDoseImages(self, Orientations: List[str], Points: List[Any], FocusOnIsocenter: List[bool], ImageSize: Any, FocusOnRoi: str) -> List[str]:
        """Method for retrieving dose view images for the total plan dose."""
        ...
    def InitializeDoseTrackingFromPlan(self, TreatmentDelivery: TreatmentDelivery, DoseAccumulationExamination: Examination = ...) -> None:
        """Action for preparing a treatment plan for delivery. Will copy fractions from planning treatment course to delivery."""
        ...
    def LoadBeamSet(self, BeamSetInfo: Dict[str, Any]) -> RadiationSet:
        """Loads a beam set from a treatment plan. Returns a handle to the beam set."""
        ...
    def QueryBeamSetInfo(self, Filter: Dict[str, Any]) -> List[Any]:
        """Returns info on all beam sets on a treatment plan."""
        ...
    def SetBeamSetsToOptimizeSimultaneously(self, BeamSetNames: List[str]) -> None:
        """Sets beam sets to be optimized simultaneously"""
        ...
    def SetCurrent(self) -> None:
        """Sets the current plan."""
        ...
    def SetDefaultViewPosition(self, Coordinate: Optional[Union[Point3[float], Point3Dict[float]]] = ...) -> None:
        """Action that sets a default view positions"""
        ...
    def SetReportViewPositions(self, Coordinates: List[Any]) -> None:
        """Action that sets a collection of default view positions for a generated report"""
        ...
    def UnsetBeamSetsToOptimizeSimultaneously(self, BeamSetNames: List[str]) -> None:
        """Sets beam sets that were set to be optimized simultaneously to be optimized separately"""
        ...
    def UpdateDependency(self, DependentBeamSetName: str, BackgroundBeamSetName: str, DependencyUpdate: Literal['CreateDependency', 'RemoveDependency'] = ...) -> RadiationSet:
        """Changes the way a beam set depends on the other beam set. When a beam set is set as dependent, the other beam set dose is used as background dose."""
        ...

class PlanningPhase:
    @property
    def AutoScaleToPrescription(self) -> bool: ...
    @property
    def AutoOptimizationSettings(self) -> AutoOptimizationSettings: ...
    @AutoOptimizationSettings.setter
    def AutoOptimizationSettings(self, value: AutoOptimizationSettings) -> None: ...
    @property
    def AutoScaleManagers(self) -> ScriptObjectCollection[AutoScaleManager]: ...
    @AutoScaleManagers.setter
    def AutoScaleManagers(self, value: List[AutoScaleManager]) -> None: ...
    @property
    def Constraints(self) -> List[Union[CompositeFunction, DoseBasedRoiFunction]]: ...
    @Constraints.setter
    def Constraints(self, value: List[Union[CompositeFunction, DoseBasedRoiFunction]]) -> None: ...
    @property
    def Mco(self) -> Mco: ...
    @Mco.setter
    def Mco(self, value: Mco) -> None: ...
    @property
    def Objective(self) -> Union[CompositeFunction, DoseBasedRoiFunction]: ...
    @Objective.setter
    def Objective(self, value: Union[CompositeFunction, DoseBasedRoiFunction]) -> None: ...
    @property
    def OptimizationParameters(self) -> OptimizationParameters: ...
    @OptimizationParameters.setter
    def OptimizationParameters(self, value: OptimizationParameters) -> None: ...
    @property
    def OptimizationReferenceDose(self) -> Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]: ...
    @OptimizationReferenceDose.setter
    def OptimizationReferenceDose(self, value: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]) -> None: ...
    @property
    def OptimizedBeamSets(self) -> ScriptObjectCollection[RadiationSet]: ...
    @property
    def OptimizedMachineLearningDose(self) -> MachineLearningDose: ...
    @OptimizedMachineLearningDose.setter
    def OptimizedMachineLearningDose(self, value: MachineLearningDose) -> None: ...
    @property
    def PlanningPhaseDose(self) -> CompositeDose: ...
    @PlanningPhaseDose.setter
    def PlanningPhaseDose(self, value: CompositeDose) -> None: ...
    @property
    def PlanningPhaseDoseDependencies(self) -> ScriptObjectCollection[PlanningPhaseDoseDependency]: ...
    @PlanningPhaseDoseDependencies.setter
    def PlanningPhaseDoseDependencies(self, value: List[PlanningPhaseDoseDependency]) -> None: ...
    @property
    def PredictedMachineLearningDose(self) -> MachineLearningDose: ...
    @PredictedMachineLearningDose.setter
    def PredictedMachineLearningDose(self, value: MachineLearningDose) -> None: ...
    @property
    def PreTreatment(self) -> PlanningPhase: ...
    @PreTreatment.setter
    def PreTreatment(self, value: PlanningPhase) -> None: ...
    @property
    def ProgressOfOptimization(self) -> ProgressOfOptimization: ...
    @ProgressOfOptimization.setter
    def ProgressOfOptimization(self, value: ProgressOfOptimization) -> None: ...
    @property
    def TotalDoseOnPartialTreatmentCourse(self) -> CompositeDose: ...
    @TotalDoseOnPartialTreatmentCourse.setter
    def TotalDoseOnPartialTreatmentCourse(self, value: CompositeDose) -> None: ...
    @property
    def TreatmentCourseSource(self) -> TreatmentCourse: ...
    @TreatmentCourseSource.setter
    def TreatmentCourseSource(self, value: TreatmentCourse) -> None: ...
    def AddBiologicalOptimizationFunction(self, RoiName: str, EndpointOrTumorStage: str, IsConstraint: bool = ..., Bound: Optional[float] = ..., ModelType: str = ..., ResponseFunctionType: Literal['Tcp', 'Ntcp'] = ..., UseRepair: bool = ..., UseRepopulation: bool = ...) -> DoseBasedRoiFunction:
        """Adds a biological optimization function."""
        ...
    def AddMcoCreateDeliverablePlanFunctions(self) -> None:
        """Creates a copy of the optimization problem used for creating the MCO deliverable plan."""
        ...
    def AddOnesidedUniformRefDoseFunction(self, RoiName: str, ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, WeightForMinDose: float, WeightForMaxDose: float, VolumeThreshold: float, IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add a onesided uniform reference dose optimization function to the OptimizationProblem."""
        ...
    def AddOptimizationFunction(self, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'] = ..., RoiName: str = ..., IsConstraint: bool = ..., RestrictAllBeamsIndividually: bool = ..., RestrictToBeams: List[str] = ..., IsRobust: bool = ..., RestrictToBeamSet: str = ..., UseRbeDose: bool = ..., UseEqd: bool = ...) -> DoseBasedRoiFunction:
        """Creates and adds an objective constituent or a constraint."""
        ...
    def AddOptimizationReferenceDose(self, MachineLearningModelID: str, MachineLearningModelVersion: int = ..., MachineLearningParameters: Dict[str, Any] = ...) -> None:
        """Adds optimization reference dose."""
        ...
    def AddPredictedMachineLearningDose(self, MachineLearningModelID: str, MachineLearningModelVersion: int = ..., MachineLearningParameters: Dict[str, Any] = ...) -> None:
        """Adds predicted machine learning dose."""
        ...
    def AddReferenceIsoDoseVolumeFunction(self, RoiName: str, ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, Weight: float, IsoDoseVolumeWeights: List[float], ThresholdDoses: List[float], IsoDoseVolumeFunctions: List[str], VoxelWeights: List[float], IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add an onesided uniform reference DVH optimization function to the OptimizationProblem."""
        ...
    def AddReferenceOptimizationFunction(self, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'] = ..., ReferenceDoseDistribution: Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose] = ..., RoiName: str = ..., IsConstraint: bool = ..., RestrictAllBeamsIndividually: bool = ..., RestrictToBeams: List[str] = ..., IsRobust: bool = ..., RestrictToBeamSet: str = ..., UseRbeDose: bool = ..., UseEqd: bool = ...) -> DoseBasedRoiFunction:
        """Creates and adds a reference optimization function"""
        ...
    def AddWeightedOptimizationFunction(self, RoiName: str, FunctionType: Literal['MinDose', 'MaxDose', 'MinDvh', 'MaxDvh', 'UniformDose', 'MinEud', 'MaxEud', 'TargetEud', 'DoseFallOff', 'RefDoseFallOff', 'UniformityConstraint', 'MaxRefDvh', 'MinRefDvh', 'UniformRefDvh', 'OnesidedUniformRefDvh', 'MaxRefDose', 'MinRefDose', 'UniformRefDose', 'OnesidedUniformRefDose', 'RefIsoDoseVolume', 'TcpMarsden', 'TcpPoissonLQ', 'NtcpPoissonLQ', 'NtcpLyman', 'SmoothMinDvh', 'SmoothMaxDvh', 'SpatialDosePrior', 'TotalCrossEntropy', 'PlanningGoal', 'MinLet_d', 'MaxLet_d'], ReferenceDoseDistribution: PredictedMachineLearningDose, HideFromScript: bool, Weight: float, IsRobust: bool, UseRbeDose: bool) -> DoseBasedRoiFunction:
        """Add a weighted optimization function to the OptimizationProblem."""
        ...
    def ApplyOptimizationTemplate(self, Template: TemplateTreatmentOptimization, AssociatedRoisAndPois: Dict[str, Any] = ..., ReplaceExistingOptimizationFunctions: bool = ...) -> None:
        """Copies optimization functions from a template."""
        ...
    def ClearConstituentFunctions(self) -> None:
        """Remove all constituent functions from the problem."""
        ...
    def CreateMco(self) -> Mco:
        """Creates an MCO object."""
        ...
    def EvaluateOptimizationFunctions(self) -> None:
        """Evaluates the optimization functions of this optimization problem"""
        ...
    def GetBackgroundDose(self) -> Union[AuxiliaryDataInDoseGrid, BeamFractionDose, CompositeDose, EQD2Dose, FractionDose, MachineLearningDose, MappedDose, PredictedMachineLearningDose]:
        """Returns the background dose, including dose from dependent beamsets and adaptive fractions"""
        ...
    def PersistFineTuningOptimizationSettings(self, ClinicalGoals: List[DoseBasedRoiFunction], RoiList: List[RegionOfInterest], OptimalityTolerance: float, MaxNumberOfIterations: int, ComputeIntermediateDose: bool, ComputeFinalDose: bool, ClinicalGoalRelativeImportance: float, SpatialConservationObjectiveWeight: float, ClinicalGoalShift: float) -> None:
        """Saves settings to the fine-tuning optimization problem."""
        ...
    def ResetOptimization(self) -> None:
        """Resets the optimization."""
        ...
    def RunFineTuningOptimization(self, ClinicalGoalsToExplore: List[DoseBasedRoiFunction] = ..., ConservationRois: List[RegionOfInterest] = ..., OptimizationSpecs: List[Any] = ...) -> None:
        """Action performing fine-tuning with respect to clinical goals."""
        ...
    def RunOptimization(self) -> None:
        """Runs an optimization."""
        ...
    def RunReduceOARDoseOptimization(self, UseVoxelBasedMimickingForTargets: bool = ..., UseVoxelBasedMimickingForOrgansAtRisk: bool = ..., OrgansAtRiskToImprove: List[Any] = ..., TargetsToMaintain: List[Any] = ..., OrgansAtRiskToMaintain: List[Any] = ...) -> None:
        """Runs a reduce organ-at-risk optimization."""
        ...
    def SetAutoOptimizationSettings(self, AutoPlanningStrategyName: str, PlanningIntentionName: str, RoiNameMatches: Dict[str, Any], MachineLearningModelId: Optional[str] = ..., AutoPlanningStrategyType: Literal['MachineLearningPlanning', 'ECHO'] = ...) -> None:
        """Sets auto-optimization settings for the optimization problem. Existing settings will be over-written, and all objectives and constraints will be cleared."""
        ...
    def SingleOptimization(self) -> None:
        """Do not use this action for new scripts. It may not be available in future versions."""
        ...

class PlanningPhaseDoseDependency:
    @property
    def RadiationSetSource(self) -> RadiationSet: ...
    @RadiationSetSource.setter
    def RadiationSetSource(self, value: RadiationSet) -> None: ...

class PlanningGoal:
    @property
    def GoalCriteria(self) -> Literal['AtLeast', 'AtMost']: ...
    @GoalCriteria.setter
    def GoalCriteria(self, value: Literal['AtLeast', 'AtMost']) -> None: ...
    @property
    def IsComparativeGoal(self) -> bool: ...
    @IsComparativeGoal.setter
    def IsComparativeGoal(self, value: bool) -> None: ...
    @property
    def ParameterValue(self) -> float: ...
    @ParameterValue.setter
    def ParameterValue(self, value: float) -> None: ...
    @property
    def PrimaryAcceptanceLevel(self) -> float: ...
    @PrimaryAcceptanceLevel.setter
    def PrimaryAcceptanceLevel(self, value: float) -> None: ...
    @property
    def Priority(self) -> int: ...
    @Priority.setter
    def Priority(self, value: int) -> None: ...
    @property
    def RejectPlanOnFail(self) -> bool: ...
    @RejectPlanOnFail.setter
    def RejectPlanOnFail(self, value: bool) -> None: ...
    @property
    def SecondaryAcceptanceLevel(self) -> Optional[float]: ...
    @SecondaryAcceptanceLevel.setter
    def SecondaryAcceptanceLevel(self, value: Optional[float]) -> None: ...
    @property
    def Type(self) -> Literal['PlanningValue', 'AverageDose', 'VolumeAtDose', 'DoseAtVolume', 'VolumeAtGamma', 'AverageGamma', 'VolumeAtDifference', 'AverageDifference', 'DoseAtAbsoluteVolume', 'AbsoluteVolumeAtDose', 'DoseAtPoint', 'ConformityIndex', 'HomogeneityIndex']: ...
    @Type.setter
    def Type(self, value: Literal['PlanningValue', 'AverageDose', 'VolumeAtDose', 'DoseAtVolume', 'VolumeAtGamma', 'AverageGamma', 'VolumeAtDifference', 'AverageDifference', 'DoseAtAbsoluteVolume', 'AbsoluteVolumeAtDose', 'DoseAtPoint', 'ConformityIndex', 'HomogeneityIndex']) -> None: ...

class PlanningGoalFunction:
    @property
    def AcceptanceLevel(self) -> float: ...
    @AcceptanceLevel.setter
    def AcceptanceLevel(self, value: float) -> None: ...
    @property
    def FunctionType(self) -> Literal['MaxDoseAtVolume', 'MinDoseAtVolume', 'MaxVolumeAtDose', 'MinVolumeAtDose', 'MaxAverageDose', 'MinAverageDose', 'MinConformityIndex', 'MinHomogeneityIndex']: ...
    @FunctionType.setter
    def FunctionType(self, value: Literal['MaxDoseAtVolume', 'MinDoseAtVolume', 'MaxVolumeAtDose', 'MinVolumeAtDose', 'MaxAverageDose', 'MinAverageDose', 'MinConformityIndex', 'MinHomogeneityIndex']) -> None: ...
    @property
    def ParameterValue(self) -> float: ...
    @ParameterValue.setter
    def ParameterValue(self, value: float) -> None: ...
    @property
    def PenaltyType(self) -> Literal['Linear', 'Power', 'Ramp']: ...
    @PenaltyType.setter
    def PenaltyType(self, value: Literal['Linear', 'Power', 'Ramp']) -> None: ...
    @property
    def Smoothness(self) -> float: ...
    @Smoothness.setter
    def Smoothness(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    @property
    def LqModelParameters(self) -> LqModelParameters: ...
    @LqModelParameters.setter
    def LqModelParameters(self, value: LqModelParameters) -> None: ...

class ParetoPlanSetup:
    @property
    def ParetoPlanWeightIndex(self) -> int: ...
    @property
    def ForRadiationSet(self) -> RadiationSet: ...
    @ForRadiationSet.setter
    def ForRadiationSet(self, value: RadiationSet) -> None: ...
    @property
    def ParetoPlan(self) -> RadiationSet: ...
    @ParetoPlan.setter
    def ParetoPlan(self, value: RadiationSet) -> None: ...
    @property
    def TradeOffEvaluations(self) -> ScriptObjectCollection[TradeOffEvaluation]: ...
    @TradeOffEvaluations.setter
    def TradeOffEvaluations(self, value: List[TradeOffEvaluation]) -> None: ...
    @property
    def WeightedObjectiveFunctions(self) -> ScriptObjectCollection[WeightedObjectiveFunction]: ...
    @WeightedObjectiveFunctions.setter
    def WeightedObjectiveFunctions(self, value: List[WeightedObjectiveFunction]) -> None: ...

class PlannedEncounter:
    @property
    def ReferenceId(self) -> str: ...
    @property
    def RelativeDayInCycle(self) -> int: ...
    @property
    def MedicationActivities(self) -> ScriptObjectCollection[MedicationActivity]: ...
    @MedicationActivities.setter
    def MedicationActivities(self, value: List[MedicationActivity]) -> None: ...
    @property
    def RegimenTemplateReference(self) -> RegimenTemplateReference: ...
    @RegimenTemplateReference.setter
    def RegimenTemplateReference(self, value: RegimenTemplateReference) -> None: ...

class VerificationPlan:
    @property
    def BeamSet(self) -> RadiationSet: ...
    @BeamSet.setter
    def BeamSet(self, value: RadiationSet) -> None: ...
    @property
    def DoseGrid(self) -> DoseGrid: ...
    @DoseGrid.setter
    def DoseGrid(self, value: DoseGrid) -> None: ...
    @property
    def DoseGridStructures(self) -> DoseGridStructures: ...
    @DoseGridStructures.setter
    def DoseGridStructures(self, value: DoseGridStructures) -> None: ...
    @property
    def ForTreatmentPlan(self) -> TreatmentPlan: ...
    @ForTreatmentPlan.setter
    def ForTreatmentPlan(self, value: TreatmentPlan) -> None: ...
    @property
    def OfRadiationSet(self) -> RadiationSet: ...
    @OfRadiationSet.setter
    def OfRadiationSet(self, value: RadiationSet) -> None: ...
    @property
    def PhantomStudy(self) -> PhantomStudy: ...
    @PhantomStudy.setter
    def PhantomStudy(self, value: PhantomStudy) -> None: ...
    def ScriptableQADicomExport(self, ExportFolderPath: str = ..., Connection: Dict[str, Any] = ..., RayGatewayTitle: str = ..., TomoOriginalPlanOverride: str = ..., QaPlanIdentity: str = ..., ExportExamination: bool = ..., ExportExaminationStructureSet: bool = ..., ExportBeamSet: bool = ..., ExportRtRadiationSet: bool = ..., ExportRtRadiations: bool = ..., ExportBeamSetDose: bool = ..., ExportBeamSetBeamDose: bool = ..., IgnorePreConditionWarnings: bool = ..., TransferSyntaxOverride: str = ...) -> str:
        """Exports specified DICOM datasets to either disk or SCP."""
        ...
    def UpdateVerificationPlanDoseGrid(self, Corner: Any = ..., VoxelSize: Any = ..., NumberOfVoxels: Any = ...) -> None:
        """Updates the verification plan dose grid. Existing dose grids are reused and redundant dose grids are removed."""
        ...

class BackupPlanIncludingTreatmentPlanGroup:
    @property
    def FractionNumber(self) -> int: ...
    @FractionNumber.setter
    def FractionNumber(self, value: int) -> None: ...
    @property
    def AdaptionTo(self) -> TreatmentPlan: ...
    @AdaptionTo.setter
    def AdaptionTo(self, value: TreatmentPlan) -> None: ...
    @property
    def AutomatedReplanningSettingsPerRadiationSet(self) -> ScriptObjectCollection[AutomatedReplanningRadiationSetSettings]: ...
    @AutomatedReplanningSettingsPerRadiationSet.setter
    def AutomatedReplanningSettingsPerRadiationSet(self, value: List[AutomatedReplanningRadiationSetSettings]) -> None: ...
    @property
    def ForTreatmentPlan(self) -> TreatmentPlan: ...
    @ForTreatmentPlan.setter
    def ForTreatmentPlan(self, value: TreatmentPlan) -> None: ...
    @property
    def Settings(self) -> BackupPlanSettings: ...
    @Settings.setter
    def Settings(self, value: BackupPlanSettings) -> None: ...
    @property
    def TreatmentPlan(self) -> TreatmentPlan: ...
    @TreatmentPlan.setter
    def TreatmentPlan(self, value: TreatmentPlan) -> None: ...
    @property
    def TreatmentPlans(self) -> ScriptObjectCollection[TreatmentPlanIncludingTreatmentPlanGroup]: ...
    @TreatmentPlans.setter
    def TreatmentPlans(self, value: List[TreatmentPlanIncludingTreatmentPlanGroup]) -> None: ...
    @property
    def VerificationPlans(self) -> ScriptObjectCollection[VerificationPlan]: ...
    @VerificationPlans.setter
    def VerificationPlans(self, value: List[VerificationPlan]) -> None: ...

class BackupPlanSettings:
    @property
    def NumberOfSegments(self) -> int: ...
    @property
    def TargetVsOarWeightRatio(self) -> float: ...

class TreatmentPlan:
    @property
    def Comments(self) -> str: ...
    @Comments.setter
    def Comments(self, value: str) -> None: ...
    @property
    def IsBackupPlan(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlanGenerationProtocol(self) -> str: ...
    @property
    def PlannedBy(self) -> str: ...
    @PlannedBy.setter
    def PlannedBy(self, value: str) -> None: ...
    @property
    def AblationTreatment(self) -> AblationTreatment: ...
    @AblationTreatment.setter
    def AblationTreatment(self, value: AblationTreatment) -> None: ...
    @property
    def BeamSets(self) -> ScriptObjectCollection[RadiationSet]: ...
    @BeamSets.setter
    def BeamSets(self, value: List[RadiationSet]) -> None: ...
    @property
    def EqdParameters(self) -> EqdParameters: ...
    @EqdParameters.setter
    def EqdParameters(self, value: EqdParameters) -> None: ...
    @property
    def PlanOptimizations(self) -> ScriptObjectCollection[PlanningPhase]: ...
    @PlanOptimizations.setter
    def PlanOptimizations(self, value: List[PlanningPhase]) -> None: ...
    @property
    def Regimens(self) -> ScriptObjectCollection[Regimen]: ...
    @Regimens.setter
    def Regimens(self, value: List[Regimen]) -> None: ...
    @property
    def Review(self) -> Review: ...
    @Review.setter
    def Review(self, value: Review) -> None: ...
    @property
    def TreatmentCourse(self) -> TreatmentCourse: ...
    @TreatmentCourse.setter
    def TreatmentCourse(self, value: TreatmentCourse) -> None: ...
    @property
    def TreatmentPhases(self) -> ScriptObjectCollection[TreatmentPhase]: ...
    @TreatmentPhases.setter
    def TreatmentPhases(self, value: List[TreatmentPhase]) -> None: ...
    def AddNewAutomaticPlanningBeamSet(self, MachineLearningModelID: str, MachineLearningModelParameters: Dict[str, Any] = ..., AutoPlanningStrategyName: str = ..., PlanningIntentionName: str = ..., RoiNameMatches: Dict[str, Any] = ..., Name: str = ..., ExaminationName: str = ..., MachineName: str = ..., Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set for machine learning optimization."""
        ...
    def AddNewBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set."""
        ...
    def AddNewCyberKnifeMachineQaBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set for CyberKnife QA. Modality has to be Photons. Treatment technique has to be CyberKnife."""
        ...
    def AddNewResearchIntentBeamSet(self, Name: str, ExaminationName: str, MachineName: str, Modality: Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons'] = ..., TreatmentTechnique: Literal['Undefined', 'Conformal', 'SMLC', 'VMAT', 'DMLC', 'ProtonPencilBeamScanning', 'ProtonPencilBeamScanningArc', 'LineScanning', 'UniformScanning', 'Wobbling', 'SingleScattering', 'DoubleScattering', 'ApplicatorAndCutout', 'StaticArc', 'ConformalArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'Mixed', 'HeliumPencilBeamScanning', 'LithiumPencilBeamScanning', 'CarbonPencilBeamScanning', 'OxygenPencilBeamScanning', 'BNCT', 'HDR', 'CyberKnife', 'XRayConformal', 'XRayStaticArc', 'DirectNeutronConformal', 'DirectNeutronSMLC'] = ..., PatientPosition: Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze'] = ..., NumberOfFractions: int = ..., CreateSetupBeams: bool = ..., UseLocalizationPointAsSetupIsocenter: bool = ..., UseUserSelectedIsocenterSetupIsocenter: bool = ..., Comment: str = ..., RbeModelName: str = ..., EnableDynamicTrackingForVero: bool = ..., NewDoseSpecificationPointNames: List[str] = ..., NewDoseSpecificationPoints: List[Any] = ..., MotionSynchronizationTechniqueSettings: Union[MotionSynchronizationTechniqueSettings, Any] = ..., Custom: str = ..., ToleranceTableLabel: str = ...) -> RadiationSet:
        """Adds a new beam set with Plan intent 'Research'. For a beam set with this plan intent,"""
        ...
    def AutomaticPlanningPreprocessing(self) -> None:
        """Prepare plan for running automatic planning algorithm. Only used for automatic planning machine learning models."""
        ...
    def CopyBeamSetAndOptimizationProblemToCurrentPlan(self, RadiationSets: List[RadiationSet], ExaminationName: str) -> None:
        """Copy beam sets and associated objectives/constraints to current plan."""
        ...
    def CreateAlternativePlan(self, PlanName: str, ExaminationName: str) -> None:
        """An alternative plan is created by copying a plan and its beam sets to a different examination."""
        ...
    def EditBrachyOptimizationSettings(self, MaximumNumberOfIterations: int, OptimizationTolerance: float, DwellTimeLimits: Any) -> None:
        """Edits optimization settings for a brachy plan."""
        ...
    def EditBrachyTreatmentPlan(self, PlanName: str, PlannedBy: str = ..., Comment: str = ..., NumberOfFractions: int = ...) -> None:
        """Edits a brachy treatment plan."""
        ...
    def GetPlanUuid(self) -> Optional[str]:
        """Gets the UUID from the TreatmentPlan"""
        ...
    def GetTotalDoseGrid(self) -> DoseGrid:
        """Gets the dose grid for the total dose of the treatment plan."""
        ...
    def GetTotalDoseStructureSet(self) -> ExaminationStructureSet:
        """Gets the structure set for the total dose of the treatment plan."""
        ...
    def GetTotalPlanDoseImages(self, Orientations: List[str], Points: List[Any], FocusOnIsocenter: List[bool], ImageSize: Any, FocusOnRoi: str) -> List[str]:
        """Method for retrieving dose view images for the total plan dose."""
        ...
    def InitializeDoseTrackingFromPlan(self, TreatmentDelivery: TreatmentDelivery, DoseAccumulationExamination: Examination = ...) -> None:
        """Action for preparing a treatment plan for delivery. Will copy fractions from planning treatment course to delivery."""
        ...
    def LoadBeamSet(self, BeamSetInfo: Dict[str, Any]) -> RadiationSet:
        """Loads a beam set from a treatment plan. Returns a handle to the beam set."""
        ...
    def QueryBeamSetInfo(self, Filter: Dict[str, Any]) -> List[Any]:
        """Returns info on all beam sets on a treatment plan."""
        ...
    def SetBeamSetsToOptimizeSimultaneously(self, BeamSetNames: List[str]) -> None:
        """Sets beam sets to be optimized simultaneously"""
        ...
    def SetCurrent(self) -> None:
        """Sets the current plan."""
        ...
    def SetDefaultViewPosition(self, Coordinate: Optional[Union[Point3[float], Point3Dict[float]]] = ...) -> None:
        """Action that sets a default view positions"""
        ...
    def SetReportViewPositions(self, Coordinates: List[Any]) -> None:
        """Action that sets a collection of default view positions for a generated report"""
        ...
    def UnsetBeamSetsToOptimizeSimultaneously(self, BeamSetNames: List[str]) -> None:
        """Sets beam sets that were set to be optimized simultaneously to be optimized separately"""
        ...
    def UpdateDependency(self, DependentBeamSetName: str, BackgroundBeamSetName: str, DependencyUpdate: Literal['CreateDependency', 'RemoveDependency'] = ...) -> RadiationSet:
        """Changes the way a beam set depends on the other beam set. When a beam set is set as dependent, the other beam set dose is used as background dose."""
        ...

class AutomatedReplanningRadiationSetSettings:
    @property
    def ReplanningProtocolName(self) -> str: ...
    @ReplanningProtocolName.setter
    def ReplanningProtocolName(self, value: str) -> None: ...
    @property
    def ForRadiationSet(self) -> RadiationSet: ...

class PlanExploration:
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlannedBy(self) -> str: ...
    @PlannedBy.setter
    def PlannedBy(self, value: str) -> None: ...
    @property
    def ThumbnailDisplayState(self) -> Literal['ShowClinicalGoals', 'ShowTransversalDose']: ...
    @ThumbnailDisplayState.setter
    def ThumbnailDisplayState(self, value: Literal['ShowClinicalGoals', 'ShowTransversalDose']) -> None: ...
    @property
    def ClinicalGoalFunctions(self) -> List[Union[CompositeFunction, DoseBasedRoiFunction]]: ...
    @ClinicalGoalFunctions.setter
    def ClinicalGoalFunctions(self, value: List[Union[CompositeFunction, DoseBasedRoiFunction]]) -> None: ...
    @property
    def ExplorationFilters(self) -> ExplorationFilters: ...
    @ExplorationFilters.setter
    def ExplorationFilters(self, value: ExplorationFilters) -> None: ...
    @property
    def ExplorationPlans(self) -> ScriptObjectCollection[ExplorationPlan]: ...
    @ExplorationPlans.setter
    def ExplorationPlans(self, value: List[ExplorationPlan]) -> None: ...
    def AddClinicalGoalToPlanExploration(self, RoiName: str, GoalCriteria: Literal['AtLeast', 'AtMost'] = ..., GoalType: Literal['PlanningValue', 'AverageDose', 'VolumeAtDose', 'DoseAtVolume', 'VolumeAtGamma', 'AverageGamma', 'VolumeAtDifference', 'AverageDifference', 'DoseAtAbsoluteVolume', 'AbsoluteVolumeAtDose', 'DoseAtPoint', 'ConformityIndex', 'HomogeneityIndex'] = ..., PrimaryAcceptanceLevel: float = ..., SecondaryAcceptanceLevel: Optional[float] = ..., ParameterValue: float = ..., IsComparativeGoal: bool = ..., BeamSet: RadiationSet = ..., Priority: int = ..., AssociateToPlan: bool = ...) -> None:
        """Adds a clinical goal to a plan exploration"""
        ...
    def AddPlanToExploration(self, TreatmentPlan: TreatmentPlan) -> ExplorationPlan:
        """Add an existing treatment plan to an exploration."""
        ...
    def ApplyClinicalGoalTemplateToExploration(self, Template: TemplateTreatmentOptimization, AssociatedRoisAndPois: Dict[str, Any] = ..., ReplaceExistingClinicalGoals: bool = ...) -> None:
        """Copies clinical goals from a template."""
        ...
    def ComputePlanExplorationDoses(self) -> None:
        """Computes final dose for all exploration plans feasible for dose computation."""
        ...
    def CopyClinicalGoalInPlanExploration(self, FunctionToCopy: DoseBasedRoiFunction) -> None:
        """Action for duplicating an existing plan exploration clinical goal"""
        ...
    def DeleteClinicalGoalFromExploration(self, FunctionToRemove: DoseBasedRoiFunction) -> None:
        """Deletes a clinical goal."""
        ...
    def DeletePlanExploration(self) -> None:
        """Deletes a plan exploration."""
        ...
    def EditClinicalGoalInPlanExploration(self, FunctionToEdit: DoseBasedRoiFunction, RoiName: str, GoalCriteria: Literal['AtLeast', 'AtMost'] = ..., GoalType: Literal['PlanningValue', 'AverageDose', 'VolumeAtDose', 'DoseAtVolume', 'VolumeAtGamma', 'AverageGamma', 'VolumeAtDifference', 'AverageDifference', 'DoseAtAbsoluteVolume', 'AbsoluteVolumeAtDose', 'DoseAtPoint', 'ConformityIndex', 'HomogeneityIndex'] = ..., PrimaryAcceptanceLevel: float = ..., SecondaryAcceptanceLevel: Optional[float] = ..., ParameterValue: float = ..., IsComparativeGoal: bool = ..., BeamSet: RadiationSet = ..., Priority: int = ..., AssociateToPlan: bool = ...) -> None:
        """Action for editing a clinical goal."""
        ...
    def EditPlanExploration(self, Name: str, Description: str = ..., PlannedBy: str = ...) -> None:
        """Edits a plan exploration."""
        ...
    def EvaluateClinicalGoals(self) -> None:
        """Evaluates all clinical goals."""
        ...
    def ResetExplorationFilters(self) -> None:
        """Resets the current value of all exploration filters to default and resets the filter limits (max and min) of clinical goal filters to default."""
        ...
    def ScaleFiltersToSelectedPlans(self, ExplorationPlans: List[ExplorationPlan]) -> None:
        """Sets the filter limit (max and min) for clinical goals in a plan exploration to the max or min clinical goal value of the specified exploration plans."""
        ...

class ExplorationPlan:
    @property
    def IsCandidate(self) -> bool: ...
    @IsCandidate.setter
    def IsCandidate(self, value: bool) -> None: ...
    @property
    def ClinicalGoals(self) -> ScriptObjectCollection[ClinicalGoal]: ...
    @ClinicalGoals.setter
    def ClinicalGoals(self, value: List[ClinicalGoal]) -> None: ...
    @property
    def ForTreatmentPlan(self) -> TreatmentPlan: ...
    @ForTreatmentPlan.setter
    def ForTreatmentPlan(self, value: TreatmentPlan) -> None: ...
    @property
    def InPlanExploration(self) -> PlanExploration: ...
    @InPlanExploration.setter
    def InPlanExploration(self, value: PlanExploration) -> None: ...
    @property
    def OptimizationProtocol(self) -> PlanGenerationProtocol: ...
    @OptimizationProtocol.setter
    def OptimizationProtocol(self, value: PlanGenerationProtocol) -> None: ...
    def RemovePlanFromExploration(self) -> None:
        """Removes the plan from the exploration."""
        ...
    def SetIsCandidate(self, IsCandidate: bool) -> None:
        """Sets the status of the IsCandidate flag of an exploration plan."""
        ...

class PlanGenerationProtocol:
    @property
    def Approved(self) -> bool: ...
    @Approved.setter
    def Approved(self, value: bool) -> None: ...
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def Disease(self) -> str: ...
    @Disease.setter
    def Disease(self, value: str) -> None: ...
    @property
    def IsAutomatedReplanningProtocol(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> None: ...
    def Unload(self) -> None:
        """Unloads the plan generation protocol"""
        ...

class BackupPlanProtocol:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlanGenerationProtocols(self) -> ScriptObjectCollection[PlanGenerationProtocol]: ...
    @PlanGenerationProtocols.setter
    def PlanGenerationProtocols(self, value: List[PlanGenerationProtocol]) -> None: ...
    def Unload(self) -> bool:
        """Unloads the selected backup protocol. Changes must be saved prior to unloading. Do not use the protocol after unloading."""
        ...
