from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.patient_db_types import Cycle



class Regimen:
    @property
    def Intent(self) -> Literal['Curative', 'Palliative', 'Adjuvant', 'Neoadjuvant', 'DiseaseModification', 'Other']: ...
    @property
    def Name(self) -> str: ...
    @property
    def Cycles(self) -> ScriptObjectCollection[Cycle]: ...
    @Cycles.setter
    def Cycles(self, value: List[Cycle]) -> None: ...
    @property
    def RegimenTemplateReference(self) -> RegimenTemplateReference: ...
    @RegimenTemplateReference.setter
    def RegimenTemplateReference(self, value: RegimenTemplateReference) -> None: ...

class RegimenTemplateReference:
    @property
    def OriginReferenceId(self) -> str: ...
    @property
    def RegimenTemplateAggregateId(self) -> str: ...

class RegimenTemplate:
    @property
    def CommissionedBy(self) -> str: ...
    @property
    def CommissionTime(self) -> Optional[str]: ...
    @property
    def Contraindications(self) -> str: ...
    @property
    def Indications(self) -> str: ...
    @property
    def Intent(self) -> Literal['Curative', 'Palliative', 'Adjuvant', 'Neoadjuvant', 'DiseaseModification', 'Other']: ...
    @property
    def IsCommissioned(self) -> bool: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Sites(self) -> ScriptObjectCollection[str]: ...
    @property
    def Cycles(self) -> ScriptObjectCollection[Cycle]: ...
    @Cycles.setter
    def Cycles(self, value: List[Cycle]) -> None: ...
