from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.dose import DoseGrid, DoseReferenceIdentifier
    from raystation.v2025.machine_db_types import Material
    from raystation.v2025.patient_db_types import AlgorithmVersion, BinaryRoi, DeformableStructureRegistration, DerivedRoiStatus, DicomImportHistory, EqdValues, Examination, ExpandContractExpressionNode, GeneratedGeometryStatus, InternalGeometryExpressionNode, MbsMesh, OperatorExpressionNode, RegionOfInterest, Review, SurfaceScanInfo, TriangleMesh, TriangulationParametersData, WallExpressionNode
    from raystation.v2025.plan import TreatmentPlan



class RoiSpecificEqd:
    @property
    def EqdValues(self) -> EqdValues: ...
    @property
    def ForRoi(self) -> RegionOfInterest: ...

class RoiPrescriptionDoseReference:
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def DoseAbsoluteVolume(self) -> float: ...
    @DoseAbsoluteVolume.setter
    def DoseAbsoluteVolume(self, value: float) -> None: ...
    @property
    def DoseValue(self) -> float: ...
    @DoseValue.setter
    def DoseValue(self, value: float) -> None: ...
    @property
    def DoseVolume(self) -> float: ...
    @DoseVolume.setter
    def DoseVolume(self, value: float) -> None: ...
    @property
    def IsDeprecatedPrescriptionRelatingToBackgroundDose(self) -> bool: ...
    @property
    def PrescriptionType(self) -> Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose']: ...
    @property
    def RelativePrescriptionLevel(self) -> float: ...
    @RelativePrescriptionLevel.setter
    def RelativePrescriptionLevel(self, value: float) -> None: ...
    @property
    def DoseReferenceIdentifier(self) -> DoseReferenceIdentifier: ...
    @property
    def OnStructure(self) -> RegionOfInterest: ...
    @OnStructure.setter
    def OnStructure(self, value: RegionOfInterest) -> None: ...
    def DeletePrescriptionDoseReference(self) -> None:
        """Deletes the prescription dose reference"""
        ...
    def EditRoiPrescriptionDoseReference(self, RoiName: str = ..., PoiName: str = ..., DoseVolume: float = ..., PrescriptionType: Literal['AverageDose', 'DoseAtVolume', 'DoseAtAbsoluteVolume', 'DoseAtPoint', 'NearMinimumDose', 'NearMaximumDose', 'MedianDose'] = ..., Description: str = ..., DoseValue: float = ..., RelativePrescriptionLevel: float = ...) -> None:
        """Edits a prescription dose reference in the beam set prescription."""
        ...
    def SetPrimaryPrescriptionDoseReference(self) -> None:
        """Sets the prescription dose reference as primary."""
        ...

class RoiVolumeDistribution:
    @property
    def RelativeVolumes(self) -> np.ndarray: ...
    @RelativeVolumes.setter
    def RelativeVolumes(self, value: np.ndarray) -> None: ...
    @property
    def TotalVolume(self) -> float: ...
    @TotalVolume.setter
    def TotalVolume(self, value: float) -> None: ...
    @property
    def VoxelIndices(self) -> np.ndarray: ...
    @VoxelIndices.setter
    def VoxelIndices(self, value: np.ndarray) -> None: ...
    @property
    def AlgorithmVersion(self) -> AlgorithmVersion: ...
    @AlgorithmVersion.setter
    def AlgorithmVersion(self, value: AlgorithmVersion) -> None: ...

class RoiMaterial:
    @property
    def OfMaterial(self) -> Material: ...
    @OfMaterial.setter
    def OfMaterial(self, value: Material) -> None: ...

class RoiExpressionNode:
    @property
    def Children(self) -> List[Union[ExpandContractExpressionNode, InternalGeometryExpressionNode, OperatorExpressionNode, RoiExpressionNode, WallExpressionNode]]: ...
    @Children.setter
    def Children(self, value: List[Union[ExpandContractExpressionNode, InternalGeometryExpressionNode, OperatorExpressionNode, RoiExpressionNode, WallExpressionNode]]) -> None: ...
    @property
    def RegionOfInterest(self) -> RegionOfInterest: ...
    @RegionOfInterest.setter
    def RegionOfInterest(self, value: RegionOfInterest) -> None: ...

class RoiGeometry:
    @property
    def DicomImportHistory(self) -> DicomImportHistory: ...
    @DicomImportHistory.setter
    def DicomImportHistory(self, value: DicomImportHistory) -> None: ...
    @property
    def GeneratedGeometryStatus(self) -> GeneratedGeometryStatus: ...
    @GeneratedGeometryStatus.setter
    def GeneratedGeometryStatus(self, value: GeneratedGeometryStatus) -> None: ...
    @property
    def OfRoi(self) -> RegionOfInterest: ...
    @OfRoi.setter
    def OfRoi(self, value: RegionOfInterest) -> None: ...
    @property
    def PrimaryShape(self) -> Union[BinaryRoi, MbsMesh, RoiContourSet, TriangleMesh]: ...
    @PrimaryShape.setter
    def PrimaryShape(self, value: Union[BinaryRoi, MbsMesh, RoiContourSet, TriangleMesh]) -> None: ...
    @property
    def SurfaceScanInfo(self) -> SurfaceScanInfo: ...
    @SurfaceScanInfo.setter
    def SurfaceScanInfo(self, value: SurfaceScanInfo) -> None: ...
    def DeleteRoiGeometry(self) -> None:
        """Deletes the geometry of a region of interest."""
        ...
    def EditEyeExternal(self, RightLeftMargin: float = ..., InferiorSuperiorMargin: float = ..., PosteriorAnteriorMargin: float = ...) -> None:
        """Edits an eye model-aligned external box geometry that covers the eye model with a margin."""
        ...
    def ExportRoiGeometryAsMetaImage(self, MetaFileName: str, Unit: Literal['None', 'Millimeter', 'Centimeter', 'Grey', 'Centigrey', 'Percent', 'Fraction', 'GramPerCm3', 'Degrees', 'MeV', 'CubicCentimeter', 'MV', 'Particles', 'GigaParticles', 'Meter', 'MegaParticles', 'Second', 'Millisecond', 'Milligram', 'Kilogram', 'MeVPerCm', 'KeVPerMicrometer', 'MeVPerA', 'Gram', 'Minute', 'MU', 'Watt'], AsExamination: bool = ...) -> None:
        """Export an ROI geometry (using its voxel representation) as meta image file (http://www.itk.org/Wiki/ITK/MetaIO/Documentation)."""
        ...
    def ExportRoiGeometryAsSTL(self, DestinationDirectory: str, OutputUnit: Literal['None', 'Millimeter', 'Centimeter', 'Grey', 'Centigrey', 'Percent', 'Fraction', 'GramPerCm3', 'Degrees', 'MeV', 'CubicCentimeter', 'MV', 'Particles', 'GigaParticles', 'Meter', 'MegaParticles', 'Second', 'Millisecond', 'Milligram', 'Kilogram', 'MeVPerCm', 'KeVPerMicrometer', 'MeVPerA', 'Gram', 'Minute', 'MU', 'Watt'] = ...) -> None:
        """Export the geometry as a triangle mesh on the binary STL file format. The color is written in VisCAM/SolidView style."""
        ...
    def GenerateTumorModelGeometry(self) -> None:
        """Generates the geometry for a tumor model."""
        ...
    def GetBoundingBox(self) -> List[Any]:
        """Gets the bounding box of the ROI geometry."""
        ...
    def GetCenterOfRoi(self) -> Tuple[float, ...]:
        """Gets the ROI center of mass."""
        ...
    def GetConnectedComponents(self, MaxVolume: float = ..., MinVolume: float = ..., MaxNumberOfComponents: int = ...) -> None:
        """Action for extracting 26-connected components from a geometry."""
        ...
    def GetCoordinateForMaxGrayLevel(self) -> Tuple[float, ...]:
        """Gets the coordinate for the voxel inside an ROI which has the highest graylevel."""
        ...
    def GetDependentRois(self) -> List[str]:
        """Gets the name of all ROIs included in the derived ROI expression."""
        ...
    def GetRoiGeometryAsVoxels(self, Corner: Any = ..., VoxelSize: Any = ..., NrVoxels: Any = ...) -> np.ndarray:
        """Returns a voxel representation of the RoiGeometry. The voxels are resampled on the supplied grid, defined in the DICOM patient coordinate system. Voxel values are in the range 0-255 depending on how much of the voxel that is covered by the ROI (0 - none, 255 - full coverage)."""
        ...
    def GetRoiVolume(self) -> float:
        """Gets the volume of the RoiGeometry. This volume is calculated on a high-resolution geometry specific voxelization grid and is independent of dose grid discretization."""
        ...
    def HasContours(self) -> bool:
        """Returns true if PrimaryShape has contours."""
        ...
    def ImportRoiGeometryFromSTL(self, FileName: str, UnitInFile: Literal['None', 'Millimeter', 'Centimeter', 'Grey', 'Centigrey', 'Percent', 'Fraction', 'GramPerCm3', 'Degrees', 'MeV', 'CubicCentimeter', 'MV', 'Particles', 'GigaParticles', 'Meter', 'MegaParticles', 'Second', 'Millisecond', 'Milligram', 'Kilogram', 'MeVPerCm', 'KeVPerMicrometer', 'MeVPerA', 'Gram', 'Minute', 'MU', 'Watt'] = ..., TransformationMatrix: Optional[Union[Matrix4, Matrix4Dict]] = ...) -> None:
        """Import a mesh from a binary STL file to the given ROI geometry. The geometry must be empty."""
        ...
    def IsRoiGeometryEditable(self) -> bool:
        """Returns true if RoiGeometry can be edited"""
        ...
    def KeepConnectedComponent3D(self, Point: Any) -> None:
        """Action for keeping a 26-connected 3D component of a geometry based on a user selected point placed inside the component."""
        ...
    def SetRepresentation(self, Representation: str) -> None:
        """Primary shape of the ROI geometry will (if necessary) be changed to the selected representation. Representation can be:"""
        ...

class RoiContourSet:
    @property
    def Contours(self) -> ScriptObjectCollection[Any]: ...
    @Contours.setter
    def Contours(self, value: List[Any]) -> None: ...
    @property
    def IsClosed(self) -> bool: ...
    @IsClosed.setter
    def IsClosed(self, value: bool) -> None: ...
    @property
    def LineType(self) -> Literal['PolyLine', 'CardinalSpline', 'CubicBSpline']: ...
    @LineType.setter
    def LineType(self, value: Literal['PolyLine', 'CardinalSpline', 'CubicBSpline']) -> None: ...
    @property
    def DerivedRoiStatus(self) -> DerivedRoiStatus: ...
    @DerivedRoiStatus.setter
    def DerivedRoiStatus(self, value: DerivedRoiStatus) -> None: ...

class StructureRegistrationGroup:
    @property
    def Name(self) -> str: ...
    @property
    def DeformableStructureRegistrations(self) -> ScriptObjectCollection[DeformableStructureRegistration]: ...
    @DeformableStructureRegistrations.setter
    def DeformableStructureRegistrations(self, value: List[DeformableStructureRegistration]) -> None: ...
    @property
    def RegisteredPois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @RegisteredPois.setter
    def RegisteredPois(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def RegisteredRois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @RegisteredRois.setter
    def RegisteredRois(self, value: List[RegionOfInterest]) -> None: ...
    def ExpandDeformationGrid(self, TargetExaminationNames: List[str], CreateNewGroup: bool = ..., NewGroupName: str = ..., MaxNumberOfIterations: int = ..., TreatmentPlan: TreatmentPlan = ..., SuperiorInferiorMargin: float = ..., AnteriorPosteriorMargin: float = ..., RightLeftMargin: float = ...) -> None:
        """Expands an existing deformation grid to a desired grid + an optional margin. No resampling is made, the original resolution is used."""
        ...
    def RenameStructureRegistrationGroup(self, NewName: str) -> None:
        """Rename a registration group, and all registrations in the group that were named from the registration group name."""
        ...

class RoiBasedDeformableRegistrationGroup:
    @property
    def Name(self) -> str: ...
    @property
    def DeformableStructureRegistrations(self) -> ScriptObjectCollection[DeformableStructureRegistration]: ...
    @DeformableStructureRegistrations.setter
    def DeformableStructureRegistrations(self, value: List[DeformableStructureRegistration]) -> None: ...
    @property
    def RegisteredPois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @RegisteredPois.setter
    def RegisteredPois(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def RegisteredRois(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @RegisteredRois.setter
    def RegisteredRois(self, value: List[RegionOfInterest]) -> None: ...
    def ExpandDeformationGrid(self, TargetExaminationNames: List[str], CreateNewGroup: bool = ..., NewGroupName: str = ..., MaxNumberOfIterations: int = ..., TreatmentPlan: TreatmentPlan = ..., SuperiorInferiorMargin: float = ..., AnteriorPosteriorMargin: float = ..., RightLeftMargin: float = ...) -> None:
        """Expands an existing deformation grid to a desired grid + an optional margin. No resampling is made, the original resolution is used."""
        ...
    def RenameStructureRegistrationGroup(self, NewName: str) -> None:
        """Rename a registration group, and all registrations in the group that were named from the registration group name."""
        ...

class RoiVisualizationSettings:
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> None: ...
    @property
    def ShowDRRContours(self) -> bool: ...
    @ShowDRRContours.setter
    def ShowDRRContours(self, value: bool) -> None: ...
    @property
    def VisualizationMode2D(self) -> Literal['Contour', 'Filled', 'FilledContour', 'Off']: ...
    @VisualizationMode2D.setter
    def VisualizationMode2D(self, value: Literal['Contour', 'Filled', 'FilledContour', 'Off']) -> None: ...
    @property
    def VisualizationMode3D(self) -> Literal['Shaded', 'Wireframe', 'ShadedWireframe', 'SemiTransparent', 'Off']: ...
    @VisualizationMode3D.setter
    def VisualizationMode3D(self, value: Literal['Shaded', 'Wireframe', 'ShadedWireframe', 'SemiTransparent', 'Off']) -> None: ...
    @property
    def VisualizationModeBEV(self) -> Literal['Contour', 'Shaded', 'Wireframe', 'ShadedWireframe', 'Off']: ...
    @VisualizationModeBEV.setter
    def VisualizationModeBEV(self, value: Literal['Contour', 'Shaded', 'Wireframe', 'ShadedWireframe', 'Off']) -> None: ...

class RoiGeometryReference:
    @property
    def RoiGeometryInOtherCase(self) -> RoiGeometry: ...
    @RoiGeometryInOtherCase.setter
    def RoiGeometryInOtherCase(self, value: RoiGeometry) -> None: ...
    @property
    def RoiInThisCase(self) -> RegionOfInterest: ...
    @RoiInThisCase.setter
    def RoiInThisCase(self, value: RegionOfInterest) -> None: ...

class StructureRegistration:
    @property
    def DefaultForDoseDeformation(self) -> bool: ...
    @property
    def DeformationMatrix(self) -> np.ndarray: ...
    @DeformationMatrix.setter
    def DeformationMatrix(self, value: np.ndarray) -> None: ...
    @property
    def Description(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def RigidTransformationMatrix(self) -> np.ndarray: ...
    @RigidTransformationMatrix.setter
    def RigidTransformationMatrix(self, value: np.ndarray) -> None: ...
    @property
    def DeformationGrid(self) -> DoseGrid: ...
    @DeformationGrid.setter
    def DeformationGrid(self, value: DoseGrid) -> None: ...
    @property
    def FromExamination(self) -> Examination: ...
    @FromExamination.setter
    def FromExamination(self, value: Examination) -> None: ...
    @property
    def Review(self) -> Review: ...
    @Review.setter
    def Review(self, value: Review) -> None: ...
    @property
    def ToExamination(self) -> Examination: ...
    @ToExamination.setter
    def ToExamination(self, value: Examination) -> None: ...
    def ExportDeformedMetaImage(self, MetaFileName: str, Unit: Literal['None', 'Millimeter', 'Centimeter', 'Grey', 'Centigrey', 'Percent', 'Fraction', 'GramPerCm3', 'Degrees', 'MeV', 'CubicCentimeter', 'MV', 'Particles', 'GigaParticles', 'Meter', 'MegaParticles', 'Second', 'Millisecond', 'Milligram', 'Kilogram', 'MeVPerCm', 'KeVPerMicrometer', 'MeVPerA', 'Gram', 'Minute', 'MU', 'Watt']) -> None:
        """Export a deformed image as a meta image file (http://www.itk.org/Wiki/ITK/MetaIO/Documentation)."""
        ...
    def RenameStructureRegistration(self, NewName: str, Description: str = ...) -> None:
        """Rename a rigid or deformable registration, optionally adding or updating the description of the registration as well."""
        ...

class RoiOverlapMeasures:
    @property
    def DiceSimilarityCoefficient(self) -> float: ...
    @property
    def Precision(self) -> float: ...
    @property
    def Specificity(self) -> float: ...
    @property
    def Sensitivity(self) -> float: ...
    @property
    def MeanDistanceToAgreement(self) -> float: ...
    @property
    def MaxDistanceToAgreement(self) -> float: ...

class RoiMeshingData:
    @property
    def RoiName(self) -> str: ...
    @property
    def TriangulationParameters(self) -> TriangulationParametersData: ...
    @property
    def Priority(self) -> int: ...
