from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ElectronBeam, PhotonBeam
    from raystation.v2025.imaging import ImageExportData, ImagerReceptor
    from raystation.v2025.ion import IonBeam
    from raystation.v2025.machine import MachineReference
    from raystation.v2025.machine_db_types import MlcLayer
    from raystation.v2025.patient import PatientToBeamMapping
    from raystation.v2025.patient_db_types import Block, BnctBeam, Compensator, RegionOfInterest, Segment



class SetupCorrection:
    @property
    def CouchRotationAngle(self) -> float: ...
    @CouchRotationAngle.setter
    def CouchRotationAngle(self, value: float) -> None: ...
    @property
    def CouchRotationAxis(self) -> Tuple[float, ...]: ...
    @CouchRotationAxis.setter
    def CouchRotationAxis(self, value: Tuple[float, ...]) -> None: ...
    @property
    def CouchTranslation(self) -> Tuple[float, ...]: ...
    @CouchTranslation.setter
    def CouchTranslation(self, value: Tuple[float, ...]) -> None: ...

class SetupBeam:
    @property
    def ArcRotationDirection(self) -> Literal['None', 'Clockwise', 'CounterClockwise']: ...
    @property
    def ArcStopGantryAngle(self) -> Optional[float]: ...
    @property
    def BeamMU(self) -> float: ...
    @BeamMU.setter
    def BeamMU(self, value: float) -> None: ...
    @property
    def BeamQualityId(self) -> str: ...
    @BeamQualityId.setter
    def BeamQualityId(self, value: str) -> None: ...
    @property
    def CouchPitchAngle(self) -> float: ...
    @CouchPitchAngle.setter
    def CouchPitchAngle(self, value: float) -> None: ...
    @property
    def CouchRollAngle(self) -> float: ...
    @CouchRollAngle.setter
    def CouchRollAngle(self, value: float) -> None: ...
    @property
    def CouchRotationAngle(self) -> float: ...
    @CouchRotationAngle.setter
    def CouchRotationAngle(self, value: float) -> None: ...
    @property
    def CreatedDuringOptimization(self) -> bool: ...
    @property
    def DeliveryTechnique(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def GantryAngle(self) -> float: ...
    @GantryAngle.setter
    def GantryAngle(self, value: float) -> None: ...
    @property
    def InitialCollimatorAngle(self) -> float: ...
    @property
    def InitialJawPositions(self) -> np.ndarray: ...
    @property
    def MachineReference(self) -> MachineReference: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Number(self) -> int: ...
    @Number.setter
    def Number(self, value: int) -> None: ...
    @property
    def PatientPosition(self) -> Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']: ...
    @property
    def PlanGenerationTechnique(self) -> Optional[Literal['Imrt', 'Conformal', 'Mixed']]: ...
    @PlanGenerationTechnique.setter
    def PlanGenerationTechnique(self, value: Optional[Literal['Imrt', 'Conformal', 'Mixed']]) -> None: ...
    @property
    def SetupImagingSystemName(self) -> str: ...
    @SetupImagingSystemName.setter
    def SetupImagingSystemName(self, value: str) -> None: ...
    @property
    def Blocks(self) -> ScriptObjectCollection[Block]: ...
    @Blocks.setter
    def Blocks(self, value: List[Block]) -> None: ...
    @property
    def Boli(self) -> ScriptObjectCollection[RegionOfInterest]: ...
    @Boli.setter
    def Boli(self, value: List[RegionOfInterest]) -> None: ...
    @property
    def Compensator(self) -> Compensator: ...
    @Compensator.setter
    def Compensator(self, value: Compensator) -> None: ...
    @property
    def Isocenter(self) -> PatientToBeamMapping: ...
    @property
    def LowerLayer(self) -> MlcLayer: ...
    @property
    def Segments(self) -> ScriptObjectCollection[Segment]: ...
    @Segments.setter
    def Segments(self, value: List[Segment]) -> None: ...
    @property
    def UpperLayer(self) -> MlcLayer: ...
    def ClearTreatOrProtectRoi(self, RoiName: str) -> None:
        """Clear ROI from Treat or Protect usage for the beam."""
        ...
    def ConformBlock(self) -> None:
        """Generates a block aperture according to the treat and protect settings."""
        ...
    def ConformMlc(self) -> None:
        """Generates a MLC aperture according to the treat and protect settings."""
        ...
    def CreateRectangularField(self, Width: float = ..., Height: float = ..., CenterCoordinate: Any = ..., MoveMLC: bool = ..., MoveAllMLCLeaves: bool = ..., MoveJaw: bool = ..., JawMargins: Any = ..., DeleteWedge: bool = ..., PreventExtraLeafPairFromOpening: bool = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Creates rectangular field."""
        ...
    def DeleteArcTrajectory(self) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Deletes the arc trajectory on a beam."""
        ...
    def DeleteSegment(self, SegmentNumber: int = ...) -> None:
        """Deletes a segment."""
        ...
    def EditBeamLeafPositions(self, LeafPositions: np.ndarray) -> None:
        """Action for updating leaf positions for all segments of a beam"""
        ...
    def GetBEVImage(self, ShowFluence: bool) -> str:
        """Method for retrieving BEV image for a beam."""
        ...
    def GetDRRImage(self) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetDRRImageForSegment(self, SegmentIndex: int) -> str:
        """Method for retrieving DRR image for a treatment beam or a setup beam."""
        ...
    def GetSourceToSkinDistance(self) -> float:
        """Method for retrieving the source-to-skin distance for photon and electron beams."""
        ...
    def GetSourceToSurfaceDistance(self) -> float:
        """Method for retrieving the source-to-surface distance for photon and electron beams."""
        ...
    def SetArcTrajectory(self, GantryAngles: np.ndarray, CouchAngles: np.ndarray, CollimatorAngles: np.ndarray, ArcRotationDirection: Literal['None', 'Clockwise', 'CounterClockwise'] = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the arc trajectory on a beam."""
        ...
    def SetArcTrajectoryFromTemplate(self, NameOfTemplate: str) -> None:
        """Sets the arc trajectory on a beam from a template."""
        ...
    def SetBolus(self, BolusName: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets the bolus with name BolusName on this photon beam. Returns the beam."""
        ...
    def SetDoseSpecificationPoint(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Select a dose specification point for this beam."""
        ...
    def SetInitialJawPositions(self, X1: float = ..., X2: float = ..., Y1: float = ..., Y2: float = ...) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets initial jaw positions to the beam."""
        ...
    def SetIsocenter(self, Name: str) -> Union[BnctBeam, ElectronBeam, IonBeam, PhotonBeam, SetupBeam]:
        """Sets an isocenter to a beam. If the name of the isocenter does not exist, a new isocenter will be created."""
        ...
    def SetIsocenterToMidpointInExternal(self) -> None:
        """Sets the isocenter for a beam to the midplane of the patient (external)."""
        ...
    def SetTreatOrProtectRoi(self, TopMargin: float = ..., BottomMargin: float = ..., LeftMargin: float = ..., RightMargin: float = ..., RoiName: str = ...) -> None:
        """Select to use ROI as Treat or Protect."""
        ...

class SetupMargins:
    @property
    def LateralLowerMargin(self) -> float: ...
    @LateralLowerMargin.setter
    def LateralLowerMargin(self, value: float) -> None: ...
    @property
    def LateralUpperMargin(self) -> float: ...
    @LateralUpperMargin.setter
    def LateralUpperMargin(self, value: float) -> None: ...
    @property
    def LongitudinalLowerMargin(self) -> float: ...
    @LongitudinalLowerMargin.setter
    def LongitudinalLowerMargin(self, value: float) -> None: ...
    @property
    def LongitudinalUpperMargin(self) -> float: ...
    @LongitudinalUpperMargin.setter
    def LongitudinalUpperMargin(self, value: float) -> None: ...
    @property
    def PitchLowerMargin(self) -> float: ...
    @PitchLowerMargin.setter
    def PitchLowerMargin(self, value: float) -> None: ...
    @property
    def PitchUpperMargin(self) -> float: ...
    @PitchUpperMargin.setter
    def PitchUpperMargin(self, value: float) -> None: ...
    @property
    def RollLowerMargin(self) -> float: ...
    @RollLowerMargin.setter
    def RollLowerMargin(self, value: float) -> None: ...
    @property
    def RollUpperMargin(self) -> float: ...
    @RollUpperMargin.setter
    def RollUpperMargin(self, value: float) -> None: ...
    @property
    def VerticalLowerMargin(self) -> float: ...
    @VerticalLowerMargin.setter
    def VerticalLowerMargin(self, value: float) -> None: ...
    @property
    def VerticalUpperMargin(self) -> float: ...
    @VerticalUpperMargin.setter
    def VerticalUpperMargin(self, value: float) -> None: ...
    @property
    def YawLowerMargin(self) -> float: ...
    @YawLowerMargin.setter
    def YawLowerMargin(self, value: float) -> None: ...
    @property
    def YawUpperMargin(self) -> float: ...
    @YawUpperMargin.setter
    def YawUpperMargin(self, value: float) -> None: ...
    def ResetSetupMargins(self) -> None:
        """Resets the setup margins to default."""
        ...

class SetupBeamsSettings:
    @property
    def UseSetupBeams(self) -> bool: ...
    @property
    def UseLocalizationPointAsSetupIsocenter(self) -> bool: ...
    @property
    def UseUserSelectedIsocenterAsSetupIsocenter(self) -> bool: ...

class SetupImagingSystem:
    @property
    def DefaultSetupBeamGantryAngle(self) -> Optional[float]: ...
    @property
    def Name(self) -> str: ...
    @property
    def UseForTreatmentBeamDRRs(self) -> bool: ...
    @property
    def SetupImagers(self) -> List[Union[SetupImagerFixedInRoom, SetupImagerGantryMounted]]: ...

class SetupImagerFixedInRoom:
    @property
    def FixedGantryAngle(self) -> float: ...
    @property
    def FixedGantryPitchAngle(self) -> float: ...
    @property
    def FixedImageReceptorAngle(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def SourceAxisDistance(self) -> float: ...
    @property
    def ImageExportData(self) -> ImageExportData: ...
    @property
    def ImagerReceptor(self) -> ImagerReceptor: ...

class SetupImagerGantryMounted:
    @property
    def ImagingGantryAngleOffset(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def SourceAxisDistance(self) -> float: ...
    @property
    def ImageExportData(self) -> ImageExportData: ...
    @property
    def ImagerReceptor(self) -> ImagerReceptor: ...
