from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import ArcTrajectory
    from raystation.v2025.beam_set import TreatmentSetup
    from raystation.v2025.dose import DoseDependencyStringArgs
    from raystation.v2025.imaging import ImageRegionStatistics
    from raystation.v2025.machine import MachineReference
    from raystation.v2025.machine_db_types import Material
    from raystation.v2025.ml import FileImportLog
    from raystation.v2025.optimization import OptimizationProblem
    from raystation.v2025.patient import PatientModel
    from raystation.v2025.patient_db_types import ApprovalInformation, BaseToleranceTable, ColorMap, ContractInformation, EvaluationSetup, Examination, HybridDeformableRegistrationInfo, OrganToFunctionMap, RegionOfInterest, ResponseFunctionParameters, RigidRegistrationInfo, TriangleMesh



class TemplateArcTrajectory:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ArcTrajectory(self) -> ArcTrajectory: ...
    @ArcTrajectory.setter
    def ArcTrajectory(self, value: ArcTrajectory) -> None: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @FileImportLog.setter
    def FileImportLog(self, value: FileImportLog) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateBrachyDwellTimeDistribution:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    @property
    def TemplateBrachyChannels(self) -> ScriptObjectCollection[TemplateBrachyChannel]: ...
    @TemplateBrachyChannels.setter
    def TemplateBrachyChannels(self, value: List[TemplateBrachyChannel]) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and releases locks."""
        ...

class TemplateBrachyChannel:
    @property
    def ChannelNumber(self) -> int: ...
    @ChannelNumber.setter
    def ChannelNumber(self, value: int) -> None: ...
    @property
    def DwellTimes(self) -> np.ndarray: ...
    @DwellTimes.setter
    def DwellTimes(self, value: np.ndarray) -> None: ...

class TemplateColorMap:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Type(self) -> Literal['Dose', 'DoseDifference', 'Fluence', 'FluenceDifference', 'Response', 'ResponseDifference', 'Gamma', 'Compensator', 'DisplacementField', 'Pet', 'Rbe', 'Let', 'LetDifference']: ...
    @Type.setter
    def Type(self, value: Literal['Dose', 'DoseDifference', 'Fluence', 'FluenceDifference', 'Response', 'ResponseDifference', 'Gamma', 'Compensator', 'DisplacementField', 'Pet', 'Rbe', 'Let', 'LetDifference']) -> None: ...
    @property
    def ColorMap(self) -> ColorMap: ...
    @ColorMap.setter
    def ColorMap(self, value: ColorMap) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateMaterial:
    @property
    def IsAvailableForPlanning(self) -> bool: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @FileImportLog.setter
    def FileImportLog(self, value: FileImportLog) -> None: ...
    @property
    def Material(self) -> Material: ...
    @Material.setter
    def Material(self, value: Material) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateMbsModel:
    @property
    def Alignment(self) -> Literal['Undefined', 'Left', 'Right', 'Upper', 'Lower']: ...
    @property
    def CaseType(self) -> Literal['General', 'PelvicMale', 'PelvicFemale', 'PelvicOther', 'HeadNeck', 'Thorax', 'Abdomen']: ...
    @property
    def Description(self) -> str: ...
    @property
    def DisplayColor(self) -> str: ...
    @property
    def EigenValues(self) -> np.ndarray: ...
    @property
    def EigenVectors(self) -> ScriptObjectCollection[Any]: ...
    @property
    def Gender(self) -> Literal['Female', 'Male', 'Other', 'Unknown']: ...
    @property
    def IsDeprecated(self) -> bool: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def ModelId(self) -> str: ...
    @property
    def ModelVersion(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def NumberOfProfileSamples(self) -> int: ...
    @property
    def SampleDistance(self) -> float: ...
    @property
    def Structure(self) -> Literal['Bladder', 'Prostate', 'Rectum', 'Cervix', 'Uterus', 'Vagina', 'FemoralHead', 'Pelvis', 'BrainStem', 'SpinalCord', 'ParotidGland', 'Mandible', 'Lung', 'Other', 'Balloon', 'Tumor', 'Outline', 'Kidney', 'Brain', 'Medulla', 'Eye', 'Liver', 'Spleen', 'Pancreas', 'Gallbladder', 'Duodenum', 'Stomach']: ...
    @property
    def TextureInfo(self) -> np.ndarray: ...
    @property
    def TextureInfoModality(self) -> Literal['CT', 'MR', 'Cbct', 'Pet', 'Undefined']: ...
    @property
    def VertexTrackerSettings(self) -> Dict[str, Any]: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @FileImportLog.setter
    def FileImportLog(self, value: FileImportLog) -> None: ...
    @property
    def ModelMesh(self) -> TriangleMesh: ...
    @ModelMesh.setter
    def ModelMesh(self, value: TriangleMesh) -> None: ...
    def SetImageRegionStatisticsUsingWriteLock(self, ImageRegionStatistics: Union[ImageRegionStatistics, Any]) -> None:
        """Sets ImageRegionStatistics for a templatembsmodel"""
        ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplatePatientModel:
    @property
    def Description(self) -> str: ...
    @property
    def InitializationType(self) -> Literal['Undefined', 'GeometriesFromTemplate', 'EmptyGeometries', 'GeometriesFromTemplateAndUseRigidRegistration', 'GeometriesFromTemplateAndUseDeformableRegistration', 'AtlasBased']: ...
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    @property
    def ContractInformation(self) -> ContractInformation: ...
    @ContractInformation.setter
    def ContractInformation(self, value: ContractInformation) -> None: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @FileImportLog.setter
    def FileImportLog(self, value: FileImportLog) -> None: ...
    @property
    def PatientModel(self) -> PatientModel: ...
    @PatientModel.setter
    def PatientModel(self, value: PatientModel) -> None: ...
    @property
    def StructureSetExaminations(self) -> ScriptObjectCollection[Examination]: ...
    @StructureSetExaminations.setter
    def StructureSetExaminations(self, value: List[Examination]) -> None: ...
    @property
    def TemplateDeepLearningRois(self) -> ScriptObjectCollection[TemplateDeepLearningRoi]: ...
    @TemplateDeepLearningRois.setter
    def TemplateDeepLearningRois(self, value: List[TemplateDeepLearningRoi]) -> None: ...
    @property
    def TemplateMappingPois(self) -> ScriptObjectCollection[TemplateMappingStructure]: ...
    @TemplateMappingPois.setter
    def TemplateMappingPois(self, value: List[TemplateMappingStructure]) -> None: ...
    @property
    def TemplateMappingRois(self) -> ScriptObjectCollection[TemplateMappingStructure]: ...
    @TemplateMappingRois.setter
    def TemplateMappingRois(self, value: List[TemplateMappingStructure]) -> None: ...
    def EditStructureTemplateProperties(self, TemplateName: str = ..., TemplateDescription: str = ..., InitializationType: Optional[Literal['Undefined', 'GeometriesFromTemplate', 'EmptyGeometries', 'GeometriesFromTemplateAndUseRigidRegistration', 'GeometriesFromTemplateAndUseDeformableRegistration', 'AtlasBased']] = ...) -> None:
        """Edit name, description and/or initialization type for structure template"""
        ...
    def ExportStructureTemplate(self, FileName: str, Anonymize: bool = ...) -> None:
        """Exports a structure template to a backup (.rsbak) file."""
        ...
    def ExtendStructureTemplate(self, PatientModel: PatientModel, ExaminationNames: List[str], RoiNames: List[str], PoiNames: List[str], RoiAndModelGeneratedRoiGeometryDictionary: Dict[str, Any] = ..., RoiAssociations: Dict[str, Any] = ..., PoiAssociations: Dict[str, Any] = ..., AssociateStructuresByName: bool = ...) -> None:
        """Extend structure template with examinations and structures."""
        ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateDeepLearningRoi:
    @property
    def MachineLearningModelName(self) -> str: ...
    @MachineLearningModelName.setter
    def MachineLearningModelName(self, value: str) -> None: ...
    @property
    def ModelRoiName(self) -> str: ...
    @ModelRoiName.setter
    def ModelRoiName(self, value: str) -> None: ...
    @property
    def RegionOfInterest(self) -> RegionOfInterest: ...
    @RegionOfInterest.setter
    def RegionOfInterest(self, value: RegionOfInterest) -> None: ...

class TemplateMappingStructure:
    @property
    def HybridDeformableRegistrationInfo(self) -> HybridDeformableRegistrationInfo: ...
    @HybridDeformableRegistrationInfo.setter
    def HybridDeformableRegistrationInfo(self, value: HybridDeformableRegistrationInfo) -> None: ...
    @property
    def RegionOfInterest(self) -> RegionOfInterest: ...
    @RegionOfInterest.setter
    def RegionOfInterest(self, value: RegionOfInterest) -> None: ...
    @property
    def RigidRegistrationInfo(self) -> RigidRegistrationInfo: ...
    @RigidRegistrationInfo.setter
    def RigidRegistrationInfo(self, value: RigidRegistrationInfo) -> None: ...

class TemplatePlanExploration:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlanGenerationProtocolNames(self) -> ScriptObjectCollection[str]: ...
    @PlanGenerationProtocolNames.setter
    def PlanGenerationProtocolNames(self, value: List[str]) -> None: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateResponseParameters:
    @property
    def IsFactorySetting(self) -> bool: ...
    @property
    def TissueName(self) -> str: ...
    @property
    def FileImportLog(self) -> FileImportLog: ...
    @FileImportLog.setter
    def FileImportLog(self, value: FileImportLog) -> None: ...
    @property
    def ResponseFunctionParameters(self) -> ResponseFunctionParameters: ...
    @ResponseFunctionParameters.setter
    def ResponseFunctionParameters(self, value: ResponseFunctionParameters) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...

class TemplateTreatmentOptimization:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    @property
    def DoseDependencyArgsPerOptimizationFunction(self) -> ScriptObjectCollection[DoseDependencyStringArgs]: ...
    @DoseDependencyArgsPerOptimizationFunction.setter
    def DoseDependencyArgsPerOptimizationFunction(self, value: List[DoseDependencyStringArgs]) -> None: ...
    @property
    def EvaluationSetups(self) -> ScriptObjectCollection[EvaluationSetup]: ...
    @EvaluationSetups.setter
    def EvaluationSetups(self, value: List[EvaluationSetup]) -> None: ...
    @property
    def FunctionToRoiMaps(self) -> ScriptObjectCollection[OrganToFunctionMap]: ...
    @FunctionToRoiMaps.setter
    def FunctionToRoiMaps(self, value: List[OrganToFunctionMap]) -> None: ...
    @property
    def OptimizationProblem(self) -> OptimizationProblem: ...
    @OptimizationProblem.setter
    def OptimizationProblem(self, value: OptimizationProblem) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and releases locks."""
        ...

class TemplateTreatmentSetup:
    @property
    def Diagnosis(self) -> str: ...
    @Diagnosis.setter
    def Diagnosis(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    @property
    def TemplateTreatmentSetupArgs(self) -> TemplateTreatmentSetupArgs: ...
    @TemplateTreatmentSetupArgs.setter
    def TemplateTreatmentSetupArgs(self, value: TemplateTreatmentSetupArgs) -> None: ...
    @property
    def TreatmentSetups(self) -> ScriptObjectCollection[TreatmentSetup]: ...
    @TreatmentSetups.setter
    def TreatmentSetups(self, value: List[TreatmentSetup]) -> None: ...
    def Unload(self) -> None:
        """Unloads the template and releases locks."""
        ...

class TemplateTreatmentSetupArgs:
    @property
    def TemplateTreatmentSetupArgsPerBeams(self) -> ScriptObjectCollection[TemplateTreatmentSetupArgsPerBeam]: ...
    @TemplateTreatmentSetupArgsPerBeams.setter
    def TemplateTreatmentSetupArgsPerBeams(self, value: List[TemplateTreatmentSetupArgsPerBeam]) -> None: ...

class TemplateTreatmentSetupArgsPerBeam:
    @property
    def ForBeam(self) -> str: ...
    @ForBeam.setter
    def ForBeam(self, value: str) -> None: ...
    @property
    def MinAirGap(self) -> Optional[float]: ...
    @MinAirGap.setter
    def MinAirGap(self, value: Optional[float]) -> None: ...
    @property
    def RangeShifter(self) -> str: ...
    @RangeShifter.setter
    def RangeShifter(self, value: str) -> None: ...
    @property
    def SnoutId(self) -> str: ...
    @SnoutId.setter
    def SnoutId(self, value: str) -> None: ...
    @property
    def ArcTrajectory(self) -> ArcTrajectory: ...
    @ArcTrajectory.setter
    def ArcTrajectory(self, value: ArcTrajectory) -> None: ...

class TemplateToleranceTable:
    @property
    def Machines(self) -> ScriptObjectCollection[MachineReference]: ...
    @Machines.setter
    def Machines(self, value: List[MachineReference]) -> None: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @ApprovalInformation.setter
    def ApprovalInformation(self, value: ApprovalInformation) -> None: ...
    @property
    def ToleranceTable(self) -> BaseToleranceTable: ...
    @ToleranceTable.setter
    def ToleranceTable(self, value: BaseToleranceTable) -> None: ...
    def RenameToleranceTableTemplate(self, Label: str) -> None:
        """Renames a tolerance table template."""
        ...
    def Unload(self) -> None:
        """Unloads the template and release locks."""
        ...
