from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.beam import PhotonEnergySpectrum
    from raystation.v2025.dose import DoseAlgorithmVersion
    from raystation.v2025.machine import TomoLinac
    from raystation.v2025.machine_db_types import ComputationSettings, ComputedDoseCurve, ComputedDoseCurvesGammaSettings, JawConversion, JawField, JawPenumbraFilter, LeafLatency, MeasuredDoseCurve, MlcLeafFilters, NormalizedDoseCurve, TransverseDistribution
    from raystation.v2025.patient_db_types import CurrentValueFilterSettings
    from raystation.v2025.plan import PlanExploration



class TomoModificationInfo:
    @property
    def AdditionalDicomUIDs(self) -> ScriptObjectCollection[str]: ...
    @property
    def DeviceSerialNumber(self) -> str: ...
    @property
    def DicomUID(self) -> str: ...
    @property
    def ImportedDicomUID(self) -> str: ...
    @property
    def ModificationTime(self) -> str: ...
    @property
    def SoftwareVersion(self) -> str: ...
    @property
    def TomoPlanInstanceUID(self) -> str: ...
    @property
    def UserName(self) -> str: ...

class TomoSegment:
    @property
    def BackJawPosition(self) -> float: ...
    @BackJawPosition.setter
    def BackJawPosition(self, value: float) -> None: ...
    @property
    def CollimatorAngle(self) -> float: ...
    @property
    def CouchYOffset(self) -> float: ...
    @CouchYOffset.setter
    def CouchYOffset(self, value: float) -> None: ...
    @property
    def DeltaGantryAngle(self) -> float: ...
    @DeltaGantryAngle.setter
    def DeltaGantryAngle(self, value: float) -> None: ...
    @property
    def DoseRate(self) -> float: ...
    @DoseRate.setter
    def DoseRate(self, value: float) -> None: ...
    @property
    def FrontJawPosition(self) -> float: ...
    @FrontJawPosition.setter
    def FrontJawPosition(self, value: float) -> None: ...
    @property
    def ImportedSourceToSurfaceDistance_ForDisplayUseOnly(self) -> Optional[float]: ...
    @property
    def JawPositions(self) -> np.ndarray: ...
    @JawPositions.setter
    def JawPositions(self, value: np.ndarray) -> None: ...
    @property
    def LeafOpenFraction(self) -> np.ndarray: ...
    @LeafOpenFraction.setter
    def LeafOpenFraction(self, value: np.ndarray) -> None: ...
    @property
    def LeafPositions(self) -> np.ndarray: ...
    @LeafPositions.setter
    def LeafPositions(self, value: np.ndarray) -> None: ...
    @property
    def RelativeWeight(self) -> float: ...
    @RelativeWeight.setter
    def RelativeWeight(self, value: float) -> None: ...
    @property
    def SegmentNumber(self) -> int: ...
    def GetBEVImageOfSegment(self) -> str:
        """Method for retrieving BEV image for a segment."""
        ...

class TomoPropertiesPerBeam:
    @property
    def BackJawPosition(self) -> float: ...
    @BackJawPosition.setter
    def BackJawPosition(self, value: float) -> None: ...
    @property
    def FrontJawPosition(self) -> float: ...
    @FrontJawPosition.setter
    def FrontJawPosition(self, value: float) -> None: ...
    @property
    def JawMode(self) -> Literal['Fixed', 'Dynamic']: ...
    @JawMode.setter
    def JawMode(self, value: Literal['Fixed', 'Dynamic']) -> None: ...
    @property
    def MaxDeliveryTime(self) -> Optional[float]: ...
    @MaxDeliveryTime.setter
    def MaxDeliveryTime(self, value: Optional[float]) -> None: ...
    @property
    def MaxDeliveryTimeFactor(self) -> Optional[float]: ...
    @MaxDeliveryTimeFactor.setter
    def MaxDeliveryTimeFactor(self, value: Optional[float]) -> None: ...
    @property
    def MaxGantryPeriod(self) -> Optional[float]: ...
    @MaxGantryPeriod.setter
    def MaxGantryPeriod(self, value: Optional[float]) -> None: ...
    @property
    def PitchTomoDirect(self) -> Optional[float]: ...
    @PitchTomoDirect.setter
    def PitchTomoDirect(self, value: Optional[float]) -> None: ...
    @property
    def PitchTomoHelical(self) -> Optional[float]: ...
    @PitchTomoHelical.setter
    def PitchTomoHelical(self, value: Optional[float]) -> None: ...
    def EditTomoBasedBeamOptimizationSettings(self, JawMode: Literal['Fixed', 'Dynamic'] = ..., PitchTomoHelical: Optional[float] = ..., PitchTomoDirect: Optional[float] = ..., BackJawPosition: float = ..., FrontJawPosition: float = ..., MaxDeliveryTime: Optional[float] = ..., MaxGantryPeriod: Optional[float] = ..., MaxDeliveryTimeFactor: Optional[float] = ...) -> None:
        """Edit the Tomo beam optimization settings for selected beam"""
        ...

class TomoDirectFilterSettings:
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...
    @property
    def DeliveryTimeFilterSetting(self) -> CurrentValueFilterSettings: ...
    @DeliveryTimeFilterSetting.setter
    def DeliveryTimeFilterSetting(self, value: CurrentValueFilterSettings) -> None: ...
    @property
    def InPlanExploration(self) -> PlanExploration: ...
    @InPlanExploration.setter
    def InPlanExploration(self, value: PlanExploration) -> None: ...
    @property
    def NrOfBeamsFilterSetting(self) -> CurrentValueFilterSettings: ...
    @NrOfBeamsFilterSetting.setter
    def NrOfBeamsFilterSetting(self, value: CurrentValueFilterSettings) -> None: ...

class TomoHelicalFilterSettings:
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...
    @property
    def DeliveryTimeFilterSetting(self) -> CurrentValueFilterSettings: ...
    @DeliveryTimeFilterSetting.setter
    def DeliveryTimeFilterSetting(self, value: CurrentValueFilterSettings) -> None: ...
    @property
    def InPlanExploration(self) -> PlanExploration: ...
    @InPlanExploration.setter
    def InPlanExploration(self, value: PlanExploration) -> None: ...

class TomoBeamQuality:
    @property
    def Label(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def BeamModels(self) -> ScriptObjectCollection[TomoBeamModelProperties]: ...
    @property
    def CommissionedForDoseAlgorithms(self) -> ScriptObjectCollection[DoseAlgorithmVersion]: ...
    @property
    def ComputedDoseCurvesGammaSettings(self) -> ComputedDoseCurvesGammaSettings: ...
    @property
    def TomoDosimetryData(self) -> TomoDosimetryData: ...
    @property
    def TomoLinac(self) -> TomoLinac: ...

class TomoBeamModelProperties:
    @property
    def BeamModel(self) -> TomoBeamModel: ...
    @property
    def BeamQuality(self) -> TomoBeamQuality: ...
    @property
    def ComputationSettings(self) -> ComputationSettings: ...
    @property
    def ComputedCurves(self) -> ScriptObjectCollection[ComputedDoseCurve]: ...
    @property
    def TomoLinac(self) -> TomoLinac: ...

class TomoBeamModel:
    @property
    def AbsoluteCalibration(self) -> float: ...
    @property
    def BothLeafFluenceOutputFactors(self) -> np.ndarray: ...
    @property
    def Efiot(self) -> float: ...
    @property
    def ForDoseAlgorithm(self) -> Literal['Undefined', 'SVD', 'CCDose', 'IonPencilBeam', 'IonMonteCarlo', 'SpotWeightPencilBeam', 'SpotWeightMonteCarlo', 'Mixed', 'Imported', 'ElectronMonteCarlo', 'IonPencilBeamFast', 'SpotWeightPencilBeamFast', 'PhotonMonteCarlo', 'XRayMonteCarlo', 'ImagingSystemMonteCarlo', 'AccurateFluenceMonteCarlo', 'CarbonPencilBeam', 'BnctExternalMonteCarloNT', 'BnctExternalMonteCarloSumitomo', 'BnctExternalMonteCarlo', 'BrachyTG43', 'SpotWeightPencilBeamOptimization', 'BrachyMonteCarlo', 'BnctExternalMonteCarloTls']: ...
    @property
    def LeftLeafFluenceOutputFactors(self) -> np.ndarray: ...
    @property
    def RightLeafFluenceOutputFactors(self) -> np.ndarray: ...
    @property
    def EnergySpectrum(self) -> PhotonEnergySpectrum: ...
    @property
    def JawConversions(self) -> ScriptObjectCollection[JawConversion]: ...
    @property
    def JawFields(self) -> ScriptObjectCollection[JawField]: ...
    @property
    def JawPenumbraFilters(self) -> ScriptObjectCollection[JawPenumbraFilter]: ...
    @property
    def MlcLeafFilters(self) -> ScriptObjectCollection[MlcLeafFilters]: ...
    @property
    def TransverseProfile(self) -> TransverseDistribution: ...

class TomoDosimetryData:
    @property
    def Ssd(self) -> float: ...
    @property
    def MeasuredCurves(self) -> ScriptObjectCollection[MeasuredDoseCurve]: ...
    @property
    def NormalizedCurves(self) -> ScriptObjectCollection[NormalizedDoseCurve]: ...

class TomoMlc:
    @property
    def LeafCenterPositions(self) -> np.ndarray: ...
    @property
    def LeafWidths(self) -> np.ndarray: ...
    @property
    def MaxActiveLeafCyclesPerSecond(self) -> float: ...
    @property
    def MinLeafCloseTime(self) -> float: ...
    @property
    def MinLeafOpenTime(self) -> float: ...
    @property
    def NumOfLeaves(self) -> int: ...
    @property
    def LeafLatencies(self) -> ScriptObjectCollection[LeafLatency]: ...

class TomoJaw:
    @property
    def DynamicJawCapable(self) -> bool: ...
    @property
    def MaxSpeed(self) -> float: ...

class TomoProperties:
    @property
    def BoreSize(self) -> float: ...
    @property
    def CenterOfRotationOffset(self) -> float: ...
    @property
    def GantryRotationPeriods(self) -> np.ndarray: ...
    @property
    def IdmsBeamId(self) -> str: ...
    @property
    def IdmsBeamRevision(self) -> int: ...
    @property
    def IdmsMachineId(self) -> str: ...
    @property
    def IdmsMachineRevision(self) -> int: ...
    @property
    def MachineGeneration(self) -> Literal['TwinPeak', 'TwinPeakPlusOne', 'Titan', 'Radixact']: ...
    @property
    def MaxCouchSpeed(self) -> float: ...
    @property
    def MinCouchSpeed(self) -> float: ...
    @property
    def MinProjectionTime(self) -> float: ...
    @property
    def NumberOfProjectionsPerRotation(self) -> int: ...
    @property
    def SourceAxisDistance(self) -> float: ...

class TomoHelicalDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def OptimizationTolerance(self) -> float: ...

class TomoDirectDefaultSettings:
    @property
    def ComputeFinalDose(self) -> bool: ...
    @property
    def MaxNumberOfIterations(self) -> int: ...
    @property
    def OptimizationTolerance(self) -> float: ...
