from __future__ import annotations

from raystation.v2025._collection import ScriptObjectCollection
from typing import Any, Dict, List, Literal, Optional, Sequence, Tuple, Union
import numpy as np

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from raystation.v2025.machine import MachineReference
    from raystation.v2025.patient_db_types import ApprovalInformation, DicomPersonName, EpisodeOfCare
    from raystation.v2025.setup import SetupMargins



class TreatmentModule_TreatmentCourse:
    @property
    def Accessories(self) -> ScriptObjectCollection[TreatmentModule_Accessory]: ...
    @property
    def AdjustedPlanParameters(self) -> ScriptObjectCollection[TreatmentModule_PlanWorkflowParameters]: ...
    @property
    def EpisodeOfCare(self) -> EpisodeOfCare: ...
    @property
    def OfflineImportParseResults(self) -> ScriptObjectCollection[TreatmentModule_OfflineImportParseResult]: ...
    @property
    def PatientIdentifier(self) -> TreatmentModule_PatientIdentifier: ...
    @property
    def Plans(self) -> ScriptObjectCollection[TreatmentModule_PlanPackage]: ...
    @property
    def Sessions(self) -> ScriptObjectCollection[TreatmentModule_Session]: ...

class TreatmentModule_Accessory:
    @property
    def AccessoryType(self) -> Literal['BinaryRangeShifter', 'FixedRangeModulator', 'AnalogRangeShifter', 'StaticRangeShifter', 'WheelFixedWeightsRangeModulator', 'WheelModulatedWeightsRangeModulator']: ...
    @property
    def Code(self) -> str: ...
    @property
    def Name(self) -> str: ...

class TreatmentModule_PlanPackage:
    @property
    def BeamDeliveryType(self) -> Literal['SMLC', 'DMLC', 'DynamicArc', 'StaticArc', 'CollapsedArc', 'TomoHelical', 'TomoDirect', 'TomoStatic', 'SingleScattering', 'DoubleScattering', 'PencilBeamScanning', 'LineScanning', 'UniformScanning', 'Wobbling', 'PencilBeamScanningArc', 'NCT', 'CyberKnife', 'Setup', 'Undefined']: ...
    @property
    def BodySite(self) -> str: ...
    @property
    def Modality(self) -> Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']: ...
    @property
    def PatientPosition(self) -> Literal['HeadFirstProne', 'HeadFirstSupine', 'HeadFirstDecubitusRight', 'HeadFirstDecubitusLeft', 'FeetFirstDecubitusRight', 'FeetFirstDecubitusLeft', 'FeetFirstProne', 'FeetFirstSupine', 'Sitting', 'OcularGaze']: ...
    @property
    def PlanGenerationTechnique(self) -> Literal['Imrt', 'Conformal', 'Mixed']: ...
    @property
    def PlanIdentifier(self) -> str: ...
    @property
    def PlanningImageFrameOfReferenceUID(self) -> str: ...
    @property
    def PlanningImageToDeliveryTransformation(self) -> np.ndarray: ...
    @property
    def RotationDisplayOrigin(self) -> Optional[Point3[float]]: ...
    @property
    def TreatmentMachine(self) -> MachineReference: ...
    @property
    def UniqueId(self) -> str: ...
    @property
    def Accessories(self) -> ScriptObjectCollection[TreatmentModule_Accessory]: ...
    @property
    def AdditionalDicomReferences(self) -> ScriptObjectCollection[TreatmentModule_DicomSopReference]: ...
    @property
    def Beams(self) -> ScriptObjectCollection[TreatmentModule_Beam]: ...
    @property
    def CollisionAvoidance(self) -> TreatmentModule_CollisionAvoidance: ...
    @property
    def Isocenters(self) -> ScriptObjectCollection[TreatmentModule_Isocenter]: ...
    @property
    def NamedPositions(self) -> ScriptObjectCollection[TreatmentModule_NamedPosition]: ...
    @property
    def PlanningImage(self) -> TreatmentModule_DicomMultiSopReference: ...
    @property
    def RespiratoryMotion(self) -> TreatmentModule_RespiratoryMotion: ...
    @property
    def SetupBeams(self) -> ScriptObjectCollection[TreatmentModule_SetupBeam]: ...
    @property
    def SetupMargins(self) -> SetupMargins: ...
    @property
    def StructureSet(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def StructureSetInformation(self) -> TreatmentModule_StructureSet: ...
    @property
    def TpsPlan(self) -> TreatmentModule_DicomSopReference: ...

class TreatmentModule_Beam:
    @property
    def CouchPitchAngle(self) -> Optional[float]: ...
    @property
    def CouchRollAngle(self) -> Optional[float]: ...
    @property
    def CouchRotationAngle(self) -> Optional[float]: ...
    @property
    def GantryAngle(self) -> Optional[float]: ...
    @property
    def Meterset(self) -> float: ...
    @property
    def MetersetUnit(self) -> str: ...
    @property
    def Modality(self) -> Optional[Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> int: ...
    @property
    def SnoutId(self) -> str: ...
    @property
    def SnoutPosition(self) -> Optional[float]: ...
    @property
    def TreatmentMachineNameAlias(self) -> str: ...
    @property
    def Accessories(self) -> ScriptObjectCollection[TreatmentModule_Accessory]: ...
    @property
    def Blocks(self) -> ScriptObjectCollection[TreatmentModule_Block]: ...
    @property
    def Boli(self) -> ScriptObjectCollection[TreatmentModule_Bolus]: ...
    @property
    def Isocenter(self) -> TreatmentModule_Isocenter: ...
    @property
    def PatientSetup(self) -> TreatmentModule_PatientSetupAlignment: ...
    @property
    def TableTopDisplacement(self) -> TreatmentModule_TableTopCoordinates: ...

class TreatmentModule_Bolus:
    @property
    def BolusName(self) -> str: ...
    @property
    def MaterialName(self) -> str: ...

class TreatmentModule_Block:
    @property
    def AccessoryCode(self) -> str: ...
    @property
    def Name(self) -> str: ...

class TreatmentModule_TableTopCoordinates:
    @property
    def Lateral(self) -> Optional[float]: ...
    @property
    def Longitudinal(self) -> Optional[float]: ...
    @property
    def Pitch(self) -> Optional[float]: ...
    @property
    def Roll(self) -> Optional[float]: ...
    @property
    def Vertical(self) -> Optional[float]: ...
    @property
    def Yaw(self) -> Optional[float]: ...

class TreatmentModule_SetupBeam:
    @property
    def BodySite(self) -> str: ...
    @property
    def CouchPitchAngle(self) -> Optional[float]: ...
    @property
    def CouchRollAngle(self) -> Optional[float]: ...
    @property
    def CouchRotationAngle(self) -> Optional[float]: ...
    @property
    def GantryAngle(self) -> Optional[float]: ...
    @property
    def ImagedVolumeLateralSize(self) -> Optional[float]: ...
    @property
    def ImagedVolumeLongitudinalSize(self) -> Optional[float]: ...
    @property
    def ImagedVolumeVerticalSize(self) -> Optional[float]: ...
    @property
    def ImagingProtocolName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> int: ...
    @property
    def Isocenter(self) -> TreatmentModule_Isocenter: ...
    @property
    def PatientSetup(self) -> TreatmentModule_PatientSetupAlignment: ...
    @property
    def RegistrationFocusRoi(self) -> ScriptObjectCollection[TreatmentModule_RoiReference]: ...
    @property
    def TableTopDisplacement(self) -> TreatmentModule_TableTopCoordinates: ...

class TreatmentModule_RoiReference:
    @property
    def ReferencedRoiName(self) -> str: ...
    @property
    def ReferencedRoiNumber(self) -> int: ...

class TreatmentModule_Isocenter:
    @property
    def DisplayColor(self) -> str: ...
    @property
    def IsocenterId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def PositionInPatientCoordinates(self) -> Tuple[float, ...]: ...

class TreatmentModule_DicomSopReference:
    @property
    def InstanceUid(self) -> str: ...
    @property
    def RetrieveApplicationEntityTitle(self) -> str: ...
    @property
    def SeriesInstanceUid(self) -> str: ...
    @property
    def SopClassUid(self) -> str: ...
    @property
    def StudyInstanceUid(self) -> str: ...

class TreatmentModule_NamedPosition:
    @property
    def Name(self) -> str: ...
    @property
    def PositionInPatientCoordinates(self) -> Tuple[float, ...]: ...
    @property
    def RoiNumber(self) -> Optional[int]: ...

class TreatmentModule_DicomMultiSopReference:
    @property
    def InstanceUids(self) -> ScriptObjectCollection[Any]: ...
    @property
    def RetrieveApplicationEntityTitle(self) -> str: ...
    @property
    def SeriesInstanceUid(self) -> str: ...
    @property
    def SopClassUid(self) -> str: ...
    @property
    def StudyInstanceUid(self) -> str: ...

class TreatmentModule_CollisionAvoidance:
    @property
    def CollisionAvoidanceStructures(self) -> ScriptObjectCollection[TreatmentModule_CollisionAvoidanceStructure]: ...

class TreatmentModule_CollisionAvoidanceStructure:
    @property
    def IsFixedToTableTop(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def RoiColor(self) -> str: ...
    @property
    def RoiGeometryId(self) -> str: ...
    @property
    def RoiNumber(self) -> Optional[int]: ...

class TreatmentModule_RespiratoryMotion:
    @property
    def CompensationTechnique(self) -> ScriptObjectCollection[Any]: ...
    @property
    def DisplayName(self) -> str: ...

class TreatmentModule_StructureSet:
    @property
    def PointsOfInterest(self) -> ScriptObjectCollection[TreatmentModule_StructureInformation]: ...
    @property
    def RegionsOfInterest(self) -> ScriptObjectCollection[TreatmentModule_StructureInformation]: ...

class TreatmentModule_StructureInformation:
    @property
    def DisplayColor(self) -> str: ...
    @property
    def GeometryUuid(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> int: ...
    @property
    def Type(self) -> Literal['Undefined', 'External', 'Ptv', 'Ctv', 'Gtv', 'TreatedVolume', 'IrradiatedVolume', 'Bolus', 'Avoidance', 'Organ', 'Marker', 'Registration', 'Isocenter', 'ContrastAgent', 'Cavity', 'BrachyChannel', 'BrachyAccessory', 'BrachySourceApplicator', 'BrachyChannelShield', 'Support', 'Fixation', 'DoseRegion', 'Control', 'LocalizationPoint', 'FieldOfView', 'AcquisitionIsocenter', 'InitialLaserIsocenter', 'InitialMatchIsocenter', 'Avatar']: ...

class TreatmentModule_Session:
    @property
    def DeliveredBy(self) -> Literal['RayTreat', 'RayCommand']: ...
    @property
    def Faulted(self) -> bool: ...
    @property
    def FullyDeliveredBeams(self) -> ScriptObjectCollection[int]: ...
    @property
    def IsContinuationSessionAllowed(self) -> bool: ...
    @property
    def SessionId(self) -> str: ...
    @property
    def StartTime(self) -> Optional[str]: ...
    @property
    def Status(self) -> Literal['Created', 'InProgress', 'Partial', 'Delivered', 'Canceled']: ...
    @property
    def BeamDeliveryInstruction(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def DeliveryNotifications(self) -> ScriptObjectCollection[TreatmentModule_SessionDeliveryNotification]: ...
    @property
    def DeliveryPlan(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def DriverSessionStatus(self) -> TreatmentModule_DriverSessionStatus: ...
    @property
    def Notes(self) -> ScriptObjectCollection[TreatmentModule_SessionNote]: ...
    @property
    def Overrides(self) -> ScriptObjectCollection[TreatmentModule_Override]: ...
    @property
    def Plan(self) -> TreatmentModule_PlanPackage: ...
    @property
    def ProgressUpdates(self) -> ScriptObjectCollection[TreatmentModule_ProgressUpdate]: ...
    @property
    def SessionMetaData(self) -> TreatmentModule_SessionMetaData: ...
    @property
    def SessionWarnings(self) -> ScriptObjectCollection[TreatmentModule_SessionWarning]: ...
    @property
    def SetupInputs(self) -> ScriptObjectCollection[TreatmentModule_SetupInput]: ...
    @property
    def SetupRecords(self) -> ScriptObjectCollection[TreatmentModule_SetupRecord]: ...
    @property
    def SetupTreatmentRecords(self) -> ScriptObjectCollection[TreatmentModule_SetupTreatmentRecord]: ...
    @property
    def SpecifiedAbsoluteCouchPoses(self) -> ScriptObjectCollection[TreatmentModule_PoseIsocenterPair]: ...
    @property
    def TableTopPropagation(self) -> TreatmentModule_TableTopPropagation: ...
    @property
    def TreatmentRecords(self) -> ScriptObjectCollection[TreatmentModule_TreatmentRecord]: ...
    def GetPlan(self) -> TreatmentModule_PlanPackage:
        """Gets a reference to the plan of the session."""
        ...
    def GetSetupRecord(self) -> TreatmentModule_SetupRecord:
        """Gets the single setup record."""
        ...

class TreatmentModule_ProgressUpdate:
    @property
    def BeamNumber(self) -> Optional[int]: ...
    @property
    def Message(self) -> str: ...
    @property
    def ProgressPercentage(self) -> Optional[float]: ...
    @property
    def Timestamp(self) -> str: ...

class TreatmentModule_TreatmentRecord:
    @property
    def FractionNumber(self) -> Optional[int]: ...
    @property
    def IsManual(self) -> bool: ...
    @property
    def PerformedStationNameCodeValues(self) -> ScriptObjectCollection[str]: ...
    @property
    def StartDateTime(self) -> str: ...
    @property
    def Beams(self) -> ScriptObjectCollection[TreatmentModule_BeamRecord]: ...
    @property
    def DeliveryPlan(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def DicomTreatmentRecord(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def HumanPerformersNames(self) -> ScriptObjectCollection[DicomPersonName]: ...
    @property
    def MachineOverrides(self) -> ScriptObjectCollection[TreatmentModule_Override]: ...

class TreatmentModule_BeamRecord:
    @property
    def ContinuationOperation(self) -> Optional[Literal['NextSpot', 'NextEnergyLayer', 'NextBeam']]: ...
    @property
    def DeliveredPrimaryMeterset(self) -> Optional[float]: ...
    @property
    def DeliveredSecondaryMeterset(self) -> Optional[float]: ...
    @property
    def DeliveredTreatmentTime(self) -> Optional[float]: ...
    @property
    def GantryAngle(self) -> Optional[float]: ...
    @property
    def Modality(self) -> Optional[Literal['Photons', 'Electrons', 'Protons', 'Helium', 'Lithium', 'Carbon', 'Oxygen', 'Neutrons', 'Brachy', 'Unsupported', 'Unknown', 'UnknownIon', 'XRayPhotons', 'DirectNeutrons']]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> int: ...
    @property
    def OnlineCouchCorrectionAlgorithm(self) -> Literal['None', 'Igrt', 'TotalShift', 'CalculatedPatientDisplacement']: ...
    @property
    def OnlineCouchCorrectionCanBeCalculated(self) -> Literal['Ok', 'CenterCouchPerformed', 'NoImageSelected', 'OfflineImport']: ...
    @property
    def PrimaryMetersetUnit(self) -> str: ...
    @property
    def SecondaryMetersetUnit(self) -> str: ...
    @property
    def SnoutId(self) -> str: ...
    @property
    def SnoutPosition(self) -> Optional[float]: ...
    @property
    def SpecifiedPrimaryMeterset(self) -> Optional[float]: ...
    @property
    def SpecifiedSecondaryMeterset(self) -> Optional[float]: ...
    @property
    def SpecifiedTreatmentTime(self) -> Optional[float]: ...
    @property
    def StartTime(self) -> Optional[str]: ...
    @property
    def TreatmentStatus(self) -> Optional[Literal['NotDelivered', 'Started', 'Delivered', 'PartiallyDelivered']]: ...
    @property
    def WasContinuation(self) -> bool: ...
    @property
    def Accessories(self) -> ScriptObjectCollection[TreatmentModule_Accessory]: ...
    @property
    def DeliveredEnergyLayers(self) -> ScriptObjectCollection[TreatmentModule_EnergyLayer]: ...
    @property
    def OnlineCouchCorrection(self) -> TreatmentModule_TableTopCoordinates: ...
    @property
    def SpecifiedEnergyLayers(self) -> ScriptObjectCollection[TreatmentModule_EnergyLayer]: ...
    @property
    def TableTopPosition(self) -> TreatmentModule_TableTopCoordinates: ...

class TreatmentModule_EnergyLayer:
    @property
    def DeliveryIndex(self) -> int: ...
    @property
    def NominalEnergy(self) -> float: ...
    @property
    def Positions(self) -> ScriptObjectCollection[Any]: ...
    @property
    def SpotSize(self) -> Tuple[float, ...]: ...
    @property
    def SynchrotronDegraderValue(self) -> Optional[float]: ...
    @property
    def Weights(self) -> np.ndarray: ...

class TreatmentModule_Override:
    @property
    def Message(self) -> str: ...
    @property
    def OverrideId(self) -> str: ...
    @property
    def OverrideType(self) -> Literal['QaNotCompleted', 'ScheduleAlert', 'OutOfOrderDelivery', 'StartSessionWithRejectedOfflineReviews', 'AllFixationDevicesNotApplied', 'RegistrationOutsideMargins', 'ApprovedRegistrationNotBasedOnLatestImage', 'ApprovedRegistrationIsNotLatest', 'MachineParameterVerificationWarning', 'ManualRecordingExceedingPlannedMetersWasPerformed', 'UserSelectedAcquiredSetupImage', 'UserCancelledANonStartedSession', 'UserCancelledAnActiveSession', 'UserCancelledAnActiveQaSession', 'Other']: ...
    @property
    def Reason(self) -> str: ...
    @property
    def Timestamp(self) -> str: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...

class TreatmentModule_SetupRecord:
    @property
    def Confirmed(self) -> bool: ...
    @property
    def Status(self) -> Literal['NotStarted', 'Started', 'Complete']: ...
    @property
    def AcquiredSetupImages(self) -> ScriptObjectCollection[TreatmentModule_AcquiredSetupImage]: ...
    @property
    def ConfirmedFixationDevices(self) -> ScriptObjectCollection[TreatmentModule_FixationDevice]: ...
    @property
    def Input(self) -> TreatmentModule_SetupInput: ...
    @property
    def Overrides(self) -> ScriptObjectCollection[TreatmentModule_Override]: ...
    @property
    def Registrations(self) -> ScriptObjectCollection[TreatmentModule_RegistrationPackage]: ...
    @property
    def SelectedAcquiredSetupImage(self) -> TreatmentModule_AcquiredSetupImage: ...
    @property
    def SelectedRegistration(self) -> TreatmentModule_RegistrationPackage: ...

class TreatmentModule_RegistrationPackage:
    @property
    def ContentTime(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def FromFrameOfReference(self) -> str: ...
    @property
    def Index(self) -> int: ...
    @property
    def Intent(self) -> str: ...
    @property
    def RigidTransformationMatrix(self) -> np.ndarray: ...
    @property
    def ToFrameOfReference(self) -> str: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...
    @property
    def Overrides(self) -> ScriptObjectCollection[TreatmentModule_Override]: ...
    @property
    def ReferenceImage(self) -> TreatmentModule_DicomMultiSopReference: ...
    @property
    def RegisteredImage(self) -> TreatmentModule_DicomMultiSopReference: ...
    @property
    def Registration(self) -> TreatmentModule_DicomSopReference: ...

class TreatmentModule_AcquiredSetupImage:
    @property
    def AcquisitionIsocenter(self) -> Optional[Point3[float]]: ...
    @property
    def AcquisitionTime(self) -> Optional[str]: ...
    @property
    def BeingReceived(self) -> bool: ...
    @property
    def FrameOfReferenceUID(self) -> str: ...
    @property
    def ImageType(self) -> Literal['CT', 'CBCT', 'MVCT', 'MR', 'DRR', 'Radiograph']: ...
    @property
    def Label(self) -> str: ...
    @property
    def LaserIsocenter(self) -> Optional[Point3[float]]: ...
    @property
    def AcquisitionTableTopPosition(self) -> TreatmentModule_TableTopCoordinates: ...
    @property
    def DicomMultiSopReference(self) -> TreatmentModule_DicomMultiSopReference: ...
    @property
    def ReferencedSetupBeam(self) -> TreatmentModule_SetupBeam: ...

class TreatmentModule_SetupInput:
    @property
    def ImagingProtocol(self) -> Literal['None', 'CBCT', 'Radiograph']: ...
    @property
    def PatientSetupAlignment(self) -> TreatmentModule_PatientSetupAlignment: ...
    @property
    def TableTopDisplacementToAcquisition(self) -> TreatmentModule_TableTopCoordinates: ...

class TreatmentModule_SessionDeliveryNotification:
    @property
    def Message(self) -> str: ...

class TreatmentModule_SessionNote:
    @property
    def Note(self) -> str: ...
    @property
    def ApprovalInformation(self) -> ApprovalInformation: ...

class TreatmentModule_SetupTreatmentRecord:
    @property
    def DicomSopReference(self) -> TreatmentModule_DicomSopReference: ...

class TreatmentModule_SessionWarning:
    @property
    def Arguments(self) -> Dict[str, Any]: ...
    @property
    def Message(self) -> str: ...
    @property
    def SignedOffByUser(self) -> str: ...
    @property
    def Subject(self) -> str: ...
    @property
    def Time(self) -> str: ...
    @property
    def WarningType(self) -> str: ...

class TreatmentModule_PoseIsocenterPair:
    @property
    def Isocenter(self) -> TreatmentModule_Isocenter: ...
    @property
    def Pose(self) -> TreatmentModule_TableTopCoordinates: ...

class TreatmentModule_DriverSessionStatus:
    @property
    def DriverSessionReady(self) -> bool: ...
    @property
    def LastReceivedRequestSequenceNumber(self) -> int: ...
    @property
    def PatientAvailableRequestSent(self) -> bool: ...
    @property
    def ScheduledFractionRequestSent(self) -> bool: ...
    @property
    def SendFailedReason(self) -> str: ...
    @property
    def SetDeliveryParametersRequestSent(self) -> bool: ...
    @property
    def SetImagingParametersRequestSent(self) -> bool: ...
    @property
    def SetPatientPositionAdjustmentParametersRequestSent(self) -> bool: ...
    @property
    def SetRegistrationParametersRequestSent(self) -> bool: ...
    @property
    def SetSetupParametersRequest(self) -> bool: ...

class TreatmentModule_SessionMetaData:
    @property
    def CheckedInStatus(self) -> Optional[Literal['CheckedIn', 'Update', 'UndoCheckIn']]: ...
    @property
    def ContinuationNumber(self) -> Optional[int]: ...
    @property
    def DeliveredInRoom(self) -> str: ...
    @property
    def FractionId(self) -> Optional[str]: ...
    @property
    def IsQaSession(self) -> bool: ...
    @property
    def NominalFractionNumber(self) -> Optional[int]: ...
    @property
    def SessionDeliveryInformationFingerprint(self) -> Optional[str]: ...

class TreatmentModule_TableTopPropagation:
    @property
    def CanPropagateToContinuationSessionInThisFraction(self) -> bool: ...
    @property
    def PropagateTableTopPositions(self) -> bool: ...

class TreatmentModule_OfflineImportParseResult:
    @property
    def SessionId(self) -> str: ...
    @property
    def TreatmentRecordOfflineImportId(self) -> str: ...
    @property
    def TreatmentSessionRecordId(self) -> str: ...
    @property
    def TreatmentRecord(self) -> TreatmentModule_TreatmentRecord: ...
    @property
    def TreatmentRecordDicomReference(self) -> TreatmentModule_DicomSopReference: ...
    @property
    def TreatmentRecordValidationResults(self) -> ScriptObjectCollection[TreatmentModule_TreatmentRecordValidationResult]: ...

class TreatmentModule_TreatmentRecordValidationResult:
    @property
    def Message(self) -> str: ...
    @property
    def Severity(self) -> Literal['Error', 'Warning']: ...

class TreatmentModule_PlanWorkflowParameters:
    @property
    def AdjustedBeamDeliveryOrder(self) -> TreatmentModule_BeamDeliveryOrderInformation: ...
    @property
    def AdjustedImagingParameters(self) -> ScriptObjectCollection[TreatmentModule_ImagingParameters]: ...
    @property
    def AdjustedSetupMargins(self) -> TreatmentModule_SetupMarginInformation: ...
    @property
    def AssociatedPlan(self) -> TreatmentModule_PlanPackage: ...
    @property
    def RegistrationInformation(self) -> TreatmentModule_RegistrationInformation: ...
    @property
    def VisualizationPresets(self) -> ScriptObjectCollection[TreatmentModule_VisualizationPreset]: ...

class TreatmentModule_ImagingParameters:
    @property
    def BodySite(self) -> str: ...
    @property
    def CreationTime(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def GantryAngle(self) -> float: ...
    @property
    def ImagedVolumeCenter(self) -> Tuple[float, ...]: ...
    @property
    def ImagedVolumeSize(self) -> Tuple[float, ...]: ...
    @property
    def ProtocolName(self) -> str: ...
    @property
    def SetupBeamNumber(self) -> int: ...

class TreatmentModule_VisualizationPreset:
    @property
    def CreationTime(self) -> str: ...
    @property
    def GroupName(self) -> str: ...
    @property
    def ImageType(self) -> Literal['DRR', 'RTImage', 'CT', 'CBCT']: ...
    @property
    def PresetValues(self) -> str: ...
    @property
    def SchemaVersion(self) -> int: ...

class TreatmentModule_BeamDeliveryOrderInformation:
    @property
    def BeamDeliveryOrder(self) -> ScriptObjectCollection[int]: ...
    @property
    def CreationTime(self) -> str: ...

class TreatmentModule_SetupMarginInformation:
    @property
    def CreationTime(self) -> str: ...
    @property
    def SetupMargins(self) -> SetupMargins: ...

class TreatmentModule_RegistrationInformation:
    @property
    def CreationTime(self) -> str: ...
    @property
    def LastApprovedRegistration(self) -> TreatmentModule_RegistrationPackage: ...

class TreatmentModule_PatientIdentifier:
    @property
    def DateOfBirth(self) -> Optional[str]: ...
    @property
    def FamilyName(self) -> str: ...
    @property
    def Gender(self) -> str: ...
    @property
    def GivenName(self) -> str: ...
    @property
    def MiddleName(self) -> str: ...
    @property
    def PatientId(self) -> str: ...

class TreatmentModule_PatientSetupAlignment:
    @property
    def InitialTableTopPositionVersion(self) -> int: ...
    @property
    def InitialLocalizationTableTopPosition(self) -> TreatmentModule_TableTopCoordinates: ...
    @property
    def Plan(self) -> TreatmentModule_PlanPackage: ...

class TreatmentModule_FixationDevice:
    @property
    def DeviceId(self) -> str: ...
    @property
    def DeviceTypeId(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Position(self) -> str: ...
    @property
    def Remark(self) -> str: ...
